### ISSUE TITLE
Manage Search Engines

### ISSUE THREAD

**Issue by adamfowlerit** [MicrosoftDocs/Edge-Enterprise#1]
Two parts - needs to have some explanation on where you find the values, ideally use Bing as an example.
Second, the actual field in the group policy only accepts a single line of information, so it doesn't seem possible to enter this multi-line value?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1cd3ad5-bb4a-54ff-84e7-18ca0b11368f
* Version Independent ID: 984abd8f-45eb-737b-ad74-07ec8261f9eb
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#feedback)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/EdgeEnterprise-pr/blob/live/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
Cleaning up old issues.  Multiple updates have been made to the documentation for the ManagedSearchEngines policy
https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#managedsearchengines

If there is still feedback for the documentation, please open a new issue.  Thanks!
