### ISSUE TITLE
Allow user to toggle enterprise mode (ie mode) for current site

### ISSUE THREAD

**Issue by brucekbari** [MicrosoftDocs/Edge-Enterprise#10]
In IE, a user could toggle 'enterprise mode' for the current site via the tools menu. This was useful for quickly validating enterprise mode additions before updating the production site list. Having this feature available in Edge would speed up our adoption immensely. 

Another thing to consider here is that we are dealing with a new class of compatibility issues that we did not have to deal with in the past with the IE site list. Sites that worked fine in IE11 mode but do not work in Chromium now need to be included in the site list. The toggle would be a huge timer saver for quickly validating these new additions. 

Other than that, thanks for the fantastic enterprise-ready product!

**Comment by Y-Kelly** [comment]
@brucekbari Hello!  I understand this was posted awhile ago but wanted to follow up. 

On a managed device, you can see the option to Open sites in Internet Explorer mode under More tools ONLY if your organization has configured the policy to "Allow Internet Explorer mode testing". See Microsoft Edge Browser Policy Documentation | Microsoft Docs.  [https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#internetexplorerintegrationtestingallowed](url).  Please give it a try! 

If you have further questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
