### ISSUE TITLE
Rewards in Microsoft Edge? - is this the terrible Coupons feature that has suddenly turned up?

### ISSUE THREAD

**Issue by ccsjnw** [MicrosoftDocs/Edge-Enterprise#100]
[Enter feedback here]

Today, Microsoft Edge v87.0.664.47 on Windows 10 Enterprise (domain joined) started offering me coupons!

I'm told this feature is only active in the US, but I'm seeing it in the UK.
(Enterprise users do not want these features forced upon them. Will Microsoft *never* learn?)

Anyway, I've looked at the latest documentation for a new Group Policy settings to completely disable this new nonsense, but all I can find is: 

Microsoft Edge Documentation dated 19 Nov 2020:
=================================

Show Microsoft Rewards experiences
Supported versions:
On Windows and macOS since 88 or later
Description
Show Microsoft Rewards experience and notifications. If you enable this policy:

Microsoft account users (excludes Azure AD accounts) in search and earn markets will see the Microsoft Rewards experience in their Microsoft Edge user profile.
The setting to enable Microsoft Rewards in Microsoft Edge settings will be enabled and toggled on.
The setting to enable Give mode will be enabled and respect the user's setting.
If you disable this policy:

Microsoft account users (excludes Azure AD accounts) in search and earn markets will not see the Microsoft Rewards experience in their Microsoft Edge user profile.
The setting to enable Microsoft Rewards in Microsoft Edge settings will be disabled and toggled off.
If you don't configure this policy:

Microsoft account users (excludes Azure AD accounts) in search and earn markets will see the Microsoft Rewards experience in their Microsoft Edge user profile.
The setting to enable Microsoft Rewards in Microsoft Edge settings will be enabled and toggled on.
The setting to enable Give mode will be enabled and respect the user's setting.

Are Microsoft Rewards the same as Coupons?

Please Microsoft, stop turning on thee 'new features' by default - you are erasing the reasons we moved away from Google Chrome.  We just want a lean, clean and standards compliant browser - not all these silly extras.

Thanks,
James.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@ccsjnw Hello - Are you referring to the new Shopping with Microsoft Edge Feature?  [https://techcommunity.microsoft.com/t5/articles/introducing-shopping-with-microsoft-edge/m-p/1870080](url)

If so, here is a link to our documentation for the EdgeShoppingAssistantEnabled policy: 
[https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-policies#edgeshoppingassistantenabled](url)

If you have further questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
