### ISSUE TITLE
Force group policy update - Wrong command

### ISSUE THREAD

**Issue by sebassem** [MicrosoftDocs/Edge-Enterprise#101]
There is a note that says "To force a group policy update, type dsregcmd /status at the Windows administrator Command Prompt (Run as administrator)." It should be "gpupdate /force" instead of "dsregcmd /status"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12e89255-aab6-fe92-7a4f-7c1a53d30f50
* Version Independent ID: dcb5637d-8829-83e2-d7e3-71714a7daf3a
* Content: [Microsoft Edge rollback for enterprises](https://docs.microsoft.com/en-us/deployedge/edge-learnmore-rollback)
* Content Source: [edgeenterprise/edge-learnmore-rollback.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-rollback.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **v-danwes**

**Comment by Y-Kelly** [comment]
@sebassem Thank you for the feedback!  The documentation has just been updated.
