### ISSUE TITLE
typo in the description talking about wildcard for different policies like PluginsAllowedForUrls

### ISSUE THREAD

**Issue by TheBaban** [MicrosoftDocs/Edge-Enterprise#103]
[Enter feedback here]
the current text is :
However, starting in M85, patterns with '' and '[.]' wildcards in the host are no longer supported for this policy.

The * are missing in the text.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#pluginsallowedforurls)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by dan-wesley** [comment]
@TheBaban Thank you for catching this. We'll fix as required.

**Comment by dan-wesley** [comment]
@TheBaban @stmoody,
Error fixed and wildcard displaying correctly.
