### ISSUE TITLE
License Requirements

### ISSUE THREAD

**Issue by fklx** [MicrosoftDocs/Edge-Enterprise#104]
[Enter feedback here]
The license requirements with the **AND** statements seem to be wrong (AAD P1/P2 and AIP P1/P2). Customer is confused!

_Azure AD Premium (P1 **and** P2)_
M365 Business Premium
Office 365 E1 and above
_Azure Information Protection (AIP) (P1**&** P2)_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fa7eda4-6e4c-c2c8-a29a-ef2eead7f04f
* Version Independent ID: 414db256-c14b-ca11-b2a7-835aa9c9e041
* Content: [Microsoft Edge Enterprise Sync](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-enterprise-sync)
* Content Source: [edgeenterprise/microsoft-edge-enterprise-sync.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-enterprise-sync.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **scottbo**

**Comment by dan-wesley** [comment]
@fklx thanks for pointing this out. I'll follow up and get this updated.

**Comment by dan-wesley** [comment]
@fklx 'and' changed to 'or' in prerequisites. Will republish.
