### ISSUE TITLE
it need to change Windows 10 RS3 -> Windows 10 1709

### ISSUE THREAD

**Issue by Nian-Kim** [MicrosoftDocs/Edge-Enterprise#105]
please use version name not codename. Because of this, I had to spend 30 minutes finding meaning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86847b80-8f8e-9493-86ff-5dfd6412b48f
* Version Independent ID: 2ce02bc3-24a1-8c9f-c787-34ab90e9f31d
* Content: [Microsoft Edge Supported Operating Systems](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-supported-operating-systems)
* Content Source: [edgeenterprise/microsoft-edge-supported-operating-systems.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-supported-operating-systems.md)
* Product: **microsoft-edge**
* GitHub Login: @srugh
* Microsoft Alias: **srugh**

**Comment by Y-Kelly** [comment]
@Nian-Kim Hello - Thanks for your feedback!  The documentation has been updated and now reads "Windows 10 SAC 1709"
