### ISSUE TITLE
Page needs to explain pre 20H2 situations in which the Blocker Toolkit settings will be ignored

### ISSUE THREAD

**Issue by marypcbuk** [MicrosoftDocs/Edge-Enterprise#106]
For customers not adopting 20H2 yet, legacy Edge is still being removed and unpinned from the taskbar after a Windows Update restart even after the Blocker Toolkit has been applied; page needs to document how/why this happens and how this can be remediated after legacy Edge has been unpinned despite the Blocker Toolkit settings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a61b65e3-8537-b144-aa8b-e9bee8b59e8d
* Version Independent ID: 0595972d-2460-3fc2-d194-4e19c383e06a
* Content: [Blocker Toolkit to disable automatic delivery of Microsoft Edge](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-blocker-toolkit)
* Content Source: [edgeenterprise/microsoft-edge-blocker-toolkit.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-blocker-toolkit.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by Y-Kelly** [comment]
@marypcbuk Hello!  Thanks for your feedback!  The team has updated the Blocker Toolkit documentation.  

Updates can be see here: [https://docs.microsoft.com/en-us/deployedge/microsoft-edge-blocker-toolkit](url)

**Comment by marypcbuk** [comment]
thanks - but while I see the line at the top saying this will be explained ( **12/10/2020** to explain pre 20H2 situations in which the Blocker Toolkit settings will be ignored) I can't see a section that actually covers this? (I checked the diff)

**Comment by dan-wesley** [comment]
@marypcbuk @Y-Kelly 
There isn't a section dedicated to this issue. The information is incorporated into the text.

**Comment by marypcbuk** [comment]
OK, so feedback that as a reader I just couldn't see anything about it!

**Comment by dan-wesley** [comment]
![image](https://user-images.githubusercontent.com/38053816/102547947-caec5c00-406e-11eb-94ed-9f20774eb4bd.png)

**Comment by marypcbuk** [comment]
In which case there is a bug in either the blocker toolkit or the Edge deployment for non-organisational PC on Windows 2004, because the blocker toolkit does not stop legacy Edge from being removed even with the side-by-side registry key enabled and if that doesn't need to be documented because it shouldn't be happening, then it would be great if it stopped happening!
