### ISSUE TITLE
Requesting version history

### ISSUE THREAD

**Issue by rigg3d** [MicrosoftDocs/Edge-Enterprise#107]
Hi team,
Hope you're doing good.

I'm not sure what the best means of reaching out is so I'm filing this request here.
Is there a source of truth available for Edge Chromium that can be used to determine what the latest version is and when it was released? I'm aware the release notes exist but I'm looking for a parsable file (CSV or JSON), similar to what Chrome has done:
https://omahaproxy.appspot.com/

Does something like this exist for Edge? If not, is there a chance something like this can be setup?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ffcaf54-ce86-1b30-e947-540bf07a54c3
* Version Independent ID: 81267e97-e284-ff00-b081-476934538326
* Content: [Microsoft Edge release notes for Stable Channel](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **aguta**

**Comment by Y-Kelly** [comment]
@rigg3d Hello - Our Release Schedule (https://docs.microsoft.com/en-us/deployedge/microsoft-edge-release-schedule) and Release Notes (https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-beta-channel and https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel) would be the recommended places to get our release information.  

You can always reach out with questions regarding Microsoft Edge on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsider). Thanks!
