### ISSUE TITLE
How can I change the priority in the Update get request?

### ISSUE THREAD

**Issue by elinside** [MicrosoftDocs/Edge-Enterprise#111]
Hello

When i run the automatic update, its telling me, that i have already the latest version. But thats not true, because when i run the update via the browser itself, it would update.
So i compared the two different requests in the UpdateLog and i noticed the different priorities:

**ManualUpdate (has "Priority":10**
[Send][url=https://msedge.api.cdp.microsoft.com/api/v1.1/contents/Browser/namespaces/Default/names/msedge-stable-win-x64/versions/latest?action=select][request={"targetingAttributes":{"AppAp":"stable-arch_x64","AppBrandCode":"GCEU","AppCohort":"rrf@0.80","AppCohortHint":"","AppCohortName":"","AppLang":"","AppMajorVersion":"87","AppRollout":0.8,"AppTargetVersionPrefix":"","AppVersion":"87.0.664.60","HardwareDiskType":2,"IsInternalUser":false,"IsMachine":true,"OemProductManufacturer":"LENOVO","OemProductName":"20JJS3JP00","OsArch":"x64","OsPlatform":"win","OsVersion":"10.0.17763.1637","Priority":10,"Updater":"MicrosoftEdgeUpdate","UpdaterVersion":"1.3.139.59"}}][filename=]

**AutoUpdate (has "Priority":0)**
[Send][url=https://msedge.api.cdp.microsoft.com/api/v1.1/contents/Browser/namespaces/Default/names/msedge-stable-win-x64/versions/latest?action=select][request={"targetingAttributes":{"AppAp":"stable-arch_x64","AppBrandCode":"GCEU","AppCohort":"rrf@0.80","AppCohortHint":"","AppCohortName":"","AppLang":"","AppMajorVersion":"87","AppRollout":0.8,"AppTargetVersionPrefix":"","AppVersion":"87.0.664.60","HardwareDiskType":2,"IsInternalUser":false,"IsMachine":true,"OemProductManufacturer":"LENOVO","OemProductName":"20JJS3JP00","OsArch":"x64","OsPlatform":"win","OsVersion":"10.0.17763.1637","Priority":0,"Updater":"MicrosoftEdgeUpdate","UpdaterVersion":"1.3.139.59"}}][filename=]

So now im wondering, how can i call the updater with different priority?

Thanks

**Comment by Y-Kelly** [comment]
@elinside Hello!  Would you be able to submit this question and diagnostic data through our in-browser feedback tool? It's under "..." menu > Help and feedback > Send feedback. 

Also, if you have further questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsider). Thanks!
