### ISSUE TITLE
missing reference and description of msedgewebview2.admx , which is now included in the admx download for edge. Should be linked as well so admins can read up on what it is.

### ISSUE THREAD

**Issue by uniquegeek** [MicrosoftDocs/Edge-Enterprise#112]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e4fa0af-82d8-c1ca-02b3-fc55eb620ff3
* Version Independent ID: bd546e78-3406-0fdd-2aea-d0bd72be9f38
* Content: [Configure Microsoft Edge for Windows](https://docs.microsoft.com/en-us/deployedge/configure-microsoft-edge)
* Content Source: [edgeenterprise/configure-microsoft-edge.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/configure-microsoft-edge.md)
* Product: **microsoft-edge**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **brianalt**

**Comment by RAJU2529** [comment]
@uniquegeek . I add new admx templates

**Comment by RAJU2529** [comment]
@e01 @nam31  please close this issue #112
