### ISSUE TITLE
"Prerequisites" section needs to be more helpful

### ISSUE THREAD

**Issue by egoward** [MicrosoftDocs/Edge-Enterprise#113]
The pre-requisites bit reads a bit like a disclaimer.

Suggest you:
Call out how you can tell what a user is signed in with.
Call out what options are available to regular "Microsoft 365 Business Standard" users. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fa7eda4-6e4c-c2c8-a29a-ef2eead7f04f
* Version Independent ID: 414db256-c14b-ca11-b2a7-835aa9c9e041
* Content: [Microsoft Edge Enterprise Sync](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-enterprise-sync)
* Content Source: [edgeenterprise/microsoft-edge-enterprise-sync.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-enterprise-sync.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **scottbo**

**Comment by egoward** [comment]
Feel free to close, I expect  you're aware of this broader issue which this is no doubt a duplicate of -
  https://techcommunity.microsoft.com/t5/discussions/sync-in-new-edge-is-or-isn-t-available-to-o365-business-premium/m-p/1398218

**Comment by Y-Kelly** [comment]
@egoward The Prerequisites section (https://docs.microsoft.com/en-us/deployedge/microsoft-edge-enterprise-sync#prerequisites) has been updated.  Sync is now supported on M365 Business Premium, Business Standard, or Business Basic.  Thanks!

**Comment by egoward** [comment]
Thanks you, Y-Kelly :)
