### ISSUE TITLE
Win 10 Support?

### ISSUE THREAD

**Issue by ugeeku** [MicrosoftDocs/Edge-Enterprise#115]
This page is referencing  a script WIN 8, will it run on Windows 10?
 - powershell.exe -ExecutionPolicy Bypass .\IETelemetrySetUp-Win8.ps1 -IEFeatureOff

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2883b89f-a5ec-c549-3a9e-22c010d0b527
* Version Independent ID: 6518eff2-f389-a4c7-0d8d-f3ba47c650cc
* Content: [Enterprise Site Discovery Step by Step Guide](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-site-discovery#download-enterprise-site-discovery-tools)
* Content Source: [edgeenterprise/edge-ie-mode-site-discovery.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode-site-discovery.md)
* Product: **microsoft-edge**
* GitHub Login: @appcompatguy
* Microsoft Alias: **cjacks**

**Comment by Y-Kelly** [comment]
Clean up of old issues.  The document referenced was recently refreshed, if you are still having problems and would like to report a documentation issue to the team, please open a new issue and include relevant information/repro steps in the Comment section.
