### ISSUE TITLE
Incorrect Prerequisites

### ISSUE THREAD

**Issue by dpakraj** [MicrosoftDocs/Edge-Enterprise#116]
Prerequisites seems to be correct it is working for other subscriptions that is not listed in the requirements. Client has M365 Business standard and it works

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fa7eda4-6e4c-c2c8-a29a-ef2eead7f04f
* Version Independent ID: 414db256-c14b-ca11-b2a7-835aa9c9e041
* Content: [Configure and troubleshoot Microsoft Edge sync](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-enterprise-sync)
* Content Source: [edgeenterprise/microsoft-edge-enterprise-sync.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-enterprise-sync.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **scottbo**

**Comment by Y-Kelly** [comment]
@dpakraj We've recently made some changes/updates to this document.
