### ISSUE TITLE
--kiosk-idle-timeout-minutes should have an "=" symbol

### ISSUE THREAD

**Issue by rpertusio** [MicrosoftDocs/Edge-Enterprise#117]
The following documentation is not clear enough:

**SECTION**: Additional command line options

**CURRENT**: --kiosk-idle-timeout-minutes : Change the time (in minutes) from the last user activity before Microsoft Edge kiosk mode resets the user's session.

**PROPOSED**: --kiosk-idle-timeout-minutes=X : Change the time (where X is the number of minutes) from the last user activity before Microsoft Edge kiosk mode resets the user's session.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 229e4d46-19a6-c042-8ce1-844c44c00112
* Version Independent ID: 8ab07629-42a6-e7a1-86a9-f8103825ebc4
* Content: [Configure Microsoft Edge kiosk mode](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode)
* Content Source: [edgeenterprise/microsoft-edge-configure-kiosk-mode.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-configure-kiosk-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @Aguta
* Microsoft Alias: **aguta**

**Comment by Y-Kelly** [comment]
@rpertusio Thanks for the feedback!  I'll passed this on to the Kiosk Mode team.

**Comment by Y-Kelly** [comment]
@rpertusio The documentation should be updated [https://docs.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode#additional-command-line-options](url)

Thanks!

**Comment by WCJr03** [comment]
I'm using Edge version 106 and want to use the command line option "msedge.exe --kiosk www.contoso.com --edge-kiosk-type=public-browsing --kiosk-idle-timeout-minutes=1" to setup a desktop shortcut to a website.  The shortcut will open the website but the "--edge-kiosk-type=public-browsing" and "--kiosk-idle-timeout-minutes=1" command line options are not working. Any help or clarification will be greatly appreciated.
