### ISSUE TITLE
Link to SleepingTabsEnabled has typo

### ISSUE THREAD

**Issue by Jand66** [MicrosoftDocs/Edge-Enterprise#118]
The link in the New Policies section for version 88 to "SleepingTabsEnabled" is broken. 
It should be https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-policies#sleepingtabsenabled instead of https://docs.microsoft.com/en-us/DeployEdge/.microsoft-edge-policies#sleepingtabsenabled (dot before microsoft-edge)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ffcaf54-ce86-1b30-e947-540bf07a54c3
* Version Independent ID: 81267e97-e284-ff00-b081-476934538326
* Content: [Microsoft Edge release notes for Stable Channel](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel#version-88070550-january-21)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **aguta**

**Comment by dan-wesley** [comment]
@Jand66 Thank you for catching this, we'll fix right away

**Comment by dan-wesley** [comment]
Fixed  and republished
