### ISSUE TITLE
Wrong entry for ProxyMode

### ISSUE THREAD

**Issue by strav970** [MicrosoftDocs/Edge-Enterprise#119]
At the ProxySettings section it refers to ProxyMode "fixed_server" where it should be "fixed_servers"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#description-92)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@strav970 Hi!  I believe the documentation has been updated.  If you are still able to reproduce please feel free to open this issue again and include a link to the section that should be updated.  Thank you!
