### ISSUE TITLE
There are no registry key options provided for UpdateDefault policy

### ISSUE THREAD

**Issue by cb55555** [MicrosoftDocs/Edge-Enterprise#12]
The docs indicate the following options:

> If you enable this policy, Microsoft Edge Update handles Microsoft Edge updates according to how you configure the following options:
>- Always allow updates: Updates are always applied when found, either by periodic update check or by a manual update check.
>- Automatic silent updates only: Updates are applied only when they're found by the periodic update check.
>- Manual updates only: Updates are applied only when the user runs a manual update check.
>- Updates disabled: Updates are never applied.

The registry settings are detailed as follows:
>Windows Registry Settings
>- Path: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\EdgeUpdate
>- Value Name: UpdateDefault
>- Value Type: REG_DWORD
>
>Example value:
>0x00000003

Which option is 0x00000003 and what are the values for the other options?

Also, what is a "manual update check"? When I go to edge://settings/profiles and click "About Microsoft Edge", I see a message "Checking for updates", and it immediately installs any updates. Is this what you mean by "manual update check"? If so, this is a terrible way to "manually check" for updates if the end result is that the update is automatically installed.

**Comment by Y-Kelly** [comment]
Clean up of old issues.  Appears the question was previously answered and the values provided.  

If you would like to report a Microsoft Edge Enterprise documentation issue to the team please open a new issue and include relevant information/repro steps in the Comment section.

If you have general questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsiderForum) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
