### ISSUE TITLE
Wrong info at newtabpage

### ISSUE THREAD

**Issue by se-swuste** [MicrosoftDocs/Edge-Enterprise#120]
The url to use when configuring a "NewTabPageLocation" is about:blank and not as suggested: about://blank

**Comment by RAJU2529** [comment]
@se-swuste  Which article are you referring to?

**Comment by se-swuste** [comment]
Sorry, I wasn't aware this is not visible. I am referring to: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#newtabpagelocation

**Comment by Y-Kelly** [comment]
@se-swuste Thanks for reporting! I've contacted the team to take a look!

**Comment by Y-Kelly** [comment]
@se-swuste The documentation has been updated.  Thanks! 

![image](https://user-images.githubusercontent.com/74324031/111376840-32f61280-865d-11eb-9d95-e6b0e034279b.png)
