### ISSUE TITLE
Please add on edge pdf documentation following:

### ISSUE THREAD

**Issue by IrakliLomidze** [MicrosoftDocs/Edge-Enterprise#121]
PDF open parameters:

Like a  view=FitH

How to Disable Highlight
How to Disable Drawing over a page
How to Disable search on the internet
How to Disable search on Rotations

How to Disable save
How to Disable print

Thank you in advance.

**Comment by Y-Kelly** [comment]
@IrakliLomidze Thanks for your feedback!  I've asked our team to take a look.  We'll follow up if the team has any questions.

**Comment by Y-Kelly** [comment]
Clean up of old issues.  Feedback has been provided to the team.  

Any additional feedback can be provided through the browser. ("..." menu > Help and feedback > Send feedback)
