### ISSUE TITLE
Uzyskaj Premium

### ISSUE THREAD

**Issue by TO643** [MicrosoftDocs/Edge-Enterprise#122]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a61b65e3-8537-b144-aa8b-e9bee8b59e8d
* Version Independent ID: 0595972d-2460-3fc2-d194-4e19c383e06a
* Content: [Blocker Toolkit to disable automatic delivery of Microsoft Edge](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-blocker-toolkit)
* Content Source: [edgeenterprise/microsoft-edge-blocker-toolkit.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-blocker-toolkit.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by Y-Kelly** [comment]
@TO643 Hello!  If you had an issue to report with our documentation please provide more information.  Thanks!
