### ISSUE TITLE
Missing update of Kiosk mode with assigned access for new stable EDGE versions

### ISSUE THREAD

**Issue by ManfredPohlemann** [MicrosoftDocs/Edge-Enterprise#124]
Hello,

there is already the stable version 88 Build 88.0.705.56 out and the documentation still refers to "the Microsoft Edge Dev Channel, version 87.0.644.4" for assigned access. Could this please be updated?

Regards,
Manfred Pohlemann

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 229e4d46-19a6-c042-8ce1-844c44c00112
* Version Independent ID: 8ab07629-42a6-e7a1-86a9-f8103825ebc4
* Content: [Configure Microsoft Edge kiosk mode](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode)
* Content Source: [edgeenterprise/microsoft-edge-configure-kiosk-mode.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-configure-kiosk-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @Aguta
* Microsoft Alias: **aguta**

**Comment by Y-Kelly** [comment]
@ManfredPohlemann Hello!  Thanks for the feedback.  I believe the documentation has been updated.  

[https://docs.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode#single-app-kiosk](url)
"Microsoft Edge kiosk mode with assigned access single app is currently available for testing with the latest Windows 10 Insider Preview Build, version 20215 or higher, and with the Microsoft Edge Beta Channel, version 89 or higher."

Thanks!
