### ISSUE TITLE
DNS over HTTPS (DoH) configuration is not limited to a profile

### ISSUE THREAD

**Issue by haneef95** [MicrosoftDocs/Edge-Enterprise#125]
Hi,

One of the key incentives of the new is to Chromium based Edge is the Profiles feature, whereby there's almost complete separation between all the profiles.

However, when configuring secure DNS over HTTPS, the settings are global across all profiles. There should be an option to disable it from being global, rather, individual to the profile.

That would allow Organisations to configure DNS filtering/proxy on BYOD and additional Gateway based authorisation mechanisms for accessing internal apps.

Thanks,

**Comment by RAJU2529** [comment]
@haneef95  Which article are you referring to?

**Comment by Y-Kelly** [comment]
Clean up of old issues.  Normally these issues are specifically for Microsoft Edge Enterprise documentation.  

If you have feedback or feature requests for Microsoft Edge, you can submit them through the browser. ("..." menu > Help and feedback > Send feedback).  Thanks!
