### ISSUE TITLE
CTRL+N blocked (open a new window) not working

### ISSUE THREAD

**Issue by jajjaar** [MicrosoftDocs/Edge-Enterprise#127]
As tested with Public-Browsing CTRL+T blocked (open new tab) works ok but CTRL+N blocked (open a new window) does not work. Keyboard shortcut CTRL+N still open new page. Any workaround suggestion/s.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 229e4d46-19a6-c042-8ce1-844c44c00112
* Version Independent ID: 8ab07629-42a6-e7a1-86a9-f8103825ebc4
* Content: [Configure Microsoft Edge kiosk mode](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode)
* Content Source: [edgeenterprise/microsoft-edge-configure-kiosk-mode.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-configure-kiosk-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @Aguta
* Microsoft Alias: **aguta**

**Comment by Y-Kelly** [comment]
@jajjaar Hello - Can you share what version of MS Edge and Window 10 version you are using?  Thanks!

**Comment by jajjaar** [comment]
@Y-Kelly hi, thank you for responding. I tried in both Edge version 89.0.774.34 (Official build) beta (64-bit) and version 88.0.705.74 (Official build) (64-bit) on Windows 10 Version 20H2 (OS Build 19042.804).

**Comment by Y-Kelly** [comment]
@jajjaar The team is looking into this issue and had a follow up question.  When Ctrl+N does not work, are you using Assigned Access or just launching MS Edge from the command line?  Thanks!

**Comment by Y-Kelly** [comment]
Closing as there has not been a recent reply.  

If you have further questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
