### ISSUE TITLE
Any word on continued support for downloading Silverlight plugin

### ISSUE THREAD

**Issue by cjlotz** [MicrosoftDocs/Edge-Enterprise#128]
The document gives a good explanation of the different applications supported and not supported by IE mode (Silverlight, Flash etc.).  However it does not mention whether the Silverlight plugin will still be installable once Silverlight reaches end of life.  IE mode means nothing if new PC's cannot download and install the Silverlight plugin because the installer is not available anymore.  Can this be clarified?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 418ea780-28cd-c78d-8855-df5188dd4be9
* Version Independent ID: 15be2361-06cf-5683-9213-8aec3aebef67
* Content: [About IE mode](https://docs.microsoft.com/en-us/DeployEdge/edge-ie-mode)
* Content Source: [edgeenterprise/edge-ie-mode.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by Y-Kelly** [comment]
@cjlotz Hello - Based upon the Silverlight documentation (https://support.microsoft.com/en-us/windows/silverlight-end-of-support-0a3be3c7-bead-e203-2dfd-74f0a64f1788) the installer will not be available after the end of support date.  

![image](https://user-images.githubusercontent.com/74324031/109573289-a3206800-7aa3-11eb-84fa-ab2852774e07.png)

I would recommend reaching out to the Silverlight team for additional questions/clarification.  Thanks!
