### ISSUE TITLE
AuthServerAllowList can also accept intranet server URLs

### ISSUE THREAD

**Issue by brkdncr** [MicrosoftDocs/Edge-Enterprise#129]
In the Example, it might be helpful to include "contoso" as an example.  This is because when AuthServerAllowList is set, this seems to disable intranet detection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-policies#authserverallowlist)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@brkdncr Thanks!  I've passed this suggestion on to the team.

**Comment by Y-Kelly** [comment]
Clean up of old issues, this has been relayed to the team and they will update as necessary.  Also, you can submit feedback directly through the browser.  ("..." menu > Help and feedback > Send feedback).
