### ISSUE TITLE
If you follow the link that should open IE in enterprise mode, a window will open on Edge side as well

### ISSUE THREAD

**Issue by KazumaHorino** [MicrosoftDocs/Edge-Enterprise#13]
I have noticed that when you click a link that opens Internet Explorer in the Enterprise mode of the Chromium based Edge, for some reasons it opens a new empty tab, which has to be closed by the user.
If you could fix this, we can take out one step from the user and might be able to increase the user satisfaction.
Thank you.

**Comment by Y-Kelly** [comment]
Clean up of old issues.  If you are still having an issue and have Microsoft Unified Support, you can reach out to that support service for help or you can contact App Assure at https://aka.ms/AppAssure.
