### ISSUE TITLE
Will "Release notes for Microsoft Edge Stable Channel" be updated with 88.0.705.81?

### ISSUE THREAD

**Issue by Jand66** [MicrosoftDocs/Edge-Enterprise#130]
I noticed that the "Microsoft Edge Stable Channel" page is not updated with the 88.0.705.81 version which was released last week. Will this page be further updated or has this info moved to another page?

**Comment by Y-Kelly** [comment]
@Jand66 Hi!  I believe there is currently an issue with documentation publishing.  The information will be updated once resolved!  The release notes have not moved.  Thanks for checking!

**Comment by Jand66** [comment]
@Y-Kelly, thank you. Would there be any ETA on resolving the issue?

**Comment by Y-Kelly** [comment]
@Jand66 Should be updated now :) https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel#version-88070581-february-25

**Comment by Jand66** [comment]
Thank you!
