### ISSUE TITLE
Link to Microsoft Edge Policy Template does not work

### ISSUE THREAD

**Issue by woerndlit** [MicrosoftDocs/Edge-Enterprise#133]
In the section "Disable Internet Explorer 11 as a standalone browser" under "1. Download and install the latest Microsoft Edge Policy Template".

Error: The link directs to: "https://www.microsoft.com/en-us/business/download"
Possible solution: Direct the link to: "https://www.microsoft.com/en-us/edge/business/download"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b557e6ee-bb46-7b9c-108b-c78829c6d8b4
* Version Independent ID: dd39c398-eb44-ab64-69ee-d860147072df
* Content: [Disable Internet Explorer 11](https://docs.microsoft.com/en-us/deployedge/edge-ie-disable-ie11)
* Content Source: [edgeenterprise/edge-ie-disable-ie11.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-disable-ie11.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **shisub**

**Comment by dan-wesley** [comment]
@woerndlit This is fixed.
