### ISSUE TITLE
Broken Link under RoamingProfileLocation

### ISSUE THREAD

**Issue by tjc-jhol** [MicrosoftDocs/Edge-Enterprise#137]
The variable link under [RoamingProfileLocation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#roamingprofilelocation) goes to a 404 page.

The broken link is:  https://go.microsoft.com/fwlink/?linkid=2095041

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@tjc-jhol Thanks! This should be fixed now.  Closing issue.
