### ISSUE TITLE
This page refers to an earlier version of Edge. EG No longer is there a Sync reset option

### ISSUE THREAD

**Issue by keeneye** [MicrosoftDocs/Edge-Enterprise#138]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa2b6bb-c572-6b62-0b2a-5d11cc6c16c2
* Version Independent ID: bbd72cfb-0dd2-dce0-ede7-6887a2992bad
* Content: [Reset Microsoft Edge data](https://docs.microsoft.com/en-us/deployedge/edge-learnmore-reset-data-in-cloud)
* Content Source: [edgeenterprise/edge-learnmore-reset-data-in-cloud.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-reset-data-in-cloud.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **scottbo**

**Comment by Zian** [comment]
I observed that in Edge Version 95.0.1020.53 (Official build) (64-bit), after you sign out, there is no way to get to "Reset sync". "Reset sync" is only visible when you are signed in.

In case it helps, I've copied the documentation page's auto-generated text when I clicked to submit feedback and pasted the text below.

* ID: 3fa2b6bb-c572-6b62-0b2a-5d11cc6c16c2
* Version Independent ID: bbd72cfb-0dd2-dce0-ede7-6887a2992bad
* Content: [Reset Microsoft Edge data](https://docs.microsoft.com/en-us/deployedge/edge-learnmore-reset-data-in-cloud)
* Content Source: [edgeenterprise/edge-learnmore-reset-data-in-cloud.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-reset-data-in-cloud.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
Clean up of old issues.  Like previous answer provided, you need to sign in for the "Reset Sync" option to be available.
