### ISSUE TITLE
"Sites to open when the browser starts"

### ISSUE THREAD

**Issue by rpertusio** [MicrosoftDocs/Edge-Enterprise#139]
Please identify which version of Edge will support the Admin Template "Sites to open when the browser starts" in Assigned Access (single app) mode.

Intune referred to this setting as "Custom Start pages" under Device Restrictions for 'Microsoft Edge Legacy (Version 45 and earlier)'

**Comment by OftKilted** [comment]
> Please identify which version of Edge will support the Admin Template "Sites to open when the browser starts" in Assigned Access (single app) mode.
> 
> Intune referred to this setting as "Custom Start pages" under Device Restrictions for 'Microsoft Edge Legacy (Version 45 and earlier)'

If this is pointing to Edge Legacy in Intune, this would only support the non-chromium versions of MS Edge, due to the location of the policy. All of the Edge Chromium policies are not located in that policy location.

Can you indicate the full ADMX path of the policy for your inquiry?

**Comment by rpertusio** [comment]
It seems my comment isn't properly linked to the "Kiosk Mode" page I intended to comment on. I'm attaching it below.

The Admin Template setting being referenced:

\Microsoft Edge\Startup, home page and new tab page
     Action to take on startup = "Enabled" , "Open a List of URLs"
     Sites to open when the browser starts = "Enabled", "< URLs >"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 229e4d46-19a6-c042-8ce1-844c44c00112
* Version Independent ID: 8ab07629-42a6-e7a1-86a9-f8103825ebc4
* Content: [Configure Microsoft Edge kiosk mode](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode)
* Content Source: [edgeenterprise/microsoft-edge-configure-kiosk-mode.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-configure-kiosk-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @Aguta
* Microsoft Alias: **aguta**

**Comment by OftKilted** [comment]
> It seems my comment isn't properly linked to the "Kiosk Mode" page I intended to comment on. I'm attaching it below.
> 
> The Admin Template setting being referenced:
> 
> \Microsoft Edge\Startup, home page and new tab page
> Action to take on startup = "Enabled" , "Open a List of URLs"
> Sites to open when the browser starts = "Enabled", "< URLs >"
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 229e4d46-19a6-c042-8ce1-844c44c00112
> * Version Independent ID: 8ab07629-42a6-e7a1-86a9-f8103825ebc4
> * Content: [Configure Microsoft Edge kiosk mode](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode)
> * Content Source: [edgeenterprise/microsoft-edge-configure-kiosk-mode.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-configure-kiosk-mode.md)
> * Product: **microsoft-edge**
> * GitHub Login: @Aguta
> * Microsoft Alias: **aguta**

It looks like the intune policy is referencing the old legacy version, where this kiosk policy is referencing the current Chromium edition. The policy you’re linking calls out v87 or higher. Which is the current release level. Not legacy.

**Comment by rpertusio** [comment]
Sorry I'm not being clear, here.
I'm trying to open multiple URLs ("Sites to open when the browser starts") in Edge Chromium.

The documentation doesn't list this particular setting as being available in v89/v90/v91.  (Most other legacy Edge settings in the documentation have a release date for parity.)

- **Legacy Edge**:  "Custom Start Pages" (works OK for Legacy Edge, Win10 Assigned Access Kiosk mode)
- **Chromium Edge**: "Action to take on startup" and "Sites to open when the browser starts" (does NOT work in Chromium Edge, Win10 Assigned Access Kiosk mode)

Please indicate in the documentation which Chromium Edge version will support it.

**Comment by Y-Kelly** [comment]
@rpertusio Hello!  I've reached out to our Kiosk mode team.  

Here is there reply/recommendations: 

**_My understanding is that you are trying to open multiple URLs within different tabs for within Edge Kiosk mode Assigned Access Single App._** 

**_Are you trying to use the Digital\Interactive Signage (that runs full screen) or Public Browsing (tabbed browsing)?  I would presume this would be under the public browsing, which is a multi-tab experience._** 

**_It is possible to open multiple URLs, depending on how you are configuring assigned access:_** 

- **_Via Windows Settings \ Intune: in the field that you can configure the homepage just enumerate the sites you want to configure and separate them by space_**

_**For e.g.: site1.com site2.com site3.com**_

![image](https://user-images.githubusercontent.com/74324031/114104387-9d2a5d80-987f-11eb-89b7-6b35f72756d5.png)

 

- **_Via PowerShell: you can configure the command line and the same just enumerate the sites you want to configure and separate them by space_**

**_msedge.exe --kiosk www.contoso.com www.contoso2.com www.contoso3.com --edge-kiosk-type=public-browsing_** 

Let us know if there are any further questions.  Thanks!

**Comment by rpertusio** [comment]
Thank you.  Setting the 'space between' worked.

**For the Intune PG team (Intune/Windows)**
It would be helpful to specify the 'space' is the method for multiple URLs in Assigned Access Single-app Kiosk mode (w/ Public Browsing). The (i) info bubble (see arrow in my screenshot) would be a great place to put it.

**For the Intune or Edge (Kiosk) Documentation team:**
For reference, the transition of this functionality from OLD (legacy Edge) and NEW (Edge Chromium) wasn't clear.  Any improvements in documentation to clarify this would help the next person.

OLD vs NEW equivalent:

![image](https://user-images.githubusercontent.com/2339691/114236728-05e10b00-9950-11eb-8d6b-8a4545baa7ab.png)
![image](https://user-images.githubusercontent.com/2339691/114236663-f19d0e00-994f-11eb-817b-79a5bb732d70.png)

Thank you.  You can close this issue once you've taken whatever action you deem appropriate (with PG and/or documentation)

-Ryan

**Comment by Y-Kelly** [comment]
Thanks for the feedback! I've passed your suggestions on to the team.  Closing this issue now.
