### ISSUE TITLE
Edge sign in conditional access?

### ISSUE THREAD

**Issue by testad** [MicrosoftDocs/Edge-Enterprise#14]
Hi, I hope the feedback fits this page as it includes the Q&A. Can you please Specify if/how it is possible to use conditional access or other policy to restrict or condition Edge sign in attempts (desktop and mobile). If I now want to tie all these sensitive data to user identities, e.g password manager and form fill, how do I prevent compromised user credentials from being used by a malicious actor via Edge on an unmanaged device for example? Like we do with M365 resources. I only want allow Edge sign in for our user accounts on managed devices.

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ca3f20e-22b7-2d5a-67eb-0da9d27dcde8
* Version Independent ID: 7f6980c3-ce44-f0bc-fd76-bdf8cb7938b5
* Content: [Microsoft Edge Enterprise Sync](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-enterprise-sync)
* Content Source: [edgeenterprise/microsoft-edge-enterprise-sync.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-enterprise-sync.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **scottbo**

**Comment by joegoerlich** [comment]
Fully agree! We are also looking for a solution for that.
Same was asked also in #28 as well as at https://techcommunity.microsoft.com/t5/enterprise/azure-ad-conditional-access-for-edge-profile-sign-in/m-p/1538339

**Comment by nashuatek** [comment]
I too am looking for a solution for this. Do we know if MS is considering this as something they may plan to work on?

**Comment by Y-Kelly** [comment]
Clean up of old issues.  This discussion is a couple of years old.  Documentation for Conditional Access can be found here: https://docs.microsoft.com/en-us/deployedge/ms-edge-security-conditional-access

If you would like to report a Microsoft Edge Enterprise documentation issue to the team please open a new issue and include relevant information/repro steps in the Comment section.

If you have general questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsiderForum) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!

**Comment by Y-Kelly** [comment]
Following up as some documentation was recently updated: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-enterprise-sync-faq#is-it-possible-to-prevent-sign-in-and-sync-with-an-enterprise-account-on-an-unmanagednon-compliant-device

![image](https://user-images.githubusercontent.com/74324031/185214251-a05095e5-d716-4779-9cb5-c117379002ca.png)
