### ISSUE TITLE
Edge default startup parameters

### ISSUE THREAD

**Issue by soryusen** [MicrosoftDocs/Edge-Enterprise#141]
Hello team, 

I talked to a Windows advisor today, but they weren't able to help me and suggested I post here. 

My problem is the following. For a project of mine, I am running Chromium Edge in single-app kiosk Mode. This recently became available in the preview versions, and so far it is looking okay. However, due to the nature of the application, I need Edge to run with specific startup parameters. 

I have tested with Chrome running the following startup modifiers: --disable-web-security --disable-site-isolation-trials --user-data-dir="C://Chrome dev session"; those are working fine for the Chromium Edge as well, if added them to the target of the shortcut used to start the browser. 

disable-web-security - run the browser with CORS disabled;
disable-site-isolation-trials - needed to be able to properly run the cross-origin frames

When configuring kiosk mode, however, I do not have the option to add those. I've went over the currently available registries to check if there is one that I can set and have those modifiers added as a default Edge behavior, so that the kiosk mode runs them properly, yet I am currently unable to find such registries.

Is there the option to add some not-default windows registry in the Edge registries that can give me the same functionality?

Looking forward to your replies.

Best,
Nick

**Comment by ericlaw1979** [comment]
Generally, disabling web security features (using the two command line arguments you've identified here) is a very dangerous configuration and is not recommended. Can you elaborate a bit more about your scenario-- why do you need these flags set?

**Comment by soryusen** [comment]
Hello Eric,

Thank You for the reply. 
 

What we currently have is a locally operated website that must show in kiosk mode (single-app assigned access kiosk mode, luckily chormium edge can now be used with it). That website relies on iframes to visualize certain elements of a third-party vendor's website (that is running their proprietary  machine, so to us it is a black box). As we have no control over the vendor's code/environment, the only option that we have available is to use the iframes. Usually in an out-of-kioks-mode testing setup, we can easily run a shortcut with the required parameters and this is what we currently use for dev/testing purposes.

We are aware of the risks you mentioned, however the running setup does not allow for other options at this point. Also the setup does not allow for browsing public websites, it is limited to only the locally running website, so we believe we have the risks minimized. 
If we do not disable the cors though, the iframes cannot work properly and the entire flow does not work and we're getting the standard error:

`core.js:5980 ERROR DOMException: Blocked a frame with origin "http://localhost" from accessing a cross-origin frame.`

Another  thing is that I would prefer to be able to benefit from the added security features of the single-app kiosk mode, rather than running just Edge with --kiosk parameter  in any user context. The latter requires way too many additional tweaks and functionality disabling to be reliable, not to mention there is a brief moment where the loading process can be interrupted, in case the device running it gets "misplaced".

Hope that clears out our scenario and our request. Looking forward to hearing your thoughts.

Best regards,
Nick

**Comment by soryusen** [comment]
Any update on the above?

**Comment by Y-Kelly** [comment]
Clean up of old issues.  Normally GitHub Issues are used to report a Microsoft Edge Enterprise documentation issue.  Closing as there has not been any recent activity or updates.

If you still need help with this scenario, you can reach out to Support (https://developer.microsoft.com/en-us/microsoft-edge/support/) or the FastTrack team (https://docs.microsoft.com/en-us/fasttrack/products-and-capabilities#microsoft-edge) for assistance with MS Edge deployment.
