### ISSUE TITLE
Update information regarding behavior.

### ISSUE THREAD

**Issue by Mhudson97** [MicrosoftDocs/Edge-Enterprise#142]
When IE is disabled, it leaves the link on the task bar.  when a user clicks  on the link on the task bar it says, "can't open, would you like to remove this link?" 
This invalidates this note in the docs:

When users try to launch shortcuts or file associations that use IE11, they will be redirected to open the same file/URL in Microsoft Edge.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b557e6ee-bb46-7b9c-108b-c78829c6d8b4
* Version Independent ID: dd39c398-eb44-ab64-69ee-d860147072df
* Content: [Disable Internet Explorer 11](https://docs.microsoft.com/en-us/deployedge/edge-ie-disable-ie11)
* Content Source: [edgeenterprise/edge-ie-disable-ie11.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-disable-ie11.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **shisub**

**Comment by Y-Kelly** [comment]
@Mhudson97 Hi!  You mentioned a link is left on the taskbar, do you mean the IE11 icon?  If you can send a screenshot and also one of the error message that would be helpful.  Thank you!

**Comment by Y-Kelly** [comment]
Closing due to no reply.  Thanks!
