### ISSUE TITLE
WSUS support should be mentioned

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/Edge-Enterprise#143]
Everyone asking. Support for native WSUS updates without MECM should be mentioned or documented. If they are supported or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d806f80-9f3a-6c06-4465-116f40dd4b4b
* Version Independent ID: 25bfe392-86c0-2953-191f-7648985d956c
* Content: [Plan your deployment of Microsoft Edge](https://docs.microsoft.com/en-us/deployedge/deploy-edge-plan-deployment)
* Content Source: [edgeenterprise/deploy-edge-plan-deployment.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/deploy-edge-plan-deployment.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
Clean up of older issues.  More information about WSUS can be found here: 

- https://learn.microsoft.com/en-us/deployedge/microsoft-edge-frequently-asked-questions#does-windows-server-update-services-wsus-support-the-initial-deployment-of-microsoft-edge
- https://support.microsoft.com/en-us/topic/update-in-wsus-for-the-new-microsoft-edge-for-windows-10-version-1809-1903-1909-and-2004-october-29-2020-b4980418-4ec4-dee7-3b17-1c6499bd127c

If you need further help with WSUS or Microsoft Edge updates you can reach out to [Support - Microsoft Edge Developer](https://developer.microsoft.com/en-us/microsoft-edge/support/).  Thanks!
