### ISSUE TITLE
Kiosk Settings are GA

### ISSUE THREAD

**Issue by cconrado** [MicrosoftDocs/Edge-Enterprise#144]
Just wanted to confirm that most of these settings are already GA for Edge Chromium. I believe whats missing is just the setup for intune.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 229e4d46-19a6-c042-8ce1-844c44c00112
* Version Independent ID: 8ab07629-42a6-e7a1-86a9-f8103825ebc4
* Content: [Configure Microsoft Edge kiosk mode](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode)
* Content Source: [edgeenterprise/microsoft-edge-configure-kiosk-mode.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-configure-kiosk-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @Aguta
* Microsoft Alias: **aguta**

**Comment by Y-Kelly** [comment]
@cconrado Hi!  We've updated the documentation with the Windows/Microsoft Edge versions: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode#single-app-kiosk

Information about setting assigned access single app using Intune can be found here: https://www.youtube.com/watch?v=6WUOlGmQfNo&t=347s

Thanks!
