### ISSUE TITLE
Please provide example how to create value for Dictionary data type OMA-URI

### ISSUE THREAD

**Issue by bohdan-top** [MicrosoftDocs/Edge-Enterprise#145]
In this documentation [https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/configure-edge-with-mdm.md](url)
under section **Dictionary and String data type example** there is only example for string data type and I can't figure out how to specify values for Dictionary.

**Comment by Y-Kelly** [comment]
@bohdan-top Thanks for the feedback!  The team will work on updating our documentation.

**Comment by mkruger-msft** [comment]
@bohdan-top examples of setting ManagedFavorites, a dictionary policy, were added to the following sections:
[https://docs.microsoft.com/en-us/deployedge/configure-edge-with-mdm#dictionary-or-string-data-type](https://docs.microsoft.com/en-us/deployedge/configure-edge-with-mdm#dictionary-or-string-data-type)
[https://docs.microsoft.com/en-us/deployedge/configure-edge-with-mdm#dictionary-and-string-data-type-examples](https://docs.microsoft.com/en-us/deployedge/configure-edge-with-mdm#dictionary-and-string-data-type-examples)

I hope that provides a good working example and clears up proper usage. 

Thanks for the feedback.
