### ISSUE TITLE
Edge Stable release notes have been inaccurate

### ISSUE THREAD

**Issue by yamauchikazu** [MicrosoftDocs/Edge-Enterprise#146]
Recently, the release notes of Edge Stable have been inaccurate.

https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel

Incorrect info:
Version 89.0.774.74: April 12
Version 89.0.774.68: April 1

Correct info:
Version 89.0.774.76: April 12
Version 89.0.774.75: April 8
Version 89.0.774.68: April 1

**Comment by Y-Kelly** [comment]
@yamauchikazu Hello!  I believe the Release Notes have been updated: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel

Closing this issue.  Thanks!

**Comment by tasty0tomato** [comment]
> @yamauchikazu Hello! I believe the Release Notes have been updated: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel
> 
> Closing this issue. Thanks!

Maybe the release information should be with the release in the same time or just a little later, or it won't be helpful at all. Such as when edge 90 is release, I can finally know what happened in the last two 89.
