### ISSUE TITLE
Powershell Options

### ISSUE THREAD

**Issue by ManfredPohlemann** [MicrosoftDocs/Edge-Enterprise#147]
General feedback:
The documentation on the new MS Edge Kiosk Mode ist still horrible. Here only 3 examples:
- last link in "Multi-app kiosk" is broken
- Assigned Access for MS Edge is already enabled in Windows 1909 (information from Product Team during Ingite AMA session), no need for Beta or Insider Builds
- Kiosk experience setting via Assigned Access as stated in my question below is not explained

Question:
How do I set MS Edge Kiosk Mode for Digital Signage or Public Browsing if using Assigned Access? For Edge Legacy I had to set reg-keys - there is nothing said about it for the new Edge.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 229e4d46-19a6-c042-8ce1-844c44c00112
* Version Independent ID: 8ab07629-42a6-e7a1-86a9-f8103825ebc4
* Content: [Configure Microsoft Edge kiosk mode](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode)
* Content Source: [edgeenterprise/microsoft-edge-configure-kiosk-mode.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-configure-kiosk-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @Aguta
* Microsoft Alias: **aguta**

**Comment by Y-Kelly** [comment]
@ManfredPohlemann Hi!  Thank you very much for the feedback!  The team has made some updates to the documentation.  (https://docs.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode)

> * last link in "Multi-app kiosk" is broken

Link removed

> * Assigned Access for MS Edge is already enabled in Windows 1909 (information from Product Team during Ingite AMA session), no need for Beta or Insider Builds

Updated https://docs.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode#microsoft-edge-with-assigned-access

> * Kiosk experience setting via Assigned Access as stated in my question below is not explained

Setting assigned access single app can be done via a few methods: 
- Windows settings: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode#configure-using-windows-settings

- Intune: https://www.youtube.com/watch?v=6WUOlGmQfNo&t=347s

- Via MDM Bridge WMI Provider (powershell script) https://docs.microsoft.com/en-us/windows/configuration/kiosk-mdm-bridge 
Microsoft Edge is treated as a regular win32 app: 
`“<App DesktopAppPath="%ProgramFiles(x86)%\Microsoft\Edge\Application\msedge.exe" />” `

Closing this issue.  Thanks!
