### ISSUE TITLE
Profile Sync

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/Edge-Enterprise#148]
I have dozens of profiles depending on the customer I am supporting. Can these profiles also get synced?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fa7eda4-6e4c-c2c8-a29a-ef2eead7f04f
* Version Independent ID: 414db256-c14b-ca11-b2a7-835aa9c9e041
* Content: [Configure Microsoft Edge enterprise sync](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-enterprise-sync)
* Content Source: [edgeenterprise/microsoft-edge-enterprise-sync.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-enterprise-sync.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **scottbo**

**Comment by RAJU2529** [comment]
@makdaddy8888 , I have Microsoft personal account, whenever  I sign in new device profiles, favourites and passwordsare synced automatically across the devices until you sync is disabled in GPO

**Comment by Y-Kelly** [comment]
@makdaddy8888 If you are still having an issue with sync, Please reach out to support   https://microsoftedgesupport.microsoft.com/hc/en-us  They should be able to gather logs and help investigate your specific case.   Thanks!
