### ISSUE TITLE
Edge Stable release notes always not on time

### ISSUE THREAD

**Issue by tasty0tomato** [MicrosoftDocs/Edge-Enterprise#149]
Maybe the release information should be with the release in the same time or just a little later, or it won't be helpful at all. Such as when edge 90 is release, I can finally know what happened in the last two 89.

_Originally posted by @tasty0tomato in https://github.com/MicrosoftDocs/Edge-Enterprise/issues/146#issuecomment-821816200_

**Comment by Y-Kelly** [comment]
@tasty0tomato Thank you for your feedback, I've passed it on to the team. We are working to improve the process for our release notes!
