### ISSUE TITLE
typo in password manager doc

### ISSUE THREAD

**Issue by ericlaw1979** [MicrosoftDocs/Edge-Enterprise#152]
Typo:

have Microsof**R**t Edge installed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b166ffb-afd3-2808-de99-e69d31951868
* Version Independent ID: 629c1102-d959-1122-8200-41735ed9c667
* Content: [Microsoft Edge password manager security](https://review.docs.microsoft.com/en-us/DeployEdge/microsoft-edge-security-password-manager?branch=pr-en-us-424)
* Content Source: [edgeenterprise/microsoft-edge-security-password-manager.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-security-password-manager.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **supalsul**

**Comment by Y-Kelly** [comment]
@ericlaw1979 Hi! Confirmed the typo should be fixed in a newer draft of this document.  Closing this issue.  Let me know if you have questions!
