### ISSUE TITLE
PDF digital signature

### ISSUE THREAD

**Issue by hobpet** [MicrosoftDocs/Edge-Enterprise#153]
Thee **[view-and-validate-certificate-based-digital-signatures](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-pdf#view-and-validate-certificate-based-digital-signatures
)** section is misleading. 

The statement is that you can validate the certificate, but the matter of fact you cannot yet, only in non production channels.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bf00e03-8344-1808-bffb-f5abe0b423e5
* Version Independent ID: 139b136c-b2b9-ee14-7da3-ba23d5ee2fd3
* Content: [PDF reader in Microsoft Edge](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-pdf)
* Content Source: [edgeenterprise/microsoft-edge-pdf.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-pdf.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **adigan**

**Comment by Y-Kelly** [comment]
@hobpet Hello!  In the Prerequisites, support, and constraints section at the top of the page (https://docs.microsoft.com/en-us/deployedge/microsoft-edge-pdf#prerequisites-support-and-constraints) it specifically calls out what channel the feature is available.  

![image](https://user-images.githubusercontent.com/74324031/116626084-8b2c5f80-a8ff-11eb-808e-9ada6ae8da89.png)

The [View and validate certificate-based digital signatures ](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-pdf#view-and-validate-certificate-based-digital-signatures) section provides an explanation of the feature.  I will pass your feedback on to the team.  Thanks!
