### ISSUE TITLE
Question on the meaning of "turn off"

### ISSUE THREAD

**Issue by michael-searleATcentralaz-edu** [MicrosoftDocs/Edge-Enterprise#155]
[
Near the end of this document, there is a sentence which states

"We currently don't support the following features and recommend that you turn off."

The statement is followed by a list of features. In this case, does "turn off" mean that I should not configure any values for those settings, or does it mean that I should configure a value that disables the features?
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73109af0-4206-7ef1-daad-bd026d5c4dcc
* Version Independent ID: 67e2ceab-e8b2-08b0-d254-63455a666086
* Content: [Plan your kiosk mode transition](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-kiosk-mode-transition-plan)
* Content Source: [edgeenterprise/microsoft-edge-kiosk-mode-transition-plan.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-kiosk-mode-transition-plan.md)
* Product: **microsoft-edge**
* GitHub Login: @Aguta
* Microsoft Alias: **aguta**

**Comment by Y-Kelly** [comment]
@michael-searleATcentralaz-edu Hi!  Just to confirm, this document is mentioned in your issue: Content: [Plan your kiosk mode transition](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-kiosk-mode-transition-plan)

Are you actually referring to this section?  https://docs.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode#functional-limitations

Thanks!

**Comment by michael-searleATcentralaz-edu** [comment]
Yes, that is correct. Thank you for checking.

___________________________________________


Michael Searle

IT Analyst - Software

Central Arizona College

480-677-7854

________________________________

**Comment by Y-Kelly** [comment]
@michael-searleATcentralaz-edu I've talked to the kiosk mode team and they've said: 

**_Thank you for the feedback and we will be updating the text to better reflect the statement. 
We recommend that you should configure a value that disables the features._** 

Closing this issue.

**Comment by michael-searleATcentralaz-edu** [comment]
Thank you so much. I appreciate the clarification.

Best wishes,

Michael

___________________________________________


Michael Searle

IT Analyst - Software

Central Arizona College

480-677-7854

________________________________
