### ISSUE TITLE
"Allow Microsoft Edge to monitor user passwords" changed to "Configure password protection warning trigger"

### ISSUE THREAD

**Issue by alexbleicker** [MicrosoftDocs/Edge-Enterprise#16]
[Enter feedback here]
PasswordMonitorAllowed
Allow Microsoft Edge to monitor user passwords

This section is called "Configure password protection warning trigger" in Microsoft Endpoint Manager now

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1cd3ad5-bb4a-54ff-84e7-18ca0b11368f
* Version Independent ID: 984abd8f-45eb-737b-ad74-07ec8261f9eb
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-policies#passwordmonitorallowed)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
Clean up of old issues.  Looks like the policy documentation has been updated.  

![image](https://user-images.githubusercontent.com/74324031/178841883-e7a93fd7-66c2-410f-8abc-22aac4d3e0a7.png)
