### ISSUE TITLE
Edge 90 doen't start in Kiosk Mode

### ISSUE THREAD

**Issue by Fubaruba** [MicrosoftDocs/Edge-Enterprise#161]
It does start when using the command line, as described in https://docs.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode

But, when I choose the [Windows Setting Route](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode#configure-using-windows-settings) (that actually boots Windows in Kiosk Mode, I get the error:

`You App could not be started, press Ctrl Alt Delete or contact your administrator. Error code 0xfffffffff`

What should I do? If I rename the Edge folder (as some online sources suggest, it falls back to an old version of Chrome)

**Comment by Y-Kelly** [comment]
@Fubaruba Hello!  Can you share what version of Windows you are using when you are seeing the error?

**Comment by Fubaruba** [comment]
@Y-Kelly this is Windows 10 Pro on an Intel NUC pc. Both Windows and Edge have been updated to their latest versions. I have chosen to go a different route with our project though as Edge in kiosk mode has more issues for me (privacy mode when in kiosk mode for instance)...

**Comment by Y-Kelly** [comment]
@Fubaruba Thanks for following up!  I'll close this issue for now.  

If you have additional questions regarding Microsoft Edge apart from documentation issues please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
