### ISSUE TITLE
ADDITIONAL JAVA PLUGIN INSTALLATION

### ISSUE THREAD

**Issue by FamousBern** [MicrosoftDocs/Edge-Enterprise#164]
[Enter feedback here]
![image](https://user-images.githubusercontent.com/32365949/118363328-81138d80-b59c-11eb-8668-28a59046640e.png)

After enabling IE mode correctly in edge using GPO. Trying to open a java reports application we get the error in the attached snip, even after downloading and installing the plugin.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b539b61a-453d-9032-3f9c-8e0a537a8f7d
* Version Independent ID: 89647f8d-5793-5fab-d430-c549976ddad3
* Content: [IE mode troubleshooting and FAQ](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-faq)
* Content Source: [edgeenterprise/edge-ie-mode-faq.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode-faq.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **shisub**

**Comment by Y-Kelly** [comment]
@FamousBern Hello - Can you confirm the page is opening properly in IE mode?  

If it is in IE mode, there will be an IE logo in the address bar. 
![image](https://user-images.githubusercontent.com/74324031/118734858-1bb9d980-b7f4-11eb-887b-9e749ed62954.png)

Can you also share what version of MS Edge you are using?  In the upper-right corner of Microsoft Edge, select the ellipses icon (...), and then select Settings. Select About Microsoft Edge to see your version of Microsoft Edge.  Thanks!

**Comment by Y-Kelly** [comment]
Closing this issue as there has been no reply.  

If you have further questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
