### ISSUE TITLE
In My Experience Microsoft Edge Refuses to Install on Windows Server 2019

### ISSUE THREAD

**Issue by 5U8cVs** [MicrosoftDocs/Edge-Enterprise#165]
In My Experience Microsoft Edge Refuses to Install on Windows Server 2019.  I've tried twice.  The standard Microsoft muddle of web pages allowed me to download Microsoft Edge which eventually complained that the PC was running an OS older than Windows 7.   The plan at Microsoft was to eliminate the familiar end user interface part of Windows Server entirely for security reasons.  But there are many paying customers who would complain.  So there is a desktop version on offer which I am using.  Obviously a person who desires to run a browser will require an end user interface quite like the one in Windows 10.  The preferred end user interface (preferred by Microsoft) has a minimal end user interface that allows you to configure Windows Server 2019 using PowerShell.  PowerShell doesn't run a web browser.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86847b80-8f8e-9493-86ff-5dfd6412b48f
* Version Independent ID: 2ce02bc3-24a1-8c9f-c787-34ab90e9f31d
* Content: [Microsoft Edge Supported Operating Systems](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-supported-operating-systems)
* Content Source: [edgeenterprise/microsoft-edge-supported-operating-systems.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-supported-operating-systems.md)
* Product: **microsoft-edge**
* GitHub Login: @srugh
* Microsoft Alias: **srugh**

**Comment by Y-Kelly** [comment]
@5U8cVs Hi! Microsoft Edge is supported on Windows Server 2019.  

Here are a couple of options you can try to download: 

- Visit https://www.microsoft.com/en-us/edge and on the page select "Windows Server 2019" from the dropdown box

![image](https://user-images.githubusercontent.com/74324031/118567758-3bd19600-b72b-11eb-84d2-3b8c9e161b36.png)

- Visit https://www.microsoft.com/en-us/edge/features and scroll down the page to "Browse across devices", in that section you can click on "Using Windows Server? Get Microsoft Edge here." 

![image](https://user-images.githubusercontent.com/74324031/118568012-bbf7fb80-b72b-11eb-96f4-6d55d2043596.png)

Let us know if you are still having issues and if you have further questions regarding Microsoft Edge apart from documentation issues please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!

**Comment by Y-Kelly** [comment]
Closing due to no response.
