### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by JCFMachado** [MicrosoftDocs/Edge-Enterprise#166]
Hi, last paragraph you have "You can share the link of the location where the XML file is hosted, ". Shouldn't it be "where the CRX file is hosted,"

Best,
JM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d275477d-dfcc-30f8-431c-e73a346ae0c0
* Version Independent ID: 3f7c98ed-e7ff-1554-84dd-44319029900f
* Content: [Self-host Microsoft Edge extensions](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-manage-extensions-webstore)
* Content Source: [edgeenterprise/microsoft-edge-manage-extensions-webstore.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-manage-extensions-webstore.md)
* Product: **microsoft-edge**
* GitHub Login: @AndreaLBarr
* Microsoft Alias: **aspoddar**

**Comment by Y-Kelly** [comment]
@JCFMachado Thanks!  The team will take a look.

**Comment by ashishnirvana1** [comment]
Thanks for pointing this out. I have raised a PR to fix this issue.
