### ISSUE TITLE
Suggestions for German translation of "What is Internet Explorer (IE) mode?"

### ISSUE THREAD

**Issue by chk1** [MicrosoftDocs/Edge-Enterprise#167]
I have some minor suggestions to the German translation of the article ["Was ist der Internet Explorer (IE)-Modus?"](https://docs.microsoft.com/de-de/deployedge/edge-ie-mode#ie-mode-doesnt-support-the-following-internet-explorer-functionality) (["What is Internet Explorer (IE) mode?"](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode#ie-mode-doesnt-support-the-following-internet-explorer-functionality))

Current English text and translation:
> Browser Helper Objects
> Browserhilfsobjekte

Suggestion:
> Browserhilfsobjekte (Browser Helper Objects, BHOs)

The translated term "Browserhilfsobjekte" is not used much (couldn't find a lot on Microsoft sites via search engine), and since it's a technical term should probably include the original English term, similar to how it was done here: https://docs.microsoft.com/de-de/microsoft-edge/deploy/microsoft-edge-faq

---

Current English text and translation:
> IE11 or Microsoft Edge F12 developer tools
> IE11 oder Entwicklungstools von Microsoft Edge F12

Suggestion:
> IE11 oder Microsoft Edge F12 Entwicklungstools

The translation is wrong and does not make sense ("IE11 or Developer Tools from Microsoft Edge F12")

---

Lastly, the "Feedback" link at the bottom tries to create a new Issue in the archived repository [MicrosoftDocs/EdgeEnterprise](https://github.com/MicrosoftDocs/EdgeEnterprise), which results in a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 418ea780-28cd-c78d-8855-df5188dd4be9
* Version Independent ID: 15be2361-06cf-5683-9213-8aec3aebef67
* Content: [What is Internet Explorer mode?](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode#feedback)
* Content Source: [edgeenterprise/edge-ie-mode.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by TinaMcN** [comment]
@chk1 thanks for reporting these issues.  I'm checking with a German linguist specialist regarding your suggestions.
The Feedback link is not supposed to appear on the localized pages, I'm asking the localization vendors to remove it.   If you find any other feedback in the German Edge content you are welcome to log it via the English content and you can tag me (TinaMcN).

**Comment by TinaMcN** [comment]
@chk1 the German page is updated: "IE11 oder Entwicklungstools von Microsoft Edge F12" was changed to "IE11- oder Microsoft Edge F12-Entwicklungstools" and "Der IE-Modus unterstützt die folgenden Funktionen von Internet Explorer" was changed to "Im IE-Modus werden folgende Funktionen von Internet Explorer unterstützt".  The linguist decided to leave "Browserhilfsobjekte" as is.  The feedback link was removed.  Thanks again for reporting these issues, much appreciated!

**Comment by chk1** [comment]
Thanks!
