### ISSUE TITLE
Will InternetExplorerIntegrationLevel NeedIE (2) still work after June 15, 2022?

### ISSUE THREAD

**Issue by tukiyo** [MicrosoftDocs/Edge-Enterprise#168]
* [The future of Internet Explorer on Windows 10 is in Microsoft Edge | Windows Experience Blog](https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge/)

> The Internet Explorer 11 desktop application will be retired on June 15, 2022.

I think it would be better to add an expiration date to this statement for NeedIE (2),
or if it works for later days, please write it that.

![needie](https://user-images.githubusercontent.com/1517645/119238323-cc213800-bb7c-11eb-8612-5288266a1165.png)

**Comment by Y-Kelly** [comment]
@tukiyo After June 15, 2022, you won't be able to launch the IE11 stand-alone application.  IE mode is the path forward for any app or site that needs IE11 for any reason. If IE mode isn't working for a specific site or app, please let us know so we can fix any gaps with the feature.  I'll pass on the request to update our documentation.  Closing this issue.
