### ISSUE TITLE
Have chromium base version on change-log description

### ISSUE THREAD

**Issue by cooperd** [MicrosoftDocs/Edge-Enterprise#169]
Various companies use the beta channel to check backward compatibles and in some cases open issues for chromium when spotted a regression, it's easy to track on Chrome beta when the fix is apply and in which version it's release.

On Edge beta there's no transparency on which chromium base version it's relay on - so we (the companies) doesn't a clear understanding which Edge beta contain the fix / features that apply to both - Chrom and Edge.

Please add the base version of chromium or chromium commits log that are part of the next Beta release for better visibility. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 137aaa56-062f-5b4a-68c0-5357a72a3188
* Version Independent ID: 4329b647-dac9-9903-bc4e-25a3d7027ecc
* Content: [Microsoft Edge release notes for Beta Channel](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-beta-channel#feedback)
* Content Source: [edgeenterprise/microsoft-edge-relnote-beta-channel.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-relnote-beta-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @AndreaLBarr
* Microsoft Alias: **aguta**

**Comment by Y-Kelly** [comment]
@cooperd Thanks for the feedback! Will pass it along to the team.
