### ISSUE TITLE
AutoImportAtFirstRun fails when Chrome is configured with 'Set user data directory' value

### ISSUE THREAD

**Issue by OftKilted** [MicrosoftDocs/Edge-Enterprise#17]
### AutoImportAtFirstRun
https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#autoimportatfirstrun

When configured to "Enabled" and value "2 - Automatically imports all supported datatypes and settings from Google Chrome."

The data import fails if the Google Chrome Group Policy "Set user data directory" has been configured.  The import capture doesn't understand the data has been 'relocated' using the [Chromium User Data Directory Variables](https://www.chromium.org/administrators/policy-list-3/user-data-directory-variables) and a directory path.  And the Edge GPO doesn't allow defining where that profile data is pulled from.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1cd3ad5-bb4a-54ff-84e7-18ca0b11368f
* Version Independent ID: 984abd8f-45eb-737b-ad74-07ec8261f9eb
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-policies)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@OftKilted Cleaning up old issues.  This feature is not supported yet.  The team does have it on the roadmap but there is no ETA.  They are aware of this GitHub issue that you opened and will reach out if more information is necessary.
