### ISSUE TITLE
Please provide more information about the process model

### ISSUE THREAD

**Issue by jjpearce** [MicrosoftDocs/Edge-Enterprise#170]
Will you please add more information about the process model when using IE Mode? For example, how does TabProcGrowth work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 418ea780-28cd-c78d-8855-df5188dd4be9
* Version Independent ID: 15be2361-06cf-5683-9213-8aec3aebef67
* Content: [What is Internet Explorer mode?](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode)
* Content Source: [edgeenterprise/edge-ie-mode.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by Y-Kelly** [comment]
@jjpearce Thanks for the feedback!  Will pass it on to the team.
