### ISSUE TITLE
microsoft-edge-policy-map-legacy-to-newedge Missing

### ISSUE THREAD

**Issue by CharingJC** [MicrosoftDocs/Edge-Enterprise#174]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffa86de3-3cf2-da5b-2e15-42ddca111985
* Version Independent ID: 053e9ece-0f7d-b1c2-bfd6-18e2dbfebf29
* Content: [Microsoft Edge policy mapping overview](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policy-map-overview)
* Content Source: [edgeenterprise/microsoft-edge-policy-map-overview.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policy-map-overview.md)
* Product: **microsoft-edge**
* GitHub Login: @BrianAlt
* Microsoft Alias: **brianalt**

**Comment by Y-Kelly** [comment]
@CharingJC Hello!  Microsoft Edge Legacy support ended on March 9th (https://blogs.windows.com/msedgedev/2021/03/09/microsoft-edge-legacy-end-of-support/) and the policy mapping documentation has been removed.  We will be updating https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policy-map-overview today to remove the broken link.  Thanks for the feedback!  Please let us know if you have any further questions.
