### ISSUE TITLE
Accidentally linking to site restricted to Microsoft staff only? 

### ISSUE THREAD

**Issue by grnathan** [MicrosoftDocs/Edge-Enterprise#175]
This article opens with:

```
This article describes the options and steps for managing extensions by using group policies. These options assume that you already have Microsoft Edge managed for your users. If you have not already set up Microsoft Edge to be managed for your users please follow the below link to do so now.

- [Manage Microsoft Edge extensions in the enterprise](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Freview.docs.microsoft.com%2Fen-us%2FDeployEdge%2Fmicrosoft-edge-manage-extensions%3Fbranch%3Dpr-en-us-565&data=04%7C01%7Cv-andreabarr%40microsoft.com%7C6e4d287e8b014524d8d808d8fa6bc8a4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637534688176646040%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=drRb3DhNVZJO0uKX9MfE5%2BjGAflHyCSUoGOPqRr5U7Q%3D&reserved=0)


```
where "Manage Microsoft Edge extensions in the enterprise" is the anchor text for a hyperlink that 

a) looks like it contains SafeLinks metadata so the document will be assessed for malware content each time someone reading Microsoft Docs clicks on it.

b) looks like it points to a site 'review.docs.microsoft.com' that is not accessible to the general public / ITPro audience for whom this article has been published. 

I anticipate both of these issues were inadvertent and can be easily fixed by updating the target URL specified by the Hyperlink above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc77d006-bbf3-747e-4d7c-573e57680174
* Version Independent ID: b9ed5785-c4a5-19b6-fbd7-1a3d30027f08
* Content: [Use group policies to manage Microsoft Edge extensions](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-manage-extensions-policies)
* Content Source: [edgeenterprise/microsoft-edge-manage-extensions-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-manage-extensions-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @AndreaLBarr
* Microsoft Alias: **aspoddar**

**Comment by Y-Kelly** [comment]
@grnathan Thanks for pointing that out!  I believe this is the correct link https://docs.microsoft.com/en-us/deployedge/microsoft-edge-manage-extensions.  We'll work on updating.

**Comment by Y-Kelly** [comment]
Link has been updated.  Thanks!
