### ISSUE TITLE
IE Mode Without Enterprise Mode Site List

### ISSUE THREAD

**Issue by monkeyskullfire** [MicrosoftDocs/Edge-Enterprise#176]
This is regarding the question "Can I open a site in IE mode without an Enterprise Mode Site list?".  On Edge 91.0.864.41, using this flag results in a banner stating it's an unsupported command line flag and there is no "Open sites in Internet Explorer mode" option in the More Tools menu.  Is this information outdated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28703ce7-f6f6-da62-358a-541989933804
* Version Independent ID: 89647f8d-5793-5fab-d430-c549976ddad3
* Content: [IE mode troubleshooting and FAQ](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-faq)
* Content Source: [edgeenterprise/edge-ie-mode-faq.yml](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode-faq.yml)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **shisub**

**Comment by Y-Kelly** [comment]
@monkeyskullfire Hi!  I am testing with MS Edge Version 92.0.902.30 (Official build) beta (64-bit) and I'm able to see the "Open sites in Internet Explorer mode" option.  

![image](https://user-images.githubusercontent.com/74324031/123868951-3bf5b180-d8e5-11eb-812d-bca6e9187b5e.png)

If you are still having an issue, please take a look at the new InternetExplorerIntegrationReloadInIEModeAllowed policy https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#internetexplorerintegrationreloadiniemodeallowed, which may help.  Thanks!

**Comment by monkeyskullfire** [comment]
@Y-Kelly The "Open sites in Internet Explorer mode" option is working for me now (via policy InternetExplorerIntegrationTestingAllowed).  However, the new InternetExplorerIntegrationReloadInIEModeAllowed doesn't appear to be working.  https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#internetexplorerintegrationreloadiniemodeallowed explains how to implement it, but does not explain how to use it.  I don't see any additional options in the menu to reload the page in IE mode, unless I also have InternetExplorerIntegrationTestingAllowed enabled (which is now deprecated).

**Comment by Y-Kelly** [comment]
@monkeyskullfire Please see the documentation that explains more in depth: https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-local-site-list

Thanks!

**Comment by Y-Kelly** [comment]
Closing this issue.  If you have further questions regarding Microsoft Edge not related to the documentation please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
