### ISSUE TITLE
Extended Stable

### ISSUE THREAD

**Issue by oswiz** [MicrosoftDocs/Edge-Enterprise#178]
Customers are told that they can opt for Extended Stable but nothing in the documentation tells them how to do that--what action they have to take to get on Extended Stable--and they are concerned about that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d1bc306-56a5-f501-b3e0-a661d57b1db4
* Version Independent ID: e4ef685b-8570-be80-9547-9956042b967e
* Content: [Microsoft Edge release schedule](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-release-schedule?ranMID=24542&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-5KOwUptElDmCjnIoFW.feA&epi=je6NUbpObpQ-5KOwUptElDmCjnIoFW.feA&irgwc=1&OCID=AID2000142_aff_7593_1243925&tduid=%28ir__rit9vefn0kkfqwa1kk0sohzgkn2xurqvwxwjkq6r00%29%287593%29%281243925%29%28je6NUbpObpQ-5KOwUptElDmCjnIoFW.feA%29%28%29&irclickid=_rit9vefn0kkfqwa1kk0sohzgkn2xurqvwxwjkq6r00)
* Content Source: [edgeenterprise/microsoft-edge-release-schedule.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-release-schedule.md)
* Product: **microsoft-edge**
* GitHub Login: @AndreaLBarr
* Microsoft Alias: **aguta**

**Comment by Y-Kelly** [comment]
@oswiz Please see the new blog post with more information about Extended Stable: https://blogs.windows.com/msedgedev/2021/07/15/opt-in-extended-stable-release-cycle/

Thanks!
