### ISSUE TITLE
"Disable Internet Explorer 11 as a standalone browser" Policy Setting Not Available in 20H2 ADMX

### ISSUE THREAD

**Issue by USCloud-EricWilborn** [MicrosoftDocs/Edge-Enterprise#179]
Good afternoon. The "Disable Internet Explorer 11 as a standalone browser" Policy setting is not available in 20H2 ADMX. I've downloaded and searched through the ADML file. However, it is present in the 21H1 ADMX hosted by MS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b557e6ee-bb46-7b9c-108b-c78829c6d8b4
* Version Independent ID: dd39c398-eb44-ab64-69ee-d860147072df
* Content: [Disable Internet Explorer 11](https://docs.microsoft.com/en-us/deployedge/edge-ie-disable-ie11)
* Content Source: [edgeenterprise/edge-ie-disable-ie11.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-disable-ie11.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **shisub**

**Comment by Y-Kelly** [comment]
@USCloud-EricWilborn Hi! For 20H2 machines, specific Windows Updates is required.  Please see our documentation for more info:  https://docs.microsoft.com/en-us/deployedge/edge-ie-disable-ie11#prerequisites

Let us know if you are still having an issue after updating.  Thanks!

**Comment by Y-Kelly** [comment]
Closing issue, there has been no reply.
