### ISSUE TITLE
Link to download policies for legacy edge only let you download the policies for the new edge

### ISSUE THREAD

**Issue by grantborthwick** [MicrosoftDocs/Edge-Enterprise#18]
The link to Install the Policy Definitions from [Microsoft Edge for Business](https://www.microsoft.com/edge/business/download) no longer appears to have policies for legacy edge. Everything on the page is for the new edge.

![image](https://user-images.githubusercontent.com/2301725/84087137-24344e00-a9af-11ea-82af-9941fdaca838.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d96bfa14-a7be-f140-f914-564fe81c94e8
* Version Independent ID: 8343f63e-b2e4-27bc-11ad-3db51c4e3f03
* Content: [Access the old version of Microsoft Edge](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-sysupdate-access-old-edge)
* Content Source: [edgeenterprise/microsoft-edge-sysupdate-access-old-edge.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-sysupdate-access-old-edge.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **jtkim**

**Comment by Y-Kelly** [comment]
Cleaning up old issues.  Closing.  Support for Microsoft Edge Legacy ended on March 9, 2021
