### ISSUE TITLE
The "extension installforcelist" also applies to Enterprise.

### ISSUE THREAD

**Issue by Rina-Nakagawa** [MicrosoftDocs/Edge-Enterprise#180]
The actual behavior is different from the description of "extension install force list".
In the explanation, it is described as follows.

---------
On Microsoft Windows instances, apps and extensions from outside the Microsoft Edge Add-ons website can only be forced installed if the instance is joined to a Microsoft Active Directory domain, and running Windows 10 Pro.
---------

In fact, it works fine with Enterprise editions as well as Windows 10 pro.

Please correct the documentation. ASAP.

The documentation on the Google Chrome side has the same explanation. Copy and paste is not recommended, no matter how much you use the same policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#feedback)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@Rina-Nakagawa Thanks!  I've passed your feedback on to the team about updating the documentation.

**Comment by Rina-Nakagawa** [comment]
Thank you so much for your sincere correspondence to my requests.

**Comment by Y-Kelly** [comment]
@Rina-Nakagawa Hello! The documentation for the ExtensionInstallForcelist Policy has been updated.  

https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#extensioninstallforcelist

Thank you!
