### ISSUE TITLE
Dealing with 2 schemes

### ISSUE THREAD

**Issue by timothy-lam** [MicrosoftDocs/Edge-Enterprise#181]
Please can you include how to deal with addresses formatted with blob:https:// where two scheme exist.
Or update to say its not possible if that's the case.

Tried adding the below to ExemptDomainFileTypePairsFromFileTypeDownloadWarnings which all fail:
{"domains": ["example.dynamics.com"], "file_extension": "msg"}
{"domains": ["blob:https://example.dynamics.com"], "file_extension": "msg"}
{"domains": ["blob://https://example.dynamics.com"], "file_extension": "msg"}

The only way its been achieved thus far is with the wildcard which defeats the point of this security feature
{"domains": ["*"], "file_extension": "msg"}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ef3dced-d3dd-cc50-1f19-9d3d1daed0ea
* Version Independent ID: 38ce76ad-83dc-efc5-d27e-7ef903e567b0
* Content: [Filter format for Microsoft Edge URL policies](https://docs.microsoft.com/en-us/DeployEdge/edge-learnmmore-url-list-filter%20format#additional-filter-information)
* Content Source: [edgeenterprise/edge-learnmmore-url-list-filter format.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmmore-url-list-filter format.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **brianalt**

**Comment by Y-Kelly** [comment]
@timothy-lam Hello!  I can see our developers are currently working on an update so the ExemptDomainFileTypePairsFromFileTypeDownloadWarnings Policy will support blob: urls, which might be the issue you are encountering.  We can follow up once the update is available.  Thanks!

**Comment by Y-Kelly** [comment]
@timothy-lam Our developers released a fix available in MS Edge Canary Version 93.0.953.0+ and ExemptDomainFileTypePairsFromFileTypeDownloadWarnings should now support blob: urls.  Please try and see if your issue still reproduces on a newer build.  Thanks!

**Comment by Y-Kelly** [comment]
Closing issue.  If you have further questions regarding Microsoft Edge and not related to documentation please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
