### ISSUE TITLE
Document refers to Deprecated PowerShell module

### ISSUE THREAD

**Issue by alex-pontin** [MicrosoftDocs/Edge-Enterprise#182]
This document (specifically in troubleshooting steps 4 + 5 for the 'Issue: “**Sync is not available for this account**.”' sub header) references the AADRM PowerShell module which is deprecated, it needs to be updated to refer to the new AIPService module.
                                               
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33cc47c1-b277-96a1-8db2-411e3a4036e8
* Version Independent ID: d3c665a7-96f6-150f-d905-d33a7ff40a28
* Content: [Diagnose and fix Microsoft Edge sync issues](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-troubleshoot-enterprise-sync)
* Content Source: [edgeenterprise/microsoft-edge-troubleshoot-enterprise-sync.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-troubleshoot-enterprise-sync.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **scottbo**

**Comment by Y-Kelly** [comment]
@alex-pontin Thanks!  I've reached out to the team about updating the documentation.

**Comment by Y-Kelly** [comment]
@alex-pontin We've updated the documentation.  Thanks for letting us know!
