### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by KevinNSTA** [MicrosoftDocs/Edge-Enterprise#184]
Several broken links on here. Like `./microsoft-edge/extensions-chromium/developer-guide/alternate-distribution-options`  and I see two more "./" links around 

`./microsoft-edge/extensions-chromium/enterprise/hosting-and-updating` and 
`./powershell/module/microsoft.powershell.utility/get-filehash` 

there are also some other broken or self-referencing links on this other page https://github.com/MicrosoftDocs/Edge-Enterprise/issues/183 so some of the others could be off too and wrong, but this is what I found 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@KevinNSTA Thanks!  We'll work on getting these updated.

**Comment by Y-Kelly** [comment]
@KevinNSTA The links in the documentation have been updated.  Thanks again!
