### ISSUE TITLE
ExemptDomainFileTypePairsFromFileTypeDownloadWarnings - Group Policy does not seem to work.

### ISSUE THREAD

**Issue by sullcromenterprise** [MicrosoftDocs/Edge-Enterprise#185]
[Enter feedback here]
ExemptDomainFileTypePairsFromFileTypeDownloadWarnings

I have tried all these variations including the ones in teh example and it has not worked.  Not sure what is wrong.

{"domains": ["office.com”], "file_extension": "*"}
[{"domains": ["office.com”], "file_extension": "*"}]
{"file_extension": "*", "domains": ["office.com”], }
[{"file_extension": "*", "domains": ["office.com”], }]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@sullcromenterprise Hi! For questions like this we have the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise).  

There has been an ongoing conversation about this specific policy and a user has shared their specific tested working example, please see: https://techcommunity.microsoft.com/t5/enterprise/smartscreen-turned-off-gt-java-webstart-jnlp-files-are-marked-as/m-p/1584480/highlight/true#M2272


Thanks!

**Comment by DonPick** [comment]
the example in the docs is still unclear and this poor example makes it hard to get the setting working correctly. 
The Group Policy settings for 'Disable download file type extension-based warnings for specified file types on domains', requires an array/table of values to be entered. The example in docs attempts to articulate this by showing 'square brackets', but these square brackets surrounding the array/table must NOT be entered into the GP editor, and, each file_extension MUST be entered on a separate line in the editor, or the policy will not apply.

Example:

The following example value would prevent file type extension-based download warnings on jnlp, msg, and vsd extensions for telstrx.com & telstrx.com.au domains. It will show the user a file type extension-based download warning on any other domain for jnlp, msg and vsd files.

_[ { "file_extension": "jnlp", "domains": ["telstrx.com", "telstrx.com.au"] }, { "file_extension": "msg", "domains": ["telstrx.com", "telstrx.com.au"] }, { "file_extension": "vsd", "domains": ["telstrx.com", "telstrx.com.au"] } ]_

>> do NOT enter the enclosing square brackets <<
>> you MUST load each on a separate line <<

this is actually entered like so:
Value
{ "file_extension": "jnlp", "domains": ["telstrx.com", "telstrx.com.au"] }
{ "file_extension": "msg", "domains": ["telstrx.com", "telstrx.com.au"] }
{ "file_extension": "vsd", "domains": ["telstrx.com", "telstrx.com.au"] }

Further, the linked discussion in TechCommunity does NOT usefully illustrate this issue nor how to solve it within GP editor.
Regards

DonP
