### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by martospy** [MicrosoftDocs/Edge-Enterprise#186]
It looks like the version links are broken and missing the DeployEdge/ in their URLs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d1bc306-56a5-f501-b3e0-a661d57b1db4
* Version Independent ID: e4ef685b-8570-be80-9547-9956042b967e
* Content: [Microsoft Edge release schedule](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-release-schedule)
* Content Source: [edgeenterprise/microsoft-edge-release-schedule.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-release-schedule.md)
* Product: **microsoft-edge**
* GitHub Login: @AndreaLBarr
* Microsoft Alias: **aguta**

**Comment by AndreaLBarr** [comment]
@martospy Thank you for reporting this. I have fixed the links. It may take up to half an hour for them to be live on the Doc's site.  I am going to close this Issue as resolve.
