### ISSUE TITLE
Variable ${client_name} is written with closing parenthesis instead brace

### ISSUE THREAD

**Issue by dfs-** [MicrosoftDocs/Edge-Enterprise#187]
On the page in the variables, which are Windows only it is named

`${client_name)` (notice the parenthesis)

instead of 

`${client_name}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 368f8445-849a-3cf6-527d-51a0cda7e921
* Version Independent ID: d773ce6f-7153-1c82-d2c8-76d66b0435e5
* Content: [Create Microsoft Edge user data directory variables](https://docs.microsoft.com/en-us/DeployEdge/edge-learnmore-create-user-directory-vars#feedback)
* Content Source: [edgeenterprise/edge-learnmore-create-user-directory-vars.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-create-user-directory-vars.md)
* Product: **microsoft-edge**
* GitHub Login: @AndreaLBarr
* Microsoft Alias: **brianalt**

**Comment by RAJU2529** [comment]
@dfs- Thanks for pointing out.

**Comment by Y-Kelly** [comment]
@dfs- @RAJU2529 Thanks! The documentation has been updated.
