### ISSUE TITLE
These instructions don't apply at all to Edge version 91

### ISSUE THREAD

**Issue by anthonynz** [MicrosoftDocs/Edge-Enterprise#188]
The instructions here are completely unrelated to Edge version 91, but the page says it applies to version 88+

Step 1 back up your favourites is not possible.
* There is no "Settings and more" option.
* There is no "Favourites" under settings.

I was sent to this page from within Edge / Settings / Profiles.

It has the following message:

_We're having trouble syncing browsing data across your signed-in devices. [Learn more](https://go.microsoft.com/fwlink/?linkid=2150968)_

Microsoft Edge
Version 91.0.864.59 (Official build) (64-bit)

I have 3 profiles in Edge, and two of them are syncing fine, it's just one that has decided to stop syncing.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa2b6bb-c572-6b62-0b2a-5d11cc6c16c2
* Version Independent ID: bbd72cfb-0dd2-dce0-ede7-6887a2992bad
* Content: [Reset Microsoft Edge data](https://docs.microsoft.com/en-us/deployedge/edge-learnmore-reset-data-in-cloud?source=docs)
* Content Source: [edgeenterprise/edge-learnmore-reset-data-in-cloud.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-reset-data-in-cloud.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **collw**

**Comment by RAJU2529** [comment]
@anthonynz . I also confirmed, those settings are not there.

**Comment by Y-Kelly** [comment]
@anthonynz @RAJU2529 Please see the following which should explain the instructions more and hopefully will help! 

- Settings and more can be found in the upper-right corner of Microsoft Edge (the ellipses icon ...) 

![image](https://user-images.githubusercontent.com/74324031/124815464-27846b00-df1c-11eb-96c3-8c92215d3058.png)

- Then select Favorites 

- Then in the Favorites menu select More options (the ellipses icon …) 

![image](https://user-images.githubusercontent.com/74324031/124815751-7d591300-df1c-11eb-84ab-263a41a3bcfb.png)

- and select Export favorites

I'll reach out to the team and see if the documentation can be updated to include more information.  Let us know if you are still having an issue finding with exporting your favorites.  Thanks! 

_-Kelly_

**Comment by anthonynz** [comment]
Thanks Kelly,

I can find each of the functions in the instructions if I look for it, but it doesn't change fact that the instructions are wrong on the entire page.

It's like it was written for a different product.

I don't really want to waste my time on it if it doesn't solve my profile syncing issue.

**Comment by Y-Kelly** [comment]
@anthonynz Hi!  If you can explain which instructions are wrong I can make sure to pass on your feedback to the team.  Thanks!

**Comment by RAJU2529** [comment]
@Y-Kelly . Still  v91 is stable and officially supported, so I seen settings on v91, according to that version, I changed settings  and I created PR

**Comment by Y-Kelly** [comment]
Documentation has been updated.  Closing issue.
