### ISSUE TITLE
ExternalProtocolDialogShowAlwaysOpenCheckbox documentation doesn't say anything about not being respected when sites are http

### ISSUE THREAD

**Issue by PockyBum522** [MicrosoftDocs/Edge-Enterprise#19]
Please, please, mention in docs that ExternalProtocolDialogShowAlwaysOpenCheckbox DOES NOT RESPECT being enabled in edge://flags if you are trying to view a site over http.

I've been trying to use it with an intranet site that we're not terribly worried about serving over https at the moment but it would not work, no matter what with the latest edge update. (83.0.478.44) 

All edge chromium documentation mentions nothing about the checkbox ONLY showing up when a site is served over https no matter what you have this flag set to.

We were using it just fine until the latest update, and then I had the darnedest time tracking it down when it suddenly disappeared. Now I know why.

Thank you

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1cd3ad5-bb4a-54ff-84e7-18ca0b11368f
* Version Independent ID: 984abd8f-45eb-737b-ad74-07ec8261f9eb
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#http-authentication-policies)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
Clean up of old issues.  Confirmed that documentation states "This policy only applies to https:// links."  https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#externalprotocoldialogshowalwaysopencheckbox
