### ISSUE TITLE
Adding comment to identify extension ID

### ISSUE THREAD

**Issue by v1lden** [MicrosoftDocs/Edge-Enterprise#190]
RE: Administrative Templates > Microsoft Edge > Extensions > Allow specific extensions to be installed

It would be great to be able to identify an extension ID at a glance within the group policy settings e.g. allow a comment.

This may be possible but not documented on docs.microsoft but from what I can tell, there is no option to comment/identify an extension, only a value field for a extension ID which would require us to record or manually lookup the ID outside of GPMC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc77d006-bbf3-747e-4d7c-573e57680174
* Version Independent ID: b9ed5785-c4a5-19b6-fbd7-1a3d30027f08
* Content: [Use group policies to manage Microsoft Edge extensions](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-manage-extensions-policies)
* Content Source: [edgeenterprise/microsoft-edge-manage-extensions-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-manage-extensions-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @AndreaLBarr
* Microsoft Alias: **aspoddar**

**Comment by Y-Kelly** [comment]
@v1lden Hi!  The extensions team has created a separate space on GitHub for feedback like this.  Please see https://github.com/microsoft/MicrosoftEdge-Extensions and you can either open an Issue or Discussion.  Thanks!
