### ISSUE TITLE
JSON notation fails to describe InPrivate checkbox

### ISSUE THREAD

**Issue by middletonk** [MicrosoftDocs/Edge-Enterprise#194]
The Edge extensions UI has a checkbox to allow extensions in InPrivate mode. There are zero mentions of "InPrivate" in this article. How can this behavior/checkbox be replicated in JSON notation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06f0b77d-8fc4-90c1-93cb-e781352efdf2
* Version Independent ID: 2a21fd70-443b-8ac1-4541-d5b6bf882881
* Content: [Detailed guide to the ExtensionSettings policy](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-manage-extensions-ref-guide)
* Content Source: [edgeenterprise/microsoft-edge-manage-extensions-ref-guide.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-manage-extensions-ref-guide.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **aspoddar**

**Comment by Y-Kelly** [comment]
@middletonk Hi! The extensions team has created a separate space on GitHub for feedback like this. Please see https://github.com/microsoft/MicrosoftEdge-Extensions and you can either open an Issue or Discussion. Thanks!
