### ISSUE TITLE
--ie-mode-test flag appears to no longer work

### ISSUE THREAD

**Issue by jeff-bb** [MicrosoftDocs/Edge-Enterprise#196]
Looks like there were changes to the space in 86 and against 92. There are some new GPOs to control the behavior as well, as documented at https://support.microsoft.com/en-us/office/internet-explorer-mode-in-microsoft-edge-6604162f-e38a-48b2-acd2-682dbac6f0de?ui=en-us&rs=en-us&ad=us . That documentation could stand to be merged into this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28703ce7-f6f6-da62-358a-541989933804
* Version Independent ID: 89647f8d-5793-5fab-d430-c549976ddad3
* Content: [IE mode troubleshooting and FAQ](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-faq)
* Content Source: [edgeenterprise/edge-ie-mode-faq.yml](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode-faq.yml)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **shisub**

**Comment by Y-Kelly** [comment]
@jeff-bb Hello!  Just to confirm, what version of MS Edge are you using where you noticed the --ie-mode-test flag is not working?  Thanks!

**Comment by jeff-bb** [comment]
91+

**Comment by Y-Kelly** [comment]
@jeff-bb I'm using Version 92.0.902.55 (Official build) beta (64-bit) and was able to use the command line flag.  

![image](https://user-images.githubusercontent.com/74324031/126567648-e3f895d0-797e-418e-808e-2421bf09588c.png)

Did you see any error messages?

**Comment by jeff-bb** [comment]
I received the same "unsupported command line flag" message, showing that it at least was aware of it -- but the More tools options were not present. It wasn't until I altered GPO to turn it on that it would show up (regardless of command line). 

This image is on a device with no GPOs set, 91.0.864.71. As a work around, we are deploying the GPOs that enable it without the command line option, but documentation wise there appears to be some discrepancy.

![image](https://user-images.githubusercontent.com/38505668/126569067-316173e0-6c9e-4e13-a3f8-2e9749c5622f.png)

**Comment by Y-Kelly** [comment]
@jeff-bb You mentioned needing to use GPO.  Are you using [InternetExplorerIntegrationReloadInIEModeAllowed](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#internetexplorerintegrationreloadiniemodeallowed) or [InternetExplorerIntegrationTestingAllowed](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#internetexplorerintegrationtestingallowed)?

Appreciate the feedback!  I can let the IE mode team know and check about updating the FAQ.

**Comment by jeff-bb** [comment]
Because of the version divide, I'm currently setting both. Once we have everything at >=92 we will just use the newer one.

**Comment by Y-Kelly** [comment]
@jeff-bb Thanks again!  We've removed that specific portion of the FAQ for the time being.
