### ISSUE TITLE
Edge Kiosk mode with silent printing - how?

### ISSUE THREAD

**Issue by shapeh** [MicrosoftDocs/Edge-Enterprise#197]
How do I launch Microsoft Edge with parameters? I am especially interested in launching Edge with the `--kiosk-printing` option, so that the print dialogue box does not appear. 
I have posted my troubles here: https://stackoverflow.com/questions/68322730/how-to-set-up-microsoft-edge-chromium-in-kiosk-mode-with-silent-printing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 229e4d46-19a6-c042-8ce1-844c44c00112
* Version Independent ID: 8ab07629-42a6-e7a1-86a9-f8103825ebc4
* Content: [Configure Microsoft Edge kiosk mode](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode)
* Content Source: [edgeenterprise/microsoft-edge-configure-kiosk-mode.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-configure-kiosk-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @Aguta
* Microsoft Alias: **aguta**

**Comment by Y-Kelly** [comment]
Clean up of old issues.  The team does have --kiosk-printing in the backlog but there is no ETA.  You can also submit feature requests through the browser.  ("..." menu > Help and feedback > Send feedback)

Currently "UI print settings lockdown" is a supported feature in kiosk mode (Link to documentation: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode#kiosk-mode-supported-features)
