### ISSUE TITLE
Printing policies - silent print 

### ISSUE THREAD

**Issue by shapeh** [MicrosoftDocs/Edge-Enterprise#198]
We are in the need of policy for silent printing, i.e. the same as passing `--kiosk-printing` to msedge.exe.
We are using Edge in Kiosk mode to print labels / name tags at a reception. The policy would come in handy since you cannot pass parameters to msedge.exe in Assigned Access / Kiosk mode via Windows Settings.

We have looked for settings in GPO but nothing is to be found.
https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-policies#printing-policies

**Comment by Y-Kelly** [comment]
Clean up of old issues. As mentioned in the other issues, the team does have --kiosk-printing in the backlog but there is no ETA. You can also submit feature requests through the browser. ("..." menu > Help and feedback > Send feedback)

Currently "UI print settings lockdown" is a supported feature in kiosk mode (Link to documentation: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode#kiosk-mode-supported-features)
