### ISSUE TITLE
Enabled ClickOnce Support and waiting for the result

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/Edge-Enterprise#20]
Just now i enabled this **ClickOnce Support** feature  on the chromium-based edge browser v
Version 83.0.478.44 (Official Build) (64-bit).
i want to verify this feature, how that works in reality.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8101f32-2f63-f2dd-06a4-ba3ae23786c6
* Version Independent ID: f6010158-dd84-09c4-4d8b-d74ae12d6d18
* Content: [ClickOnce and DirectInvoke in Microsoft Edge](https://docs.microsoft.com/en-us/deployedge/edge-learn-more-co-di)
* Content Source: [edgeenterprise/edge-learn-more-co-di.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/edge-learn-more-co-di.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kele**

**Comment by Y-Kelly** [comment]
Clean up of old issues.  To verify the behavior, you need to navigate to a site using ClickOnce.
