### ISSUE TITLE
ClickOnce support in Edge

### ISSUE THREAD

**Issue by joeyfreeman** [MicrosoftDocs/Edge-Enterprise#200]
The first sentence of the article seems to indicate ClickOnce is not supported in the current version of Edge:
"ClickOnce and DirectInvoke are features available in IE and Microsoft Edge (version 45 and earlier) that support the use of a file handler to download files from a website."

This is misleading because ClickOnce works out of the box for Edge v87 and above.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ef8deb0-cf41-dffe-409c-6d4cfeb1ee19
* Version Independent ID: 4a966703-f3f0-3600-3224-8b786881f08c
* Content: [ClickOnce and DirectInvoke in Microsoft Edge](https://docs.microsoft.com/en-us/deployedge/edge-learn-more-co-di)
* Content Source: [edgeenterprise/edge-learn-more-co-di.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learn-more-co-di.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
@joeyfreeman Thanks for the feedback!  We've updated the sentence in the documentation.
