### ISSUE TITLE
no puedo abrir  mi cuenta 

### ISSUE THREAD

**Issue by josevara2020** [MicrosoftDocs/Edge-Enterprise#202]
Request Id: 08c11a39-bbae-4e5c-b9d0-fd981f7d9d00
Correlation Id: 4f9c9afe-b5af-fbe0-9690-8633ddd2ab4b
Timestamp: 2021-07-19T00:20:34.580Z
Nombre de la aplicación: Office 365 Exchange Online
Id. de la aplicación: 00000002-0000-0ff1-ce00-000000000000
Dirección IP: 190.239.139.173
Identificador del dispositivo: No disponible
Plataforma del dispositivo: Windows 10
Estado del dispositivo: Unregistered

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27c87844-d7d4-22ff-92dc-49cea06e2e85
* Version Independent ID: 909054ee-53da-8d02-8347-57aeb1d96f32
* Content: [Microsoft Edge and Conditional Access](https://docs.microsoft.com/en-us/deployedge/ms-edge-security-conditional-access)
* Content Source: [edgeenterprise/ms-edge-security-conditional-access.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/ms-edge-security-conditional-access.md)
* Product: **microsoft-edge**
* GitHub Login: @srugh
* Microsoft Alias: **srugh**

**Comment by Y-Kelly** [comment]
@josevara2020 Sorry, it looks like you have encountered some issue.  I'm unable to understand what is exactly happening.  This is used specifically for Microsoft Edge Enterprise Documentation issues.   

If you have questions regarding Microsoft Edge you can try reaching out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
