### ISSUE TITLE
Cant "Reset Sync" Microsoft Edge

### ISSUE THREAD

**Issue by BeYourself91** [MicrosoftDocs/Edge-Enterprise#206]
Hello

recently I reinstalled windows on my laptop. I signed in my Microsoft account in new windows and removed my previous device from "https://account.microsoft.com/devices". Then I opened the Edge and signed in my account

After all my browser data was synced, I saw that when I right-click [(this pic)](https://i.ibb.co/FxqhtWM/Screenshot-2021-07-22-212923.png) or click in the browser's address bar [(this pic)](https://i.ibb.co/drptX5K/Screenshot-2021-07-22-213050.png), it shows the previous device while I deleted it from the Microsoft account.

I tried very hard to remove it, but when I reset sync, all the data is deleted, but by re-signing in and turning on Sync, the name of the previous device appears in the "Send This Page to other devices" section.

Now I understand that before syncing reset, Microsoft account must be signed out of all devices [(this pic)](https://i.ibb.co/sQDbmZt/Screenshot-2021-07-22-214107.png)

While I installed the new Windows and forgot to sign out of my account in the edge browser in the previous Windows and I no longer have access to the Windows device and its Edge browser Because the previous Windows was completely erased and the current Windows has been replaced

Now how can I completely delete the previous device that signed in to Edge ? or How can I completely reset sync ?

Previous device name (previous Windows): DESKTOP-**FAFI388** (Which you see in the first two photos)
Current device name (new Windows): DESKTOP-**U5UBI8B** [(this pic)](https://i.ibb.co/Rbxkmn9/Untitled-1.jpg) (As you can see, this is the only device on my Microsoft account and I deleted the other devices and they no longer exist.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa2b6bb-c572-6b62-0b2a-5d11cc6c16c2
* Version Independent ID: bbd72cfb-0dd2-dce0-ede7-6887a2992bad
* Content: [Reset Microsoft Edge data](https://docs.microsoft.com/en-us/deployedge/edge-learnmore-reset-data-in-cloud)
* Content Source: [edgeenterprise/edge-learnmore-reset-data-in-cloud.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-reset-data-in-cloud.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
@BeYourself91 Hello!  Sorry to hear about the sync issues.  Normally this is for Microsoft Edge Enterprise Documentation issues.  
If you haven't had a chance yet, I would recommend reaching out to support for further assistance: https://microsoftedgesupport.microsoft.com/hc/en-us
