### ISSUE TITLE
Install IE to Edge BHO policy not working

### ISSUE THREAD

**Issue by kennv-nwl** [MicrosoftDocs/Edge-Enterprise#208]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90451dc6-e4b1-9973-2309-5399e9a63496
* Version Independent ID: ce664b18-ab7e-604a-c475-55ce86b15284
* Content: [Redirection from Internet Explorer to Microsoft Edge for compatibility with modern web sites](https://docs.microsoft.com/en-us/deployedge/edge-learnmore-neededge)
* Content Source: [edgeenterprise/edge-learnmore-neededge.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-neededge.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **laannade**

**Comment by kennv-nwl** [comment]
Hi, I have applied the Prevent Install of IEtoEDGE BHO group policy. the policy has applied, but the BHO helper is still showing. this is even after an Edge update has been applied. I have also applied the Redirect incompatible sites policy and I think this is working, but why has this not removed the helper install

**Comment by Y-Kelly** [comment]
@kennv-nwl Just to confirm, is the BHO still appearing after you had a Microsoft Edge Stable Update?  

https://docs.microsoft.com/en-us/deployedge/edge-learnmore-neededge#policy-redirectsitesfrominternetexplorerpreventbhoinstall

![image](https://user-images.githubusercontent.com/74324031/126847330-acdebc87-f7fe-45be-bf00-d549801b62f6.png)

Thanks!

**Comment by kennv-nwl** [comment]
Hi,

yes, we applied the policy in May and manually set the BHO to disabled. after the July update to 92.0.902.55 it has not uninstalled the BHO and has set itself back to enabled

Thanks

**Comment by Y-Kelly** [comment]
@kennv-nwl Hi!  It looks like you might be getting some assistance with the folks on the Q&A site (https://docs.microsoft.com/en-us/answers/questions/487337/ietoedge-bho-group-policy-issue.html).  I'll close this issue as it does not seem like there is a documentation issue.  Thanks!
