### ISSUE TITLE
The link in Description of InternetExplorerIntegrationLevel can be improved

### ISSUE THREAD

**Issue by JamCheese** [MicrosoftDocs/Edge-Enterprise#21]
The description of **InternetExplorerIntegrationLevel**  [https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#internetexplorerintegrationlevel](url) redirects readers to the following URL: https://go.microsoft.com/fwlink/?linkid=2094210

However, the explanation to this specific policy should be found here, which is another page under the same section:
**https://docs.microsoft.com/en-us/DeployEdge/edge-ie-mode-policies#configure-internet-explorer-integration**

This may cause confusion to the readers/users.
I think we can update the link redirection to make it more accurate and improve user experience.

**Comment by Y-Kelly** [comment]
Clean up of old issues.  It appears the link redirects to the suggested page.  Closing.
