### ISSUE TITLE
"Translate this page" feature fails to position <code> tags correctly.

### ISSUE THREAD

**Issue by niyazikeklik** [MicrosoftDocs/Edge-Enterprise#210]
Original
![image](https://user-images.githubusercontent.com/27292457/126905336-a1ee6f9a-87bd-41b3-8a72-6f6306023cc7.png)

It looks like this when translated into Turkish.
![image](https://user-images.githubusercontent.com/27292457/126905520-871e9c90-0993-4776-a0b6-f8ebad9d06c7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ffcaf54-ce86-1b30-e947-540bf07a54c3
* Version Independent ID: 81267e97-e284-ff00-b081-476934538326
* Content: [Microsoft Edge release notes for Stable Channel](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @AndreaLBarr
* Microsoft Alias: **aguta**

**Comment by Y-Kelly** [comment]
@niyazikeklik Hello!  Are the screenshots from the Microsoft Edge Enterprise Documentation site (https://docs.microsoft.com/en-us/DeployEdge/)?  

If you are having an issue with "Translate this page" on a different site,  please submit feedback and diagnostic data through the browser? ("..." menu > Help and feedback > Send feedback).  Thanks!

**Comment by Y-Kelly** [comment]
@niyazikeklik Closing issue.
