### ISSUE TITLE
Group policy error with Edge 92.0.902.67

### ISSUE THREAD

**Issue by PGRITS** [MicrosoftDocs/Edge-Enterprise#213]
Importing of the current release (92.0.902.67) GPOs lead to error shown in the screenshot while editing the GPO.
![image](https://user-images.githubusercontent.com/88655360/128859650-87ea315a-c294-40be-af79-a6c14501e0db.png)
Apparently the ADMX file references to a name in the ADML files that is not there.
![image](https://user-images.githubusercontent.com/88655360/128859779-b348710f-3ebc-4ef1-b19f-69c53ac52cb2.png)
![image](https://user-images.githubusercontent.com/88655360/128859922-014ddcbd-be1d-4f9c-a8d7-320a890639ab.png)

Edit:
Second screenshot is from the en-US.adml file.

**Comment by Y-Kelly** [comment]
@PGRITS The team has fixed this issue and they are hoping the next release should have the fix.  Please test this scenario again once the update is available.  

If you have further questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
