### ISSUE TITLE
dead link to vidoe

### ISSUE THREAD

**Issue by CathyMoya** [MicrosoftDocs/Edge-Enterprise#216]
Hi, the link to the video about security/compatibility/manageability is 404
https://docs.microsoft.com/en-us/microsoft-edge-video-security-compatibility-manageability.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27c87844-d7d4-22ff-92dc-49cea06e2e85
* Version Independent ID: 909054ee-53da-8d02-8347-57aeb1d96f32
* Content: [Microsoft Edge and Conditional Access](https://docs.microsoft.com/en-us/deployedge/ms-edge-security-conditional-access)
* Content Source: [edgeenterprise/ms-edge-security-conditional-access.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/ms-edge-security-conditional-access.md)
* Product: **microsoft-edge**
* GitHub Login: @srugh
* Microsoft Alias: **srugh**

**Comment by Y-Kelly** [comment]
@CathyMoya Thanks for letting us know!  We've updated the link :)
