### ISSUE TITLE
Page or Domain for Local Sites List

### ISSUE THREAD

**Issue by mattstaton** [MicrosoftDocs/Edge-Enterprise#219]
[When adding a URL to the local sites list, does it apply only for that specific page, or does it apply for to all pages under the domain? The documentation isn't clear.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 459e4d0d-27b0-753e-3a60-b8ec6b2092b5
* Version Independent ID: 05413a17-f068-8429-af7f-77665f321bbb
* Content: [Local site list for IE mode](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-local-site-list)
* Content Source: [edgeenterprise/edge-ie-mode-local-site-list.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode-local-site-list.md)
* Product: **microsoft-edge**
* GitHub Login: @AndreaLBarr
* Microsoft Alias: **shisub**

**Comment by Y-Kelly** [comment]
@mattstaton Hello!  There are a couple of scenarios you could be asking about.  Hopefully this answers your question.  

From the documentation: After a site has been reloaded in IE mode "in-page" navigations will stay in IE mode (for example, a link, script, or form on the page, or a server-side redirect from another "in-page" navigation).

If you add https://www.testsite.com/ to the local site list and navigate to https://www.testsite.com/ you will be in IE mode and remain in IE mode when you are on the site, which is called "in-page" navigations in the documentation.  

If you add https://www.testsite.com/ to the local site list and navigate to https://www.testsite.com/abcdef you will not be in IE mode and you need to navigate specifically to https://www.testsite.com/ to be in IE mode.  

Closing this issue.  Thanks!
