### ISSUE TITLE
Policy updates missing for 93

### ISSUE THREAD

**Issue by holow29** [MicrosoftDocs/Edge-Enterprise#220]
The 'Policy Updates' section is missing for release 93, though it is present on the beta release notes page. I hope this is simply an oversight as the policy updates section plays a major role in organizational update preparedness.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ffcaf54-ce86-1b30-e947-540bf07a54c3
* Version Independent ID: 81267e97-e284-ff00-b081-476934538326
* Content: [Microsoft Edge release notes for Stable Channel](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @AndreaLBarr
* Microsoft Alias: **aguta**

**Comment by Y-Kelly** [comment]
@holow29 Thanks!  We've updated the Stable 93 Release Notes with the Policy information (https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel#version-93096138-september-02)
