### ISSUE TITLE
cannot install it

### ISSUE THREAD

**Issue by duolingo9999** [MicrosoftDocs/Edge-Enterprise#223]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29248239-1b63-c9f5-8453-e80ecd6a985e
* Version Independent ID: 71cb6d47-5eb6-621e-4832-aba93190d2f6
* Content: [Allow list for Microsoft Edge endpoints](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-security-endpoints)
* Content Source: [edgeenterprise/microsoft-edge-security-endpoints.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-security-endpoints.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by Y-Kelly** [comment]
@duolingo9999 Did you have a specific question about MS Edge Enterprise Documentation?
