### ISSUE TITLE
Excel download for EDGE Policy for EDGE Version 93 is NOT AVAILABLE

### ISSUE THREAD

**Issue by NConnects** [MicrosoftDocs/Edge-Enterprise#226]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by NConnects** [comment]
@stmoody , Hi Moody, could you please have a look in this?

**Comment by Y-Kelly** [comment]
@NConnects Can you provide more details about where this Excel file is normally posted?  Thanks!

**Comment by NConnects** [comment]
@Y-Kelly 
https://www.microsoft.com/en-us/download/details.aspx?id=55319
It shows 92 version.

**Comment by Y-Kelly** [comment]
@NConnects Thanks for the information!  There was a delay updating the Security Baselines for v93.  I believe the team is trying to get the update published this week.  

Closing this issue but if you don't see the update by the end of this week, please feel free to follow up.  Thanks!
