### ISSUE TITLE
Settings > Profiles > Reset sync  does not appear from me ??

### ISSUE THREAD

**Issue by terryclancy** [MicrosoftDocs/Edge-Enterprise#229]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa2b6bb-c572-6b62-0b2a-5d11cc6c16c2
* Version Independent ID: bbd72cfb-0dd2-dce0-ede7-6887a2992bad
* Content: [Reset Microsoft Edge data](https://docs.microsoft.com/en-us/deployedge/edge-learnmore-reset-data-in-cloud)
* Content Source: [edgeenterprise/edge-learnmore-reset-data-in-cloud.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-reset-data-in-cloud.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
@terryclancy Hello - You can find "Reset Sync" by going to Settings > Profiles > Sync > Reset sync at the bottom of the page.

Or you can navigate to edge://settings/profiles/sync/configure.  Thanks!
