### ISSUE TITLE
Scope of coverage

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/Edge-Enterprise#23]
This only works for traditional AD? What about AAD-only tenant customers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d4f5747-e035-ee79-312b-8d64dc4a2e05
* Version Independent ID: a01f06b0-b33d-63f3-fa4e-232d3ae6f16d
* Content: [Microsoft Edge support for Windows Information Protection](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-security-windows-information-protection)
* Content Source: [edgeenterprise/microsoft-edge-security-windows-information-protection.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-security-windows-information-protection.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by Y-Kelly** [comment]
Clean up of old issues.  Closing as this question was previously answered.
