### ISSUE TITLE
Incorrect requirements for Edge Sync

### ISSUE THREAD

**Issue by rndthoughts** [MicrosoftDocs/Edge-Enterprise#231]
The documentation states that support is availability with one of the following subscriptions:

•	Azure AD Premium (P1 or P2)
•	M365 Business Premium, Business Standard, or Business Basic
•	Office 365 E1 and above
•	Azure Information Protection (AIP) (P1 or P2)
•	All EDU subscriptions (Microsoft Apps for Students or Faculty, Exchange Online for Students or Faculty, O365 A1 or above, M365 A1 or above, or Azure Information Protection P1 or P2 for Students or Faculty)

However this is incorrect as stated by your support representative (see support case 27494970).  If you have Business Basic then AIP is not included you need to *additionally purchase* AIP which is not clear above.  I would suggest:

- Azure AD Premium (P1 or P2)
- M365 Business Premium or Business Standard
- Office 365 E1 and above.
- To use M365 Business Basic you will need the an additional Azure Information Protection (AIP) (P1 or P2 subscription)
- Azure Information Protection (AIP) (P1 or P2)
- All EDU subscriptions (Microsoft Apps for Students or Faculty, Exchange Online for Students or Faculty, O365 A1 or above, M365 A1 or above, or Azure Information Protection P1 or P2 for Students or Faculty)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fa7eda4-6e4c-c2c8-a29a-ef2eead7f04f
* Version Independent ID: 414db256-c14b-ca11-b2a7-835aa9c9e041
* Content: [Configure Microsoft Edge enterprise sync](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-enterprise-sync)
* Content Source: [edgeenterprise/microsoft-edge-enterprise-sync.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-enterprise-sync.md)
* Product: **microsoft-edge**
* GitHub Login: @AndreaLBarr
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
@rndthoughts Thanks for the feedback!  I'll reach out to the Sync team and pass on the suggested changes.

**Comment by Y-Kelly** [comment]
@rndthoughts Hello!  The team has confirmed that Sync should be available for Business Basic without AIP.  For your specific case the team can investigate further, would you all be able to submit diagnostic data through our in-browser feedback tool? It's under "..." menu > Help and feedback > Send feedback.  Please select "Send diagnostic data"

Also, for the team to be about to find it quickly, can you include the string "GitHubSync" in the description and let me know once you've submitted it?  Thank you!

**Comment by uedevservices** [comment]
That's rather frustrating as your support team are under the impression that it's not available on Basic without AIP additionally purchased.  Feedback sent with "GitHubSync" in the description as requested.

**Comment by rndthoughts** [comment]
That's rather frustrating as your support team are under the impression that it's not available on Basic without AIP additionally purchased.  Feedback sent with "GitHubSync" in the description as requested.
