### ISSUE TITLE
KB4523205

### ISSUE THREAD

**Issue by hisamatsu-kin1** [MicrosoftDocs/Edge-Enterprise#232]
[Enter feedback here]

I  clicked "Version 1809	KB4523205"  because I am using the 1809.
then it shows the blow page.
https://support.microsoft.com/en-us/topic/november-12-2019-kb4523205-os-build-17763-864-100bc05a-c300-a329-94ea-9767f1266176

Then I clicked "To get the standalone package for this update, go to the Microsoft Update Catalog website."

However I encountered the dead-link/download. please tell me solution.
https://www.catalog.update.microsoft.com/Search.aspx?q=KB4523205.

Best regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1bb66bc-c066-499a-41b3-19bd4df6a0e2
* Version Independent ID: d3cc7612-203e-b1bb-3f26-00f00291552b
* Content: [Windows updates for Microsoft Edge](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-sysupdate-windows-updates?form=MY01SV&OCID=MY01SV)
* Content Source: [edgeenterprise/microsoft-edge-sysupdate-windows-updates.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-sysupdate-windows-updates.md)
* Product: **microsoft-edge**
* GitHub Login: @RyanHechtMSFT
* Microsoft Alias: **jtkim**

**Comment by Y-Kelly** [comment]
@hisamatsu-kin1 Thanks for the feedback!  The article had some outdated information.  We've made some updates - https://docs.microsoft.com/en-us/deployedge/microsoft-edge-sysupdate-windows-updates
