### ISSUE TITLE
Authenticating users before autofill has been available for months

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/Edge-Enterprise#233]
"(!)  Note

Microsoft recognizes the value in authenticating users before autofill and this functionality will be added to Microsoft Edge in a future release."

This was added more than two months ago:

[https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel#:~:text=Added%20privacy%20for%20your%20saved%20passwords%20If%20you%20are%20using%20a%20device%20you%20share%20with%20others%20or%20have%20left%20your%20computer%20unlocked%20for%20whatever%20reason%2C%20you%20can%20now%20opt%20for%20a%20second%20verification%20using%20your%20device%20password%20to%20avoid%20others%20getting%20access%20to%20your%20website%20passwords.%20Simple!](url)

https://support.microsoft.com/en-us/topic/additional-privacy-for-your-saved-passwords-31dbd670-e314-4901-a546-6f302548502e

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f651e68c-34bf-d399-88e9-c9a0928d8be4
* Version Independent ID: ad34ee59-01d3-c64d-d123-5484264190b8
* Content: [Microsoft Edge password manager security ](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-security-password-manager-security)
* Content Source: [edgeenterprise/microsoft-edge-security-password-manager-security.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-security-password-manager-security.md)
* Product: **microsoft-edge**
* GitHub Login: @AndreaLBarr
* Microsoft Alias: **v-andreabarr**

**Comment by Y-Kelly** [comment]
@BR77BE The documentation has been updated.  Thanks for the feedback!
