### ISSUE TITLE
Internet Explorer (IE) mode...   for how long?

### ISSUE THREAD

**Issue by tjmcallister** [MicrosoftDocs/Edge-Enterprise#234]
Will the "Internet Explorer (IE) mode" in Edge persist past the date Internet Explorer is no longer supported (June 2022)?  Does it require Internet Explorer to be installed?  I ask that specifically if our network/policies remove Internet Explorer after June 2022?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 418ea780-28cd-c78d-8855-df5188dd4be9
* Version Independent ID: 15be2361-06cf-5683-9213-8aec3aebef67
* Content: [What is Internet Explorer mode?](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode)
* Content Source: [edgeenterprise/edge-ie-mode.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by Y-Kelly** [comment]
@tjmcallister Hello - Internet Explorer mode in Microsoft Edge will be supported through at least 2029. (More information here: https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge/ or here: https://docs.microsoft.com/en-us/lifecycle/faq/internet-explorer-microsoft-edge#what-is-the-lifecycle-policy-for-internet-explorer-)

If you have further questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
