### ISSUE TITLE
Edge 95 incorrect date message

### ISSUE THREAD

**Issue by ben-mcginty** [MicrosoftDocs/Edge-Enterprise#235]
The edge 95 beta release date should be 28, not 82 (i think)
![image](https://user-images.githubusercontent.com/44914602/135217020-494726c1-8e52-4b79-a0d4-96a4c3933b2a.png)

This was on the release schedule page https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-release-schedule

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d1bc306-56a5-f501-b3e0-a661d57b1db4
* Version Independent ID: e4ef685b-8570-be80-9547-9956042b967e
* Content: [Microsoft Edge release schedule](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-release-schedule)
* Content Source: [edgeenterprise/microsoft-edge-release-schedule.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-release-schedule.md)
* Product: **microsoft-edge**
* GitHub Login: @AndreaLBarr
* Microsoft Alias: **aguta**

**Comment by Y-Kelly** [comment]
@ben-mcginty Yes, that is a typo!  :)  The team is correcting it right now.  Thanks for letting us know.
