### ISSUE TITLE
Excel download for EDGE Policy for EDGE Version 94 is NOT AVAILABLE - This is reoccuring for every release

### ISSUE THREAD

**Issue by NConnects** [MicrosoftDocs/Edge-Enterprise#236]
Hi Team, Excel download for EDGE Policy for EDGE Version 94 is NOT AVAILABLE and this seems to be reoccuring issue. 

this need to be addressed when Microsoft releases new EDGE version.

**Comment by NConnects** [comment]
@Y-Kelly, please address this at the earliest.

**Comment by Y-Kelly** [comment]
@NConnects Please see this post regarding the Security baseline for Microsoft Edge v94: https://techcommunity.microsoft.com/t5/microsoft-security-baselines/security-baseline-for-microsoft-edge-v94/ba-p/2784793

This area of Tech Community should get updated with a new article for each release: https://techcommunity.microsoft.com/t5/microsoft-security-baselines/bg-p/Microsoft-Security-Baselines

Thanks!
