### ISSUE TITLE
Printnightmare Issue - When can we expect permanent fix from MS where user will not be prompted for Admin Cred popup

### ISSUE THREAD

**Issue by NConnects** [MicrosoftDocs/Edge-Enterprise#237]
Dear Team, This is w.r.t Printnightmare, after applying the patch, we see users are welcoming with admin credentials which is very annoying for IT admins. Additionally, printers are part of trusted list and despite having this setting, we are having this issue. 

 When shall we expect Permanent fix where user will not see admin cred popup?

**Comment by Y-Kelly** [comment]
@NConnects Sorry, normally this is for MS Edge Enterprise Documentation issues.  

I'm not familiar with the print issue you are experiencing or the patch you mentioned.  

Have you submit diagnostic data/feedback through the browser? ("..." menu > Help and feedback > Send feedback)

You can also reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
