### ISSUE TITLE
Policy Item not included in standalone template

### ISSUE THREAD

**Issue by frozenak** [MicrosoftDocs/Edge-Enterprise#24]
Double-click Configure which channel of Microsoft Edge to use for opening redirected sites.

That policy item, "Configure which channel of Microsoft Edge to use for opening redirected sites," is not actually included in any of the standalone template packages.
This item seems to only be found in the inetres files of local policy files.
eg, it's only available via gpedit.msc and not via Group Policy Management Editor.

I downloaded the 1909 templates and searched inetres.adml for "configure which" and there were zero results.
With 1909 templates installed in the central store, that item also does not exist.

Windows Server 2016 Essentials has it available via gpedit.msc
Windows 10 1803 has it available via gpedit.msc
Windows 10 1909 has it available via gpedit.msc

Not available in ADMX package provided via:
https://www.microsoft.com/en-us/download/confirmation.aspx?id=100591

So, not exactly an issue with the page, per se, but the page provides inaccurate information for the reality of things.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: add98763-6344-6d9e-b1f4-39c995100050
* Version Independent ID: 5a9ac6ef-92ff-edfc-b3a6-af758642210f
* Content: [Configure IE mode Policies](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-policies#redirect-sites-from-ie-to-microsoft-edge)
* Content Source: [edgeenterprise/edge-ie-mode-policies.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/edge-ie-mode-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @cjacks
* Microsoft Alias: **cjacks**

**Comment by Y-Kelly** [comment]
Clean up of old issues.  It appears that Windows 10 Enterprise and Education November 2019 Update (1909) is out of support as of May 10, 2022 (https://docs.microsoft.com/en-us/lifecycle/products/windows-10-enterprise-and-education).  

I do not think there is any way to update the ADMX file you have mentioned https://www.microsoft.com/en-us/download/confirmation.aspx?id=100591
