### ISSUE TITLE
Recommended vs Mandatory policies for macOS

### ISSUE THREAD

**Issue by tgrosst** [MicrosoftDocs/Edge-Enterprise#25]
Neither this page nor the Edge policies page (https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-policies) explain how to set a macOS policy in Intune to Recommended vs Mandatory. Can this be added?

The Edge policies page lists all the Edge policies has both Recommended and Mandatory policy locations for Windows, but not for macOS.

The documentation on "Configure policy settings on Windows" describes the difference: https://docs.microsoft.com/en-us/deployedge/configure-microsoft-edge#configure-policy-settings-on-windows

According to https://stackoverflow.com/questions/38206916/mandatory-chrome-policies-on-mac there are two different locations for the plist depending on if you want to set a policy as Recommended (~/Library/Preferences/) vs Mandatory (/Library/Managed Preferences/), but this page doesn't explain how to pick one when configuring a policy with Intune.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c05c4e5-63bf-1b01-52e5-bd7ee10c737e
* Version Independent ID: 4ab1fe14-adf0-4588-19fd-5cac5e703b13
* Content: [Configure Microsoft Edge for macOS using a .plist](https://docs.microsoft.com/en-us/deployedge/configure-microsoft-edge-on-mac)
* Content Source: [edgeenterprise/configure-microsoft-edge-on-mac.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/configure-microsoft-edge-on-mac.md)
* Product: **microsoft-edge**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **brianalt**

**Comment by Y-Kelly** [comment]
Clean up of old issues.  I can confirm that this issue has been passed on to the team but they have not had a chance to address yet and there is currently no ETA.  

For immediate help you can reach out to Support (https://developer.microsoft.com/en-us/microsoft-edge/support/) or the FastTrack team (https://docs.microsoft.com/en-us/fasttrack/products-and-capabilities#microsoft-edge) for assistance with MS Edge deployment.

**Comment by zakx** [comment]
This is still the case sadly, any updates @Y-Kelly?
