### ISSUE TITLE
Typo or extra note for *IECountInfo?

### ISSUE THREAD

**Issue by scott-ip1** [MicrosoftDocs/Edge-Enterprise#250]
[Enter feedback here]
Is the asterisk on "*IECountInfo." a typo or is there some extra note supposed to be attached to that property?

Step 10 under the Configuration Manager setup

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2883b89f-a5ec-c549-3a9e-22c010d0b527
* Version Independent ID: 6518eff2-f389-a4c7-0d8d-f3ba47c650cc
* Content: [Enterprise Site Discovery Step by Step Guide](https://docs.microsoft.com/en-us/DeployEdge/edge-ie-mode-site-discovery)
* Content Source: [edgeenterprise/edge-ie-mode-site-discovery.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode-site-discovery.md)
* Product: **microsoft-edge**
* GitHub Login: @appcompatguy
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
@scott-ip1 Hi - Thanks for the feedback.  I'm checking with the team about this documentation.

**Comment by dan-wesley** [comment]
@Y-Kelly @scott-ip1 This looks like a typo to me. Can I go ahead and fix it?

**Comment by dan-wesley** [comment]
@Y-Kelly @scott-ip1 I looked at the markdown source, it was definitely a typo. I done the fix and will republish
