### ISSUE TITLE
ProxyPacMandatory setting

### ISSUE THREAD

**Issue by perhof** [MicrosoftDocs/Edge-Enterprise#251]
Where are the examples for the ProxyPacMandatory setting in the ProxySettings policy?
It would be nice if it could be included in the example s on this page.

It says "For more detailed examples go to https://go.microsoft.com/fwlink/?linkid=2094936" but the page at that link only shows Edge command line options and it doesn't mention ProxyPacMandatory at all. In my opinion it is a quite useless link in this context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@perhof Thanks for reaching out!  I'm checking with the team about the examples.

**Comment by Y-Kelly** [comment]
@perhof Here is information from our developer: 

> ProxyPacMandatory is just a Boolean field. If set, there must also be a PAC file set in the ProxySettings and all network traffic must either flow through that PAC file or the proxy must be bypassed via the ProxyBypassList field. If that PAC file fails to download or execute, all network traffic is blocked.

The policy documentation should be updated.  (https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#proxysettings)

Thanks for the feedback!
