### ISSUE TITLE
Policies do not combine down the OU hierarchy

### ISSUE THREAD

**Issue by joegoerlich** [MicrosoftDocs/Edge-Enterprise#253]
Some policies store their setting as REG_SZ with 1,2,3,... This scheme for the registry keys prevents values set by GPOs down the OU hierarchy from being combined. 
For example, formerly in IE another scheme was used to store such values. Back then it was possible to set a GPO on top level with a set of certain URLs and set an additional GPO on a sub-OU with a set of additional URLs. Both GPOs have been applied and the settings have been combined to a large list. With the new scheme in MS Edge (Chrome) instead of being combined the GPO from the sub-OU replaces all values from the GPO of parent OUs.

**Comment by Y-Kelly** [comment]
@joegoerlich Thanks for the feedback.  We've had other similar requests but no ETA for a change right now.  (For example, see previous discussion on Tech Community: https://techcommunity.microsoft.com/t5/enterprise/microsoft-edge-group-policies-for-lists-like-pop-ups-do-not/m-p/2279658/highlight/true#M3357)

I've passed your feedback on to the team.  

_-Kelly_
