### ISSUE TITLE
TLS Cipher Suite Deny List policy

### ISSUE THREAD

**Issue by joegoerlich** [MicrosoftDocs/Edge-Enterprise#254]
in v85 support for the TLS Cipher Suite Deny List management policy was added. 
I have a hard time to use the TLS Cipher Suite Deny List policy. 
For example, if I like to block all cipher suites not offering PFS, it would be a mess to configure. There are 350 different ciphers registered at IANA, two third of them without PFS.

Would be good to know which of the 350 ciphers are supported by MS Edge and filter them for the unwanted ones.

I read somewhere else, that Edge comes now with an own crypto library and does no longer relay on SCHANNEL. Therefore, schannel restrictions do no longer apply for MS Edge, but do for IE.
The list of IANA cipher suites is rather long and it makes sense to prevent usage of certain cipher suites by adding them to the list only if they are initially supported by MS Edge. 

Also see https://techcommunity.microsoft.com/t5/discussions/tls-cipher-suite-deny-list-management-policy/m-p/2095633

**Comment by ericlaw1979** [comment]
Edge is based on Chromium and uses the same ciphersuites provided by BoringSSL. 

https://clienttest.ssllabs.com:8443/ssltest/viewMyClient.html is a good page for seeing which ciphers your browser supports.

In Edge 97 Canary, that list comprises:

```
TLS_AES_128_GCM_SHA256 (0x1301)   Forward Secrecy	128
TLS_AES_256_GCM_SHA384 (0x1302)   Forward Secrecy	256
TLS_CHACHA20_POLY1305_SHA256 (0x1303)   Forward Secrecy	256
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)   Forward Secrecy	128
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)   Forward Secrecy	128
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02c)   Forward Secrecy	256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)   Forward Secrecy	256
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca9)   Forward Secrecy	256
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca8)   Forward Secrecy	256

TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)  WEAK	128
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)  WEAK	256
TLS_RSA_WITH_AES_128_GCM_SHA256 (0x9c)  WEAK	128
TLS_RSA_WITH_AES_256_GCM_SHA384 (0x9d)  WEAK	256
TLS_RSA_WITH_AES_128_CBC_SHA (0x2f)  WEAK	128
TLS_RSA_WITH_AES_256_CBC_SHA (0x35)  WEAK	256
```

So if you wanted to disable those ciphers without Forward Secrecy, you'd use

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\TLSCipherSuiteDenyList]
"1"="0xc013"
"2"="0xc014"
"3"="0x009c"
"4"="0x009d"
"5"="0x002f"
"6"="0x0035"
```

**Comment by joegoerlich** [comment]
Thanks Eric, this is exactly what i was looking for!
