### ISSUE TITLE
Edge support on Windows Server 2016 SAC?

### ISSUE THREAD

**Issue by StephendillonMS** [MicrosoftDocs/Edge-Enterprise#257]
What about support for Edge on Windows Server 2016 SAC? What if it has extended support or not? We know of at least one Edge policy that is broken (Aopen tab in IE Mode) - Customer is using Server 2016 for their Citrix environment so they have hundreds of Citrix users who cannot see the option to toggle between IE Mode and Edge mode, leading to an inconsistent test/validation experience for users on Citrix than those on physical devices. 

Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86847b80-8f8e-9493-86ff-5dfd6412b48f
* Version Independent ID: 2ce02bc3-24a1-8c9f-c787-34ab90e9f31d
* Content: [Microsoft Edge Supported Operating Systems](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-supported-operating-systems)
* Content Source: [edgeenterprise/microsoft-edge-supported-operating-systems.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-supported-operating-systems.md)
* Product: **microsoft-edge**
* GitHub Login: @srugh
* Microsoft Alias: **srugh**

**Comment by Y-Kelly** [comment]
@StephendillonMS There are specific prerequisites for IE mode.  Also, there are prerequisites for some IE mode features, like the local site list.  Is this the policy you were referring to InternetExplorerIntegrationReloadInIEModeAllowed?    

Here is some documentation: 
- https://docs.microsoft.com/en-us/deployedge/edge-ie-mode#prerequisites
- https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-local-site-list

Thanks!

**Comment by StephendillonMS** [comment]
Thanks and yes… it doesn’t work on Server 2016 😲 And it’s officially ‘not suported’ by Microsoft so it won’t be fixed. It works on Server 2019 and even earlier versions of Server lol…

Cheers
Steve



Steve Dillon (They/Them) | Microsoft FastTrack
Senior escalation engineer helping with the deployment, configuration, security, and maintenance of Microsoft Edge, M365 Apps, Surface, Windows 10.

Upcoming leave/time off:-
Monday, 20th December 2021 - Sunday, 9th January 2022
