### ISSUE TITLE
Position on VBScript support in Edge compatibility mode is unclear

### ISSUE THREAD

**Issue by kemalsangrar** [MicrosoftDocs/Edge-Enterprise#258]
I am looking to clarify the position on whether applications that use VBScript will continue to work in compatibility mode but have been struggling to get a clear picture.

Can the documentation be updated to answer the following questions:

- Will compatibility-mode on Edge support running scripts in VBScript?
- Will this continue to work in Windows 11?

Thanks!

**Comment by Y-Kelly** [comment]
@kemalsangrar Hello!  Microsoft Edge IE mode will be supported at least through 2029.  Additionally, Microsoft will give one year of notice before retiring the IE mode experience when the time comes.   More information here: https://techcommunity.microsoft.com/t5/windows-it-pro-blog/internet-explorer-11-desktop-app-retirement-faq/ba-p/2366549

For more information about, VBScript, I would suggest reaching out to the VBScript team.  Thanks!
