### ISSUE TITLE
windows 11's IE mode work differently then win 10's?

### ISSUE THREAD

**Issue by dodream8** [MicrosoftDocs/Edge-Enterprise#259]
we test edge ie mode on windows 11.

some DOM click event is not working.
(on windows 10's ie mode, it works fine)

I found IE version is different.
 win10 : 11.0.19041
 win11 : 11.0.22000

i think, dynamic element's event is ignored.

**Comment by Y-Kelly** [comment]
@dodream8 Thanks for reaching out!  Normally these GitHub issues are specifically for Microsoft Edge Enterprise Documentation. 

In this case it might be best to reach out to Support (https://microsoftedgesupport.microsoft.com/hc/en-us) they should be able to work with you directly and investigate the issues you experiencing.
