### ISSUE TITLE
Question on URLAllowList with customer schema with dots in it

### ISSUE THREAD

**Issue by RvLeiden** [MicrosoftDocs/Edge-Enterprise#26]
I'd like to allow launching of CitrixEndpointAnalysis (on MacOS). The schema used is: com.citrix.agmacepa:
Tried to add this to URLAllowList as (without quotes): "com.citrix.agmacepa:*" or "com.citrix.agmacepa://*" but it looks like none of these are correctly recognized. A schema without dots (eg receiver://*) works fine.
How can I add the com.citrix.agmacepa schema as allowed url?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3fd4df5-4081-d511-27ef-cbb8d9ff66c0
* Version Independent ID: 1202601a-fda5-32da-742c-d469b050f8ba
* Content: [Filter format for Microsoft Edge URL policies](https://docs.microsoft.com/en-us/DeployEdge/edge-learnmmore-url-list-filter%20format#feedback)
* Content Source: [edgeenterprise/edge-learnmmore-url-list-filter format.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/edge-learnmmore-url-list-filter format.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **brianalt**

**Comment by Y-Kelly** [comment]
Clean up of old issues.  This discussion is a couple of years old and does not have any recent activity.

If you still need assistance you can reach out to [Support](https://developer.microsoft.com/en-us/microsoft-edge/support/) or the [FastTrack Team](https://www.microsoft.com/en-us/fasttrack/microsoft-365/microsoft-edge?rtc=1) and they can help with your specific scenario.

**Comment by ericlaw1979** [comment]
Still a bug in Edge 111. Upstream tracked as https://bugs.chromium.org/p/chromium/issues/detail?id=1352943
