### ISSUE TITLE
Wrong policy is specified in the FAQ topic "What is the default refresh interval after updates are made to site list contents?"

### ISSUE THREAD

**Issue by cakin027** [MicrosoftDocs/Edge-Enterprise#260]
The section https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-cloud-site-list-mgmt#what-is-the-default-refresh-interval-after-updates-are-made-to-site-list-contents says the following: 

What is the default refresh interval after updates are made to site list contents?

The site list is refreshed in Microsoft Edge every two hours. You can change this interval the NavigationDelayForInitialSiteListDownloadTimeout policy. The minimum refresh interval is 30 minutes.

It points to the NavigationDelayForInitialSiteListDownloadTimeout policy for this, but it should point to the internetexplorerintegrationsitelistrefreshinterval policy: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#internetexplorerintegrationsitelistrefreshinterval

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1a4c286-c376-c1aa-86d8-80a842861435
* Version Independent ID: a1a4c286-c376-c1aa-86d8-80a842861435
* Content: [Cloud Site List Management for Internet Explorer (IE) mode (Public Preview)'](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-cloud-site-list-mgmt)
* Content Source: [edgeenterprise/edge-ie-mode-cloud-site-list-mgmt.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode-cloud-site-list-mgmt.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **shisub**

**Comment by Y-Kelly** [comment]
@cakin027 Thanks for the feedback! I've passed it on to the team to review.

**Comment by Y-Kelly** [comment]
@cakin027 The documentation has been updated.  Thanks for letting us know.
