### ISSUE TITLE
Issues setting up profile sync and no guidance on service endpoint connectivity

### ISSUE THREAD

**Issue by elegault** [MicrosoftDocs/Edge-Enterprise#263]
I have an issue where my profile sync is stuck at "Setting up sync". Steps 3-4 in [this section](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-troubleshoot-enterprise-sync#issue-stuck-at-setting-up-sync-or-couldnt-connect-to-the-sync-server-retrying) suggest pinging the specified service endpoint URLs (in my case, the Server URL value is empty in the Environment Info section of my Sync Internals dump). However, it does not offer any guidance about exactly what to do if the connections aren't available to the client computer.

In my case, I get this error for the Microsoft Edge sync service endpoints:

![image](https://user-images.githubusercontent.com/4130365/143384385-d6ad21da-41fe-42de-a922-b5eae2e62dbf.png)
And this error for https://api.aadrm.com:

![image](https://user-images.githubusercontent.com/4130365/143384522-df385a11-9ee9-4a85-a9d8-0c2a6cb128c1.png)

What can I do? Below is my data dump
![image](https://user-images.githubusercontent.com/4130365/143384792-624c5612-8da6-422f-b319-af5a63501e8e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33cc47c1-b277-96a1-8db2-411e3a4036e8
* Version Independent ID: d3c665a7-96f6-150f-d905-d33a7ff40a28
* Content: [Diagnose and fix Microsoft Edge sync issues](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-troubleshoot-enterprise-sync)
* Content Source: [edgeenterprise/microsoft-edge-troubleshoot-enterprise-sync.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-troubleshoot-enterprise-sync.md)
* Product: **microsoft-edge**
* GitHub Login: @AndreaLBarr
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
@elegault Hi!  Have you tried to reach out to Microsoft Edge Support https://www.microsoftedgeinsider.com/support?
They should be able to gather logs and help investigate your specific case.  Thanks!

**Comment by elegault** [comment]
The support system for enterprise Edge Support makes my head hurt, and it appears I still need to pay even though I have an M365 Business Standard account. The issue actually resolved itself on the weekend. Now it's broken again. Sigh.
