### ISSUE TITLE
Edge Updates documentation missing info

### ISSUE THREAD

**Issue by johanVAva3** [MicrosoftDocs/Edge-Enterprise#264]
[Enter feedback here]

1) The TargetVersionPrefix section is empty:
https://docs.microsoft.com/en-us/deployedge/microsoft-edge-update-policies#targetversionprefix

2) The Channel Overview states a 'supported' column. For the Dev channel, it is 'No'. Not clear what exactly is not supported for the Dev Channel.
https://docs.microsoft.com/en-us/deployedge/microsoft-edge-channels#channel-overview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96fddabd-2bac-2fab-a5ea-25c000b425fc
* Version Independent ID: 41bba38e-bd24-0496-da04-012d6deb5db8
* Content: [Microsoft Edge Update Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-update-policies#targetversionprefix)
* Content Source: [edgeenterprise/microsoft-edge-update-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-update-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by johanVAva3** [comment]
Remark nr.1 can be ignored, is OK.

**Comment by Y-Kelly** [comment]
@johanVAva3 Hi!  "Supported" refers to Assisted Support.  

Like the article mentions, more information about support can be found here: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-support-lifecycle
