### ISSUE TITLE
File:// Path for self hosted extnsions didn't work

### ISSUE THREAD

**Issue by excelsi** [MicrosoftDocs/Edge-Enterprise#265]
I have a question to sel-host Extensions on a File:// path regarding this page and:
https://docs.microsoft.com/en-us/deployedge/microsoft-edge-manage-extensions-policies

In my Tests the file path for ExentsionInstallForceList (example for sure with the right ID):

mfjlfjaknfckffgjgmdfeheeealceoak;file:///C:/temp/Update.xml
or
mfjlfjaknfckffgjgmdfeheeealceoak;file://localhost/C:/temp/Update.xml

and the Update.XML contents:

<?xml version='1.0' encoding='UTF-8'?> 
<gupdate xmlns='http://www.google.com/update2/response' protocol='2.0'> 
  <app appid='ekilpdeokbpjmminmhfcgkncmmohmfeb'> 
  <updatecheck codebase='file:///C:/temp/helloworld.crx' version='1.0' /> 
  </app> 
</gupdate> 

didn't work and the Extension was not installed.

So is the File:// Path supported or has it to be on a HTTP?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d275477d-dfcc-30f8-431c-e73a346ae0c0
* Version Independent ID: 3f7c98ed-e7ff-1554-84dd-44319029900f
* Content: [Self-host Microsoft Edge extensions](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-manage-extensions-webstore#distribute-a-privately-hosted-extension)
* Content Source: [edgeenterprise/microsoft-edge-manage-extensions-webstore.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-manage-extensions-webstore.md)
* Product: **microsoft-edge**
* GitHub Login: @AndreaLBarr
* Microsoft Alias: **aspoddar**

**Comment by Y-Kelly** [comment]
@ashishnirvana1 Would you be able to help with this extension question?

**Comment by Y-Kelly** [comment]
Clean up of old issues.  

@excelsi Looking at the extension documentation it appears you do need to use http/https.  See the note here: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-manage-extensions-policies#force-install-an-extension
