### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Ryu-Syrius** [MicrosoftDocs/Edge-Enterprise#266]
Microsoft Edge Browser Policies link is broken.

https://review.docs.microsoft.com/DeployEdge/microsoft-edge-policies

Requires special sign-in, with authorization warning.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 229e4d46-19a6-c042-8ce1-844c44c00112
* Version Independent ID: 8ab07629-42a6-e7a1-86a9-f8103825ebc4
* Content: [Configure Microsoft Edge kiosk mode](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode)
* Content Source: [edgeenterprise/microsoft-edge-configure-kiosk-mode.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-configure-kiosk-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @Aguta
* Microsoft Alias: **aguta**

**Comment by Y-Kelly** [comment]
@Ryu-Syrius Thanks for the feedback!  

Is it just the link in this section https://docs.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode#multi-app-kiosk or is there any other broken links you've found?

![image](https://user-images.githubusercontent.com/74324031/143963003-ce849b24-aa7c-4cf1-b1ed-d0c674d7ef14.png)

**Comment by Ryu-Syrius** [comment]
I only tried a few links.  This is the only one I noticed.  I was
attempting to reference the browser policies for a multi-app deployment.

**Comment by Y-Kelly** [comment]
@Ryu-Syrius OK, thanks!  I'll ask the team to update.

**Comment by Y-Kelly** [comment]
@Ryu-Syrius Thanks again! 

Link has been fixed.  Closing issue.
