### ISSUE TITLE
Feedback on the item "ConfigureViewInFileExplorer".

### ISSUE THREAD

**Issue by hhidakaa** [MicrosoftDocs/Edge-Enterprise#267]
[Enter feedback here]
Feedback on the item "ConfigureViewInFileExplorer".
This item describes how to register a single site, but does not describe how to register multiple sites.
It is possible to register multiple sites by writing the following, but we would like you to include it in the official documentation.
Please include it in the official documentation.
{ "cookies": [ "rtFa", "FedAuth" ], "domain": "contoso.sharepoint.com" }, { "cookies": [ "rtFa", "FedAuth" ], "domain": "test.sharepoint.com" }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#configureviewinfileexplorer)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@hhidakaa Thanks for the feedback!  I've passed this on to the team.

**Comment by Y-Kelly** [comment]
@hhidakaa The documentation has been updated: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#configureviewinfileexplorer

Thanks!
