### ISSUE TITLE
Landing page detection & RDP services

### ISSUE THREAD

**Issue by BrettF-ALES** [MicrosoftDocs/Edge-Enterprise#27]
So, it's not clear if using the Win7 version is ok for 2008R2 as there is no 2008R2 to manually download. Safe for Terminal Server?
 Yes yes, upgrade we know, our "summer plans" have been a little pushed back like everyone else. Now we have a farm we need to keep alive as is until the world goes back to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b402dcf-d79b-71a2-a942-4b5b17cfe1b2
* Version Independent ID: 861380ed-e39d-6896-5fee-09649afda5f7
* Content: [Microsoft Edge Supported Operating Systems](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-supported-operating-systems#feedback)
* Content Source: [edgeenterprise/microsoft-edge-supported-operating-systems.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-supported-operating-systems.md)
* Product: **microsoft-edge**
* GitHub Login: @srugh
* Microsoft Alias: **srugh**

**Comment by Y-Kelly** [comment]
Cleaning up old issues.  Question appears to have been previously answered.  

If you have further questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
