### ISSUE TITLE
Clarification: Why do Microsoft security baselines recommend disabling the password manager?

### ISSUE THREAD

**Issue by LaPhi** [MicrosoftDocs/Edge-Enterprise#270]
Please can you add more information about the statement in the section "Why do Microsoft security baselines recommend disabling the password manager?"
At the moment the statement is not very helpful and raises more questions.

1. Which worm?
2. What is the attack vector/scenario?
3. What security-enhancing features will be added?
4. When will the security-enhancing features be added? (Roadmap?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f651e68c-34bf-d399-88e9-c9a0928d8be4
* Version Independent ID: ad34ee59-01d3-c64d-d123-5484264190b8
* Content: [Microsoft Edge password manager security ](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-security-password-manager-security#why-do-microsoft-security-baselines-recommend-disabling-the-password-manager)
* Content Source: [edgeenterprise/microsoft-edge-security-password-manager-security.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-security-password-manager-security.md)
* Product: **microsoft-edge**
* GitHub Login: @AndreaLBarr
* Microsoft Alias: **v-andreabarr**

**Comment by Y-Kelly** [comment]
@LaPhi Thanks for reaching out!  We are checking with the team for clarification.

**Comment by Y-Kelly** [comment]
@LaPhi  It is on our roadmap to update the security baselines.  You should be able to see updates announced here: https://techcommunity.microsoft.com/t5/microsoft-security-baselines/bg-p/Microsoft-Security-Baselines

In regards to your specific questions, please see the following answers from the team: 

**Which worm?**
_This term was used to give an example of a virus that could potentially compromise all the PCs in an enterprise, once it has access. It was used as an example of the perceived trade-offs of using a password manager (where the benefit is defense against phishing sites, but comes at a potential risk of consolidating all your passwords in one location which could – in theory – be stolen by said worm)_

**What is the attack vector/scenario?**
_This term is used to signify that by having the password encryption keys of a device available in memory for any application that is running on the same machine, they can be unencrypted and stolen very easily. But this is stated as an incorrect assessment of the password manager as it’s threat model does not cover within its ambit defending against full-trust malware running on a device._ 

**What security-enhancing features will be added?**
_•	PassGen
•	Primary Password
•	Password Monitor_

**When will the security-enhancing features be added? (Roadmap?)**
_All have been added to Microsoft Edge_
