### ISSUE TITLE
NewTabPageLocation in Recommened Settings blocks user changes as well

### ISSUE THREAD

**Issue by mattncsu** [MicrosoftDocs/Edge-Enterprise#272]
Was this issue resolved (https://github.com/MicrosoftDocs/EdgeEnterprise/issues/49)?

> NewTabPageLocation in Recommened Settings blocks user changes as well. Seems to be a bug.

**Comment by Y-Kelly** [comment]
@mattncsu Hi! For the NewTabPageLocation policy, the recommended version of this policy does not currently work and functions exactly like the mandatory version.  https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-policies#newtabpagelocation
