### ISSUE TITLE
moje

### ISSUE THREAD

**Issue by MICHALKAMIL** [MicrosoftDocs/Edge-Enterprise#276]
[Wprowadź tutaj swoją opinię]

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 3fa2b6bb-c572-6b62-0b2a-5d11cc6c16c2
* Version Independent ID: bbd72cfb-0dd2-dce0-ede7-6887a2992bad
* Content: [Reset Microsoft Edge data](https://docs.microsoft.com/pl-pl/deployedge/edge-learnmore-reset-data-in-cloud)
* Content Source: [edgeenterprise/edge-learnmore-reset-data-in-cloud.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-reset-data-in-cloud.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **collw**

**Comment by MICHALKAMIL** [comment]
[
[Backup-codes-michal.w.1391.txt](https://github.com/MicrosoftDocs/Edge-Enterprise/files/7697094/Backup-codes-michal.w.1391.txt)
](url)

**Comment by dan-wesley** [comment]
@MICHALKAMIL I'm sorry, I don't understand your feedback. Can you provide it in English? Thank you.

**Comment by Y-Kelly** [comment]
Closing
