### ISSUE TITLE
[ikugyi

### ISSUE THREAD

**Issue by MICHALKAMIL** [MicrosoftDocs/Edge-Enterprise#277]
[
[Backup-codes-michal.w.1391.txt](https://github.com/MicrosoftDocs/Edge-Enterprise/files/7697094/Backup-codes-michal.w.1391.txt)
](url)

_Originally posted by @MICHALKAMIL in https://github.com/MicrosoftDocs/Edge-Enterprise/issues/276#issuecomment-991642405_

**Comment by Y-Kelly** [comment]
@MICHALKAMIL Do you have an issue with the Microsoft Edge Enterprise Documentation?

**Comment by Y-Kelly** [comment]
closing
