### ISSUE TITLE
Topic Mentioned Twice:

### ISSUE THREAD

**Issue by CharingJC** [MicrosoftDocs/Edge-Enterprise#278]
[Enter feedback here]
Following Topic Mentioned Twice:
Can I test a site in Microsoft Edge while it is configured to open IE mode in the Enterprise Mode Site List?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b539b61a-453d-9032-3f9c-8e0a537a8f7d
* Version Independent ID: 89647f8d-5793-5fab-d430-c549976ddad3
* Content: [IE mode troubleshooting and FAQ](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-faq)
* Content Source: [edgeenterprise/edge-ie-mode-faq.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode-faq.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **shisub**

**Comment by dan-wesley** [comment]
@CharingJC I'll pass your question on to someone who answer it. Thank you.

**Comment by dan-wesley** [comment]
@CharingJC Redundant faq item deleted, text in remaining updated.
