### ISSUE TITLE
How to prevent users signing into edge synchronisation bookmarks on personal device?

### ISSUE THREAD

**Issue by appelboom** [MicrosoftDocs/Edge-Enterprise#28]
In the enterprise we wish to allow sync across devices  by unsetting and then permitting the types https://docs.microsoft.com/en-gb/DeployEdge/microsoft-edge-policies#syncdisabled

Testing shows that users can sign into personal devices which we wish to prevent however there appears that there is no Conditional Access condition to prevent a synchronisation signin from a unmanaged device.
Application	Microsoft Edge
Client app	Mobile Apps and Desktop clients
Resource	         Microsoft Activity Feed Service
Browser	         Edge
Authentication method RemoteNGC

The scenario we wish to prevent is users leaking the bookmarks of enterprise applications

Eric

**Comment by Y-Kelly** [comment]
Documentation has been updated here: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-enterprise-sync-faq#is-it-possible-to-prevent-sign-in-and-sync-with-an-enterprise-account-on-an-unmanagednon-compliant-device

![image](https://user-images.githubusercontent.com/74324031/185213338-9226421a-ae4c-4a40-b1a0-da0b69b67443.png)

Closing this issue.
