### ISSUE TITLE
Availability in US gov clouds?

### ISSUE THREAD

**Issue by chuckdorsett** [MicrosoftDocs/Edge-Enterprise#280]
Greetings. I am a CSAM for a government customer. Kindly comment/clarify what cloud instances this new exciting feature is available in. Looking at the M365 roadmap item (https://www.microsoft.com/en-us/microsoft-365/roadmap?featureid=88257) it looks like only worldwide (commercial) and not any of the gov clouds in US yet. My customers are in GCC (Moderate). At a minimum, an "applies to:" note at the bottom here would be useful. Thanks! Feel free to contact me via my alias chdorset.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1a4c286-c376-c1aa-86d8-80a842861435
* Version Independent ID: a1a4c286-c376-c1aa-86d8-80a842861435
* Content: [Cloud Site List Management for Internet Explorer (IE) mode'](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-cloud-site-list-mgmt)
* Content Source: [edgeenterprise/edge-ie-mode-cloud-site-list-mgmt.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode-cloud-site-list-mgmt.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **shisub**

**Comment by Y-Kelly** [comment]
@chuckdorsett Thanks!  Documentation being updated, closing this issue.
