### ISSUE TITLE
Problems with the extension policy documentation

### ISSUE THREAD

**Issue by shubhamrai1993** [MicrosoftDocs/Edge-Enterprise#283]
```
For Microsoft Edge, all settings will start under this key:

HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\

The next key that you will create is either the Extension ID for individual scope or an asterisk (*) for the Default Scope. For example, you'd use the following location for settings that apply to Google Hangouts:

HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\ExtensionSettings\nckgahadagoaajjgafhacjanaoiihapd
```
The example has another key between Edge and the extension id i.e. `ExtensionSettings`. This is creating confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06f0b77d-8fc4-90c1-93cb-e781352efdf2
* Version Independent ID: 2a21fd70-443b-8ac1-4541-d5b6bf882881
* Content: [Detailed guide to the ExtensionSettings policy](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-manage-extensions-ref-guide#using-installation_mode-property-to-force-install-extensions)
* Content Source: [edgeenterprise/microsoft-edge-manage-extensions-ref-guide.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-manage-extensions-ref-guide.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **aspoddar**

**Comment by dan-wesley** [comment]
@shubhamrai1993 Thank you for your feedback. Just to confirm, the key for the Google hangouts example should be:

HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\nckgahadagoaajjgafhacjanaoiihapd

**Comment by dan-wesley** [comment]
@ashishnirvana1 Hi Ashish, do you want to weigh in on this? Thanks, dan

**Comment by Y-Kelly** [comment]
@shubhamrai1993 Our developers have confirmed that HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\ExtensionSettings is the correct path to configure the ExtensionSettings policy.

They also mentioned that all MS Edge policies live under HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge. If someone wants to configure ExtensionSettings, that can be done at the path mentioned above. For some other policy (say ExtensionInstallForceList), that can be done in a similar way at this path: SOFTWARE\Policies\Microsoft\Edge\ExtensionInstallForcelist

Thanks!
