### ISSUE TITLE
RSS feeds?

### ISSUE THREAD

**Issue by kbjc11686** [MicrosoftDocs/Edge-Enterprise#284]
Does this page support RSS feeds? Tried adding /rss.xml and /feed.xml but I'd rather ask here now if you support it. And if not, can you enable support for it? Very useful way for us to track update releases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ffcaf54-ce86-1b30-e947-540bf07a54c3
* Version Independent ID: 81267e97-e284-ff00-b081-476934538326
* Content: [Microsoft Edge release notes for Stable Channel](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel#feedback)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **leahtu**

**Comment by Y-Kelly** [comment]
@kbjc11686 Thank you for your feedback.  Currently, we do not support RSS feeds and we do not have anything on our short term roadmap regarding new features to notify users about documentation updates but I have passed your suggestions on to the team.
