### ISSUE TITLE
EDGE 97 Excel Policy template not updated - Similar issue on every new release

### ISSUE THREAD

**Issue by NConnects** [MicrosoftDocs/Edge-Enterprise#288]
Hi Microsoft Team,

EDGE 97 Excel policy template is not updated in below link. Please check and update.  

https://www.microsoft.com/en-us/download/details.aspx?id=55319

https://techcommunity.microsoft.com/t5/discussions/latest-edge-browser-policies-in-excel-template-not-showing-not/m-p/3054347

**Comment by NConnects** [comment]
@Y-Kelly, Could you please check this?

**Comment by Y-Kelly** [comment]
@NConnects Hi!  I would recommend checking out https://techcommunity.microsoft.com/t5/microsoft-security-baselines/bg-p/Microsoft-Security-Baselines to monitor when the update is available.  

You can also provide feedback to the team directly through the Security Baseline Community https://techcommunity.microsoft.com/t5/microsoft-security-baselines/bd-p/Security-Baselines.  Thanks!

**Comment by NConnects** [comment]
Hi Y-Kelly, But, still i dont see the baseline for EDGE 97 in mentioned link

https://techcommunity.microsoft.com/t5/microsoft-security-baselines/bg-p/Microsoft-Security-Baselines

**Comment by NConnects** [comment]
@Y-Kelly , Still I don't see EDGE 97 Compliance baseline templates. It should get updated after every new release. In the mentioned link, I could see only EDGE 96.
