### ISSUE TITLE
URLAllowlist documentation is missing protocol handling

### ISSUE THREAD

**Issue by NilsPeper** [MicrosoftDocs/Edge-Enterprise#29]
URLAllowlist is capable to whitelist more than just regular URLs.
e.g.:
"ms-excel://*"
"msteams://*"
[...]
"receiver://*" for citrix

Can't find this information in the current documentation.

**Comment by Y-Kelly** [comment]
Cleaning up old issues.  Policy documentation for URLAllowlist now does include URL pattern information https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#urlallowlist
