### ISSUE TITLE
InstallDefault prevents WebView2 Runtime installation

### ISSUE THREAD

**Issue by JoshTech1** [MicrosoftDocs/Edge-Enterprise#290]
Hello,

Setting InstallDefault to 0 prevents the WebView2 Runtime installation from occurring. I tried changing each of the four Install{GUID} values, one at a time, from 0 to 1, but continually found that the WebView2 Runtime installer produced an error saying group policy was preventing the installation. Only after I changed InstallDefault from 0 to 1 did the install proceed.

It would be helpful to have this documented as it was preventing installation of a third-party application which includes WebView2 Runtime.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96fddabd-2bac-2fab-a5ea-25c000b425fc
* Version Independent ID: 41bba38e-bd24-0496-da04-012d6deb5db8
* Content: [Microsoft Edge Update Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-update-policies#microsoft-edge-webview)
* Content Source: [edgeenterprise/microsoft-edge-update-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-update-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@JoshTech1 Documentation about Microsoft Edge - Update policies and WebView2 can be found here: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/enterprise#group-policies-for-webview2

It mentions that "Microsoft Edge - Update policies are available for IT admins to manage the install and update aspects of the WebView2 Runtime. The Microsoft Edge browser and WebView2 Runtime are updated using the same update mechanism."  Thanks!
