### ISSUE TITLE
When will the release notes for 96.0.1054.72 be added?

### ISSUE THREAD

**Issue by tatsuya-midorikawa** [MicrosoftDocs/Edge-Enterprise#291]
When will the release notes for 96.0.1054.72 be added?
Also, what changes have been made in 96.0.1054.72?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ffcaf54-ce86-1b30-e947-540bf07a54c3
* Version Independent ID: 81267e97-e284-ff00-b081-476934538326
* Content: [Microsoft Edge release notes for Stable Channel](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **leahtu**

**Comment by Y-Kelly** [comment]
@tatsuya-midorikawa Sorry for the delay.  The Release Notes have been updated: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel

Thanks!
