### ISSUE TITLE
Documentation is localized too infrequently.

### ISSUE THREAD

**Issue by tatsuya-midorikawa** [MicrosoftDocs/Edge-Enterprise#292]
Hi,

The time between when the English documentation is updated and when it is localized is very long.
For example, the release notes for Edge are ver. 97.0.1072.55 in the English version, but they are stuck at ver. 94.0.992.58 in the Japanese version.
To be honest, if the interval is more than a month, the information is too old to be of any use.
May I ask you to increase the frequency of your updates?

Thanks,
midoliy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ffcaf54-ce86-1b30-e947-540bf07a54c3
* Version Independent ID: 81267e97-e284-ff00-b081-476934538326
* Content: [Microsoft Edge release notes for Stable Channel](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **leahtu**

**Comment by Y-Kelly** [comment]
Comparing the Stable release notes for [en-us](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel) to [ja-jp](https://docs.microsoft.com/ja-jp/deployedge/microsoft-edge-relnote-stable-channel) I do not see any difference in the information.  This might have been an intermittent issue.  Closing.
