### ISSUE TITLE
profile not syncing?

### ISSUE THREAD

**Issue by Linas08** [MicrosoftDocs/Edge-Enterprise#295]
I do not see the Reset Sync option I try settings > Profiles > Reset sync. but there is no Reset Sync?
how to get the users profile to sync?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa2b6bb-c572-6b62-0b2a-5d11cc6c16c2
* Version Independent ID: bbd72cfb-0dd2-dce0-ede7-6887a2992bad
* Content: [Reset Microsoft Edge data](https://docs.microsoft.com/en-us/deployedge/edge-learnmore-reset-data-in-cloud)
* Content Source: [edgeenterprise/edge-learnmore-reset-data-in-cloud.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-reset-data-in-cloud.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
@Linas08 Hello - You should be able to find Reset Sync by navigating to Settings -> Profiles -> Sync and then scroll down to Rest sync.  You should also be able to just navigate directly to edge://settings/profiles/sync

![image](https://user-images.githubusercontent.com/74324031/149584652-fc97bc90-d059-4db6-9a70-fc754f0f6451.png)

**Comment by Linas08** [comment]
I tried and there is no Reset sync now under Profiles why will the profile not sync?


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
