### ISSUE TITLE
Android OS requirements may be incorrect

### ISSUE THREAD

**Issue by ericnoble1991** [MicrosoftDocs/Edge-Enterprise#296]
I have a Samsung SM-T365 Tablet running Android 5.1.1 and the Google Play Store states that it is not compatible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86847b80-8f8e-9493-86ff-5dfd6412b48f
* Version Independent ID: 2ce02bc3-24a1-8c9f-c787-34ab90e9f31d
* Content: [Microsoft Edge Supported Operating Systems](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-supported-operating-systems)
* Content Source: [edgeenterprise/microsoft-edge-supported-operating-systems.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-supported-operating-systems.md)
* Product: **microsoft-edge**
* GitHub Login: @srugh
* Microsoft Alias: **srugh**

**Comment by Y-Kelly** [comment]
@ericnoble1991 Hello - I checked and can see that we've had feedback from other devices that are running Android 5.1.1.  Are you still reproducing the error?  It might be an issue specific to the device.
