### ISSUE TITLE
Other conditions that can trigger the popup

### ISSUE THREAD

**Issue by aharown17** [MicrosoftDocs/Edge-Enterprise#297]
I'm getting the popup on a development site that is all http, no https at all--only on .doc and .docx files (so far). PDF files download without difficulty.
Information about other triggers for this popup/notice would be great.
Can lack of https entirely set it off?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79fb9385-b88f-56ac-1a9b-a7f5692030de
* Version Independent ID: 2a838189-6755-acd6-fcfe-082d6e8d1e7f
* Content: [Learn how Microsoft Edge handles mixed content downloads](https://docs.microsoft.com/en-us/DeployEdge/edge-learnmore-mixed-content-downloads)
* Content Source: [edgeenterprise/edge-learnmore-mixed-content-downloads.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-mixed-content-downloads.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **collw**

**Comment by ericlaw1979** [comment]
Can you please show a screenshot of the edge://downloads page while in this bad state?

**Comment by Y-Kelly** [comment]
Clean up of old issues.  There has not been activity in this thread for a while.  



If you have general questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsiderForum) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
