### ISSUE TITLE
Wrong translation on Japanese version 

### ISSUE THREAD

**Issue by nonakaji** [MicrosoftDocs/Edge-Enterprise#299]
[Enter feedback here]
In this doc, 
[We will continue to support Microsoft Edge on Windows 7 and on Windows Server 2008 R2 until January 15, 2023. ]
but on Japanese version doc, the date is written as January 15, 2022.

Please fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86847b80-8f8e-9493-86ff-5dfd6412b48f
* Version Independent ID: 2ce02bc3-24a1-8c9f-c787-34ab90e9f31d
* Content: [Microsoft Edge Supported Operating Systems](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-supported-operating-systems)
* Content Source: [edgeenterprise/microsoft-edge-supported-operating-systems.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-supported-operating-systems.md)
* Product: **microsoft-edge**
* GitHub Login: @srugh
* Microsoft Alias: **srugh**

**Comment by Y-Kelly** [comment]
@nonakaji Just to confirm, is this where you were seeing a typo?  https://docs.microsoft.com/ja-jp/deployedge/microsoft-edge-supported-operating-systems

I'm currently not able to reproduce.  Here is a screenshot:

![image](https://user-images.githubusercontent.com/74324031/151891178-a1d76c77-b550-4d5f-9189-f870309bb7ab.png)

**Comment by nonakaji** [comment]
Thank you. I just confirmed the fix.

Regards,
Norihiko Nakajima
