### ISSUE TITLE
Windows 10 IoT Enterprise LTSC

### ISSUE THREAD

**Issue by MPICOLLET** [MicrosoftDocs/Edge-Enterprise#3]
Edge Browser will be supported on Windows 10 IoT Enterprise LTSC by microsoft ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b402dcf-d79b-71a2-a942-4b5b17cfe1b2
* Version Independent ID: 861380ed-e39d-6896-5fee-09649afda5f7
* Content: [Microsoft Edge Supported Operating Systems](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-supported-operating-systems#feedback)
* Content Source: [edgeenterprise/microsoft-edge-supported-operating-systems.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-supported-operating-systems.md)
* Product: **microsoft-edge**
* GitHub Login: @srugh
* Microsoft Alias: **srugh**

**Comment by Y-Kelly** [comment]
Closing this old issue.  Documentation for supported operating systems here: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-supported-operating-systems
