### ISSUE TITLE
How about a section for when IE is incorrectly detected as not turned on in features?

### ISSUE THREAD

**Issue by yowl** [MicrosoftDocs/Edge-Enterprise#30]
I have a case where Edge, Internet Explorer mode diagnostic information shows Enable Internet Explorer in Windows features:
Off   .   But in Windows features it is checked and is working.  What to do in this case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52acc6ed-8a4c-2e63-a31c-3742c316b471
* Version Independent ID: 502578e7-154b-5b54-1d07-234979ae625f
* Content: [IE mode FAQ](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-faq)
* Content Source: [edgeenterprise/edge-ie-mode-faq.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/edge-ie-mode-faq.md)
* Product: **microsoft-edge**
* GitHub Login: @cjacks
* Microsoft Alias: **cjacks**

**Comment by Y-Kelly** [comment]
Clean up of old issues.  Closing.  

This is used to report Microsoft Edge Enterprise documentation issues.  

If you still have questions about Microsoft Edge, please reach out on the [Microsoft Edge Tech Community](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsiderForum) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
