### ISSUE TITLE
Quick docs needed for Developers looking to setup IE Mode in Chromium Edge to AD-HOC test legacy content 

### ISSUE THREAD

**Issue by scunliffe** [MicrosoftDocs/Edge-Enterprise#300]
All of the docs listed here so far that I've found have been purely IT admin focused.  There is a need from developers to be able to enable IE mode locally on their Chromium Edge install, to be able to quickly add/remove/toggle adding the site(s) they work on to (A) ensure that the legacy content still works in IE Mode, and (B) more importantly, aggressively work on updating the content ASAP to not require IE Mode long term.

e.g. If their browser is currently controlled by Group Policy, what is the *exact* group policy setting they need to tell their IT department to toggle to allow a developer to be able to add/remove an ad-hoc site from IE Mode.

**Comment by Y-Kelly** [comment]
@scunliffe If you are on a managed device, here is the documentation https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-local-site-list#enable-the-local-site-list-experience.  Once set up, this will allow users to choose "Reload in Internet Explorer mode".  

If you are on a personal device (not managed), here is the documentation https://support.microsoft.com/en-us/office/internet-explorer-mode-in-microsoft-edge-6604162f-e38a-48b2-acd2-682dbac6f0de

Thanks!
