### ISSUE TITLE
RestrictSigninToPattern policy value data incorrect

### ISSUE THREAD

**Issue by hlekhi** [MicrosoftDocs/Edge-Enterprise#301]
Hi there,

I am trying to implement a policy in our small sized organization to disable sign in with the personal account. I can't even sign in to sync data with the company's email address. 

It should only prevent me from accessing personal accounts, however we would like to access work account. It is giving me the same error 
------------ Your system administrator has not granted xxx@domain.com sign in permissions. You can try another email address, contact your system administrator for more information ----------------------
 
It seems something is wrong with the regular expression. Kindly assist.

Cheers
Himanish

**Comment by Y-Kelly** [comment]
@hlekhi The RestrictSigninToPattern is a list of accounts that are allowed to sign in.  Just to confirm, is it the work account information that you used when configuring the policy?

**Comment by hlekhi** [comment]
@Y-Kelly  Yes, I used the work account when configuring the policy. . I think I found the problem. It was because of the usage of the double quotes in the registry key. I shouldn't have used the double quotes. :)


I was using ".*@domain.com" instead of .*@domain.com

Cheers :)

**Comment by Y-Kelly** [comment]
Great, thanks!  I'll close this :)
