### ISSUE TITLE
Duplicate policies in release notes

### ISSUE THREAD

**Issue by SIkebe** [MicrosoftDocs/Edge-Enterprise#302]
There are a lot of duplicate policies in "New Policies" sections.
For example, `InternetExplorerIntegrationWindowOpenWidthAdjustment` is in 95.0.1020.30, 96.0.1054.29, 97.0.1072.55, 98.0.1108.43.
It is difficult to assume exactly which version of Edge introduced the polices.

@dan-wesley Could you fix that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ffcaf54-ce86-1b30-e947-540bf07a54c3
* Version Independent ID: 81267e97-e284-ff00-b081-476934538326
* Content: [Microsoft Edge release notes for Stable Channel](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **leahtu**

**Comment by SIkebe** [comment]
Related to #285

**Comment by Y-Kelly** [comment]
@SIkebe Thanks!  This has been fixed.  Closing the issue.
