### ISSUE TITLE
The page mentions the policy "Allow sites to be reloaded in Internet Explorer mode", while in the latest ADMX file the policy is named "Allow UNCONFIGURED sites to be reloaded in Internet Explorer mode"

### ISSUE THREAD

**Issue by johanVAva3** [MicrosoftDocs/Edge-Enterprise#306]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 459e4d0d-27b0-753e-3a60-b8ec6b2092b5
* Version Independent ID: 05413a17-f068-8429-af7f-77665f321bbb
* Content: [Local site list for Internet Explorer (IE) mode](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-local-site-list#policy-internetexplorerintegrationreloadiniemodeallowed)
* Content Source: [edgeenterprise/edge-ie-mode-local-site-list.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode-local-site-list.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **shisub**

**Comment by Y-Kelly** [comment]
@johanVAva3 Just to confirm, I believe "Allow sites to be reloaded in Internet Explorer mode" is referring to the setting in Microsoft Edge not the policy description.  
![image](https://user-images.githubusercontent.com/74324031/153312594-73dbb8d9-ea56-47df-948a-d6ec0f7befd7.png)

![image](https://user-images.githubusercontent.com/74324031/153312910-80652774-472e-40e9-97f0-6d8a01363f4a.png)

**Comment by johanVAva3** [comment]
Hi Kelly, yes it seems to be correct then. Issue may be closed.

Anyway, it would have added value for the article to mention the policy correct with its name ('....unconfigured sites...'), value 'InternetExplorerIntegrationReloadInIEModeAllowed' and data.
Mentioning it like 'policy: InternetExplorerIntegrationReloadInIEModeAllowed' does not give the full info for IT admins, if that is the target audience for the article.

**Comment by Y-Kelly** [comment]
@johanVAva3 Thanks!
