### ISSUE TITLE
BackgroundModeEnabled

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/Edge-Enterprise#307]
Hello,

Seems this not working, deployed well to PC via Endpoint, but when EDGE closed still can see "msedge.exe" processes running in the task manager:

![image](https://user-images.githubusercontent.com/39700914/153366508-3b6ad403-bb55-488e-81ce-dca38dfc79b7.png)

After EDGE closed:

![image](https://user-images.githubusercontent.com/39700914/153366727-a8897ae2-0e5d-4970-a42b-64129ef95660.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@lightupdifire Hi!  We've reached out to our developers.  One thing that might be happening is startup boost could be keeping the msedge.exe process running.  https://support.microsoft.com/en-us/topic/get-help-with-startup-boost-ebef73ed-5c72-462f-8726-512782c5e442

There is a policy for startup boost as well: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#startupboostenabled

If you are still having an issue, it would be helpful to get more information.  Specifically, can you share more about your scenario and what you are trying to achieve?  Thanks!

**Comment by lightupdifire** [comment]
@Y-Kelly 
I try to close Edge so it doesn't run in the background. After setting "startupboostenabled" to 0 all processes closed! Thanks :)
Maybe a document update is needed to add info about the combination of both policies?

**Comment by Y-Kelly** [comment]
@lightupdifire Thanks!  Closing this issue.
