### ISSUE TITLE
About [AutoLaunchProtocolsFromOrigins] Policy

### ISSUE THREAD

**Issue by hhidakaa** [MicrosoftDocs/Edge-Enterprise#309]
We have verified the [AutoLaunchProtocolsFromOrigins] policy and confirmed that only lower case letters can be used to specify protocols.
As the above information is not mentioned in the public information, there is a high possibility of confusion among engineers who view the page.
Please add it to the public information.

<It works fine
[{"allowed_origins": ["*"], "protocol": "skype"}]]

<Does not work properly
[{"allowed_origins": ["*"], "protocol": "Skype"}]]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#feedback)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@hhidakaa Thanks for the suggestion.  I've pass this information on to the team to evaluate updating the documentation.

**Comment by Y-Kelly** [comment]
Clean up of old issues, this has been relayed to the team and they have a work item in the backlog.  They will update as necessary.

**Comment by Y-Kelly** [comment]
@hhidakaa Team has made the update which should be reflected in an upcoming refresh of the browser policy reference doc.  Thanks!
