### ISSUE TITLE
Add Releases and Changelog when larger changes are made

### ISSUE THREAD

**Issue by apizz** [MicrosoftDocs/Edge-Enterprise#31]
For many admins, we watch these documentation repos for new management preferences and changes.  However, there currently isn't a way to be automatically notified of these from this repo.

When changes are made to the documentation with preference additions and changes, it would be really helpful to add these to a change log under this repo's releases so that we can be notified when these occur.  This way we can we use the 'Releases' notification option.  This is similar to what is done with Firefox in their policy-templates repo: https://github.com/mozilla/policy-templates/releases/tag/v1.16

![Screen Shot 2020-05-06 at 8 05 54 AM](https://user-images.githubusercontent.com/11789931/81174816-79c0a980-8f70-11ea-89a7-048260f60eb8.png)

Additionally, this would help track these larger changes over time.

**Comment by Y-Kelly** [comment]
@apizz Cleaning up some older issues.  

Thank you for your feedback.  Currently, we do not have anything on our short-term roadmap regarding new features to notify users about documentation updates but I have passed your suggestions on to the team.
