### ISSUE TITLE
MicrosoftEdgeInsiderPromotionEnabled not working

### ISSUE THREAD

**Issue by JasonNVSD** [MicrosoftDocs/Edge-Enterprise#311]
I have MicrosoftEdgeInsiderPromotionEnabled set to false, but I'm still seeing Insider promotion.

![image](https://user-images.githubusercontent.com/26413177/154539061-49669417-4d34-4bae-9fb3-0f5b785fa7c6.png)

![image](https://user-images.githubusercontent.com/26413177/154539162-59aedb0f-c3cf-4817-bc8d-f7df87a60eec.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-ca/DeployEdge/microsoft-edge-policies#microsoftedgeinsiderpromotionenabled)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@JasonNVSD Hi!  Looks like we've had other reports about the policy not working and the team is currently investigating.  We can follow up once we have more information.  Thanks!

**Comment by Y-Kelly** [comment]
@JasonNVSD Our developers just released a fix which should be in MS Edge Canary channel v100.0.1181.0+.  Please test and let us know if you are still having an issue.  

We are investigating backporting the fix to v99.  Thanks!
