### ISSUE TITLE
Wrong release date v98 for Extended Stable release

### ISSUE THREAD

**Issue by NorbertKlein-Ildefeld** [MicrosoftDocs/Edge-Enterprise#312]
v98 was release to Extended Stable in Feb 
![image](https://user-images.githubusercontent.com/44286782/154638456-4a5f04ab-f983-4065-bb95-4fab2c931d68.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d1bc306-56a5-f501-b3e0-a661d57b1db4
* Version Independent ID: e4ef685b-8570-be80-9547-9956042b967e
* Content: [Microsoft Edge release schedule](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-release-schedule)
* Content Source: [edgeenterprise/microsoft-edge-release-schedule.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-release-schedule.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **leahtu**

**Comment by dan-wesley** [comment]
@NorbertKlein-Ildefeld Thank you for the information, I'll sync up with Leah on this.

**Comment by dan-wesley** [comment]
The extended stable should be released before stable 99. Remember, these dates are projections.

**Comment by NorbertKlein-Ildefeld** [comment]
You are confusing me. Extended stable release has been on v98 since beginning of February. Release schedule table is misleading
![image](https://user-images.githubusercontent.com/44286782/155082804-44c5c5ab-2bd9-4d96-8fb5-ee556dcdd9cf.png)

**Comment by dan-wesley** [comment]
@NorbertKlein-Ildefeld thank you for your feedback. We're republishing the doc which will hopefully clarify things.

**Comment by NorbertKlein-Ildefeld** [comment]
yes, much clearer now. Many thanks
