### ISSUE TITLE
Edit Required for the below article

### ISSUE THREAD

**Issue by AshishSukhija1** [MicrosoftDocs/Edge-Enterprise#314]
Document referred:- https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-site-discovery 
Section that has incorrect / misleading info: https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-site-discovery#configure-the-site-discovery-sample-report 

After Step 6, we should mention what Data Source to select (Microsoft SQL Server), it defaults to Microsoft SQL Server Analysis Services. And sometimes, we need to switch the account or open Report Builder with elevated permissions otherwise it wont show any database. Apart from that, the second report (.rdl) file for ActiveX has missing info in the Query This section: https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-site-discovery#configure-the-activex-sample-report

In Step-11, USE CM_A1B should be the first line in the query, its missing. And we also have to replace CM_A1B with the actual name of the database 4 more times in that query, see below:

FROM [CM_A1B].[dbo].[v_GS_IEURLINFO]) AS IEURLInfo CROSS APPLY String.nodes ('/M') AS Split(a) ) AS IEURLInfo, [CM_A1B].[dbo].[v_ClientMachines] AS ClientInfo, [CM_A1B].[dbo].[v_GS_IESYSTEMINFO] AS IESystemInfo, [CM_A1B].[dbo].[v_GS_IECOUNTINFO] AS IECountInfo Please reachout for any queries.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2883b89f-a5ec-c549-3a9e-22c010d0b527
* Version Independent ID: 6518eff2-f389-a4c7-0d8d-f3ba47c650cc
* Content: [Enterprise Site Discovery Step by Step Guide](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-site-discovery)
* Content Source: [edgeenterprise/edge-ie-mode-site-discovery.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode-site-discovery.md)
* Product: **microsoft-edge**
* GitHub Login: @appcompatguy
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
@AshishSukhija1 Thanks for the feedback!  We've made updates and changes to the document (https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-site-discovery).
