### ISSUE TITLE
AutoImportAtFirstRun don't work over Edge v97

### ISSUE THREAD

**Issue by yosada** [MicrosoftDocs/Edge-Enterprise#315]
AutoImportAtFirstRun don't work on Edge v97, v98. It works on v94, v95, v96.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@yosada Are you using both the AutoImportAtFirstRun and HideFirstRunExperience policies?  

We've had some other reports and are currently investigating.  We can follow up with insights from the team or if we need additional information.  Thanks!

**Comment by yosada** [comment]
@Y-Kelly  No, I just set AutoImportAtFirstRun only.

Since v97, first run experience has changed, so it may seem that MS dropped this function.

**Comment by Y-Kelly** [comment]
@yosada Hi!  Our developers have released a fix on MS Edge Canary Channel v101.0.1204.0+.  Let us know if you are still able to reproduce after updating.  

Also, I believe they are working on backporting the fix to v100.  Thanks!

**Comment by yosada** [comment]
Thank you. It seems OK.

**Comment by Y-Kelly** [comment]
Thanks.  Closing this issue.
