### ISSUE TITLE
CreateDesktopShortcutDefault and others missing from edge://policy

### ISSUE THREAD

**Issue by JasonNVSD** [MicrosoftDocs/Edge-Enterprise#316]
The policies work but some of them aren't listed in the "Microsoft Edge Update Policies" section of edge://policy

Is this by design?  If yes, please say so in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96fddabd-2bac-2fab-a5ea-25c000b425fc
* Version Independent ID: 41bba38e-bd24-0496-da04-012d6deb5db8
* Content: [Microsoft Edge Update Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-update-policies)
* Content Source: [edgeenterprise/microsoft-edge-update-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-update-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@JasonNVSD Hello - Is this issue still occurring?  If so, do you know what other Update Policies were not showing up in edge://policy?  Thanks!

**Comment by Y-Kelly** [comment]
@JasonNVSD Closing as it has been a couple months with no reply.  I do see there was work done in this area to add Update Policies to edge://policy.  If you are still reproducing the issue, please provide additional details or you can contact Microsoft Support (https://developer.microsoft.com/en-us/microsoft-edge/support/) to investigate your specific case.  Thanks!
