### ISSUE TITLE
Please reveal WHERE/HOW new features can be accessed!

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/Edge-Enterprise#317]
When new features are mentioned in release notes, please reveal where and how they can be found or used.

E.G. PDF thumbnail navigation (via PDF Toolbar, Table of Contents, Image icon) and Custom Primary Password (via Settings, Profiles, Passwords).

You know where you've hidden these new things but we do not.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ffcaf54-ce86-1b30-e947-540bf07a54c3
* Version Independent ID: 81267e97-e284-ff00-b081-476934538326
* Content: [Microsoft Edge release notes for Stable Channel](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-relnote-stable-channel)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **leahtu**

**Comment by Y-Kelly** [comment]
Thank you for the feedback about the release notes.  We are continually trying to improve the release notes and your feedback has been relayed to the team.
