### ISSUE TITLE
Bad Link

### ISSUE THREAD

**Issue by JasonNVSD** [MicrosoftDocs/Edge-Enterprise#318]
In the RollbackToTargetVersion section, there's a link to https://go.microsoft.com/fwlink/?linkid=2133918 which is 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96fddabd-2bac-2fab-a5ea-25c000b425fc
* Version Independent ID: 41bba38e-bd24-0496-da04-012d6deb5db8
* Content: [Microsoft Edge Update Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-update-policies#rollbacktotargetversion)
* Content Source: [edgeenterprise/microsoft-edge-update-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-update-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by dan-wesley** [comment]
@JasonNVSD Thank you for catching this. We'll follow up.

**Comment by RAJU2529** [comment]
@dan-wesley , Please merge it PR #337, if it is correct

**Comment by Y-Kelly** [comment]
Link in documentation looks to be updated.  Closing.
