### ISSUE TITLE
Application of AT to local GP settings

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/Edge-Enterprise#32]
When settings are established in Intune's AT for Edge, do their values get reflected in the target computers' local Group Policy editor? Even though the configuration profiles are successfully applied, the GP editor shows all the respective settings as Not configured.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47a3485-ce79-9bbf-aac2-060792af6d06
* Version Independent ID: 9e9eacea-96fd-6856-da7e-7149edefabe4
* Content: [Configure Microsoft Edge policy settings for Windows using Microsoft Intune](https://docs.microsoft.com/en-us/deployedge/configure-edge-with-intune)
* Content Source: [edgeenterprise/configure-edge-with-intune.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/configure-edge-with-intune.md)
* Product: **microsoft-edge**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by Y-Kelly** [comment]
Clean up of old issues.  This was opened a couple of years ago already.  

If the issue continues to reproduce, you can submit feedback to the team through the browser ("..." menu > Help and feedback > Send feedback) or you can reach out to Support (https://developer.microsoft.com/en-us/microsoft-edge/support/) to help investigate.
