### ISSUE TITLE
InsecureContentAllowedForUrls Feedback

### ISSUE THREAD

**Issue by neilhoward84** [MicrosoftDocs/Edge-Enterprise#320]
Better examples please for 'InsecureContentAllowedForUrls'

Also it's a tad confusing when you say  * is not an accepted value for this policy.  Yet the example uses a *

"[*.]example.edu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#insecurecontentallowedforurls)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@neilhoward84 I heard back from the policy owners and wildcards * are allowed as a part of a larger pattern, like in the example but are not allowed on its own.  

The team is discussing how to improve and clarify the documentation.  Thanks!
