### ISSUE TITLE
Incorrect version

### ISSUE THREAD

**Issue by tekstryder** [MicrosoftDocs/Edge-Enterprise#321]
Current stable version is 99.0.1150.3**8** not 99.0.1150.3**9**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ffcaf54-ce86-1b30-e947-540bf07a54c3
* Version Independent ID: 81267e97-e284-ff00-b081-476934538326
* Content: [Microsoft Edge release notes for Stable Channel](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel#version-990115039-march-10)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **leahtu**

**Comment by dan-wesley** [comment]
@tekstryder Thank you for your feedback. I spoke to the Release note PM and checked the pipeline history for the stable channel. The correct build number for the current stable version is 99.0.1150.39

**Comment by tekstryder** [comment]
Apologizes for the noise. That's the Linux build number I was reporting.
