### ISSUE TITLE
disable ie via intune/endpoint manager

### ISSUE THREAD

**Issue by nb-ofs** [MicrosoftDocs/Edge-Enterprise#322]
Computer Configuration/Administrative Templates/Windows Components/Internet Explorer.

both via a admin template or settings catalog the disable policy feature doesnt appear to exist in intune/endpoint manager?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b557e6ee-bb46-7b9c-108b-c78829c6d8b4
* Version Independent ID: dd39c398-eb44-ab64-69ee-d860147072df
* Content: [Disable Internet Explorer 11](https://docs.microsoft.com/en-gb/deployedge/edge-ie-disable-ie11)
* Content Source: [edgeenterprise/edge-ie-disable-ie11.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-disable-ie11.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **shisub**

**Comment by Y-Kelly** [comment]
@nb-ofs Hello - This feature requires specific Windows Updates.  Can you confirm your OS and that you have the correct prerequisites?  https://docs.microsoft.com/en-gb/deployedge/edge-ie-disable-ie11#prerequisites  Thanks!

**Comment by nb-ofs** [comment]
@Y-Kelly Intune/Endpoint manager has nothing to do with an O/S update. 
Are you saying you havent made those policies available in intune/endpoint as yet?

**Comment by Y-Kelly** [comment]
@nb-ofs My understanding after talking to the team is that this is an OS policy and if you download the related ADMX file into Intune it should be available.  By ensuring you have the pre-requisite operating system updates it will update the ADMX files (specifically inetres.adml and inetres.admx).  

The team has an active work item to update the documentation with Intune directions.  I have passed on your feedback to them.  Thanks!

**Comment by Y-Kelly** [comment]
@nb-ofs Following up, disabling IE should be available in Intune.  

Some information from the Q&A Forum: 
https://learn.microsoft.com/en-us/answers/questions/873769/disable-internet-explorer-11-from-intune.html#:~:text=Firstly%2C%20I%20would%20like%20to%20confirm%20if%20the%20profile%20is%20configured%20as%20below%3A
