### ISSUE TITLE
Request for better reference

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/Edge-Enterprise#323]
The prerequisites section refers us to an article about "Enable Enterprise State Roaming" but when we go to that article it states that it does not apply to Edge Chromium. Please change the link to  point to something that is relevant. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fa7eda4-6e4c-c2c8-a29a-ef2eead7f04f
* Version Independent ID: 414db256-c14b-ca11-b2a7-835aa9c9e041
* Content: [Configure Microsoft Edge enterprise sync](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-enterprise-sync)
* Content Source: [edgeenterprise/microsoft-edge-enterprise-sync.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-enterprise-sync.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **collw**

**Comment by dan-wesley** [comment]
@DeanGross Thank you for pointing this out. We'll make the appropriate update to the document as soon as possible.

**Comment by Y-Kelly** [comment]
@DeanGross Thanks for the feedback! We have refreshed and updated the Sync article.

If you would like to report any new Microsoft Edge Enterprise documentation issues to the team please open another issue and include relevant information/repro steps in the Comment section.
