### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by 29039** [MicrosoftDocs/Edge-Enterprise#324]
https://docs.microsoft.com/en-us/deployedge/initial-preferences-support-on-microsoft-edge-browser

8054482a-2c85-6e6d-a67d-956854999322

The link "Microsoft Edge Enterprise landing page" points to:

`https://docs.microsoft.com/en-us/edge/business/download`

It should be:

`https://www.microsoft.com/en-us/edge/business/download`

**Comment by Y-Kelly** [comment]
@29039 Thanks!  The link has been updated and should be working now.
