### ISSUE TITLE
Cannot Bulid ".openpublishing.build.ps1"

### ISSUE THREAD

**Issue by kenakung** [MicrosoftDocs/Edge-Enterprise#325]
I'm try run .ps1 is error Please help

![image](https://user-images.githubusercontent.com/2121346/160122996-17a71345-bb73-4450-8c09-c0314b7e9b6d.png)

**Comment by Y-Kelly** [comment]
@kenakung Can you share what you are trying to do?  ".openpublishing.build.ps1" is a private repro.  

Do you have a specific issue with the Microsoft Edge Enterprise documentation?  Thanks!

**Comment by Y-Kelly** [comment]
Closing issue as there has been no reply.
