### ISSUE TITLE
Cannot find "Computer Configuration>Administrative Templates>Microsoft Edge Update>Applications>Microsoft Edge>." under group policy editor.

### ISSUE THREAD

**Issue by SenseYang** [MicrosoftDocs/Edge-Enterprise#327]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12e89255-aab6-fe92-7a4f-7c1a53d30f50
* Version Independent ID: dcb5637d-8829-83e2-d7e3-71714a7daf3a
* Content: [Microsoft Edge rollback for enterprises](https://docs.microsoft.com/en-us/deployedge/edge-learnmore-rollback)
* Content Source: [edgeenterprise/edge-learnmore-rollback.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-rollback.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **collw**

**Comment by dan-wesley** [comment]
@SenseYang Thank you for this feedback. We'll investigate further and get back to you.

**Comment by dan-wesley** [comment]
@SenseYang I was able to navigate as documented but had to install the latest administrative template for Microsoft Edge and Edge update. Perhaps this needs to be better emphasized in the docs.
![image](https://user-images.githubusercontent.com/38053816/161829511-20202bae-f637-4c37-b6c0-d39243fdb165.png)

**Comment by dan-wesley** [comment]
@RAJU2529 will di
