### ISSUE TITLE
Deleting Edge Internet explorer mode sites

### ISSUE THREAD

**Issue by beytullahcakirr** [MicrosoftDocs/Edge-Enterprise#328]
Hello,

I open Internet Explorer mode in Edge. Then I add some pages to run in Internet explorer mode. When I close the browser and open it again, the pages I added are deleted. How can I proceed, can you help?

Have a nice day.

**Comment by Y-Kelly** [comment]
@beytullahcakirr It looks like our developer has released a fix to MS Edge Canary Channel v102.0.1217.0+.  They are also working to backport the fix to the other channels.  

Please update to the latest Canary version and let us know if you are still reproducing the issue.  Thanks!

**Comment by beytullahcakirr** [comment]
I downloaded and tested the latest version of Canary and my problem was solved. I may not be able to install canary on all end user computers. When will this fix come to the stable version, do you know?

Thanks for support!

**Comment by Y-Kelly** [comment]
@beytullahcakirr We've just released MS Edge Stable Version 100.0.1185.36 ([Microsoft Edge release notes for Stable Channel | Microsoft Docs](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel#version-1000118536-april-7)) and it should include the fix.  

 
Please let us know if you still have an issue after updating.  Thanks!
