### ISSUE TITLE
Incorrect Link

### ISSUE THREAD

**Issue by all2001** [MicrosoftDocs/Edge-Enterprise#329]
On the Provision favorites for Microsoft Edge page in 2nd paragraph there is incorrect link that directs to
https://deployedge/microsoft-edge-policies#configure-favorites
This address seems to be incorrect
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3415ed3-5ccf-198d-cee7-2dbbfe4b0959
* Version Independent ID: f1e17aeb-6ab5-3db2-80ac-c16514f80cf6
* Content: [Provision favorites for Microsoft Edge](https://docs.microsoft.com/en-us/deployedge/edge-learnmore-provision-favorites)
* Content Source: [edgeenterprise/edge-learnmore-provision-favorites.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-provision-favorites.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **capoon**

**Comment by Y-Kelly** [comment]
@all2001 Thanks!  We've updated the link in the article.  Please let us know if you see any other issues.
