### ISSUE TITLE
Disabling IE on non-domain joined machines

### ISSUE THREAD

**Issue by SpitFire-666** [MicrosoftDocs/Edge-Enterprise#330]
Was hoping to see some info here about disabling IE for non-domain machines. I know you can do it via gpedit.msc locally but this doesn't scale well. 

If there's a reg key that I could script to disable IE (but not remove it), that would be awesome.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b557e6ee-bb46-7b9c-108b-c78829c6d8b4
* Version Independent ID: dd39c398-eb44-ab64-69ee-d860147072df
* Content: [Disable Internet Explorer 11](https://docs.microsoft.com/en-us/deployedge/edge-ie-disable-ie11)
* Content Source: [edgeenterprise/edge-ie-disable-ie11.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-disable-ie11.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **shisub**

**Comment by Y-Kelly** [comment]
@SpitFire-666 Hello - Here is information from our developer.  

IE11 will be disabled if this regkey is set: **Software\Policies\Microsoft\Internet Explorer\Main!NotifyDisableIEOptions**

The accepted values for this are
0: Do not notify that IE11 is disabled
1: Always notify that IE11 is disabled
2: Notify once per user that IE11 is disabled

Thanks!
