### ISSUE TITLE
elkh

### ISSUE THREAD

**Issue by elkhalafy0** [MicrosoftDocs/Edge-Enterprise#331]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c0ccb95-a7bb-149b-c108-6e05bd6250cb
* Version Independent ID: 100b846e-b653-e339-69b0-7fffd03bbd9a
* Content: [Microsoft Edge support for Microsoft Defender SmartScreen](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-security-smartscreen)
* Content Source: [edgeenterprise/microsoft-edge-security-smartscreen.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-security-smartscreen.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by Y-Kelly** [comment]
@elkhalafy0 Hello - If you would like to report a Microsoft Edge Enterprise documentation issue to the team please open a new issue and include relevant information/repro steps in the Comment section.  

If you have general questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
