### ISSUE TITLE
QuickViewOfficeFilesEnabled does not support Intranet files

### ISSUE THREAD

**Issue by Nii-co** [MicrosoftDocs/Edge-Enterprise#332]
[Enter feedback here]
For the policy: QuickViewOfficeFilesEnabled
Currently the feature does not support for Intranet files that cannot be accessed via Internet, please make it clear in doc to avoid confusion.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@Nii-co Hello - Recently the policy documentation for QuickViewOfficeFilesEnabled was updated and specifically calls out the files need to be publicly accessible.  

Here is the description: Allows you to set whether users can view **publicly accessible** Office files on the web that aren't on OneDrive or SharePoint. (For example: Word documents, PowerPoint presentations, and Excel spreadsheets) 

Thanks!
