### ISSUE TITLE
Completely Rewrite this, please.

### ISSUE THREAD

**Issue by JeremyVyska** [MicrosoftDocs/Edge-Enterprise#335]
[Enter feedback here]

I'm not sure what feedback to give here, but this guide was ghastly levels of unhelpful.  It points you to Azure Docs, which MIGHT have been relevant... but the features it tells you to enable specific group policies through AIP, when you go to Azure Portal, are retired and have been since over a year ago.

Please rewrite for current functionality and requirements.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fa7eda4-6e4c-c2c8-a29a-ef2eead7f04f
* Version Independent ID: 414db256-c14b-ca11-b2a7-835aa9c9e041
* Content: [Configure Microsoft Edge enterprise sync](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-enterprise-sync)
* Content Source: [edgeenterprise/microsoft-edge-enterprise-sync.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-enterprise-sync.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
@JeremyVyska Thanks for the feedback!  We have refreshed and updated the Sync article.  

If you would like to report any new Microsoft Edge Enterprise documentation issues to the team please open another issue and include relevant information/repro steps in the Comment section.

**Comment by JeremyVyska** [comment]
Definitely opening a new case.  I just browsed every commit in May on this, and all that changed were language tweaks and _more_ links and references to a retired product.  I'll be clearer in what I'm asking for, since I haven't been enable to get Edge Sync working in 2 months, and if I can't, I have no idea who can.
