### ISSUE TITLE
Written differently on other pages

### ISSUE THREAD

**Issue by Simpuhl** [MicrosoftDocs/Edge-Enterprise#336]
These are written the other way around on all other MS Documentation 

  <Association Identifier=".pdf" ProgId="MSEdgePDF" ApplicationName="Microsoft Edge" />
  <Association Identifier=".html" ProgId="MSEdgeHTM" ApplicationName="Microsoft Edge" />
  <Association Identifier=".htm" ProgId="MSEdgeHTM" ApplicationName="Microsoft Edge" />
  <Association Identifier="http" ProgId="MSEdgeHTM" ApplicationName="Microsoft Edge" />
  <Association Identifier="https" ProgId="MSEdgeHTM" ApplicationName="Microsoft Edge" />

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e858557-d417-cb01-9f4f-ed214087790c
* Version Independent ID: 9cbd34f5-7a9a-1e3a-d832-1a945db28726
* Content: [Set Microsoft Edge as the default browser on Windows and macOS](https://docs.microsoft.com/en-us/deployedge/edge-default-browser)
* Content Source: [edgeenterprise/edge-default-browser.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-default-browser.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **brianalt**

**Comment by Y-Kelly** [comment]
@Simpuhl Hello!  Can you provide more information or details about the issue in the Documentation?  Not quite sure, what you mean by "other way around".  Also, if you have examples (links) to the other Documenation you are mentioning that would be great.  Thanks!

**Comment by Y-Kelly** [comment]
@Simpuhl Closing this issue as we have not had a reply.  If you would like to report a Microsoft Edge Enterprise documentation issue to the team please open a new issue and include relevant information/repro steps in the Comment section.

If you have general questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
