### ISSUE TITLE
New update announced but NO UPDATE happens

### ISSUE THREAD

**Issue by raphaelbm2011** [MicrosoftDocs/Edge-Enterprise#338]
[The STABLE channel page at 
https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel
shows an update Version 101.0.1210.43: May 9

However,  when I go to update edge NO UPDATE is performed. From past experience the update becomes "available" in a few days time. Today is May 10 2022.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ffcaf54-ce86-1b30-e947-540bf07a54c3
* Version Independent ID: 81267e97-e284-ff00-b081-476934538326
* Content: [Microsoft Edge release notes for Stable Channel](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel#feedback)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **leahtu**

**Comment by raphaelbm2011** [comment]
![ms edge is up to date NOT - 2022-05-10_10-13-07](https://user-images.githubusercontent.com/105278040/167597126-240d13f1-c4e3-4b8d-a83d-af4d3d99f5b8.jpg)

**Comment by Y-Kelly** [comment]
@raphaelbm2011 Thanks for letting us know!  Looks like Version 101.0.1210.43 was a specific update only for mobile.  We've updated the Release Notes.
