### ISSUE TITLE
ExemptDomainFileTypePairsFromFileTypeDownloadWarnings domains documentation is incorrect.

### ISSUE THREAD

**Issue by mkaply** [MicrosoftDocs/Edge-Enterprise#339]
The policy documentation for ExemptDomainFileTypePairsFromFileTypeDownloadWarnings 

https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md#exemptdomainfiletypepairsfromfiletypedownloadwarnings

says this:

**The URL pattern should be formatted according to https://go.microsoft.com/fwlink/?linkid=2095322.**

but that is not correct.

The domains parameter only supports actual domains (foo.com) or an asterisk. If you try to use a match pattern (http://*.foo.com/*), it fails.

This error was copied from the Chrome policy documentation:

https://chromeenterprise.google/policies/#ExemptDomainFileTypePairsFromFileTypeDownloadWarnings

I would submit a patch to fix, but I'm not sure if it's correct to fix this here when the Google documentation is still wrong.

**Comment by Y-Kelly** [comment]
@mkaply Hello - I have reached out to the team about this.  Since it is incorrect in the Chrome documentation as well, you can report the issue here: https://bugs.chromium.org/p/chromium/issues/list

**Comment by Y-Kelly** [comment]
Closing as this has been sent to the team to update accordingly.  

(Though the policy is marked as deprecated and not sure if documentation for this policy will be actively updated.)
