### ISSUE TITLE
Mobile devices sync settings vs. SyncDisabled

### ISSUE THREAD

**Issue by crefohb** [MicrosoftDocs/Edge-Enterprise#34]
The Mobile devices sync settings in the Edge settings contains a sign-in button to Edge, even if the SyncDisabled GPO is enabled. Is there a way to remove or deactivate the Mobile device settings?

**Comment by Y-Kelly** [comment]
Clean up of old issues.  Change was made in version 90.0.796.0+ the page/section in Settings will be completely hidden when either SignIn or Sync are set to disabled via Group Policy. The section won't show up in the navigation page in settings and the URL to get to this page will also not work (the user will just be redirected to the root of the Settings experience).
