### ISSUE TITLE
Old version of SAP GUI still opens in IE Standalone

### ISSUE THREAD

**Issue by PiKappZ746** [MicrosoftDocs/Edge-Enterprise#340]
We currently have SAP GUI 7.40 and are testing the "Disable Internet Explorer 11 as a standalone browser" setting. It works as expected when trying to launch IE from anywhere in the operating system.  However, when a link is launched from SAP GUI 7.40, the stand-alone IE browser still gets launched. Is there any way to prevent this?

**Comment by Y-Kelly** [comment]
@PiKappZ746 It looks like starting from SAP GUI 7.70 you are able to change the default browser to MS Edge.  Here is an article from SAP with more information: https://userapps.support.sap.com/sap/support/knowledge/en/3069413

I think you should be able to reach out to SAP for more details.  Thanks!
