### ISSUE TITLE
Is it possibe to lock the default browser settings? Missing user based GPO for setting file associations

### ISSUE THREAD

**Issue by crefohb** [MicrosoftDocs/Edge-Enterprise#35]
The result of the procedure at [https://docs.microsoft.com/en-us/deployedge/edge-default-browser](url): Users are still able to change the default browser or click "Reset to Microsoft recommended defaults". At next reboot the GPO is re applied and Edge will be default browser again.

Is ist possible to lock the default browser settings by GPO so users can't change them?
Why there is no user based GPO to set default file associations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d80a2f5-5b21-a16b-c401-5e1c40be6f00
* Version Independent ID: b63c5b42-443b-687c-a445-58fa4de6b84b
* Content: [Set Microsoft Edge as the default browser on Windows and macOS](https://docs.microsoft.com/en-us/deployedge/edge-default-browser#feedback)
* Content Source: [edgeenterprise/edge-default-browser.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/edge-default-browser.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **brianalt**

**Comment by Y-Kelly** [comment]
Clean up of old issues.  This discussion is a couple of years old and does not have any recent activity.  

If you are still experiencing this, you can submit feature requests through our in-browser feedback tool. It's under "..." menu > Help and feedback > Send feedback.  

You can also reach out to [Support](https://developer.microsoft.com/en-us/microsoft-edge/support/) or you can visit [Microsoft Edge Tech Community](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsiderForum) / [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise).
