### ISSUE TITLE
Recommended NewTabPageLocation unsupported work around

### ISSUE THREAD

**Issue by NetMage** [MicrosoftDocs/Edge-Enterprise#350]
It might be nice to mention that while the `NewTabPageLocation` entry in the `Recommended` hive acts as mandatory, a work around is for the local user to create a `NewTabPageLocation` in the parent `Edge` hive which will override the `Recommend` value, including setting to `about:blank`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@NetMage Thank you for the feedback!  We've passed this on to the appropriate team to review and update the documentation as necessary.

**Comment by Y-Kelly** [comment]
Thank you, closing this issue as we've notified the team and they will make the updates as needed.
