### ISSUE TITLE
Wrong GPO template link

### ISSUE THREAD

**Issue by mtanlw** [MicrosoftDocs/Edge-Enterprise#351]
On this link: https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-policies#enable-internet-explorer-integration-using-group-policy
Point 3 is missing the "Windows Components" 

User Configuration/Computer Configuration > Administrative Templates > Microsoft Edge

should read

User Configuration/Computer Configuration > Administrative Templates > Windows Components > Microsoft Edge.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e59013ef-aae3-ee84-8bc3-8d2ad0c52e36
* Version Independent ID: f4e73402-3baf-a72b-96c5-cee4f04b8298
* Content: [Configure IE mode Policies](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-policies)
* Content Source: [edgeenterprise/edge-ie-mode-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @AndreaLBarr
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
@mtanlw Would you be able to provide more information about what is missing in the documentation?  

Also, you linked to GitHub Issue 3 -> https://github.com/MicrosoftDocs/Edge-Enterprise/issues/3, is this related?  Thanks!

**Comment by mtanlw** [comment]
> @mtanlw Would you be able to provide more information about what is missing in the documentation?
> 
> Also, you linked to GitHub Issue 3 -> #3, is this related? Thanks!

that was a mistake - sorry

**Comment by Y-Kelly** [comment]
@mtanlw Please see the screenshot below from our documentation (https://docs.microsoft.com/en-us/deployedge/configure-microsoft-edge#add-the-administrative-template-to-active-directory) 

![image](https://user-images.githubusercontent.com/74324031/171513721-023c10de-9105-4b58-b18f-af6d94ca8174.png)

Do you have a screenshot showing User Configuration/Computer Configuration > Administrative Templates > Windows Components > Microsoft Edge?  Thanks!

**Comment by mtanlw** [comment]
this is clear. Thanks for the clarification.
