### ISSUE TITLE
supported operating systems is not updated with Windows 10 Enterprise 2021 LTSC.

### ISSUE THREAD

**Issue by ttd1shoonya** [MicrosoftDocs/Edge-Enterprise#354]
The list of supported operating systems is not updated with Windows 10 Enterprise 2021 LTSC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86847b80-8f8e-9493-86ff-5dfd6412b48f
* Version Independent ID: 2ce02bc3-24a1-8c9f-c787-34ab90e9f31d
* Content: [Microsoft Edge Supported Operating Systems](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-supported-operating-systems)
* Content Source: [edgeenterprise/microsoft-edge-supported-operating-systems.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-supported-operating-systems.md)
* Product: **microsoft-edge**
* GitHub Login: @srugh
* Microsoft Alias: **srugh**

**Comment by Y-Kelly** [comment]
@ttd1shoonya Thank you for the feedback!  The documentation has been updated to include Windows 10 Enterprise 2021 LTSC.
