### ISSUE TITLE
About the behavior change of Microsoft Edge V98

### ISSUE THREAD

**Issue by katasukiyamazaki** [MicrosoftDocs/Edge-Enterprise#355]
[Enter feedback here]
The event that Referrer is not linked is due to the change in the operation of Edge.
Up to version 97, many site compatibility issues have been reported due to the inclusion of headers in HTTP requests.
Therefore, from version 98 of Edge, he changed the behavior so that Referrer is not included by default.

Please include the above contents in the release notes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ffcaf54-ce86-1b30-e947-540bf07a54c3
* Version Independent ID: 81267e97-e284-ff00-b081-476934538326
* Content: [Microsoft Edge release notes for Stable Channel](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **leahtu**

**Comment by Y-Kelly** [comment]
@katasukiyamazaki Hello!  There is a separate document for Site compatibility-impacting changes, here: https://docs.microsoft.com/en-us/microsoft-edge/web-platform/site-impacting-changes.  

Is the change you mentioned included in this document?  If not, can you provide more details about the behavior change you have observed?  Thanks!

**Comment by Y-Kelly** [comment]
Closing issue, there has not been any recent activity or updates.  

If you would like to report a Microsoft Edge Enterprise documentation issue to the team please open a new issue and include relevant information/repro steps in the Comment section.

If you have general questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsiderForum) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
