### ISSUE TITLE
How disable Internet Explorer 11 as a standalone browser in Windows 10 Home?

### ISSUE THREAD

**Issue by Bob-HL** [MicrosoftDocs/Edge-Enterprise#357]
Windows 10 Home doesn't have Group Policy Editor. How to disable IE 11?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b557e6ee-bb46-7b9c-108b-c78829c6d8b4
* Version Independent ID: dd39c398-eb44-ab64-69ee-d860147072df
* Content: [Disable Internet Explorer 11](https://docs.microsoft.com/en-us/deployedge/edge-ie-disable-ie11)
* Content Source: [edgeenterprise/edge-ie-disable-ie11.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-disable-ie11.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **shisub**

**Comment by Y-Kelly** [comment]
@Bob-HL Hello - After the Internet Explorer desktop application is retired on June 15, 2022, it will be out of support. Additionally, the IE11 desktop application will be disabled through a future Windows 10 cumulative monthly update and will redirect to Microsoft Edge if a user tries to access it. (Information from the FAQ: https://techcommunity.microsoft.com/t5/windows-it-pro-blog/internet-explorer-11-desktop-app-retirement-faq/ba-p/2366549)

As a Windows 10 Home user, can you share why you are trying to disable IE11 before the future Windows 10 cumulative monthly update?  Thanks!

**Comment by Dahl0000** [comment]
Were you able to figure out how to test IE?

**Comment by Bob-HL** [comment]
> Were you able to figure out how to test IE?

Testing of disabling IE is no longer required for me; and I think that MS won't allow to modify the policy with Home edition, otherwise users will be able to enable it after 15 June 2022.

What I tested and confirmed are:
- If IE feature is not installed, IE mode in Edge won't work.
- You can install Siliverlight (with an installer) without IE, but it won't work; once IE is installed, IE+Silverlight will work in Edge IE mode.
