### ISSUE TITLE
Windows 10 SAC RS3 and later ***

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/Edge-Enterprise#36]
As RS3 was a pre-release codename, why not refer to Version 1709?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b402dcf-d79b-71a2-a942-4b5b17cfe1b2
* Version Independent ID: 861380ed-e39d-6896-5fee-09649afda5f7
* Content: [Microsoft Edge Supported Operating Systems](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-supported-operating-systems)
* Content Source: [edgeenterprise/microsoft-edge-supported-operating-systems.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-supported-operating-systems.md)
* Product: **microsoft-edge**
* GitHub Login: @srugh
* Microsoft Alias: **srugh**

**Comment by Y-Kelly** [comment]
@BR77BE Hello - Thanks for your feedback! The documentation has been updated and now reads "Windows 10 SAC 1709"
