### ISSUE TITLE
Regular Expression "2" syntax seems to have error replacing * with \

### ISSUE THREAD

**Issue by BurtHarris** [MicrosoftDocs/Edge-Enterprise#360]
In portions of this document, the functionality generally associated with the metacharacter `*` seems to be written as if it were associated with the character `\`.   

This error seems to start with the paragraph saying: 
>The metacharacters \ , + , and ? are repetition operators: e1 \ matches a sequence of zero or more (possibly different) strings, each of which match e1; e1 + matches one or more; e1 ? matches zero or one.

Which would make more sense if it said:

> The metacharacters `*`, + , and ? are repetition operators: e1 `*` matches a sequence of zero or more (possibly different) strings, each of which match e1; e1 + matches one or more; e1 ? matches zero or one.

Also, it is unclear where the variant referred to as "Regular Expression 2 syntax" is applicable in Edge development.  I can find no references citing this article or the "2" syntax.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffc84fba-1c58-70db-819a-78f8039d4b1f
* Version Independent ID: c10d7b6b-7f35-f538-1000-5f352dd8a349
* Content: [Regular Expression 2 syntax](https://docs.microsoft.com/en-us/deployedge/edge-learnmore-regex)
* Content Source: [edgeenterprise/edge-learnmore-regex.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-regex.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **comanea**

**Comment by Y-Kelly** [comment]
@BurtHarris Thanks for the feedback!  We have updated the documentation.  

In regards to your question, the Regular Expression 2 syntax article is referenced in the policy documentation.  For example, the RestrictSigninToPattern policy https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#restrictsignintopattern links to the article.
