### ISSUE TITLE
PDF page

### ISSUE THREAD

**Issue by SaschaPolatkan** [MicrosoftDocs/Edge-Enterprise#361]
Hello,

I would like to open PDFs on a specific page and full-screen via a link.
Is this possible? If yes, it would be nice to have a comment on that in the documentation.
If not ... it would be very handy. Could this be implemented?

Cheers,
Sascha.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bf00e03-8344-1808-bffb-f5abe0b423e5
* Version Independent ID: 139b136c-b2b9-ee14-7da3-ba23d5ee2fd3
* Content: [PDF reader in Microsoft Edge](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-pdf)
* Content Source: [edgeenterprise/microsoft-edge-pdf.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-pdf.md)
* Product: **microsoft-edge**
* GitHub Login: @AndreaLBarr
* Microsoft Alias: **adigan**

**Comment by Y-Kelly** [comment]
@SaschaPolatkan Can you provide more details about the scenario?  You mentioned full screen, is this for kiosk mode?  There is the AutoOpenFileTypes Policy (https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-policies#autoopenfiletypes) which can be used for pdf files.

**Comment by Y-Kelly** [comment]
Closing. No recent updates to this thread.

If you are continuing to have issues and if you have Microsoft Unified Support, you can reach out to that support service for help.  

You can also reach out on Tech Community if you have further questions 
[Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise).
