### ISSUE TITLE
Yayo

### ISSUE THREAD

**Issue by DaoWays369** [MicrosoftDocs/Edge-Enterprise#366]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f651e68c-34bf-d399-88e9-c9a0928d8be4
* Version Independent ID: ad34ee59-01d3-c64d-d123-5484264190b8
* Content: [Microsoft Edge password manager security ](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-security-password-manager-security?source=docs)
* Content Source: [edgeenterprise/microsoft-edge-security-password-manager-security.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-security-password-manager-security.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **v-danwesley**

**Comment by Y-Kelly** [comment]
@DaoWays369 Hello - If you would like to report a Microsoft Edge Enterprise documentation issue to the team please open a new issue and include relevant information/repro steps in the Comment section.

If you have general questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
