### ISSUE TITLE
Site Discovery GPO Settings / admx files

### ISSUE THREAD

**Issue by andrewjohnporter** [MicrosoftDocs/Edge-Enterprise#368]
Hi,

The script that is created by Micrsooft's IE Mode tool will create a GPO with two settings. One of these is showing under Extra Registry Settings. Which ADMX file do I need for the settings used to capture Enterprise Site Discovery Data? It would be useful to include this information on this page. 

The missing setting is:
**Software\Microsoft\Internet Explorer\WMITelemetry\EnableXML**

The other setting that is referenced by an admx file is:
Windows Components\Internet Explorer~Turn on site Discovery XMl output

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e59013ef-aae3-ee84-8bc3-8d2ad0c52e36
* Version Independent ID: f4e73402-3baf-a72b-96c5-cee4f04b8298
* Content: [Configure IE mode Policies](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-policies)
* Content Source: [edgeenterprise/edge-ie-mode-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @AndreaLBarr
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
@andrewjohnporter Are you using the [Microsoft Edge deployment wizard](https://aka.ms/edgeadvisor)?  If so, the step by step instructions should walk you through the process.

Is this the script you are talking about?

![image](https://user-images.githubusercontent.com/74324031/175696190-a321fe2b-9c2f-462f-8f13-72b1001b2d5d.png)

**Comment by andrewjohnporter** [comment]
Hi, yes that's the script.

**Comment by Y-Kelly** [comment]
@andrewjohnporter Did you follow the instructions in guide?  If you are having issues and if you have Microsoft Unified Support, you can reach out to that support service for help. There’s also [FastTrack](https://www.microsoft.com/en-us/fasttrack/microsoft-365/microsoft-edge?rtc=1), available at no extra charge to customers with 150 or more paid seats of Windows 10.

**Comment by Y-Kelly** [comment]
Closing.  No recent updates to this thread.

If you are continuing to have issues please reach out to Support or FastTrack.  Thanks!
