### ISSUE TITLE
Shortcut key is not correct

### ISSUE THREAD

**Issue by kingma-sbw** [MicrosoftDocs/Edge-Enterprise#37]
Alt+F does not do a thing on Edge

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4be833d4-f235-4029-258d-6ef2387f4189
* Version Independent ID: 09525733-35da-0bf0-522b-d3f9decb367a
* Content: [Microsoft Edge language support](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-supported-languages#feedback)
* Content Source: [edgeenterprise/microsoft-edge-supported-languages.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-supported-languages.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by Y-Kelly** [comment]
Clean up of old issues.  Appears the question has been previously answered.  Closing.  

If you have general questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsiderForum) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
