### ISSUE TITLE
FirebaseUI on CocoaPods.org

### ISSUE THREAD

**Issue by DaoWays369** [MicrosoftDocs/Edge-Enterprise#370]
"target 'MyApp' do
  pod 'FirebaseUI', '~> 12.2'
end"
 https://cocoapods.org/pods/FirebaseUI#:~:text=target%20%27MyApp%27%20do%0A%20%20pod%20%27FirebaseUI%27%2C%20%27~%3E%2012.2%27%0Aend~%Web%0Andriod

**Comment by Y-Kelly** [comment]
@DaoWays369 Hello - Is this related to a Microsoft Edge Enterprise documentation issue?  If so, please open a new issue and include relevant information/repro steps in the Comment section.

If you have general questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
