### ISSUE TITLE
Space not needed for Network Share

### ISSUE THREAD

**Issue by woodsonf** [MicrosoftDocs/Edge-Enterprise#372]
[In the location of the network share there is a space between file:// and the share that doesn't need to be there. 
![2022-06-28_14-49-41](https://user-images.githubusercontent.com/108368136/176274367-a20473a6-4811-40ae-9728-6bbfc8cb7a4e.jpg)
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e59013ef-aae3-ee84-8bc3-8d2ad0c52e36
* Version Independent ID: f4e73402-3baf-a72b-96c5-cee4f04b8298
* Content: [Configure IE mode Policies](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-policies#configure-using-the-use-the-enterprise-mode-ie-website-list-policy)
* Content Source: [edgeenterprise/edge-ie-mode-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @AndreaLBarr
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
@woodsonf Thanks for the feedback!  The documentation has been updated to remove the extra space.
