### ISSUE TITLE
Importance of Site List Version number

### ISSUE THREAD

**Issue by robinherbert** [MicrosoftDocs/Edge-Enterprise#375]
Particularly for organisation migrating from an existing Site List to the new Cloud method, it's important to ensure that the Version number of a Site List must be higher than the existing one. This is because, AFAIK, Edge compares the number of the local list, to the online list, and only updates the local list if the online list has a higher version.
When importing or creating a new list in the Cloud M365 method, the version starts as '1', which means in most organisations it will never be applied.
I suspect that this would also be relevant for organisations with multiple lists, and moving users between those lists. If moved to a list with a lower Version number, they would not get it applied.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1a4c286-c376-c1aa-86d8-80a842861435
* Version Independent ID: a1a4c286-c376-c1aa-86d8-80a842861435
* Content: [Cloud Site List Management for Internet Explorer (IE) mode'](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-cloud-site-list-mgmt#steps-to-publish-a-site-list)
* Content Source: [edgeenterprise/edge-ie-mode-cloud-site-list-mgmt.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode-cloud-site-list-mgmt.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **shisub**

**Comment by Y-Kelly** [comment]
@robinherbert Hello - Are you using the [InternetExplorerIntegrationCloudSiteList](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#internetexplorerintegrationcloudsitelist) policy to configure your cloud site list?  This policy takes precedence over the [InternetExplorerIntegrationSiteList](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#internetexplorerintegrationsitelist) policy.

![image](https://user-images.githubusercontent.com/74324031/176738428-06598525-5353-4927-aa81-2b5260a4ad60.png)

Once you are using the cloud site list, to publish updates it will require a larger version number. If you try to enter a lower version number, an error message will appear and the Publish button will be disabled until a larger number is entered.

**Comment by Y-Kelly** [comment]
Closing.  No recent updates to this thread.  

Please reach out on Tech Community if you have further questions about IE mode
[Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
