### ISSUE TITLE
Microsoft account | Home

### ISSUE THREAD

**Issue by DaoWays369** [MicrosoftDocs/Edge-Enterprise#379]
https://account.microsoft.com/?ref=MeControl&refd=portal.azure.com

**Comment by Y-Kelly** [comment]
@DaoWays369 Hello - Is this related to a Microsoft Edge Enterprise documentation issue? If so, please open a new issue and include relevant information/repro steps in the Comment section.

If you have general questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
