### ISSUE TITLE
RestrictSigninToPattern policy - lack of information

### ISSUE THREAD

**Issue by andrefboliveira** [MicrosoftDocs/Edge-Enterprise#38]
Policy [RestrictSigninToPattern](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#restrictsignintopattern) is not clear.
Users frequently ask if this policy support more than one account. Since it supports patterns, it does!
Example pattern:
`.*@(contoso1\.com|contoso2\.com)`

Please update the documentation with the example and explanation above to prevent this question.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1cd3ad5-bb4a-54ff-84e7-18ca0b11368f
* Version Independent ID: 984abd8f-45eb-737b-ad74-07ec8261f9eb
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#restrictsignintopattern)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
Clean up of old issues.  Documentation was previously updated to mention multiple accounts and regex.
