### ISSUE TITLE
Edge Version 103.0.1264.60: July 13 is announced but does not update

### ISSUE THREAD

**Issue by raphaelbm2011** [MicrosoftDocs/Edge-Enterprise#381]
### ISSUE: Version 103.0.1264.60: July 13 is announced but does not update.

I note that the wording refers to "**Edge on 32-bit (x86) Windows 10 Version 1809**". Is this why it does not update?
In any case it is not made clear that the update refers to ONLY that version. Please clarify this.
thx Raphael

My system:
Windows 10 Home (x64) Version 21H1 (build 19043.1766)
TOSHIBA SATELLITE C850D-12L PSCC2E-02L00JEN

see:
https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel#version-1030126460-july-13

...and also the attached screenshot picture
Edge Version 103.0.1264.60 July 13 does not update 2022-07-14_10-54-40.jpg
![Edge Version 103 0 1264 60 July 13 does not update 2022-07-14_10-54-40](https://user-images.githubusercontent.com/105278040/178962132-f74a616e-f3ce-4735-a694-14d48a020b3a.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ffcaf54-ce86-1b30-e947-540bf07a54c3
* Version Independent ID: 81267e97-e284-ff00-b081-476934538326
* Content: [Microsoft Edge release notes for Stable Channel](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **leahtu**

**Comment by Y-Kelly** [comment]
@raphaelbm2011 Thanks for reaching out!  The Release Notes have been updated, looks like v103.0.1264.60 was a specific update for mobile iOS.
