### ISSUE TITLE
Intune policy exists in the Settings Catalog but only works on Windows insider and Windows 11 devices

### ISSUE THREAD

**Issue by Klathman** [MicrosoftDocs/Edge-Enterprise#383]
Tried to apply this setting via the settings catalog in Intune and all machines reported that the setting was not applicable except the single Windows 11 machine receiving the setting. Logged a call and ultimately got this response.

After checking internally, we found this is a known issue that this setting only applies to Windows insider in the current stage. The product group is working on patching an updated setting applicability but there is no ETA yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b557e6ee-bb46-7b9c-108b-c78829c6d8b4
* Version Independent ID: dd39c398-eb44-ab64-69ee-d860147072df
* Content: [Disable Internet Explorer 11](https://docs.microsoft.com/en-us/deployedge/edge-ie-disable-ie11#prerequisites)
* Content Source: [edgeenterprise/edge-ie-disable-ie11.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-disable-ie11.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **shisub**

**Comment by Y-Kelly** [comment]
@Klathman Thank you for the feedback.  I have passed this on to the team and they will be making documentation updates as necessary.
