### ISSUE TITLE
Permissions Documentation

### ISSUE THREAD

**Issue by Breaker119** [MicrosoftDocs/Edge-Enterprise#384]
The prerequisites state that a user has to be a Microsoft Edge Administrator or a Global Admin. However, users who are an Edge Administrator (only) cannot access admin.microsoft.com >> Org Settings. If an Edge Admin doesn't already have additional roles that would grant access to the M365 Admin Center, what additional role do they need?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1a4c286-c376-c1aa-86d8-80a842861435
* Version Independent ID: a1a4c286-c376-c1aa-86d8-80a842861435
* Content: [Cloud Site List Management for Internet Explorer (IE) mode'](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-cloud-site-list-mgmt)
* Content Source: [edgeenterprise/edge-ie-mode-cloud-site-list-mgmt.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode-cloud-site-list-mgmt.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **shisub**

**Comment by Breaker119** [comment]
My apologies - it seems there is no issue

We have a service provider who has limited roles who also needs to manage the Edge site list in the M365 Admin Center. He already has the roles Security Admin, Desktop Analytics Admin, Intune Admin, and Edge Admin. I tried setting up one of my test accounts in the same way, and I also could not open the Admin Center. However, it now seems to be working as expected...




________________________________

**Comment by Y-Kelly** [comment]
@Breaker119 Great to hear!  I'll close this issue.
