### ISSUE TITLE
uwp

### ISSUE THREAD

**Issue by tuckstarrydell** [MicrosoftDocs/Edge-Enterprise#385]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50216241-ef27-6124-7182-1133eb113378
* Version Independent ID: a8617e77-156f-b3e9-e0e2-349342ba91d9
* Content: [Microsoft Edge security, compatibility, and manageability](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-video-security-compatibility-manageability)
* Content Source: [edgeenterprise/microsoft-edge-video-security-compatibility-manageability.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-video-security-compatibility-manageability.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
@tuckstarrydell Hello - If you would like to report a Microsoft Edge Enterprise documentation issue to the team please open a new issue and include relevant information/repro steps in the Comment section.

If you have general questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsiderForum) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
