### ISSUE TITLE
With IE disabled and using new MSEdge with IE mode for some sites, can standard IE Group policies be removed or are they used?

### ISSUE THREAD

**Issue by PaulKlerkx** [MicrosoftDocs/Edge-Enterprise#386]
Hi,
   Just looking for a bit more clarity on this page regarding the disabling of Internet explorer with usage of IE mode.  When in IE mode, does edge refer to any Internet explorer group policies or does it only use new MSEdge group policy.  We have disabled IE and are using IE mode for a couple of sites, however now we have a heap of old IE group policies that we aren't sure if we can decommission or not.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b557e6ee-bb46-7b9c-108b-c78829c6d8b4
* Version Independent ID: dd39c398-eb44-ab64-69ee-d860147072df
* Content: [Disable Internet Explorer 11](https://docs.microsoft.com/en-us/deployedge/edge-ie-disable-ie11)
* Content Source: [edgeenterprise/edge-ie-disable-ie11.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-disable-ie11.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **shisub**

**Comment by Y-Kelly** [comment]
@PaulKlerkx Hello!  IE mode does use some Internet Explorer Group Policies.  More information here: https://docs.microsoft.com/en-us/deployedge/edge-ie-mode#ie-mode-supports-the-following-internet-explorer-functionality

![image](https://user-images.githubusercontent.com/74324031/180277786-420826c7-4fa5-4143-bfc1-7e1190f09b8c.png)

**Comment by Y-Kelly** [comment]
Closing this issue.  @PaulKlerkx please reach out to AppAssure or Tech Community if you have further questions about IE mode
[Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
