### ISSUE TITLE
Target page not allowing template download - "Go to the Microsoft Edge Enterprise landing page" to download the Microsoft Edge policy templates file

### ISSUE THREAD

**Issue by PaulKlerkx** [MicrosoftDocs/Edge-Enterprise#387]
not "strictly" this page, but as there doesn't appear to be an option to submit info on the Microsoft Edge Enterprise landing page and I couldn't see any indication of where to report issues, I am posting here as this page is how I got to the landing page.  

On this page, regarding this section - 
Go to the [Microsoft Edge Enterprise landing page](https://aka.ms/EdgeEnterprise) to download the Microsoft Edge policy templates file and extract the contents.

I assume that the option to "Get Policy" on the "Microsoft Edge Enterprise landing page" under "Need to download older builds and versions?" is what that is referencing. (can't see anything on the landing page that indicates where to download for the current release)  I have tried from 3 different computers and my phone (different network), however none of those buttons currently appear to work.  - these ones...
CHANNEL/VERSION  - Select build
BUILD - Select platform
PLATFORM

the download button takes you to another page, but not a download page and all this means getting to the policies isn't possible. The get policies button has a red circle with cross through icon when you hover over it (maybe because I haven't been able to select each of the drop down option yet).    

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e4fa0af-82d8-c1ca-02b3-fc55eb620ff3
* Version Independent ID: bd546e78-3406-0fdd-2aea-d0bd72be9f38
* Content: [Configure Microsoft Edge for Windows with policy settings](https://docs.microsoft.com/en-us/deployedge/configure-microsoft-edge)
* Content Source: [edgeenterprise/configure-microsoft-edge.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/configure-microsoft-edge.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **v-danwesley**

**Comment by Y-Kelly** [comment]
@PaulKlerkx Hello - Just to confirm, are you having an issue downloading the policy files from https://www.microsoft.com/en-us/edge/business/download?

I just tried clicking "Download Windows 64-bit Policy"
![image](https://user-images.githubusercontent.com/74324031/181079489-d70fd294-3417-4ec1-9aee-aa9dae54e5ac.png)

I got the following prompt and after accepting, the policy file downloaded. 

![image](https://user-images.githubusercontent.com/74324031/181079213-0d6e5012-59b2-4594-94db-5d754ed713c7.png)

**Comment by PaulKlerkx** [comment]
Hi, thanks for looking, this can be closed, it appears that page was completely redone in the past 24 hours.  When I was trying to access it was the old page, the screen shots you have posted match the new page that I am seeing now.  everything on these pages is fine.

**Comment by Y-Kelly** [comment]
@PaulKlerkx Thanks!  Yes, it does look like the site was recently updated.  Great to hear things are working as expected.
