### ISSUE TITLE
Please clarify which policies/settings can block or impact the Edge WebDriver

### ISSUE THREAD

**Issue by chibicitiberiu** [MicrosoftDocs/Edge-Enterprise#395]
We are facing a frustrating issue, with a customer in a secure environment who is unable to use our product which uses the Edge WebDriver, because for some reason the WebDriver cannot communicate with Edge. So far, we found these 3 settings which could impact or block the WebDriver from functioning. The frustrating part is how hard it is to find this information, we found some on random forums, and after a lot of searching and googling [on this site](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp).

* Application Guard with untrusted sites
* The `DeveloperToolsAvailability` policy being set to `2`
* The `RemoteDebuggingAllowed` policy being disabled

We don't know if there are any others that could prevent the WebDriver from functioning properly.

Could you please clarify this information in the documentation? Thank you.

**Comment by Y-Kelly** [comment]
@chibicitiberiu Hello - Contact information for the WebDriver team and link to their GitHub can be found here: https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/contact

Please try and contact them directly.  Thanks!
