### ISSUE TITLE
Example value for 'RestrictSigninToPattern' contains quotes that break the setting on Windows

### ISSUE THREAD

**Issue by SamErde** [MicrosoftDocs/Edge-Enterprise#397]
The example provided for the GPO setting "**Restrict which accounts can be used to sign in to Microsoft Edge**" (and the registry key setting `RestrictSigninTopattern`) on Windows devices includes quotes. When that syntax is copied into a GPO, it does not work. This also fails on regex pattern tests. Using the example syntax _without_ quotes works. I have tested and reproduced this with a GPO and also with editing the registry directly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#restrictsignintopattern)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by SamErde** [comment]
PR #398 submitted to fix this issue.

**Comment by Y-Kelly** [comment]
@SamErde This issue affects other policies as well, not only the RestrictSigninToPattern policy.  There is existing work going on to make improvements in this area and the team has it on their roadmap to fix.  

In regards to the PR submitted, this will only temporarily correct the issue.  The policy documentation gets updated weekly and even if the PR is merged, the changes will get overwritten in the next update.  

I've passed your feedback on to the team so they can take it into account when prioritizing the work.  Thanks for the feedback!
