### ISSUE TITLE
AuthSchemes is case-sensitive! Please document!

### ISSUE THREAD

**Issue by joachimme** [MicrosoftDocs/Edge-Enterprise#399]
The authentification schemes for the AuthSchemes Registry value **must** be entered in lower-case. This is a pretty nasty trap and the help in the ADMX file lists them with the first letter in upper-case. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@joachimme Thanks for the feedback, we would like to investigate.  Can you provide more details and a screenshot of where you saw the first letters upper case?  

I downloaded new Policy files from https://www.microsoft.com/en-us/edge/business/downloadand and the examples I saw were all lower case.
![image](https://user-images.githubusercontent.com/74324031/184022294-f16a0559-7dc6-40f2-b171-c9d2eb948b7f.png)

**Comment by joachimme** [comment]
@Y-Kelly Thanks for the prompt feedback. The customer is using a German-language OS and thus the ADMX files are also displayed in German and the German version is like this:

Sie können die Richtlinie mit folgenden Werten konfigurieren:
"Basic", "Digest", "NTLM" und "Negotiate".

Looks like the English version is correct but the German is maybe not wrong but at least misleading. But adding one sentence to the documentation of the AuthSchemes setting here stating must be all lower-casse would also be nice.

Best Regards,
Joachim

**Comment by Y-Kelly** [comment]
@joachimme Just to follow up, we are investigating updating the description to indicate that the value is case sensitive.  

Also, separately our localization team has found the capitalization issue occurs in the [policy documentation](https://docs.microsoft.com/de-DE/deployedge/microsoft-edge-policies#authschemes) for German and Spanish as well.  They are working on correcting the documentation.  Thanks!

**Comment by joachimme** [comment]
@Y-Kelly Thank you very much for your prompt response!
