### ISSUE TITLE
Printing policies - Print background graphics

### ISSUE THREAD

**Issue by MaxBGitHub** [MicrosoftDocs/Edge-Enterprise#4]
Is it possible to enable the "Background graphics" setting for printing via GPO?
I was able to find the " Print headers and footers" (PrintHeaderFooter) policy but 
the "Background graphics" policy seems to be missing.
https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-policies#printing-policies

Will this setting be available in the future if it isn't already?

**Comment by Y-Kelly** [comment]
@MaxBGitHub Our team is currently investigating adding a policy for Background Graphics.  It is on our radar.  

If you have further questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!

**Comment by Y-Kelly** [comment]
@MaxBGitHub We've added new polices in version 89 for Background Graphics.  

Here are links to our documentation: 

[https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#printingallowedbackgroundgraphicsmodes](url)
[https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#printingbackgroundgraphicsdefault](url)

**Comment by MaxBGitHub** [comment]
@Y-Kelly Great, Thank you for the update!

**Comment by shapeh** [comment]
I would like a policy for silent printing, i.e. `--kiosk-printing` instead of having to call:

`"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --kiosk https://example.org/ --kiosk-printing
`
The policy would come in handy since you cannot pass parameters to Assigned Access / Kiosk mode via Windows Settings.

**Comment by Y-Kelly** [comment]
@shapeh I've passed your feedback on to the team.  If you haven't had a chance yet, you can also submit feedback through the browser ("..." menu > Help and feedback > Send feedback)  Thanks!

**Comment by shapeh** [comment]
@Y-Kelly Thanks for the quick response and for passing on my comments. Hope they will be implemented. I have stopped using the Help and feedback service - we rarely see any response on that system unfortunately, despite some decent suggestions (I guess there is too looong a distance between the product teams and the people who monitor the feedback system). Github response seems to work better. :)

**Comment by Y-Kelly** [comment]
@shapeh There looks to be some discussion related to your feature request but no ETA right now.  Thanks!

**Comment by shapeh** [comment]
@Y-Kelly I have run into sever problems related to Edge with Assigned Access / security issues. I have posted it on the Feedback hub but I am not sure it will be seen by the right people. If you can, please notify the right team - please see here: https://aka.ms/AAd5fv7

**Comment by Y-Kelly** [comment]
@shapeh I don't have access to view the feedback.  

Are you trying to set up Kiosk mode for your organization?  We have a few options for help, first our FastTrack team which can help transition to MS Edge https://www.microsoft.com/en-us/fasttrack/microsoft-365/microsoft-edge, you can also reach out to our support team https://microsoftedgesupport.microsoft.com/hc/en-us or for Enterprise specific questions you can visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!

**Comment by shapeh** [comment]
@Y-Kelly - we have found some security problems with Edge in Kiosk mode. We have submitted the request to https://www.microsoftedgeinsider.com/en-us/support
Thanks.
