### ISSUE TITLE
Edge version number makes no sense

### ISSUE THREAD

**Issue by softwarecraft** [MicrosoftDocs/Edge-Enterprise#40]
"This article applies to Microsoft Edge version 78 or later." and is dated "10/22/2019". I'm running an up to date Win10 OS with all updates applied. My browser is "Microsoft Edge 44.18362.449.0". How can my Edge version be so different and much lower?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4be833d4-f235-4029-258d-6ef2387f4189
* Version Independent ID: 09525733-35da-0bf0-522b-d3f9decb367a
* Content: [Microsoft Edge language support](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-supported-languages#feedback)
* Content Source: [edgeenterprise/microsoft-edge-supported-languages.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-supported-languages.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by Y-Kelly** [comment]
Clean up of old issues.  Support for Legacy MS Edge ended on March 9, 2021.  Closing.
