### ISSUE TITLE
Licensing required

### ISSUE THREAD

**Issue by FernandoGualano** [MicrosoftDocs/Edge-Enterprise#400]
Hi!,
I read several questions about the required licensing. My specific question is the following: Is the Azure Information Protection P1/P2 license required? We have Office 365 E3 licenses. Therefore, it is a supported environment. But the Prerequisites section confuses me:

![image](https://user-images.githubusercontent.com/50090959/185718758-42a5687f-c076-491a-9484-5a3e4053249a.png)

Could you clarify this issue?

Thanks!
Fernando

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fa7eda4-6e4c-c2c8-a29a-ef2eead7f04f
* Version Independent ID: 414db256-c14b-ca11-b2a7-835aa9c9e041
* Content: [Configure Microsoft Edge enterprise sync](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-enterprise-sync)
* Content Source: [edgeenterprise/microsoft-edge-enterprise-sync.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-enterprise-sync.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
@FernandoGualano Yes, Azure Information Protection (AIP) (P1 or P2) is a required prerequisite.  Enterprise sync depends on AIP.  

If you have issues with enterprise sync in your organization, you can reach out to Microsoft Edge Support: https://support.microsoft.com/en-us/microsoft-edge or specifically for AIP: https://docs.microsoft.com/en-us/azure/information-protection/information-support#to-contact-microsoft-support.  The support teams will be able to work with you directly to investigate your specific scenario.
