### ISSUE TITLE
Tab groups feature not mentioned

### ISSUE THREAD

**Issue by Kath-Anne** [MicrosoftDocs/Edge-Enterprise#402]
Should the "tab groups" feature be listed here? It's listed in the version notes for 93.0.961.38 https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-archive-stable-channel but it's unclear if it's available on all platforms?

I also think there is a lack of promotion for this feature and no user training available. The only info I found was in a blog post https://blogs.windows.com/windowsexperience/2021/09/23/our-top-new-features-are-designed-to-put-your-family-first/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5379113-884d-a8b9-f76f-2debd872867c
* Version Independent ID: 7f6a4574-4f2e-e6ca-f8e5-d17531a0718e
* Content: [Platform support for Microsoft Edge features](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-platform-feature-matrix)
* Content Source: [edgeenterprise/microsoft-edge-platform-feature-matrix.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-platform-feature-matrix.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
@Kath-Anne Hello - The Feature matrix for platforms document does include many Microsoft Edge features but it is not a full comprehensive list.  Currently, there are no plans to add Tab Groups.  

We appreciate you reaching out and thank you for your feedback!  I will pass the suggestions on to the team.
