### ISSUE TITLE
Dates in item headings should include the year

### ISSUE THREAD

**Issue by JNLlB** [MicrosoftDocs/Edge-Enterprise#403]
Edge is now old enough for it to be unclear which year a particular version was released. 
**Version 92.0.902.55: July 22** could refer to 2019, 2020, 2021 or 2022, with no clue from other entries on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 453e1f9e-90fc-ce58-3ebb-c225481675d6
* Version Independent ID: 864cfff5-6c6f-d90b-bc09-7c6319658162
* Content: [Archived release notes for Microsoft Edge Stable Channel](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-archive-stable-channel)
* Content Source: [edgeenterprise/microsoft-edge-relnote-archive-stable-channel.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-relnote-archive-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @leahmsft
* Microsoft Alias: **leahtu**

**Comment by Y-Kelly** [comment]
@JNLlB Thanks for reaching out!  Yes, this is a great idea!

You'll notice that going forward the year will be included in the Release Notes headings.  https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel#version-1040129370-august-25-2022
