### ISSUE TITLE
NewTabPageLocation Not working in Kiosk mode Public Browsing

### ISSUE THREAD

**Issue by boivinx7** [MicrosoftDocs/Edge-Enterprise#404]
From the documentation it is suppose to work
[Configure the new tab page URL](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#newtabpagelocation) (policy)

But it only opens New InPrivate Tabs, which allows users to then go to other web sites.

**Comment by Y-Kelly** [comment]
@boivinx7 Just to confirm, does your device meet this criteria?  

![image](https://user-images.githubusercontent.com/74324031/187751813-6976dc13-6ec4-44f4-9d73-7563ecb83d36.png)
Screenshot from: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#newtabpagelocation

**Comment by boivinx7** [comment]
Yes they do.
Azure AD Hybrid Join, Intune Co-Management, All Windows 10 Enterprise 21H2.

**Comment by Y-Kelly** [comment]
@boivinx7 Thanks!  I do see that this is a known issue.  It appears that customers started reporting this in MS Edge v102.  

I can pass this on to the team but if you have Microsoft Unified Support, you can reach out to that support service or you can also provide feedback through the browser ("..." menu > Help and feedback > Send feedback) which helps the team understand the impact of this issue.

**Comment by boivinx7** [comment]
Thanks at least its a known issue, but we don't have unified support.
Thanks

**Comment by Y-Kelly** [comment]
@boivinx7 If I get any updates from the team regarding a fix, I'll follow up here.  Thanks!

**Comment by Y-Kelly** [comment]
@boivinx7 The team has released a fix and it is available in MS Edge Canary Channel (v107).  They are working on backporting the fix to Beta Channel (v106) and Stable Channel (v105).  Thanks!
