### ISSUE TITLE
Typo in DefaultSearchProviderContextMenuAccessAllowed

### ISSUE THREAD

**Issue by JNLlB** [MicrosoftDocs/Edge-Enterprise#406]
([Allow default search provider context menu search access](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#defaultsearchprovidercontextmenuaccessallowed))

"The policy value is only appled when the DefaultSearchProviderEnabled policy is enabled, and is not applicable otherwise."

! appled > _applied_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#defaultsearchprovidercontextmenuaccessallowed)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@JNLlB Thanks for the report.  I've passed this on to the team and it should be fixed in an upcoming refresh of the policy documentation.

**Comment by Y-Kelly** [comment]
Documentation has been updated and typo has been corrected: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#defaultsearchprovidercontextmenuaccessallowed

![image](https://user-images.githubusercontent.com/74324031/189401121-56ac5cd3-bf43-431e-8907-2cddf75fad5a.png)

**Comment by JNLlB** [comment]
Thank you for a swift resolution again.

Noel Burgess
