### ISSUE TITLE
如何关闭烦人的混合内容下载的安全警告提示

### ISSUE THREAD

**Issue by buqiang** [MicrosoftDocs/Edge-Enterprise#407]
如何关闭烦人的混合内容下载的安全警告提示
InsecureContentAllowedForUrls策略无法使用通配符,
不在InsecureContentBlockedForUrls策略中的网址仍然会提示安全警告
![image](https://user-images.githubusercontent.com/48707118/188098411-1bdbfc20-718a-4732-93ba-0eecc9d60ebd.png)

[https://docs.microsoft.com/en-us/DeployEdge/edge-learnmore-mixed-content-downloads#download-warnings-and-user-options](url)
[https://docs.microsoft.com/zh-cn/DeployEdge/microsoft-edge-policies#insecurecontentallowedforurls](url)
[https://docs.microsoft.com/zh-cn/DeployEdge/microsoft-edge-policies#insecurecontentblockedforurls](url)

**Comment by Y-Kelly** [comment]
@buqiang I'm using a translator so sorry if I've misinterpreted your message.  

As an end user or IT administrator, you can turn off the messages on a per site basis.  More information can be found here: https://textslashplain.com/2021/10/14/moartls-non-secure-download-blocking/.  This blog is written by Eric Lawrence, Principal PM at MSFT.  

If you would like to report a Microsoft Edge Enterprise documentation issue to the team please open a new issue and include relevant information/repro steps in the Comment section.

If you have general questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsiderForum) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
