### ISSUE TITLE
Missing Update in WSUS

### ISSUE THREAD

**Issue by CanastraRF** [MicrosoftDocs/Edge-Enterprise#409]
The newest Update for Edge Microsoft Edge Stable Channel (Version 105.0.1343.27) is not now available in WSUS.
Please publish the Update for WSUS faster.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85b3847f-f5e0-539e-6d00-81887b0a0be8
* Version Independent ID: 061f97c4-56ec-4064-9f70-7e3c1f789ac6
* Content: [Release notes for Microsoft Edge Security Updates](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-relnotes-security)
* Content Source: [edgeenterprise/microsoft-edge-relnotes-security.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-relnotes-security.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **leahtu**

**Comment by Y-Kelly** [comment]
@CanastraRF Thank you for the feedback.  I can see the team has improvements in this area planned and on their roadmap.  

If you haven't had a chance yet, you can also submit feedback directly to the team through the browser ("..." menu > Help and feedback > Send feedback)
