### ISSUE TITLE
RestrictSigninToPattern should not have quotations

### ISSUE THREAD

**Issue by tylermontneyacc** [MicrosoftDocs/Edge-Enterprise#410]
The example value is formatted in a code block. I believe the quotation marks are a mistake. It should be...

`.*@contoso\.com`

as the Mac example value does not contain quotation marks. Additionally, it is a PCRE which makes the quotation marks undesirable (if the example is simply to allow any email ending in that domain).

https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#example-value-386

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#restrictsignintopattern)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@tylermontneyacc Thanks for the feedback!  This issue affects other policies as well, not only the RestrictSigninToPattern policy. There is existing work going on to make improvements in this area and the team has it on their roadmap to fix.

I've passed your feedback on to the team so they can take it into account when prioritizing the work.
