### ISSUE TITLE
ConfigureKeyboardShortcuts

### ISSUE THREAD

**Issue by gerwintr** [MicrosoftDocs/Edge-Enterprise#412]
The ConfigureKeyboardShortcuts example could really use a example where it's shown how to disable multiple keyboard shortcuts.

currently it only lists: SOFTWARE\Policies\Microsoft\Edge\ConfigureKeyboardShortcuts = {"disabled": ["new_tab"]} as a example.

i would propose to add a example like this so it's clear that when you want to block multiple things you have to seperate them with a comma lik so: SOFTWARE\Policies\Microsoft\Edge\ConfigureKeyboardShortcuts = {"disabled": ["new_tab",,"dev_tools","etc"]}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@gerwintr Thank you for the feedback.  We have reached out to the policy owner and passed on the suggestion.  We will follow up with any updates.

**Comment by Y-Kelly** [comment]
@gerwintr The policy owner has updated the example in the policy documentation.  Thanks again! 

https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#example-value-228
![image](https://user-images.githubusercontent.com/74324031/199302938-f5e3aa3a-b6f4-4b6a-b4b7-6dd43f3ea437.png)
