### ISSUE TITLE
Link to download

### ISSUE THREAD

**Issue by Ryu-Syrius** [MicrosoftDocs/Edge-Enterprise#413]
https://learn.microsoft.com/en-us/deployedge/configure-microsoft-edge#1-download-and-install-the-microsoft-edge-administrative-template

The link "https://www.microsoft.com/en-us/edge/business/download" does not have a download option for the Microsoft Edge Administrative Templates.  You can only download the installer for Edge Enterprise.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8e4fa0af-82d8-c1ca-02b3-fc55eb620ff3
* Version Independent ID: bd546e78-3406-0fdd-2aea-d0bd72be9f38
* Content: [Configure Microsoft Edge for Windows with policy settings](https://learn.microsoft.com/en-us/deployedge/configure-microsoft-edge)
* Content Source: [edgeenterprise/configure-microsoft-edge.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/configure-microsoft-edge.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **v-danwesley**

**Comment by Ryu-Syrius** [comment]
Never mind.  I found it.  In the section "Looking for an older version of Edge?", you have to select your Channel, Build, and Platform at the bottom of the page, then select the "Get policy files", to the right of the download button.

**Comment by Y-Kelly** [comment]
@Ryu-Syrius Glad you found them.  Policy files can also be found above that, see highlighted in the screenshot.  

![image](https://user-images.githubusercontent.com/74324031/192329105-df6f9576-b629-4544-aa8d-b507364337a5.png)

Thanks!
