### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by BergaDev** [MicrosoftDocs/Edge-Enterprise#414]
[Edge for MacOS when installed will not work on system running anything less than 10.13, different to this page that states 10.12]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86847b80-8f8e-9493-86ff-5dfd6412b48f
* Version Independent ID: 2ce02bc3-24a1-8c9f-c787-34ab90e9f31d
* Content: [Microsoft Edge Supported Operating Systems](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-supported-operating-systems)
* Content Source: [edgeenterprise/microsoft-edge-supported-operating-systems.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-supported-operating-systems.md)
* Product: **microsoft-edge**
* GitHub Login: @srugh
* Microsoft Alias: **srugh**

**Comment by Y-Kelly** [comment]
@BergaDev Thanks for the feedback!  We have updated the Supported Operating Systems page.  

![image](https://user-images.githubusercontent.com/74324031/196297333-40819942-ab4b-4eb0-b5ce-13f8f56e7493.png)
