### ISSUE TITLE
Missing Edge stable 106 in Update catalog and WSUS

### ISSUE THREAD

**Issue by CanastraRF** [MicrosoftDocs/Edge-Enterprise#415]
Hi

the new release 106 of edge is in update catalog und WSUS not available.
Only edge extended and webview2 is updated to 106.
Please deploy all versions to catalog and wsus after release.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ffcaf54-ce86-1b30-e947-540bf07a54c3
* Version Independent ID: 81267e97-e284-ff00-b081-476934538326
* Content: [Microsoft Edge release notes for Stable Channel](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **leahtu**

**Comment by Y-Kelly** [comment]
@CanastraRF Sorry for the delay.  Stable is now available in Microsoft Update Catalog: https://www.catalog.update.microsoft.com/Search.aspx?q=edge

The team has been notified and they are investigating.  Thanks!
