### ISSUE TITLE
Clarify ClickOnce policy behavior

### ISSUE THREAD

**Issue by ericlaw1979** [MicrosoftDocs/Edge-Enterprise#418]
This document discusses how to avoid the clickonce security warning by setting autoopenfiletype policy. A customer thought this meant that they could set the autoopenfiletype policy to allow a particular site to use clickonce while also using the general ClickOnceEnabled policy to disable clickonce globally.

That doesn't work -- if you do it, .application files will be downloaded to the user's download folder, but they will not be directinvoked, causing them to (usually) not work correctly.

We should clarify that ClickOnce policy must be left at the default (enabled) to get ClickOnce launch behavior, even if autoopen policy is set. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ef8deb0-cf41-dffe-409c-6d4cfeb1ee19
* Version Independent ID: 4a966703-f3f0-3600-3224-8b786881f08c
* Content: [ClickOnce and DirectInvoke in Microsoft Edge](https://learn.microsoft.com/en-us/deployedge/edge-learn-more-co-di?source=recommendations)
* Content Source: [edgeenterprise/edge-learn-more-co-di.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learn-more-co-di.md)
* Product: **microsoft-edge**
* GitHub Login: @AndreaLBarr
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
Thanks @ericlaw1979 !  Doc has been updated with your feedback :)
