### ISSUE TITLE
Typo: ....A user may might have access ....

### ISSUE THREAD

**Issue by KitCat36** [MicrosoftDocs/Edge-Enterprise#420]
There is a typo in the document,
"A user **may migh**t have access to a specific workspace, but might not have access to....."

![image](https://user-images.githubusercontent.com/72892766/195427510-6d16f0ec-0f4f-498b-84e2-506a088856f4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 395cb351-c526-c346-2dd0-9f02e5e80b63
* Version Independent ID: 395cb351-c526-c346-2dd0-9f02e5e80b63
* Content: [Microsoft Edge Workspaces](https://learn.microsoft.com/en-us/DeployEdge/microsoft-edge-workspaces)
* Content Source: [edgeenterprise/microsoft-edge-workspaces.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-workspaces.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **danielfi**

**Comment by dan-wesley** [comment]
@KitCat36 Thank you for catching that. Fix is in and doc getting refreshed.
