### ISSUE TITLE
Matheus 

### ISSUE THREAD

**Issue by Teco10** [MicrosoftDocs/Edge-Enterprise#421]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1404ec79-6a71-2f91-934a-1dc58e32a6ba
* Version Independent ID: 1404ec79-6a71-2f91-934a-1dc58e32a6ba
* Content: [Browse more safely with Microsoft Edge](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-security-browse-safer)
* Content Source: [edgeenterprise/microsoft-edge-security-browse-safer.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-security-browse-safer.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **pchiquini**

**Comment by Y-Kelly** [comment]
@Teco10 Hello - If you would like to report a Microsoft Edge Enterprise documentation issue to the team please open a new issue and include relevant information/repro steps in the Comment section.

If you have general questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsiderForum) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
