### ISSUE TITLE
Matheus 

### ISSUE THREAD

**Issue by Teco10** [MicrosoftDocs/Edge-Enterprise#422]
Não consigo jogar o subway surfers no celular

**Comment by Y-Kelly** [comment]
@Teco10 Hello - If you would like to report a Microsoft Edge Enterprise documentation issue to the team please open a new issue and include relevant information/repro steps in the Comment section.

If you have general questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsiderForum) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
