### ISSUE TITLE
issue in finding Computer Configuration\Administrative Templates\Windows Components\File Explorer.

### ISSUE THREAD

**Issue by Janaselvam** [MicrosoftDocs/Edge-Enterprise#423]
[Enter feedback here]
Hi ,

I am using windows server 2016 but I am unable to find  file explorer in  following path
Computer Configuration\Administrative Templates\Windows Components\**_File Explorer_** 
under Group policy management console on Domain controller.

I was asked to implement Microsoft edge as default browser for all the host in domain but I am unable to implement.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e858557-d417-cb01-9f4f-ed214087790c
* Version Independent ID: 9cbd34f5-7a9a-1e3a-d832-1a945db28726
* Content: [Set Microsoft Edge as the default browser on Windows and macOS](https://learn.microsoft.com/en-us/deployedge/edge-default-browser?source=recommendations)
* Content Source: [edgeenterprise/edge-default-browser.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-default-browser.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **brianalt**

**Comment by Y-Kelly** [comment]
@Janaselvam Just to confirm, is this the section you are referencing **Set Microsoft Edge as the default browser on domain-joined devices** https://learn.microsoft.com/en-us/deployedge/edge-default-browser#set-microsoft-edge-as-the-default-browser-on-domain-joined-devices?  

Are you able to find the Windows Components folder?  Is it only the File Explorer folder that is missing? 

![image](https://user-images.githubusercontent.com/74324031/196275047-0a643ba9-d033-4c04-a5ae-c3aa268d5722.png)

**Comment by Y-Kelly** [comment]
Closing issue as there has not been any recent replies.

If you are continuing to have issues, you can reach out to Support (https://developer.microsoft.com/en-us/microsoft-edge/support/) for further assistance. Thanks!
