### ISSUE TITLE
Page is not accurate.

### ISSUE THREAD

**Issue by Evan193** [MicrosoftDocs/Edge-Enterprise#424]
The instructions for adding admx templates for Microsoft Edge are wrong.  The article specifies placing the admx files at domain.com\sysvol\policies\policydefinitions.  The problem is the policydefinitions folder does not exist.  It is only full of GUID folders under policies.  Please update the article to be accurate.  Some screenshots would also be nice.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8e4fa0af-82d8-c1ca-02b3-fc55eb620ff3
* Version Independent ID: bd546e78-3406-0fdd-2aea-d0bd72be9f38
* Content: [Configure Microsoft Edge for Windows with policy settings](https://learn.microsoft.com/en-us/deployedge/configure-microsoft-edge)
* Content Source: [edgeenterprise/configure-microsoft-edge.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/configure-microsoft-edge.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **v-danwesley**

**Comment by Y-Kelly** [comment]
@Evan193 If you are trying to "Add the administrative template to Active Directory" it does say you may need to create the PolicyDefinition folder.  

![image](https://user-images.githubusercontent.com/74324031/196272832-3d740d0e-d0cc-4029-8093-863485b83d2c.png)

More information is also available here: https://learn.microsoft.com/en-US/troubleshoot/windows-client/group-policy/create-and-manage-central-store

**Comment by Evan193** [comment]
Understood, thank you for the follow up.
