### ISSUE TITLE
Incorrect Steps for Perform a reset to fix a synchronization problem

### ISSUE THREAD

**Issue by LtCmdrKeene** [MicrosoftDocs/Edge-Enterprise#425]
In the section titled "Perform a reset to fix a synchronization problem", the steps are wrong.

After performing step 1, step 2 is impossible.  Going to Settings / Profiles reveals that the Sync option, which the instruction directs you to click, is disabled and unavailable. 

<img width="960" alt="image" src="https://user-images.githubusercontent.com/4219926/195998223-e20138e1-d801-42b4-8cbe-8b74616ff764.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa2b6bb-c572-6b62-0b2a-5d11cc6c16c2
* Version Independent ID: bbd72cfb-0dd2-dce0-ede7-6887a2992bad
* Content: [Reset Microsoft Edge data in the cloud](https://learn.microsoft.com/en-us/deployedge/edge-learnmore-reset-data-in-cloud)
* Content Source: [edgeenterprise/edge-learnmore-reset-data-in-cloud.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-reset-data-in-cloud.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
@LtCmdrKeene Hello - For Step 1, you should sign out of the browser everywhere _except_ the device being reset, then you should be able to do Step 2.  
 
![image](https://user-images.githubusercontent.com/74324031/196270819-e8244f7b-330a-44ae-9c2e-9a4d7fd9f6f8.png)
