### ISSUE TITLE
SiteSafetyServicesEnabled

### ISSUE THREAD

**Issue by kyleross-deckers** [MicrosoftDocs/Edge-Enterprise#426]
The display title for this policy, "Allow users to configure Site Safety services." is poorly worded.

If you 'Enable' this policy, the feature is enabled in Edge and is locked.

If you 'Disable' this policy, the feature is turned off in Edge and is locked.

The only point at which this 'Allows' users to configure anything is if the policy is 'Not Configured".

The title should be something like just 'Allow Site safety services".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#sitesafetyservicesenabled)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@kyleross-deckers Are you configuring the policy as mandatory or recommended?  If it is set to recommended, I believe that will allow users to change the setting. 

![image](https://user-images.githubusercontent.com/74324031/196278468-31992820-7465-4c0f-8990-7d575c3f599b.png)

Information about mandatory/recommended here: https://learn.microsoft.com/en-us/deployedge/configure-microsoft-edge#introduction-to-policy-settings-on-windows

**Comment by Y-Kelly** [comment]
Closing issue as there has not been any recent replies.

If you are continuing to have issues, you can reach out to Support (https://developer.microsoft.com/en-us/microsoft-edge/support/) for further assistance. Thanks!
