### ISSUE TITLE
NewTabPageSetFeedType

### ISSUE THREAD

**Issue by kyleross-deckers** [MicrosoftDocs/Edge-Enterprise#427]
The description for NewTabPageSetFeedType indicates that this setting is obsolete and directs the user to https://admin.microsoft.com instead. However, no details are provided on where to go in the admin portal to make said changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies?source=recommendations)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@kyleross-deckers Instructions for the Microsoft 365 admin center can be found here: https://learn.microsoft.com/en-us/microsoft-365/admin/manage/manage-industry-news?view=o365-worldwide#microsoft-edge-new-tab-page

Thanks!
