### ISSUE TITLE
Displayname of the ExtensionInstallBlockList wrong on one location

### ISSUE THREAD

**Issue by HeikoMayer** [MicrosoftDocs/Edge-Enterprise#428]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

[Enter feedback here]
The displayname of the ExtensionInstallBlockList-policy is named incorrectly in the paragraph "Block specific sidebar apps" as "[..]cannot be enabled". Please change it to "[..]cannot be installed"

thx,
Heiko

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6191d038-8035-aeaf-3122-3245a6d868c7
* Version Independent ID: 6191d038-8035-aeaf-3122-3245a6d868c7
* Content: [Manage the sidebar in Microsoft Edge](https://review.learn.microsoft.com/en-us/DeployEdge/microsoft-edge-sidebar?branch=main#feedback)
* Content Source: [edgeenterprise/microsoft-edge-sidebar.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-sidebar.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kylemiller**

**Comment by Y-Kelly** [comment]
@HeikoMayer Thanks for the feedback!  The doc has been updated.  

![image](https://user-images.githubusercontent.com/74324031/196776667-0e63ca83-d626-4168-a87c-103d7e698c99.png)
