### ISSUE TITLE
Where to find information on troubleshooting?

### ISSUE THREAD

**Issue by mikenri** [MicrosoftDocs/Edge-Enterprise#43]
Where is information on troubleshooting sync, and sync related error codes documented?

The link for troubleshooting returns 404 not found: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-troubleshooting

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ca3f20e-22b7-2d5a-67eb-0da9d27dcde8
* Version Independent ID: 7f6980c3-ce44-f0bc-fd76-bdf8cb7938b5
* Content: [Microsoft Edge Sync](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-enterprise-sync)
* Content Source: [edgeenterprise/microsoft-edge-enterprise-sync.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-enterprise-sync.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by Y-Kelly** [comment]
Clean up of old issues.  More information about sync issues can be found here: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-troubleshoot-enterprise-sync

If you are having a specific issue, [Support - Microsoft Edge Developer](https://developer.microsoft.com/en-us/microsoft-edge/support/) should be able to gather logs and help investigate your specific case.
