### ISSUE TITLE
Broken link to enterprise list manager

### ISSUE THREAD

**Issue by kf4ape** [MicrosoftDocs/Edge-Enterprise#430]
Broken link to enterprise list manager - links goto 404s

**Comment by Y-Kelly** [comment]
@kf4ape Hello - Can you provide the link to the document with the broken link?  Do you mean this page edge://compat/SiteListManager?  Please provide more details.  Thanks!

**Comment by kf4ape** [comment]
source 
https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode-site-list-manager.md
links
https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/internet-explorer/ie11-deploy-guide/enterprise-mode-schema-version-2-guidance

**Comment by Y-Kelly** [comment]
@kf4ape If you view the article on Microsoft Learn (https://learn.microsoft.com/en-us/deployedge/edge-ie-mode-site-list-manager) the link will work as expected (https://learn.microsoft.com/en-us/internet-explorer/ie11-deploy-guide/enterprise-mode-schema-version-2-guidance).  

Is there a reason you are viewing the Markdown source?  The link you have specified is in another repo which might be why you are seeing the 404.

**Comment by kf4ape** [comment]
I was trying to get information about the enterprise site list manager v2 and cookies for domains...as it seems like that application doesn't support domain sharing cookies

**Comment by Y-Kelly** [comment]
Is there a reason you are not using the in-browser version of the Enterprise Site List Manager (edge://compat/SiteListManager)?  

Like the documentation mentions, the standalone tool will continue to be available but will not get feature updates,  

![image](https://user-images.githubusercontent.com/74324031/196781451-cc6df6b1-3113-4187-827a-4c0915838800.png)

**Comment by kf4ape** [comment]
I am managing a 15000 user org and trying to keep a unified list so doing GPOs with XML is a necessity...also we have strict compliance in regards to users adjusting their own settings

**Comment by Y-Kelly** [comment]
Have you looked into the Cloud Site List Management https://learn.microsoft.com/en-us/deployedge/edge-ie-mode-cloud-site-list-mgmt?

**Comment by kf4ape** [comment]
Wont work as certain PCs get them based on OU GPOs...I know MS is trying to push more and more folks to the cloud for stuff but that does not fit all entities

**Comment by Y-Kelly** [comment]
Yes, I understand.  You can also submit feature requests/feedback through our in-browser feedback tool? It's under "..." menu > Help and feedback > Send feedback.  Or you can reach out to Support (https://developer.microsoft.com/en-us/microsoft-edge/support/) to help you with your specific situation.
