### ISSUE TITLE
Edge kiosk mode command line options not working

### ISSUE THREAD

**Issue by WCJr03** [MicrosoftDocs/Edge-Enterprise#432]
I'm using Edge version 106 and want to use the kiosk mode command line option "msedge.exe --kiosk www.contoso.com http://www.contoso.com --edge-kiosk-type=public-browsing --kiosk-idle-timeout-minutes=1" to setup a desktop shortcut to a website. The shortcut opens the website but the "--edge-kiosk-type=public-browsing" and "--kiosk-idle-timeout-minutes=1" command line options are not working.  Any help or clarification will be greatly appreciated.

**Comment by Y-Kelly** [comment]
@WCJr03 Did the command line work in previous versions of MS Edge?  

This is the example from the documentation (https://learn.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode#additional-command-line-options)

`msedge.exe --kiosk www.contoso.com --edge-kiosk-type=public-browsing --kiosk-idle-timeout-minutes=1`

Is there a reason you have the extra "http://www.contoso.com/" in your code?

**Comment by WCJr03** [comment]
@Y-Kelly I haven't used the command-line in previous versions.   The actual command line I'm using is "c:\program files (x86)\microsoft\edge\application\msedge.exe" --kiosk www.ohome.apps. --edge-kiosk-type=public-browsing --kiosk-idle-timeout-minutes=1.   I left out the domain.  As I said before, the shortcut will open to the website but the public browsing and idle timeout commands are not working.  I think the command line options are nerfed.

**Comment by Y-Kelly** [comment]
@WCJr03 I was not able to reproduce your issue.  

This is what I used in Command Prompt: 

`start msedge.exe --kiosk www.microsoft.com --edge-kiosk-type=public-browsing --kiosk-idle-timeout-minutes=1`

At 30 seconds there was the following message and at 1 minute the browser closed.  

![image](https://user-images.githubusercontent.com/74324031/198137022-19c2bc10-12f0-4cd0-ae6b-d0f26ed7c8f0.png)

If you are continuing to have issues, you can reach out to Support (https://developer.microsoft.com/en-us/microsoft-edge/support/) for further assistance.  Thanks!

**Comment by WCJr03** [comment]
@Y-Kelly I copied and tried the cmd line that you posted and in my environment the browser went into full-screen (no tabs) and did not end the session.  I'll go to microsoft-edge support.  Thank you for your help.
