### ISSUE TITLE
Intune first

### ISSUE THREAD

**Issue by wUEZRs** [MicrosoftDocs/Edge-Enterprise#433]
Should mention how to set it up in Intune, not focus on GPOs and the user front.

Intune is the de facto standard of managing Edge in 2022

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1404ec79-6a71-2f91-934a-1dc58e32a6ba
* Version Independent ID: 1404ec79-6a71-2f91-934a-1dc58e32a6ba
* Content: [Browse more safely with Microsoft Edge](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-security-browse-safer)
* Content Source: [edgeenterprise/microsoft-edge-security-browse-safer.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-security-browse-safer.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **pchiquini**

**Comment by Y-Kelly** [comment]
@wUEZRs Thank you for your feedback, I've passed the suggestion on to the team.
