### ISSUE TITLE
Documentation does not exist for ShouldBlockPreview added in v107.

### ISSUE THREAD

**Issue by tatsuya-midorikawa** [MicrosoftDocs/Edge-Enterprise#435]
Documentation does not exist for ShouldBlockPreview added in v107.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 96fddabd-2bac-2fab-a5ea-25c000b425fc
* Version Independent ID: 41bba38e-bd24-0496-da04-012d6deb5db8
* Content: [Microsoft Edge Update Policy Documentation](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-update-policies)
* Content Source: [edgeenterprise/microsoft-edge-update-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-update-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@tatsuya-midorikawa I've spoken with the team and they are still working on this feature.  Once it is complete, they will publish the proper documentation.  I'll also reply to your other similar issue.  Thanks!
