### ISSUE TITLE
No mention of ShouldBlockPreview added in v107.

### ISSUE THREAD

**Issue by tatsuya-midorikawa** [MicrosoftDocs/Edge-Enterprise#436]
No mention of ShouldBlockPreview added in v107.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ffcaf54-ce86-1b30-e947-540bf07a54c3
* Version Independent ID: 81267e97-e284-ff00-b081-476934538326
* Content: [Microsoft Edge release notes for Stable Channel](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **leahtu**

**Comment by Y-Kelly** [comment]
@tatsuya-midorikawa Like previously mentioned, I've spoken with the team and they are still working on this feature.  Once it is complete, they will publish the proper documentation. Thanks!
