### ISSUE TITLE
Block specific sidebar apps not working

### ISSUE THREAD

**Issue by mav147** [MicrosoftDocs/Edge-Enterprise#437]
Under the section **Block specific sidebar apps** linked below, it states we can use the group policy "control which extensions cannot be installed". 
We already have this configured as a wildcard (*) to block all extensions except those we add specifically to the "allowed extensions" GPO. This however does not appear to apply to the sidebar, as my users can still enable the Games tab etc.

https://learn.microsoft.com/en-us/deployedge/microsoft-edge-sidebar#block-specific-sidebar-apps

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6191d038-8035-aeaf-3122-3245a6d868c7
* Version Independent ID: 6191d038-8035-aeaf-3122-3245a6d868c7
* Content: [Manage the sidebar in Microsoft Edge](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-sidebar)
* Content Source: [edgeenterprise/microsoft-edge-sidebar.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-sidebar.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kylemiller**

**Comment by Y-Kelly** [comment]
@mav147 Just to confirm, the [ExtensionInstallBlockList](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#extensioninstallblocklist) policy works correctly for other extensions like ones from the [Microsoft Edge Add-ons](https://microsoftedge.microsoft.com/addons/) website.  Is that correct?  It is only the sidebar apps that are not being blocked?

**Comment by mav147** [comment]
> @mav147 Just to confirm, the [ExtensionInstallBlockList](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#extensioninstallblocklist) policy works correctly for other extensions like ones from the [Microsoft Edge Add-ons](https://microsoftedge.microsoft.com/addons/) website. Is that correct? It is only the sidebar apps that are not being blocked?

Hi Helly, yes using a wildcard for Extension Install Blocklist works fine for all the add-ons / extensions but now the sidebar has appeared in a recent update, it does not prevent users adding the "Games" extension for example. As a workaround, we could look to block the sidebar entirely but thought this was worth raising.

**Comment by Y-Kelly** [comment]
@mav147 Thanks!  I'm reaching out to the team about this issue.

**Comment by Y-Kelly** [comment]
@mav147 We are working on updating the policy and will follow up once it is available.  Thanks!

**Comment by Y-Kelly** [comment]
@mav147 The policy has been updated in Microsoft Edge v110, please see the updated documentation: https://learn.microsoft.com/en-us/deployedge/microsoft-edge-sidebar#allow-specific-sidebar-apps

Let us know if you are still having issues.  Thanks!
