### ISSUE TITLE
Wrong link for opening a general Edge support case

### ISSUE THREAD

**Issue by Leonard1919** [MicrosoftDocs/Edge-Enterprise#439]
Hi,

Leonard Severt with Microsoft Support. On this page in step 6 a link is given to get help with Edge. The link is for this

https://www.microsoftedgeinsider.com/support

That is not the correct link. It should be to the general Edge page I believe.

https://support.microsoft.com/en-us/microsoft-edge

Thanks

Leonard Severt
Microsoft Support

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 33cc47c1-b277-96a1-8db2-411e3a4036e8
* Version Independent ID: d3c665a7-96f6-150f-d905-d33a7ff40a28
* Content: [Diagnose and fix Microsoft Edge sync issues](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-troubleshoot-enterprise-sync#issue-sync-is-not-available-for-this-account)
* Content Source: [edgeenterprise/microsoft-edge-troubleshoot-enterprise-sync.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-troubleshoot-enterprise-sync.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
@Leonard1919 The current link (https://www.microsoftedgeinsider.com/support) leads enterprise customers directly to their support options (Support for Business and App Assure).  

![image](https://user-images.githubusercontent.com/74324031/201794132-48f95bbe-1bca-4388-9971-7c1771c20d76.png)

Currently, there are no plans to update the link.

**Comment by Leonard1919** [comment]
Hello Kelly,

Thanks for the follow up.

Well I am with App Assure team. And this is misleading for customers.
This implies that App Assure t-shoots sync issues with Information Protection. App Assure does not support this. General browser support team does.
It also leads to Edge Beta which is not something Enterprise customers are generally using.




Respectfully Yours,

Leonard Severt
Windows Dev Support App Assure
Windows App Assure Team Technical Advisor

Charlotte, NC   AP1/3553
***@***.******@***.***>
(980)776-7298
Mon-Fri 9 AM - 6 PM.  Eastern Time

Manager: Nam Su Kang
***@***.***
