### ISSUE TITLE
how to test active and silverlight in edge by ie mode?

### ISSUE THREAD

**Issue by rayc12** [MicrosoftDocs/Edge-Enterprise#44]

**Comment by Y-Kelly** [comment]
Clean up of old issues.  This question appears to have been answered.  

If you have further questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
