### ISSUE TITLE
Edge profiles and Azure AD CA policy and Intune requirements

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/Edge-Enterprise#440]
When using latest Edge on personal/private device (any OS) and trying to sign-in and about satisfying Azure AD Conditional access policies. Edge profile sign in completed with correct work account.
please document behavior in CA policy for Edge:
1. Will Edge be shown as "compliant device" to CA policy?
2. Will Edge be under "approved client apps" in CA policy?
3. How to check in Edge if Intune App protection policies are applied? They are needed later for CA policy - require app protection policies 
4. How to use personal windows device, with Edge, to access secure work data (blocking with CA policies). Since Windows Information protection is deprecated, and Edge profiles are new thing.

These things depend on Azure AD CA policies feature and Edge feature, since docs this page should document, and provide limitations (if any)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27c87844-d7d4-22ff-92dc-49cea06e2e85
* Version Independent ID: 909054ee-53da-8d02-8347-57aeb1d96f32
* Content: [Microsoft Edge and Conditional Access](https://learn.microsoft.com/en-us/deployedge/ms-edge-security-conditional-access)
* Content Source: [edgeenterprise/ms-edge-security-conditional-access.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/ms-edge-security-conditional-access.md)
* Product: **microsoft-edge**
* GitHub Login: @srugh
* Microsoft Alias: **srugh**

**Comment by Y-Kelly** [comment]
@hkusulja Hello - A lot of the team is out of the office due to the holiday.  I know the Intune/Conditional Access team has a lot of documentation available.  Have you looked at these documents already?  https://learn.microsoft.com/en-us/mem/intune/protect/app-based-conditional-access-intune

**Comment by hkusulja** [comment]
Hello, yes, but this is more about Edge-Enterprise features.

**Comment by Y-Kelly** [comment]
@hkusulja Thanks for the feedback.  I've passed this on to the team!

**Comment by hkusulja** [comment]
@Y-Kelly why is this closed, since it is still unresolved undocumented?
