### ISSUE TITLE
WebAppInstallForceList requires browser launch

### ISSUE THREAD

**Issue by jrj2211** [MicrosoftDocs/Edge-Enterprise#441]
I wanted to leave feedback for the PWA "WebAppInstallForceList" GPO setting and how it requires a browser launch to install the PWA apps. I think this should be reconsidered as not everyone uses the same browser if at all possible. My organization uses many browsers: Chrome/Edge/Firefox/Brave depending on personal preference. Telling everyone to launch Edge once is confusing instead of it just being automatic, like I can do with any other standalone app.

I'd love to just be able to configure Web Apps in Edge for every computer, and where they launch with Edge regardless of what browser they use daily. I have yet to test what would happen if I setup GPO's for every browser to install the PWA's, but I'm guessing if they opened Chrome and then later Edge that they would get two instances of the app, that they cant uninstall either of. 

I get that this is all relatively new technology but I just wanted to voice my concern in hopes that the future provides even PWA support. Thank you.

**Comment by Y-Kelly** [comment]
@jrj2211 This topic has come up previously and it is my understanding that the policy regkey is only read once on browser launch.  I do not know if any changes to the behavior can be made but please submit your feedback/feature request through our in-browser feedback tool. It's under "..." menu > Help and feedback > Send feedback.  Thanks!
