### ISSUE TITLE
Security baselines recommendation should be linked

### ISSUE THREAD

**Issue by marshalhagen** [MicrosoftDocs/Edge-Enterprise#442]
In the section, "Why do Microsoft security baselines recommend disabling the password manager?" Please link to the recommendation. I was looking through the baselines and couldn't find any references and assume this is old. Regardless, the explanation is extremely out of context with little if any supporting information.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f651e68c-34bf-d399-88e9-c9a0928d8be4
* Version Independent ID: ad34ee59-01d3-c64d-d123-5484264190b8
* Content: [Microsoft Edge password manager security ](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-security-password-manager-security)
* Content Source: [edgeenterprise/microsoft-edge-security-password-manager-security.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-security-password-manager-security.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **v-danwesley**

**Comment by Y-Kelly** [comment]
@marshalhagen I downloaded the most recent Security Baseline for MS Edge v107 and it looks like the PasswordManagerEnabled policy is still disabled.  

![image](https://user-images.githubusercontent.com/74324031/203654909-7cf8e235-9299-43d7-8897-662332c0a641.png)

Here is the link to the announcement to the v107 Security Baseline: https://techcommunity.microsoft.com/t5/microsoft-security-baselines/security-baseline-for-microsoft-edge-v107/ba-p/3678903

You can also provide feedback directly to the team in the above blog post or through the [Security Baseline Community](https://techcommunity.microsoft.com/t5/microsoft-security-baselines/bd-p/Security-Baselines).  Thanks!
