### ISSUE TITLE
Decide which extensions to allow

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/Edge-Enterprise#446]
Hello,

Can you please help to see if there is any way to get a list of already installed extensions in the Enterprise mode?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cf796fac-09b2-f205-62d8-69ca77f9743e
* Version Independent ID: 60767e14-08a8-f3d1-0d34-2384b739bc1f
* Content: [Manage Microsoft Edge extensions in the enterprise](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-manage-extensions)
* Content Source: [edgeenterprise/microsoft-edge-manage-extensions.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-manage-extensions.md)
* Product: **microsoft-edge**
* GitHub Login: @AndreaLBarr
* Microsoft Alias: **aspoddar**

**Comment by Y-Kelly** [comment]
@lightupdifire Hello - Can you provide more details about what you are looking for?  Are you trying to audit or inventory what extensions users (managed devices) have already installed and are in use in your environment?

**Comment by lightupdifire** [comment]
@Y-Kelly 
Yes, we try to audit or inventory what extensions users (managed devices) have already installed and are in use in the environment.

**Comment by Y-Kelly** [comment]
@lightupdifire This is something the team has on the roadmap but currently no ETA.  I've passed your feedback on to the team but you can also submit your feature request through the browser ("..." menu > Help and feedback > Send feedback).  Thanks!

**Comment by joegoerlich** [comment]
@lightupdifire maybe you this new feature from the MS Defender family is what you are looking for:
https://learn.microsoft.com/en-us/microsoft-365/security/defender-vulnerability-management/tvm-browser-extensions
