### ISSUE TITLE
ExemptFileTypeDownloadWarnings Policy value "Not Set"

### ISSUE THREAD

**Issue by KamaKama22** [MicrosoftDocs/Edge-Enterprise#448]
With the release of Edge version 105, Microsoft announced the deprecation of "ExemptDomainFileTypePairsFromFileTypeDownloadWarnings" and replaced it with "ExemptFileTypeDownloadWarnings". 
 
When attempting to copy our values from the deprecated policy to the new policy, Edge fails to recognize the values.  When looking at edge://policy, the value for "ExemptFileTypeDownloadWarnings" is set to "Not set" when I clearly have the policy set to Enabled and have populated it with values.

Edge Version: 107.0.1418.62
Group Policy Template Version:  Same as above

Thanks!

**Comment by KamaKama22** [comment]
I tried rolling back to 105.0.1343.53 (both Edge and the Group Policy templates) and still have the same result.

**Comment by Y-Kelly** [comment]
@KamaKama22 Our developer recently tested this policy and did not encounter this issue.  

One thing to check is if there are any syntax errors or any possible typos.  

If you are still having issues, you can reach out to Support (https://developer.microsoft.com/en-us/microsoft-edge/support/). They should be able to work with you directly and gather the diagnostic data to help investigate your specific case.

**Comment by KamaKama22** [comment]
Thank you @Y-Kelly , it ended up being a syntax issue!  In case anybody else has this issue and finds this thread you MUST include the [ and ] in the new Group Policy.

Example:  [  { "file_extension": "jnlp", "domains": ["somewebsite.com"] }  ]

**Comment by Y-Kelly** [comment]
@KamaKama22 Great to hear it is working!  Thank you for following up for anyone else that runs into the same issue!
