### ISSUE TITLE
external protocol dialog show always open checkbox

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/Edge-Enterprise#45]
Every time I open a Teams link I get a prompt to ask if I want to allow that website to open the app. I want it to remember my preference but that option isn't there. The docs say "If this policy is unset, the checkbox visibility is controlled by the "Enable remembering protocol launch prompting preferences" flag in edge://flags" but there is no such flag. I'm using Version 81.0.416.34 (Official build) beta (64-bit)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1cd3ad5-bb4a-54ff-84e7-18ca0b11368f
* Version Independent ID: 984abd8f-45eb-737b-ad74-07ec8261f9eb
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#see-also)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
Clean up of old issues.  The ExternalProtocolDialogShowAlwaysOpenCheckbox policy documentation was updated in v84.

![image](https://user-images.githubusercontent.com/74324031/181105925-e404456c-b74c-458f-909e-194e5fe78342.png)
