### ISSUE TITLE
Default print scaling

### ISSUE THREAD

**Issue by gkemperle** [MicrosoftDocs/Edge-Enterprise#453]
I'm missing a policy, that will allow to set the default print scaling. By default it always reverts to "Fit to printable area", and I would like to have it on "Actual Size".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#printingpapersizedefault)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@gkemperle Hello - It looks like this is on the team's roadmap but there is no ETA.  They previously released the [PrintStickySettings](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-policies#printstickysettings) policy and should be working on a 2nd policy for scaling settings.  

I have passed on your feedback to them.  If you haven't yet, you also submit feature requests through our in-browser feedback tool.  It's under "..." menu > Help and feedback > Send feedback.

**Comment by Y-Kelly** [comment]
@gkemperle In v110 the [PrintPreviewStickySettings](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#printpreviewstickysettings) policy was added.  Please take a look and see if this can help your scenario.  Thanks!
