### ISSUE TITLE
https://awmyusuf90.wordpress.com/google/home/

### ISSUE THREAD

**Issue by rwzwehhegmww** [MicrosoftDocs/Edge-Enterprise#454]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ef940b0a-15db-d815-f10f-205cbe3c403a
* Version Independent ID: 855d4eed-6071-662b-522e-e85250358938
* Content: [Microsoft Edge security for your business](https://learn.microsoft.com/en-us/deployedge/ms-edge-security-for-business?source=recommendations)
* Content Source: [edgeenterprise/ms-edge-security-for-business.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/ms-edge-security-for-business.md)
* Product: **microsoft-edge**
* GitHub Login: @seanongit
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
@rwzwehhegmww Hello - If you would like to report a Microsoft Edge Enterprise documentation issue to the team please open a new issue and include relevant information/repro steps in the Comment section.

If you have general questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsiderForum) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
