### ISSUE TITLE
RestoreOnStartupUserURLsEnabled not working on macOS

### ISSUE THREAD

**Issue by kcorrea-ncc** [MicrosoftDocs/Edge-Enterprise#459]
I am encountering the same problem as issue #444 

**RestoreOnStartupUserURLsEnabled** (boolean) policy on macOS does not allow users to add additional startup pages, despite [documentation](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#restoreonstartupuserurlsenabled) stating so.

All 3 related policies are enabled/configured:
- RestoreOnStartup = (4) Open a list of URLs
- RestoreOnStartupURLs = Specified a list of websites
- RestoreOnStartupUserURLsEnabled = True

These Edge policies are being deployed via Configuration Profile created in our MDM solution (Jamf) and deployed to the clients.

The browser shows the policies are mandatory and status OK - but the "add a new page" button is locked/greyed out.

<img width="1178" alt="edge-policies" src="https://user-images.githubusercontent.com/121965147/210613333-e9ccddfa-f6f8-4589-a9b1-4c90a197896f.png">
<img width="890" alt="edge-startup-settings" src="https://user-images.githubusercontent.com/121965147/210613335-8d74e5f8-68d3-46be-9160-220bfa1aa618.png">

### System tested:
macOS 13.1 (Ventura)
edge Version 108.0.1462.54 (Official build) (x86_64)
I also tested edge Canary Version 110.0.1572.0 (Official build) Canary (x86_64)

_Side note: This same configuration does work as expected on the Windows side, via Group Policy._

**Comment by Y-Kelly** [comment]
@kcorrea-ncc Thanks for the feedback!  I reached out to our developer and currently the policy is not available for macOS.  We plan to turn on this policy for macOS in Microsoft Edge 110.  Apologies with any confusion in our documentation.

**Comment by Y-Kelly** [comment]
@kcorrea-ncc Quick update from our developer, we unfortunately were not able to get the fix into Microsoft Edge 110.  The policy should be updated in version 111.  Thanks!
