### ISSUE TITLE
Registry Settings Options

### ISSUE THREAD

**Issue by zastrowm** [MicrosoftDocs/Edge-Enterprise#46]
Is there a registry source for these policies?  Chrome, for example, documents its @ https://www.chromium.org/administrators/policy-list-3#ExtensionInstallWhitelist ;  I attempted to use the same via `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\ExtensionInstallWhitelist` (and corresponding ExtensionInstallSources), but I still get this error attempting to install the extension:

> This extension is not from any known source, and may have been added without your knowledge.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1cd3ad5-bb4a-54ff-84e7-18ca0b11368f
* Version Independent ID: 984abd8f-45eb-737b-ad74-07ec8261f9eb
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#feedback)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by AdamSharif-MSFT** [comment]
Hello @zastrowm 
I was having the same issue, it seems that for Edge contrary to the documentation, you need to have the value in both ExtensionInstallWhitelist and ExtensionInstallAllowList

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\ExtensionInstallWhitelist]
"1"="myvalue"
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\ExtensionInstallAllowlist]
"1"="myvalue"

With these keys I was able to get my extension to work.

**Comment by darthShadow** [comment]
Has this changed recently? Setting both or either of those keys doesn't seem to be working (i.e. allowing the extension) on a Mac even though the `edge://policy` page reflects the policy changes.

**Comment by ashishnirvana1** [comment]
> Hello @zastrowm
> I was having the same issue, it seems that for Edge contrary to the documentation, you need to have the value in both ExtensionInstallWhitelist and ExtensionInstallAllowList
> 
> Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\ExtensionInstallWhitelist]
> "1"="myvalue"
> [HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\ExtensionInstallAllowlist]
> "1"="myvalue"
> 
> With these keys I was able to get my extension to work.

It should work with just one policy ExtensionInstallAllowlist - as that has been the only one used in Microsoft Edge since inception. Can you try using only this policy and confirm?

**Comment by IMNdi** [comment]
Edge says the settings are "in error" but has allowed me to go with ExtensionInstallForcelist

See https://i.imgur.com/YrwEmiC.png - The old ones are listed as error but the ForceList is up and running; The registry key is ExtensionInstallForcelist (REG_SZ 1 = <id>)

**Comment by ashishnirvana1** [comment]
Hi All, if you are still facing an issue setting up ExtensionInstallAllowList policy pls share a screenshot of the edge://policy page. Make sure you expand the Error details so that the error is visible.

**Comment by thelaughingwolf** [comment]
I was able to use `ExtensionInstallAllowlist`, although it didn't seem to take at first. I had to also reload policies from `edge://policy` and hard refresh `edge://extensions`, and then the warning disappeared.

**Comment by Y-Kelly** [comment]
Clean up of old issues.  Appears the question was previously answered.  

If you have general questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsiderForum) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!

**Comment by nhan000** [comment]
Hi, I have the same problem but for Edge Dev. Could someone point out what the registry key for Edge Dev is? Thanks so much!
