### ISSUE TITLE
Missing documentation about "Microsoft Edge and Conditional Access" policies

### ISSUE THREAD

**Issue by kathodion** [MicrosoftDocs/Edge-Enterprise#461]
Missing documentation about "Microsoft Edge and Conditional Access" policies. Where can I configure this tenant behaviour? Is that part of a conditional access rule? Is there a general setting to set this up?

Please add more information. It only says what is happening, but I want to know how to configure it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27c87844-d7d4-22ff-92dc-49cea06e2e85
* Version Independent ID: 909054ee-53da-8d02-8347-57aeb1d96f32
* Content: [Microsoft Edge and Conditional Access](https://learn.microsoft.com/en-us/deployedge/ms-edge-security-conditional-access#accessing-conditional-access-protected-resources-in-microsoft-edge)
* Content Source: [edgeenterprise/ms-edge-security-conditional-access.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/ms-edge-security-conditional-access.md)
* Product: **microsoft-edge**
* GitHub Login: @srugh
* Microsoft Alias: **srugh**

**Comment by Y-Kelly** [comment]
@kathodion Details about set-up and deployment of Conditional Access can be found under the Conditional Access team documentation, which is linked here: https://learn.microsoft.com/en-us/deployedge/ms-edge-security-conditional-access#how-to-deploy-conditional-access-in-azure-active-directory

**Comment by kathodion** [comment]
> @kathodion Details about set-up and deployment of Conditional Access can be found under the Conditional Access team documentation, which is linked here: https://learn.microsoft.com/en-us/deployedge/ms-edge-security-conditional-access#how-to-deploy-conditional-access-in-azure-active-directory

@Y-Kelly thank you, but this was different from what I was looking for. Could you give me more details about this specific rule Edge CA rule? I need help finding resources that explain how this Edge enforcement can be set up.

Could you lead me to that information or explain it, please?
