### ISSUE TITLE
Missing documentation about "Microsoft Edge enforcement with Conditional Access" policies

### ISSUE THREAD

**Issue by kathodion** [MicrosoftDocs/Edge-Enterprise#462]
regarding this issue: https://github.com/MicrosoftDocs/Edge-Enterprise/issues/461

@Y-Kelly thank you, but this was different from what I was looking for. Could you give me more details about this specific rule Edge CA rule? I need help finding resources that explain how this Edge enforcement can be set up.

Could you lead me to that information or explain it, please?

Document Details
⚠ Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.

ID: 27c87844-d7d4-22ff-92dc-49cea06e2e85
Version Independent ID: 909054ee-53da-8d02-8347-57aeb1d96f32
Content: [Microsoft Edge and Conditional Access](https://learn.microsoft.com/en-us/deployedge/ms-edge-security-conditional-access#accessing-conditional-access-protected-resources-in-microsoft-edge)
Content Source: [edgeenterprise/ms-edge-security-conditional-access.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/ms-edge-security-conditional-access.md)
Product: microsoft-edge
GitHub Login: @srugh
Microsoft Alias: srugh

**Comment by Y-Kelly** [comment]
@kathodion Do you mean Conditional Access: Conditions, which lists Microsoft Edge has a supported browser? https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-conditions#supported-browsers

If you are still having issues, you can reach out to Support for Business (https://developer.microsoft.com/en-us/microsoft-edge/support/) and they can help your specific scenario.  Thanks!

**Comment by kathodion** [comment]
> @kathodion Do you mean Conditional Access: Conditions, which lists Microsoft Edge has a supported browser? https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-conditions#supported-browsers
> 
> If you are still having issues, you can reach out to Support for Business (https://developer.microsoft.com/en-us/microsoft-edge/support/) and they can help your specific scenario. Thanks!

not what I was looking for :(, thanks. I will raise a ticket with MS premier support
