### ISSUE TITLE
Information missing for "Remove Desktop Shortcuts upon update default" Policy

### ISSUE THREAD

**Issue by DesertBear** [MicrosoftDocs/Edge-Enterprise#463]
**GP path:**
Administrative Templates/Microsoft Edge Update/Applications

For the above Group Policy path, this documentation only includes information regarding the below two Desktop Shortcut policies.

**GP name:**
```
Prevent Desktop Shortcut creation upon install default
```
```
Prevent Desktop Shortcut creation upon install
```

It is however missing any information regarding the below policy.

**GP name:**
```
Remove Desktop Shortcuts upon update default
```

![Edge GPO](https://user-images.githubusercontent.com/27423064/214028910-eb0e417d-a57a-4594-b3a8-26c41fc54352.png)

-----
Microsoft Edge 109.0.1518.61 (Official build) (64-bit)
Windows 10 Version 22H2 (Build 19045.2486)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 96fddabd-2bac-2fab-a5ea-25c000b425fc
* Version Independent ID: 41bba38e-bd24-0496-da04-012d6deb5db8
* Content: [Microsoft Edge Update Policy Documentation](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-update-policies#createdesktopshortcutdefault)
* Content Source: [edgeenterprise/microsoft-edge-update-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-update-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@DesertBear I'm checking with the team!  We will follow up with any updates.  Thanks!

**Comment by Y-Kelly** [comment]
@DesertBear The documentation has been updated and the policy has been added.  https://learn.microsoft.com/en-us/deployedge/microsoft-edge-update-policies#removedesktopshortcutdefault

Thanks!
