### ISSUE TITLE
110.0.1587.17 Crashing/Closing around every 10 minutes

### ISSUE THREAD

**Issue by Smiley1244** [MicrosoftDocs/Edge-Enterprise#464]
Edge Beta 110.0.1587.17
Please see following thread, reportedly something to do with a telemetry feed. Seems to be affecting all OSs.

[https://techcommunity.microsoft.com/t5/discussions/edge-beta-crashing-as-of-jan-20-2023-after-update-i-guess/m-p/3721884](url)

**Comment by Y-Kelly** [comment]
@Smiley1244 Thanks, please see latest update from Eric Lawrence in the thread: https://techcommunity.microsoft.com/t5/discussions/edge-beta-crashing-as-of-jan-20-2023-after-update-i-guess/m-p/3722838/highlight/true#M56978

![image](https://user-images.githubusercontent.com/74324031/214104060-70b40878-e418-4320-87dd-b4a52c768fb3.png)
