### ISSUE TITLE
ExemptFileTypeDownloadWarnings policy value not displaying correctly

### ISSUE THREAD

**Issue by MDawg957** [MicrosoftDocs/Edge-Enterprise#466]
I'm setting "ExemptFileTypeDownloadWarnings" per the formatting and it looks like it is working, but when I check in edge://policy/ the policy value shows as "[object Object]" and I am unsure if this is correct. Under the old "ExemptDomainFileTypePairsFromFileTypeDownloadWarnings" policy, it would display your string, but this one doesn't seem to do that. Is there an issue with my syntax?

Example: [ { "file_extension": "jnlp", "domains": ["example.com"] } ]
Edge version: 109.0.1518.55 (Official build) (64-bit) , stable channel

Using the latest policy template, so everything should be current.

**Comment by Y-Kelly** [comment]
@MDawg957 If there is no PII, would you be able to provide a screenshot of edge://policy showing that message for the ExemptFileTypeDownloadWarnings policy?  Thanks!

**Comment by MDawg957** [comment]
@Y-Kelly Requested screen with unnecessary items blacked out.

![image](https://user-images.githubusercontent.com/12445509/214112480-fa8440c3-de8a-4426-b86e-c0013b99b30b.png)

**Comment by Y-Kelly** [comment]
@MDawg957 Thanks!  I have confirmed this is a known issue and the team is working on the fix.  In case you notice, there are other policies that are affected.  I'll follow up with any updates from the team.

**Comment by Soljanka** [comment]
I can confirm that at least AutoLaunchProtocolsFromOrigins is also affected
![grafik](https://user-images.githubusercontent.com/7444116/214600952-e448efd4-d4a5-4b0f-87c4-2926a7d77f29.png)

**Comment by Y-Kelly** [comment]
@MDawg957 @Soljanka The fix has been released to the Microsoft Edge Canary Channel v111.0.1641.0+.  The team is still discussing backporting the change to the Stable and Beta Channels.

**Comment by Y-Kelly** [comment]
@Soljanka @MDawg957 The team has backported the fix to v110 and v109.  Each should be updated in the next week.  Let us know if you are still having issues after updating.  Thanks!
