### ISSUE TITLE
IntensiveWakeUpThrottlingEnabled must be under domain control

### ISSUE THREAD

**Issue by so-nkbys** [MicrosoftDocs/Edge-Enterprise#468]
IntensiveWakeUpThrottlingEnabled The policy must be under domain control to work, but there is no mention of it.

**Comment by Y-Kelly** [comment]
@so-nkbys Can you provide more information?  Are you referring to the Policy Documentation?  https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#intensivewakeupthrottlingenabled

There are some other policies with this messaging.  Is this what you mean by domain control? 
![image](https://user-images.githubusercontent.com/74324031/214644983-840cadc4-071f-4ff8-85d4-0ec81f98ca08.png)

**Comment by so-nkbys** [comment]
Sorry for the delay in replying.

> Are you referring to the Policy Documentation? https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#intensivewakeupthrottlingenabled
Yes, this issue is about policy documentation.

> Is this what you mean by domain control?
Yes.  I have received a response from alias "yuhara" (SR Escal Engineer) that domain participation is required for this policy to work.

My alias is snakabayashi, please IM me on Teams if you need anything.

**Comment by Y-Kelly** [comment]
Closing and taking this discussion offline.
