### ISSUE TITLE
This page is out of date AIP doesn't exist anymore

### ISSUE THREAD

**Issue by shadcollins** [MicrosoftDocs/Edge-Enterprise#469]
Sync is not working for a new E3 license. It says AIP is required but if you go to AIP on Azure is says it is a deprecated product.
No idea how to get Edge Sync working for E3 licenses.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1fa7eda4-6e4c-c2c8-a29a-ef2eead7f04f
* Version Independent ID: 414db256-c14b-ca11-b2a7-835aa9c9e041
* Content: [Configure Microsoft Edge enterprise sync](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-enterprise-sync)
* Content Source: [edgeenterprise/microsoft-edge-enterprise-sync.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-enterprise-sync.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
@shadcollins Hello!  My understanding is the AIP service is not in maintenance mode, it is the AIP client that is in maintenance mode.  Instructions to activate AIP can be found here: https://learn.microsoft.com/en-us/azure/information-protection/activate-service

I also double checked that Office 365 E3 includes AIP.  Screenshot from https://www.microsoft.com/en-us/microsoft-365/enterprise/compare-office-365-plans

![image](https://user-images.githubusercontent.com/74324031/215548561-348dac78-9fff-48ef-94aa-ade53ef8af84.png)

If you are continuing to have issues, the AIP team provides the following Microsoft Support options: https://learn.microsoft.com/en-us/azure/information-protection/information-support#support-options-and-community-resources
