### ISSUE TITLE
Precedence over BlockExternalExtensions

### ISSUE THREAD

**Issue by joegoerlich** [MicrosoftDocs/Edge-Enterprise#473]
In the "Before you begin" section it is not listed whether the ExtensionSettings overwrites also the BlockExternalExtensions policy. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06f0b77d-8fc4-90c1-93cb-e781352efdf2
* Version Independent ID: 2a21fd70-443b-8ac1-4541-d5b6bf882881
* Content: [Detailed guide to the ExtensionSettings policy](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-manage-extensions-ref-guide)
* Content Source: [edgeenterprise/microsoft-edge-manage-extensions-ref-guide.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-manage-extensions-ref-guide.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **aspoddar**

**Comment by Y-Kelly** [comment]
@joegoerlich The Extension Team has reviewed your 4 GitHub issues and this should apply to all of them: 

The policy "BlockExternalExtensions" applies to extension installations that happen from third party software applications and they do not have any impact on the policies that are defined in extension settings. Any policy definitions from the extension settings will always take precedence over "BlockExternalExtensions".

For further questions, you should be able to reach the Extension Team at https://github.com/microsoft/MicrosoftEdge-Extensions
