### ISSUE TITLE
Precedence over BlockExternalExtensions

### ISSUE THREAD

**Issue by joegoerlich** [MicrosoftDocs/Edge-Enterprise#475]
In the "Force-install an extension" and "Block extensions from a specific store or update URL" section it is not clear whether both take precendance over the BlockExternalExtensions policy. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cc77d006-bbf3-747e-4d7c-573e57680174
* Version Independent ID: b9ed5785-c4a5-19b6-fbd7-1a3d30027f08
* Content: [Use group policies to manage Microsoft Edge extensions](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-manage-extensions-policies)
* Content Source: [edgeenterprise/microsoft-edge-manage-extensions-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-manage-extensions-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @AndreaLBarr
* Microsoft Alias: **aspoddar**

**Comment by Y-Kelly** [comment]
@joegoerlich The Extension Team has reviewed your 4 GitHub issues and this should apply to all of them:

The policy "BlockExternalExtensions" applies to extension installations that happen from third party software applications and they do not have any impact on the policies that are defined in extension settings. Any policy definitions from the extension settings will always take precedence over "BlockExternalExtensions".

For further questions, you should be able to reach the Extension Team at https://github.com/microsoft/MicrosoftEdge-Extensions
