### ISSUE TITLE
Is the BlockExternalExtensions considered as legacy policy

### ISSUE THREAD

**Issue by joegoerlich** [MicrosoftDocs/Edge-Enterprise#476]
For the ExtensionSettings policy it is not clear which policies are meant with "This policy supersedes any legacy policies that might be set." 
In particular, the BlockExternalExtensions policy was added in v88 after the ExtensionSettings policy (v77). Is the BlockExternalExtensions considered as legacy policy?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#blockexternalextensions)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@joegoerlich The Extension Team has reviewed your 4 GitHub issues and this should apply to all of them:

The policy "BlockExternalExtensions" applies to extension installations that happen from third party software applications and they do not have any impact on the policies that are defined in extension settings. Any policy definitions from the extension settings will always take precedence over "BlockExternalExtensions".

For further questions, you should be able to reach the Extension Team at https://github.com/microsoft/MicrosoftEdge-Extensions
