### ISSUE TITLE
Path to setting incorrect

### ISSUE THREAD

**Issue by danwclark** [MicrosoftDocs/Edge-Enterprise#477]
Path to the "Configure favorites" setting is listed as:

`

> "Open the Group Policy Editor, navigate to Computer Configuration/Administrative Templates/ and pick Configure Favorites."

`

Should be Computer Configuration > Administrative Templates > Microsoft Edge > Configure Favorites

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c3415ed3-5ccf-198d-cee7-2dbbfe4b0959
* Version Independent ID: f1e17aeb-6ab5-3db2-80ac-c16514f80cf6
* Content: [Provision favorites for Microsoft Edge](https://learn.microsoft.com/en-us/deployedge/edge-learnmore-provision-favorites)
* Content Source: [edgeenterprise/edge-learnmore-provision-favorites.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-provision-favorites.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **capoon**

**Comment by Y-Kelly** [comment]
@danwclark We are updating the documentation with the fix, you should see it shortly.  Thanks for the feedback!
