### ISSUE TITLE
Outlook for Desktop

### ISSUE THREAD

**Issue by moshikonachmias** [MicrosoftDocs/Edge-Enterprise#479]
Hi,
I have a question re the browsers used by Office Add-ins,
[This article](https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins#wip-protected-documents) states that Volume-licensed, Office 2016 is using Internet Explorer 11 in order to run Add-ins.
Is it still the case after Internet Explorer 11 will be permanently disabled?

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90451dc6-e4b1-9973-2309-5399e9a63496
* Version Independent ID: ce664b18-ab7e-604a-c475-55ce86b15284
* Content: [Redirection from Internet Explorer to Microsoft Edge for compatibility with modern web sites](https://learn.microsoft.com/en-us/deployedge/edge-learnmore-neededge)
* Content Source: [edgeenterprise/edge-learnmore-neededge.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-neededge.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **laannade**

**Comment by Y-Kelly** [comment]
@moshikonachmias Hello - Just to clarify, you've linked to the WIP - protected documents section (https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins#wip-protected-documents), which only mentions Microsoft Edge Legacy and not IE11.  

I think this question would be more appropriate for the OfficeDev team.  Their GitHub issues are here: https://github.com/OfficeDev/office-js-docs-pr/issues or you can click on the feedback for "This page" button at the bottom of the article you are referencing.  (https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)

![image](https://user-images.githubusercontent.com/74324031/218824564-2c804147-c21c-4ea2-962e-6741322a149f.png)
