### ISSUE TITLE
Update classifications

### ISSUE THREAD

**Issue by CaptainUnlikely** [MicrosoftDocs/Edge-Enterprise#48]
I think this page should detail the classification of update for each one - for example, whether it's under "Updates", "Critical Updates", "Security Updates" in WSUS/Update Catalog.  At the minute all Edge updates seem to be classified as Updates which is non-ideal if they are in fact security updates, appreciate that's not an issue for documentation feedback but there isn't an appropriate category in the Feedback Hub which seems to be the only way to provide product feedback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76912f35-f62c-bd99-60fb-b11d3d40ba04
* Version Independent ID: 01fba630-3a9a-6a9e-2d24-a6a47b8e6926
* Content: [Release notes for Microsoft Edge Security Updates](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnotes-security#feedback)
* Content Source: [edgeenterprise/microsoft-edge-relnotes-security.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-relnotes-security.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **aguta**

**Comment by Y-Kelly** [comment]
Clean up of old issues.  Understand this is not a documentation issue.  I'm not sure if this would be for the WSUS/Update Catalog team or MS Edge team to make modifications.  Have you submit feedback through the browser? ("..." menu > Help and feedback > Send feedback)?  Another option is to reach out to [Support - Microsoft Edge Developer](https://developer.microsoft.com/en-us/microsoft-edge/support/) to help route.
