### ISSUE TITLE
Missing "Import" feature for Edge Site Lists

### ISSUE THREAD

**Issue by JLambEJG** [MicrosoftDocs/Edge-Enterprise#481]
The instructions state to select the list, then on the resulting page, select "Import list". However, there is no "Import list" button on the resulting page. See screen shot. Please correct the instructions.

![image](https://user-images.githubusercontent.com/57106905/219462473-2b25c64d-76cd-46e8-9d80-f23414bf8903.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a1a4c286-c376-c1aa-86d8-80a842861435
* Version Independent ID: a1a4c286-c376-c1aa-86d8-80a842861435
* Content: [Cloud Site List Management for Internet Explorer (IE) mode'](https://learn.microsoft.com/en-us/deployedge/edge-ie-mode-cloud-site-list-mgmt)
* Content Source: [edgeenterprise/edge-ie-mode-cloud-site-list-mgmt.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode-cloud-site-list-mgmt.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **shisub**

**Comment by Y-Kelly** [comment]
@JLambEJG Hi - I just checked with the team and they said to select the site list by clicking on the checkmark box and then the command bar will show the import option. 

Here is a screenshot: 

![image](https://user-images.githubusercontent.com/74324031/219503602-297bafba-db58-4ef5-9a1c-9fb9abb34eb0.png)

Thanks!
