### ISSUE TITLE
Code samples are title "Windows Command Prompt" instead of Terminal

### ISSUE THREAD

**Issue by cchambers-cap** [MicrosoftDocs/Edge-Enterprise#483]
This is a little detail, but it confused me for a second as to why I'd be using CMD to configure Mac settings, so I thought I'd mention it. Doesn't appear to be something I can edit on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 49b8ce2e-bda2-4835-d535-ec018117b668
* Version Independent ID: ccba60e4-da58-4ed9-b5a7-de5dce2a711f
* Content: [Configure Microsoft Edge for macOS using a property list.](https://learn.microsoft.com/en-us/deployedge/configure-microsoft-edge-on-mac)
* Content Source: [edgeenterprise/configure-microsoft-edge-on-mac.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/configure-microsoft-edge-on-mac.md)
* Product: **microsoft-edge**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **brianalt**

**Comment by Y-Kelly** [comment]
@cchambers-cap Thanks for the feedback!  We are working to update the documentation, which you should be able to see shortly.
