### ISSUE TITLE
Blocker toolkit still available?

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/Edge-Enterprise#484]
"Note: A user can block the automatic update of Microsoft Edge (Chromium-based) by using the Microsoft Edge (Chromium-based) Blocker Toolkit."

Does this still exist?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 96fddabd-2bac-2fab-a5ea-25c000b425fc
* Version Independent ID: 41bba38e-bd24-0496-da04-012d6deb5db8
* Content: [Microsoft Edge Update Policy Documentation](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-update-policies)
* Content Source: [edgeenterprise/microsoft-edge-update-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-update-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@BR77BE It appears the Blocker Toolkit is no longer available.  Support for Microsoft Edge Legacy ended on March 9, 2021.  Can you share your scenario that needs to use the Blocker Toolkit?  

I will reach out to the team about updating the documentation.
