### ISSUE TITLE
Edge Beta crashes on http urls due to AutomaticHttpsDefault policy

### ISSUE THREAD

**Issue by Florin-Anghel** [MicrosoftDocs/Edge-Enterprise#485]
Any http:// url crashes on Edge Beta. This has been identified as being triggered by the AutomaticHttpsDefault policy.
If the registry value AutomaticHttpsDefault under HLKM\Software\Policies\Microsoft\Edge is set to 0, you can navigate to any http:// url , if the registry value AutomaticHttpsDefault is set to 1 or 2, Edge Beta crashes while navigating to any http:// url.

Might this be related to the note added to the AutomaticHttpsDefault policy "Starting in Microsoft Edge 111, "UpgradePossibleDomains" is deprecated and is treated the same as "DisableAutomaticHttps". It won't work in Microsoft Edge version 114."

We have encountered this issue with Edge Beta on major version 111.
Normal Edge (extended stable channel release) works as expected with the policy setting set to 1 or 2.

**Comment by Y-Kelly** [comment]
@Florin-Anghel Thanks for the feedback!  I've reached out to the team and they are working on a fix for this.  I'll follow up with updates from them.

**Comment by Y-Kelly** [comment]
@Florin-Anghel The fix should be included in Beta 111.0.1661.30 which was released March 3, 2023.  After updating please let us know if you are still having issues.  Thanks!
