### ISSUE TITLE
About On-Premise sync support scenarios.

### ISSUE THREAD

**Issue by so-nkbys** [MicrosoftDocs/Edge-Enterprise#486]
We received a request of change about On-Premise sync documentations.

Specifically, the customer states, "We should note that we do not support any scenarios other than those that explicitly use profile.pb because it is misleading to think that a "roaming "user data" folder that holds data for a profile" is feasible.
The customer's rationale for stating this is based on the following two points.

・ Document of "On-premises sync for Active Directory (AD) users" (https://learn.microsoft.com/en-us/deployedge/microsoft-edge-on-premises-sync) does not include the statement "Do not roam the "user data" folder that holds profile data".
・ The variable "roaming_app_data" must exist in document of "Create Microsoft Edge user user data directory variables" (https://learn.microsoft.com/en-us/deployedge/edge-learnmore-create-user-directory-vars) .

Is it possible to fulfill this request?
For further information, please contact alias snakabayashi and he will be able to explain.

Regards.

**Comment by Y-Kelly** [comment]
Can you provide more information about the update suggested to https://learn.microsoft.com/en-us/deployedge/microsoft-edge-on-premises-sync?

Also, in https://learn.microsoft.com/en-us/deployedge/edge-learnmore-create-user-directory-vars I see "roaming_app_data mentioned.  

![image](https://user-images.githubusercontent.com/74324031/222524275-0270647c-35a5-44e3-a5f5-88f05aba3f05.png)

**Comment by so-nkbys** [comment]
> Can you provide more information about the update suggested to https://learn.microsoft.com/en-us/deployedge/microsoft-edge-on-premises-sync?
It would be appropriate to add "NOTE" to "How it works (https://learn.microsoft.com/en-us/deployedge/microsoft-edge-on-premises-sync#how-it-works) " with the following content

====================

> [!NOTE]
> For On-premises sync only supported scenario is syncing using profile.pb, Roaming files and folders other than profile.pb is unsupported as may cause performance problems and unexpected behavior.

====================

**Comment by so-nkbys** [comment]
> Also, in https://learn.microsoft.com/en-us/deployedge/edge-learnmore-create-user-directory-vars I see "roaming_app_data mentioned.

Yes, as you are aware, "roaming_app_data" is described in the document "Variables Documentation".

However, it is not a supported scenario to specify the Microsoft Edge user data profile folder (%USERPROFILE%\AppData\Local\Microsoft\Edge\User Data) for "roaming_app_data".
The only folder that may be specified for this folder is the folder containing profile.pb (see : On-premises sync for Active Directory (AD) users : https://learn.microsoft.com/en-us/deployedge/microsoft-edge-on-premises-sync).

Nevertheless, it has been pointed out that this is not mentioned in "roaming_app_data", thus misinterpreting the scope of the supported scenarios.

**Comment by Y-Kelly** [comment]
@so-nkbys Closing this as the conversation is continuing offline.
