### ISSUE TITLE
Work/School Microsoft 365 account cannot be signed out of the browser

### ISSUE THREAD

**Issue by SmithingJon** [MicrosoftDocs/Edge-Enterprise#487]
On stock Microsoft Edge, After signing out of Microsoft Edge and/or deleting the profile, the user is still listed in the profile dropdown and can be re-signed into any existing profile with one click. 

To reproduce: 

- Sign into browser with work/school account with sync enabled
- Sign out of profile
- User's browsing data is removed
- click profile icon
- user can be signed in again with one click
- clear browsing data
- user can still be signed in
- delete profile
- user can still be signed in

<img width="294" alt="image (1)" src="https://user-images.githubusercontent.com/81338645/222765881-2025609c-fa02-40fe-a76b-0c3001800b08.png">

No sign-ins exist in "access work or school" or "Email and accounts"

OS is Windows 11 22H2 with a local user account.

Browser version is Edge 110.0.1587.63.

**Comment by Y-Kelly** [comment]
@SmithingJon Are you deleting the profile like this?  

![image](https://user-images.githubusercontent.com/74324031/222787997-487fcc07-d21c-4d16-803a-b4552886e41a.png)

I'm currently not able to reproduce.  It would be best if you reach out to Support for Business (https://developer.microsoft.com/en-us/microsoft-edge/support/).  They should be able to gather logs and other diagnostic data to help investigate your specific case.

**Comment by SmithingJon** [comment]
I am deleting the profile that way.
