### ISSUE TITLE
Blocking Apps

### ISSUE THREAD

**Issue by JasonNVSD** [MicrosoftDocs/Edge-Enterprise#489]
WebAppInstallForceList was added in version 80, and updated in 90 and 107.  There aren't any other "WebApp" policies.

ExtensionInstallForcelist says "Set this policy to specify a list of **apps** and extensions that install silently" and "This policy supercedes ExtensionInstallBlocklist".  ExtensionInstallBlocklist doesn't mention "apps".  I tried adding an app's extension ID to ExtensionInstallBlocklist but it had no effect on the app.

Is there policy for blocking specific apps?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@JasonNVSD It looks like this is a feature in the backlog but we do not have an ETA.  I've passed on your request, but you can also submit the feature request through our in-browser feedback tool.  It's under "..." menu > Help and feedback > Send feedback.
