### ISSUE TITLE
Configure for SharePoint Online create new list from an Excel spreadsheet

### ISSUE THREAD

**Issue by CraigHumphrey** [MicrosoftDocs/Edge-Enterprise#49]
How can I configure this, so that it will detect when a user is trying to create a new list, in SharePoint Online, based on an Excel spreadsheet?  This process uses an ActiveX control and isn't a whole site, it's parameterised URL.

This possibly applies to SP on-prem too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aae869a8-2ae4-d28f-6c85-c1190609f87b
* Version Independent ID: e2bcb1d6-27f7-5e30-ae6b-7acb5ee94098
* Content: [Use Microsoft Edge with IE mode](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode)
* Content Source: [edgeenterprise/edge-ie-mode.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/edge-ie-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by Y-Kelly** [comment]
Clean up of old issues.

It sounds like your question is about IE mode, if you are still having a problem, you can get detailed guidance on how to set up Internet Explorer mode through our [Getting Started guide](https://aka.ms/IEModeGuide) or by visiting our [IE mode documentation](https://docs.microsoft.com/deployedge/edge-ie-mode). Also, you can contact App Assure at https://aka.ms/AppAssure for assistance.
