### ISSUE TITLE
Unhide how?

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/Edge-Enterprise#492]
"The Edge Sidebar can be hidden when a user isn't using it and it only reappears when a user needs it."
 
I need it!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ffcaf54-ce86-1b30-e947-540bf07a54c3
* Version Independent ID: 81267e97-e284-ff00-b081-476934538326
* Content: [Microsoft Edge release notes for Stable Channel](https://learn.microsoft.com/en-us/DeployEdge/microsoft-edge-relnote-stable-channel)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
@BR77BE If you want the sidebar to always be shown, you can turn on this toggle in edge://settings/sidebar.  

![image](https://user-images.githubusercontent.com/74324031/225084521-c9fafb97-c49f-4c6f-8210-4c1f4e58c1cb.png)

**Comment by BR77BE** [comment]
> @BR77BE If you want the sidebar to always be shown, you can turn on this toggle in edge://settings/sidebar.

No, I want the documentation to tell me **how to unhide** "the new Auto-Hide functionality" so that "**it only reappears when a user needs it.**"

**Comment by Y-Kelly** [comment]
@BR77BE If you do not have the setting to "Always show sidebar" as enabled, users can open the Sidebar by hovering on the Bing icon in the Toolbar. 

![image](https://user-images.githubusercontent.com/74324031/225373949-6f41db54-4fd9-43ea-9703-564d1cf8c8db.png)

**Comment by BR77BE** [comment]
@Y-Kelly
But to unhide it really takes a click on the Bing icon rather than a hover.

Where should users go to learn how to use these new features if not these release notes?

"What's new ..." from the Edge help menu never includes what's new.
