### ISSUE TITLE
End session button on fullscreen Kiosk

### ISSUE THREAD

**Issue by Eduardo1977** [MicrosoftDocs/Edge-Enterprise#494]
For Edge Kiosk mode Digital/Interactive signage (type=fullscreen) by default is not abled 'End session button'.
Is it possible to show 'End session button' in fullscreen mode ? Maybe, by settings in windows registers ? 
Thank you

**Comment by Y-Kelly** [comment]
@Eduardo1977 It looks like this is not currently supported.  I do see it on the roadmap but there is no ETA.  I have passed the request on to the team but you can also submit feature requests through our in-browser feedback tool.  It's under "..." menu > Help and feedback > Send feedback.

**Comment by Eduardo1977** [comment]
Buongiorno @Y-Kelly , thank you for help
Our Company develop web applications in .NET and we are Microsoft partner.
We have  Visual Studio Subscriptions, do you think we can find/get some "Edge Kiosk" advanced version ?

**Comment by Eduardo1977** [comment]
Thanks!
