### ISSUE TITLE
The "Mobile policy reference" index is not displayed in the local language version.

### ISSUE THREAD

**Issue by tmidorikawa-ms** [MicrosoftDocs/Edge-Enterprise#497]
The "Mobile policy reference" index is not displayed in the local language version.
Therefore, this page cannot be recognized and used by users who only use the local language version.

For example, a comparison of the Japanese and English versions is shown below:
【Japanese】
![image](https://user-images.githubusercontent.com/120448515/227141083-123180dc-9dc5-4207-8bd0-f223942aa15e.png)
【English】
![image](https://user-images.githubusercontent.com/120448515/227141112-27b255ff-df9e-4ac7-aad5-77f460093c40.png)

**Comment by Y-Kelly** [comment]
@tmidorikawa-ms closing as we are tracking this internally with an offline conversation.
