### ISSUE TITLE
Block access to consumer accounts - doesn't exist?

### ISSUE THREAD

**Issue by jabbrwcky1** [MicrosoftDocs/Edge-Enterprise#498]
I was very hopeful in looking at this document since as a school using Edge I want to prevent our students from accessing personal Google accounts by setting the Edge policy that passes the header to Google when they try to sign in.  I wasn't able to find this setting in Intune though, so I raised a ticket.  Support hit the 'circular argument' button and replied "In the documentation says that is possible. But we can't find the option in the list. This means that for the standard available options is not possible because the option is not available there to select." - so is it there or not?  Is it coming or was it once and never shall be again?

**Comment by jabbrwcky1** [comment]
Discovered this has now changed to 'Allowed domains for Apps' per https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#alloweddomainsforapps

**Comment by jabbrwcky1** [comment]
Thanks for replying!  Still testing but hopefully yes; looks like it does the exact same thing so the original doc should really be updated to the new policy to prevent others from going nuts trying to find a non-existent policy.

**Comment by Y-Kelly** [comment]
@jabbrwcky1 Do you have a link to the "original doc"?  I'm not sure where you have found the incorrect information.  Thanks.

**Comment by jabbrwcky1** [comment]
Apologies, I had opened this issue from that page and assumed it was tracked but clearly not!
Original page: https://learn.microsoft.com/en-us/deployedge/edge-learnmore-block-access-consumer-accounts#configure-policy-settings
Correct info: https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#alloweddomainsforapps

**Comment by Y-Kelly** [comment]
@jabbrwcky1 Thanks for the feedback!  We've updated https://learn.microsoft.com/en-us/deployedge/edge-learnmore-block-access-consumer-accounts to include the policy name and link to policy documentation.  

![image](https://user-images.githubusercontent.com/74324031/228927583-b17b1063-bccf-48a3-9a3b-1fb11bf718cb.png)
