### ISSUE TITLE
Missing first steps

### ISSUE THREAD

**Issue by Dburke225** [MicrosoftDocs/Edge-Enterprise#500]
For step one of Allow or block extensions in group policy it says where the GPO setting is but does not say if it is a computer configuration or User configuration. Please use the full path for documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cc77d006-bbf3-747e-4d7c-573e57680174
* Version Independent ID: b9ed5785-c4a5-19b6-fbd7-1a3d30027f08
* Content: [Use group policies to manage Microsoft Edge extensions](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-manage-extensions-policies)
* Content Source: [edgeenterprise/microsoft-edge-manage-extensions-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-manage-extensions-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @AndreaLBarr
* Microsoft Alias: **aspoddar**

**Comment by Y-Kelly** [comment]
@Dburke225 The documentation to configure policy settings (https://learn.microsoft.com/en-us/deployedge/configure-microsoft-edge) mentions that "You can scope policy settings to either the Computer Configuration or User Configuration".  

Are you seeing an issue when using either of these to manage Microsoft Edge extensions via policy?

**Comment by Dburke225** [comment]
That is not the document I am talking about though. The document that tells you how to set group policy objects for Edge Extensions should say it.
Use group policies to manage Microsoft Edge extensions | Microsoft Learn<https://learn.microsoft.com/en-us/deployedge/microsoft-edge-manage-extensions-policies>


Dillon Burke
Assistant Systems Engineer
Qosina Corp. | QOSMEDIX
2002-Q Orville Drive North
Ronkonkoma, NY 11779 USA
T: +1 (631) 940-6768
Email: ***@***.******@***.***>
www.qosina.com<http://www.qosina.com>  www.qosmedix.com<http://www.qosmedix.com>

**Comment by Y-Kelly** [comment]
@Dburke225 I've confirmed this format matches other documents, as it depends on the specific organization administrator to decide if the policy is for User Configuration/Computer Configuration.  

If you are having issues with the extension policies, you can reach out to Support for Business (https://developer.microsoft.com/en-us/microsoft-edge/support/).  Thanks!
