### ISSUE TITLE
Edit image?

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/Edge-Enterprise#503]
Not mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ffcaf54-ce86-1b30-e947-540bf07a54c3
* Version Independent ID: 81267e97-e284-ff00-b081-476934538326
* Content: [Microsoft Edge release notes for Stable Channel](https://learn.microsoft.com/en-us/DeployEdge/microsoft-edge-relnote-stable-channel)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
@BR77BE Can you provide more information about the issue in the docs?

**Comment by BR77BE** [comment]
> @BR77BE Can you provide more information about the issue in the docs?

The abilty to hover over a web image and get an Edge menu for "Edit image" arrived in the Stable Channel quite recently but isn't mentioned anywhere on this page. Seems like a disappointing omission.

**Comment by BR77BE** [comment]
It's new, but not in release notes:

"Speaking of making things easier and helping you stay in your flow, **this month we’re also excited to introduce the ability to edit and save web images** without additional tools or apps outside your Edge browser."

[https://blogs.windows.com/windowsexperience/2023/04/06/edge-features-to-help-you-stay-organized-and-power-your-productivity/#:~:text=Edit%20and%20save%20web%20images%20right%20where%20you%20search%20for%20them](https://blogs.windows.com/windowsexperience/2023/04/06/edge-features-to-help-you-stay-organized-and-power-your-productivity/#:~:text=Edit%20and%20save%20web%20images%20right%20where%20you%20search%20for%20them)

**Comment by Y-Kelly** [comment]
@BR77BE I've reached out to the feature owner and will work on updating release notes.  Thanks!

**Comment by Y-Kelly** [comment]
@BR77BE Release notes have been update: https://learn.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel#version-1120172234-april-6-2023

![image](https://user-images.githubusercontent.com/74324031/231004185-e523c7e9-bb84-4a3b-9f8f-de2d2cb25cce.png)
