### ISSUE TITLE
Is this information being documented elsewhere now?

### ISSUE THREAD

**Issue by feeked** [MicrosoftDocs/Edge-Enterprise#505]
This page hasn't been updated in months

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c9b05f9a-54ca-e84c-dea6-b345b643125b
* Version Independent ID: c9b05f9a-54ca-e84c-dea6-b345b643125b
* Content: [Microsoft Edge release notes for Mobile Stable Channel](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-relnote-mobile-stable-channel)
* Content Source: [edgeenterprise/microsoft-edge-relnote-mobile-stable-channel.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-relnote-mobile-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **charlielin**

**Comment by Y-Kelly** [comment]
@feeked https://learn.microsoft.com/en-us/deployedge/microsoft-edge-relnote-mobile-stable-channel is the correct location.  The document was just updated today.  Thanks!
