### ISSUE TITLE
Correction of the deployment request

### ISSUE THREAD

**Issue by hvanvulpen** [MicrosoftDocs/Edge-Enterprise#507]
Hi,

This documentation is not entirely correct.

It states in step 3 "Deploy your plist" that for Intune one should use a preference file configuration profile to deploy the plist but preferences file profile do not accept the <dict>  tags of which the example plist has several.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8cff3e97-b0cf-2168-450c-5282d318c29e
* Version Independent ID: 8cff3e97-b0cf-2168-450c-5282d318c29e
* Content: [Microsoft Edge for macOS switch from Microsoft AutoUpdate to EdgeUpdater](https://learn.microsoft.com/en-us/deployedge/edge-learnmore-edgeupdater-for-macos)
* Content Source: [edgeenterprise/edge-learnmore-edgeupdater-for-macos.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-edgeupdater-for-macos.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **azeigler**

**Comment by Y-Kelly** [comment]
@hvanvulpen We have passed this feedback on to the feature owners and they will update the documentation as necessary.    

As Microsoft Edge Stable Version 113 had already deployed, closing this issue.
