### ISSUE TITLE
Other management settings for edgeupdater

### ISSUE THREAD

**Issue by cashxx** [MicrosoftDocs/Edge-Enterprise#509]
What are other options? They the same as Chrome?   Example listed is 3 to disable edgeupdater.  Does 0, 1, 2 do anything?  I believe I have 0 set for Chrome.

https://support.google.com/chrome/a/answer/7591084?hl=en#zippy=%2Cturn-on-auto-updates-recommended%2Ccreate-a-new-property-list-file

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8cff3e97-b0cf-2168-450c-5282d318c29e
* Version Independent ID: 8cff3e97-b0cf-2168-450c-5282d318c29e
* Content: [Microsoft Edge for macOS switch from Microsoft AutoUpdate to EdgeUpdater](https://learn.microsoft.com/en-us/deployedge/edge-learnmore-edgeupdater-for-macos)
* Content Source: [edgeenterprise/edge-learnmore-edgeupdater-for-macos.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-edgeupdater-for-macos.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **azeigler**

**Comment by Y-Kelly** [comment]
@cashxx I've reached out to the team and they have confirmed for the UpdateDefault Policy (https://learn.microsoft.com/en-us/deployedge/microsoft-edge-update-policies#updatedefault) these are the values.  

•	0 = Always allow updates
•	1 = Automatic silent updates only
•	2 = Manual updates only
•	3 = Updates disabled
