### ISSUE TITLE
The DefaultApps XML code example is missing some entries for Chromium Edge:

### ISSUE THREAD

**Issue by ccsjnw** [MicrosoftDocs/Edge-Enterprise#51]
<?xml version="1.0" encoding="UTF-8"?>
<DefaultAssociations> 

 <Association Identifier=".htm" ProgId="MSEdgeHTM" ApplicationName="Microsoft Edge" />
  <Association Identifier=".html" ProgId="MSEdgeHTM" ApplicationName="Microsoft Edge" />
  <Association Identifier=".pdf" ProgId="MSEdgePDF" ApplicationName="Microsoft Edge" />
  <Association Identifier="http" ProgId="MSEdgeHTM" ApplicationName="Microsoft Edge" />
  <Association Identifier="https" ProgId="MSEdgeHTM" ApplicationName="Microsoft Edge" />
  <Association Identifier="microsoft-edge" ProgId="MSEdgeHTM" ApplicationName="Microsoft Edge" />
  <Association Identifier="microsoft-edge-holographic" ProgId="MSEdgeHTM" ApplicationName="Microsoft Edge" />
  <Association Identifier="ms-xbl-3d8b930f" ProgId="MSEdgeHTM" ApplicationName="Microsoft Edge" />
  <Association Identifier=".url" ProgId="InternetShortcut" ApplicationName="Internet Browser" />
<?xml version="1.0" encoding="UTF-8"?>
<DefaultAssociations>

**Comment by Y-Kelly** [comment]
Clean up of old issues. 

If you would like to report a Microsoft Edge Enterprise documentation issue to the team please open a new issue and include relevant information/link to document in the Comment section.
