### ISSUE TITLE
UserDataDir policy has peformance problem when set network path.

### ISSUE THREAD

**Issue by so-nkbys** [MicrosoftDocs/Edge-Enterprise#520]
Our customer has requested a change to the documentation regarding policies.
The requested policy is "UserDataDir."

Regarding "UserDataDir" policy, setting the network path often slows things down.
Therefore, they would like to specify that specifying the network path has a performance impact and that they would like to be warned not to do so.

Is it possible to fulfill this request?
For more information, please contact alias snakabayashi and we will be happy to explain.

Regards.

**Comment by Y-Kelly** [comment]
@so-nkbys Is this the documentation (https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#userdatadir) you are requesting to be updated?

![image](https://user-images.githubusercontent.com/74324031/232562905-243d7b70-a8d6-435f-97db-eb74478b9df0.png)

**Comment by Y-Kelly** [comment]
@so-nkbys Closing as we can continue the discussion internally.  Are you able to file a bug in ADO with this request?
