### ISSUE TITLE
user-installed roots on domain-managed browsers are ignored

### ISSUE THREAD

**Issue by gwinkless** [MicrosoftDocs/Edge-Enterprise#521]
Page explicitly states that user-installed roots will still work:

_Even after the change, in addition to trusting the built-in roots that ship with Microsoft Edge, the browser queries the underlying platform for—and trusts—locally installed roots that users and/or enterprises installed_

 but fails to mention that user-installed roots are ignored on domain-managed browsers.

Could have saved quite some time with this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e366b103-61bc-729b-a8dc-fe44d27ac97f
* Version Independent ID: e366b103-61bc-729b-a8dc-fe44d27ac97f
* Content: [Changes to Microsoft Edge browser TLS server certificate verification](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-security-cert-verification)
* Content Source: [edgeenterprise/microsoft-edge-security-cert-verification.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-security-cert-verification.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **erikan**

**Comment by Florin-Anghel** [comment]
It did work cause we used this work-around in our issue with "Your connection isn't private" due to the retrieval of our CRL.

I can confirm it no longer works.

**Comment by erik-anderson** [comment]
There's not different logic for managed vs. non-managed devices here. Can you share a little more detail about your precise scenario? What location are you installing the roots to?

**Comment by Y-Kelly** [comment]
@gwinkless Just following up to see if you have more information. Can you share a little more detail about your precise scenario?  What location are you installing the roots to?

**Comment by Y-Kelly** [comment]
Cleaning up old issues and closing.  @gwinkless Please follow up if you have more information.
