### ISSUE TITLE
Functional Limitations section is very bad.

### ISSUE THREAD

**Issue by IN-jwink** [MicrosoftDocs/Edge-Enterprise#525]
[Enter feedback here]
Section:  [Functional Limitations](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode#functional-limitations) is a mess.  
1. The entire section is too vague to be of any use.  For some items on the list "turn off" is entirely ambiguous.
2. Someone clearly worked on it and fell asleep while typing as "UserFeedBackAllowed" is listed twice.

I realize there are two ways to report issues, one for page issues and one for app/content.  I know that this is for reporting page issues.  This section is so bad I wasn't sure how to report both as they are in this case intrinsically linked.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 229e4d46-19a6-c042-8ce1-844c44c00112
* Version Independent ID: 8ab07629-42a6-e7a1-86a9-f8103825ebc4
* Content: [Configure Microsoft Edge kiosk mode](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode)
* Content Source: [edgeenterprise/microsoft-edge-configure-kiosk-mode.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-configure-kiosk-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **v-danwesley**

**Comment by Y-Kelly** [comment]
@IN-jwink The team has made updates to https://learn.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode#functional-limitations.
