### ISSUE TITLE
Microsoft Edge Legacy

### ISSUE THREAD

**Issue by wdeguara** [MicrosoftDocs/Edge-Enterprise#527]
This page still refers to 'Microsoft Edge Legacy' in part of it's content - a browser that is no longer supported by Microsoft.  Content needs to be updated to reflect the current Microsoft Edge (modern) browser.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a3137232-a4ef-f6d6-326b-e501e2077c3b
* Version Independent ID: eef8be2c-7867-096e-6b6d-c0b6225b4957
* Content: [Per-site configuration by policy](https://learn.microsoft.com/en-us/deployedge/per-site-configuration-by-policy#windows-security-zones)
* Content Source: [edgeenterprise/Per-Site-Configuration-by-Policy.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/Per-Site-Configuration-by-Policy.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **collw**

**Comment by ericlaw1979** [comment]
It's correct to note that Edge Legacy is no longer supported as a standalone browser, but the content here applies to WebView1 controls running EdgeHTML.

The article does discuss the current browser, see the section "Security Zones in Microsoft Edge";  for a fuller exploration of this topic, see https://textslashplain.com/2020/01/30/security-zones-in-edge/

**Comment by Y-Kelly** [comment]
Thanks, @ericlaw1979 for the information!  The doc has been updated to mention EdgeHTML and WebView1.  

@wdeguara Closing this issue.  Thanks for the feedback.
