### ISSUE TITLE
Can not "Flash" macOS

### ISSUE THREAD

**Issue by marckerr** [MicrosoftDocs/Edge-Enterprise#53]
Imaging or Flashing macOS systems is not possible as of macOS 10.14 so the following text is an incorrect statement and can not be done.
 "The first option is to flash the device with an image of macOS where Microsoft Edge has already been set as the default browser."

**Comment by Y-Kelly** [comment]
Clean up of old issues.  

If this is still an issue, please open a new issue and include relevant information and a link to document in the Comment section.
