### ISSUE TITLE
Configure Microsoft Edge enterprise sync has no information on how to configure Edge enterprise sync

### ISSUE THREAD

**Issue by ChaosFreak** [MicrosoftDocs/Edge-Enterprise#531]
This page is titled "Configure Microsoft Edge enterprise sync" and yet it contains no step-by-step instructions on how to accomplish this.
It mentions supported environments, and defines the policies, but doesn't give any instructions on where/how to set these policies.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1fa7eda4-6e4c-c2c8-a29a-ef2eead7f04f
* Version Independent ID: 414db256-c14b-ca11-b2a7-835aa9c9e041
* Content: [Configure Microsoft Edge enterprise sync](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-enterprise-sync)
* Content Source: [edgeenterprise/microsoft-edge-enterprise-sync.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-enterprise-sync.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
@ChaosFreak For organizations, there is a whole section of aka.ms/deployedge with instructions on how to configure the browser with policies.  For example: https://learn.microsoft.com/en-us/deployedge/configure-microsoft-edge

![image](https://github.com/MicrosoftDocs/Edge-Enterprise/assets/74324031/fca65c91-0dce-452a-84de-3dc473713b17)

If you need help setting up your enterprise environment, you can reach out to Support for Business: https://developer.microsoft.com/en-us/microsoft-edge/support/

Thanks!
