### ISSUE TITLE
"Disable Internet Explorer 11 as a standalone browser" step-by-step directions are incorrect

### ISSUE THREAD

**Issue by shrout1** [MicrosoftDocs/Edge-Enterprise#532]
See [Disable Internet Explorer 11 as a standalone browser](https://learn.microsoft.com/en-us/deployedge/edge-ie-disable-ie11#disable-internet-explorer-11-as-a-standalone-browser)

Step 3 states: 
Go to Computer Configuration/Administrative Templates/Windows Components/Internet Explorer

But it SHOULD state:

Go to Computer Configuration/Policies/Administrative Templates/Windows Components/Internet Explorer

The rest of the document appears correct. Just wanted to let you know!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b557e6ee-bb46-7b9c-108b-c78829c6d8b4
* Version Independent ID: dd39c398-eb44-ab64-69ee-d860147072df
* Content: [Disable Internet Explorer 11](https://learn.microsoft.com/en-us/deployedge/edge-ie-disable-ie11)
* Content Source: [edgeenterprise/edge-ie-disable-ie11.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-disable-ie11.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **shisub**

**Comment by Y-Kelly** [comment]
@shrout1 Thanks!  I'm not able to reproduce.  Currently with my device the path is Computer Configuration/Administrative Templates/Windows Components/Internet Explorer

![image](https://github.com/MicrosoftDocs/Edge-Enterprise/assets/74324031/98543417-b851-45b0-847b-30c3782355fd)

**Comment by shrout1** [comment]
![image](https://github.com/MicrosoftDocs/Edge-Enterprise/assets/4391743/5a0634e3-c002-4977-a8d4-6ecd8cbc174c)

I realize that I was looking at gpmc.msc not gpedit.msc. Would be nice if there was a way to call out the difference, but it's not the end of the world. Just trying to help the next guy!
