### ISSUE TITLE
Wrong note in "Configure Microsoft Edge enterprise sync" page?

### ISSUE THREAD

**Issue by apmpinho** [MicrosoftDocs/Edge-Enterprise#533]
The section https://learn.microsoft.com/en-us/deployedge/microsoft-edge-enterprise-sync#supported-environments, in the Enterprise sync landing page, contains the following note:

<img width="648" alt="image" src="https://github.com/MicrosoftDocs/Edge-Enterprise/assets/72249906/2d1e15b3-f56d-460e-ae71-efc86f2fc981">

If you follow the link there, you're sent to https://learn.microsoft.com/en-us/azure/active-directory/devices/enterprise-state-roaming-enable, where another note states the following:

<img width="661" alt="image" src="https://github.com/MicrosoftDocs/Edge-Enterprise/assets/72249906/25efb630-cfe8-4fbc-9cb9-2637bf46870a">

Shouldn't we remove the note in the first page, as this is, at least, confusing?

**Comment by Y-Kelly** [comment]
closing, starting internal thread to discuss this doc.
