### ISSUE TITLE
Instructions incorrect or incomplete for changing default browser via gpo

### ISSUE THREAD

**Issue by novaclark** [MicrosoftDocs/Edge-Enterprise#539]
Following the instructions on this page does not change the browser used to open internet shortcuts (.url), and it does not change the browser listed as the default web browser in the "Default apps" setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e858557-d417-cb01-9f4f-ed214087790c
* Version Independent ID: 9cbd34f5-7a9a-1e3a-d832-1a945db28726
* Content: [Set Microsoft Edge as the default browser on Windows and macOS](https://learn.microsoft.com/en-us/deployedge/edge-default-browser)
* Content Source: [edgeenterprise/edge-default-browser.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-default-browser.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **brianalt**

**Comment by Y-Kelly** [comment]
@novaclark Hello - If you would like to submit a feature request, you can submit it through the browser ("..." menu > Help and feedback > Send feedback). 

If you would like assistance with your specific Microsoft Edge setup, you can reach out to Support for Business (https://developer.microsoft.com/en-us/microsoft-edge/support/).  Thanks!
