### ISSUE TITLE
Still can't get this functionality working

### ISSUE THREAD

**Issue by cfhsncb** [MicrosoftDocs/Edge-Enterprise#54]
I'm on windows 10 enterprise build 1903 with edge stable enterprise. I've added the ADMX profiles to my local machine and configured the relevant policies. I generated a site list using the Enterprise Mode Site List Manager, and can verify that Edge has the policies enabled in edge://policy. However when I visit the sites I've designated to use IE mode they open normally in edge. I can't figure out where I've gone wrong. From everything I've read this should be working. Any help would be appreciated. If this isn't the right place to ask for help, please direct me to somewhere where I can, thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aae869a8-2ae4-d28f-6c85-c1190609f87b
* Version Independent ID: e2bcb1d6-27f7-5e30-ae6b-7acb5ee94098
* Content: [Use Microsoft Edge with IE mode](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode#feedback)
* Content Source: [edgeenterprise/edge-ie-mode.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/edge-ie-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by Y-Kelly** [comment]
Closing this old issue.
