### ISSUE TITLE
Reset/Delete settings from cloud not working

### ISSUE THREAD

**Issue by simiid** [MicrosoftDocs/Edge-Enterprise#542]
I've noticed in the build 114 that the Reset button was replaced by Re-Sync button.

While Reset was an option to delete the settings from cloud and start from scratch, Re-Sync is merging local settings with the settings from cloud and bringing the changes from cloud to local device.
Both options should be present in case the user wants to completely delete cloud sync settings, or to bring them on local device. 

https://www.reddit.com/r/MicrosoftEdge/comments/10fbu1m/microsoft_is_preparing_a_change_to_the_option/

How can I reset/delete my settings from cloud now, to start from scratch with settings and sync?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa2b6bb-c572-6b62-0b2a-5d11cc6c16c2
* Version Independent ID: bbd72cfb-0dd2-dce0-ede7-6887a2992bad
* Content: [Reset Microsoft Edge data in the cloud](https://learn.microsoft.com/en-us/deployedge/edge-learnmore-reset-data-in-cloud)
* Content Source: [edgeenterprise/edge-learnmore-reset-data-in-cloud.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-reset-data-in-cloud.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
@simiid If you visit edge://settings/profiles/sync, can you click the "Try another option" and see "Reset sync data"?  

![image](https://github.com/MicrosoftDocs/Edge-Enterprise/assets/74324031/02a60541-a0b8-4e31-85c9-5a688a0c9be8)

**Comment by simiid** [comment]
@Y-Kelly Hello, "Try another option" is not visible. I pressed Re-sync several times maybe it will appear but nothing.
Also I've checked out of curiosity in edge://flags if the reset option is disabled, but it's missing from flags as well.
I have Edge version 114.0.1823.37 (Official build) (64-bit)

![image](https://github.com/MicrosoftDocs/Edge-Enterprise/assets/4710709/aa69c9a8-3236-4c3d-b4d2-7b441c85ccde)

**Comment by Y-Kelly** [comment]
@simiid I'm also on Version 114.0.1823.37 (Official build) (64-bit) but have the "Try another option".  I'll reach out to the Sync team to clarify with them.

**Comment by simiid** [comment]
@Y-Kelly I've made a reddit post to see if others report this issue as well, if this helps.

https://www.reddit.com/r/MicrosoftEdge/comments/13zr9uy/how_to_delete_edge_settings_from_cloud/

**Comment by simiid** [comment]
@Y-Kelly Hello, today I've signed in at work with my Microsoft work account and that option to reset sync is available. I've signed out and signed back in with my personal account and that option is missing. It has to do something with the account rights I think.
But, while I was able to have that option on my work account, I tried to Reset Sync, but there is an issue, it is deleting the settings from cloud, but right after it's syncing the local ones and I don't want that., because the local settings are already the messed ones which were pulled when I signed in. If I disable sync for each option, then the Reset Sync button become disabled.

**Comment by Y-Kelly** [comment]
@simiid It does sound like the different experiences are related to your work/personal accounts.  I have not heard back from the team yet, but can follow up once I do.  

For sync related issues, it is normally best to reach out to Support for Business (https://developer.microsoft.com/en-us/microsoft-edge/support/) as they can work with you directly and gather logs and diagnostic data to investigate.
