### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by bjohnrini** [MicrosoftDocs/Edge-Enterprise#544]
The version number listed for extended stable channel as 109.X is wrong for June 13th.

**Comment by Y-Kelly** [comment]
@bjohnrini Can you please provide a link to the doc with this issue?  Thanks!

**Comment by Y-Kelly** [comment]
@bjohnrini Following up, are you still reproducing this issue?

**Comment by bjohnrini** [comment]
No

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
