### ISSUE TITLE
Microsoft Edge password manager security -> About the encryption method ->

### ISSUE THREAD

**Issue by ggbce** [MicrosoftDocs/Edge-Enterprise#549]
Microsoft Edge password manager security -> About the encryption method ->

This section talk about the storage method depending on OS platform, like Windows is DPAPI, MacOS is keychain, or Linux is Keyring or KWallet...

But what is the method for other platforms where MSEdge is possible ? Are you telling MS Edge installed on other platform doesn't offer an encryption or you just ommited the info ?

I talk about MS Edge for Apple iOS and Google Android

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f651e68c-34bf-d399-88e9-c9a0928d8be4
* Version Independent ID: ad34ee59-01d3-c64d-d123-5484264190b8
* Content: [Microsoft Edge password manager security ](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-security-password-manager-security#should-a-password-manager-be-enabled-by-an-organization)
* Content Source: [edgeenterprise/microsoft-edge-security-password-manager-security.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-security-password-manager-security.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **archandr**

**Comment by Y-Kelly** [comment]
@ggbce Article has been updated with Android and iOS information.  

https://learn.microsoft.com/en-us/deployedge/microsoft-edge-security-password-manager-security#about-the-encryption-method

Thanks for the feedback!
