### ISSUE TITLE
Provide feedback on Edge for Azure DoD Cloud

### ISSUE THREAD

**Issue by brmcmill** [MicrosoftDocs/Edge-Enterprise#550]
Hey Team!  Although it may seem obvious if a feature is not in GCC High, it more than likely is not in DoD, but I think that _verbiage_ would help here to for clarity purposes.  There's a lot of DoD customers interested in this feature.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f922a3bd-4f35-bbad-e51a-ce4821c0a662
* Version Independent ID: 580385f0-90d2-acb9-56a5-5f2bd2bfed09
* Content: [Microsoft Edge enterprise sync FAQ](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-enterprise-sync-faq)
* Content Source: [edgeenterprise/microsoft-edge-enterprise-sync-faq.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-enterprise-sync-faq.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **archandr**

**Comment by Y-Kelly** [comment]
@brmcmill The FAQ has been updated: https://learn.microsoft.com/en-us/deployedge/microsoft-edge-enterprise-sync-faq#does-microsoft-edge-support-government-community-cloud-gcc-high-and-azure-government-department-of-defense-dod-cloud-compliance

![image](https://github.com/MicrosoftDocs/Edge-Enterprise/assets/74324031/d244944d-eced-4fcc-b19d-a2d72aef8d33)
