### ISSUE TITLE
https://support.microsoft.com/en-us/account-billing/control-privacy-settings-for-your-microsoft-account-45f11f17-f3c5-7b6b-876e-22dcfcb19c0a

### ISSUE THREAD

**Issue by dh-orko** [MicrosoftDocs/Edge-Enterprise#552]

**Comment by Y-Kelly** [comment]
@dh-orko Closing.  If you would like to report a Microsoft Edge Enterprise documentation issue to the team please open a new issue and include relevant information/repro steps in the Comment section.
