### ISSUE TITLE
showrecommendationsenabled

### ISSUE THREAD

**Issue by BlueOdyssey** [MicrosoftDocs/Edge-Enterprise#554]
The policy showrecommendationsenabled doesn't appear to be in the latest release of the Edge GPO templates? Has this policy been superseded?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#showrecommendationsenabled)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@BlueOdyssey Did you download the policy file from here https://www.microsoft.com/en-us/edge/business/download?form=MA13FJ?  

I just downloaded this and was able to see the policy. 

![image](https://github.com/MicrosoftDocs/Edge-Enterprise/assets/74324031/0d6eafa6-37f4-4a10-aaa3-7362eaeb267c)

**Comment by BlueOdyssey** [comment]
@Y-Kelly this one can be closed - I feel incredibly silly. I've been looking for "_ShowRecommendationsEnabled_", "_Show Recommendations Enabled_" or "Show feature and workflow recommendations", the latter of which is what it's referred to within the Edge GUI. Didn't realise it was written up as "_Allow feature recommendations and browser assistance_".
