### ISSUE TITLE
Wow-  you tube?

### ISSUE THREAD

**Issue by jaminbern** [MicrosoftDocs/Edge-Enterprise#556]
Wow - is there really a You Tube video embedded into this page? now I have to watch an advert that makes your primary competitor richer to learn about your products? That is too funny. 

Have you completely given up on Stream?

Thanks

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b11becb9-7ff3-9c7d-a8d3-67f80cc31f3e
* Version Independent ID: b11becb9-7ff3-9c7d-a8d3-67f80cc31f3e
* Content: [Microsoft Edge for Business](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-for-business?form=MA13FJ)
* Content Source: [edgeenterprise/microsoft-edge-for-business.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-for-business.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **archandr**

**Comment by Y-Kelly** [comment]
@jaminbern Thanks for the feedback, I'll pass it on to the appropriate folks on the team.
