### ISSUE TITLE
Open in IE11 Tab, outside of Edge

### ISSUE THREAD

**Issue by browno01** [MicrosoftDocs/Edge-Enterprise#56]
Is it possible using the Schema to specify that websites once accessed via Edge, open up in IE11, instead of opening up inside the Edge interface?

**Comment by OftKilted** [comment]
In the current schema (v2) integration is not configured in the Schema, but via Group Policy for all sites.

See: [Enable Internet Explorer integration using Group Policy](https://docs.microsoft.com/en-us/DeployEdge/edge-ie-mode-policies#enable-internet-explorer-integration-using-group-policy)

**Comment by Y-Kelly** [comment]
Clean up of old issues.  IE11 has retired and is out of support as of June 15, 2022.  https://techcommunity.microsoft.com/t5/windows-it-pro-blog/internet-explorer-11-desktop-app-retirement-faq/ba-p/2366549
