### ISSUE TITLE
document.domain is not ignored in Edge 115

### ISSUE THREAD

**Issue by PyroLee** [MicrosoftDocs/Edge-Enterprise#564]
[Microsoft Edge will disable modifying document.domain](https://learn.microsoft.com/en-us/deployedge/edge-learnmore-origin-keyed-agent-cluster) said:

> Starting as soon as Microsoft Edge version 115, attempts to modify the document.domain property using JavaScript will be ignored.

But actually it's not. I can still successfully modify document.domain in Edge 115. Please see the pic:
![image](https://github.com/MicrosoftDocs/Edge-Enterprise/assets/124762851/787c05d3-14fb-42df-8d75-4c1ac8ec9c85)
Version: 115.0.1901.203 (Official build) (64-bit) 

I also tested in Edge Dev:
![image](https://github.com/MicrosoftDocs/Edge-Enterprise/assets/124762851/33f83b25-9876-44ce-9c0f-e6094c621349)
Version: 117.0.2045.1 (Official build) dev (64-bit) 

Meanwhile in Chrome:
![image](https://github.com/MicrosoftDocs/Edge-Enterprise/assets/124762851/088a5f43-751e-4153-9dd3-4ad1f59a4c5f)

Would you please tell me the exact release when document.domain modification will be disabled in Microsoft Edge? TIA.

**Comment by Y-Kelly** [comment]
@PyroLee Currently there is no exact release when the change will be occurring, as it will depend on when Microsoft Edge inherits the change from Chromium.  We have updated the documentation.  Thanks! 

![image](https://github.com/MicrosoftDocs/Edge-Enterprise/assets/74324031/b06b5803-b7d4-4074-8255-5ff76f56eaa0)

**Comment by Y-Kelly** [comment]
@PyroLee This change should be in Microsoft Edge 119.  We are working to update the doc: https://github.com/MicrosoftDocs/Edge-Enterprise/pull/609
