### ISSUE TITLE
MSA Account Profile - Which Privacy Policy for BCE?

### ISSUE THREAD

**Issue by haoewqopi** [MicrosoftDocs/Edge-Enterprise#565]
Bing Chat Enterprise (BCE) provides robust privacy protections for enterprise customers, but it only works if the user is logged into Edge with their enterprise AAD account. If a user logs in with an MSA account, those protections vanish in favor of the watered-down consumer grade privacy policies. Does the new Edge for Business now make it so that even if my users switch from their enterprise AAD account to their MSA account, they continue to receive the privacy protections offered with BCE (MS can't see my queries, prompts are not used to train the LLM, etc.)? This is not clear in your documentation. 

If Edge for Business does _not_ extend the protections described above when flipping to an MSA account, how do I administratively prevent my users from using an MSA profile in Edge for Business?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b11becb9-7ff3-9c7d-a8d3-67f80cc31f3e
* Version Independent ID: b11becb9-7ff3-9c7d-a8d3-67f80cc31f3e
* Content: [Microsoft Edge for Business](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-for-business)
* Content Source: [edgeenterprise/microsoft-edge-for-business.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-for-business.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **archandr**

**Comment by Y-Kelly** [comment]
@haoewqopi For more information, please see the Microsoft Edge for Business FAQ https://techcommunity.microsoft.com/t5/microsoft-edge-insider/microsoft-edge-for-business-faq/ba-p/3891837.  Thanks! 

For further feedback, you can press alt + shift + I in the browser to open the Send feedback dialog where you can share your thoughts. You can also leave feedback in our [TechCommunity forum](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise).  Thanks!
