### ISSUE TITLE
Passwords Manager Tab

### ISSUE THREAD

**Issue by thiagocirqueira** [MicrosoftDocs/Edge-Enterprise#568]
Version 116.0.1938.54 (Official build) (64-bit), I identified a bug in the saved passwords tab, when selecting a saved password the "Delete" option within "More Actions" (...) does not work, nothing reacts.
It is only possible to delete using the top button "Delete."
In short: "Delete" option inside (...) "More Actions" is there, but it doesn't work.

https://github.com/MicrosoftDocs/Edge-Enterprise/assets/143081292/7e5dc338-c1c2-407f-8089-693b062a16ea

**Comment by Y-Kelly** [comment]
@thiagocirqueira Thanks for the feedback.  This is a known issue.  Currently no ETA for the fix but I will pass this on to the team.
