### ISSUE TITLE
Re-Sync is not available if you disable sync (incorrect doc info)

### ISSUE THREAD

**Issue by dotnvo** [MicrosoftDocs/Edge-Enterprise#569]
The section about resetting data in cloud is incorrect:
https://learn.microsoft.com/en-us/deployedge/edge-learnmore-reset-data-in-cloud#perform-a-reset-to-remove-your-data-from-microsofts-cloud

If you disable sync, you don't have the option to 're-sync data to this device', which honestly makes sense.  It completely removes that section. I am running the latest version of edge. This might be because of an update or changed version that made these instructions incorrect. That section completely disappears.

I fixed my issue by forcing a sign out and sign back in.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa2b6bb-c572-6b62-0b2a-5d11cc6c16c2
* Version Independent ID: bbd72cfb-0dd2-dce0-ede7-6887a2992bad
* Content: [Reset Microsoft Edge data in the cloud](https://learn.microsoft.com/en-us/deployedge/edge-learnmore-reset-data-in-cloud#perform-a-reset-to-remove-your-data-from-microsofts-cloud)
* Content Source: [edgeenterprise/edge-learnmore-reset-data-in-cloud.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-reset-data-in-cloud.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **archandr**

**Comment by dotnvo** [comment]
I was going to get a screenshot but once I fixed the sync the toggle for on/off went away and I can only toggle the sub options on this page : edge://settings/profiles/sync

basically that page was in a state where I could disable sync entirely, but doing so, would make the re-sync data to this device section below it disappear.

**Comment by Y-Kelly** [comment]
@dotnvo Under edge://settings/profiles/sync there are 2 options, Re-sync and Reset sync.  The documentation is providing information to Reset sync.  Can you provide more information about what should be updated in the documentation?  

![image](https://github.com/MicrosoftDocs/Edge-Enterprise/assets/74324031/b95ed1f4-79e1-4d25-8cf0-8fd222559237)

Regarding your experience in your second comment, I agree if you disable sync entirely, then the Re-sync section would disappear.

**Comment by dotnvo** [comment]
I guess Edge has some context awareness if there are current sync issues

My plan was to recreate the situation, but  I don't have the option to 'turn off sync' here anymore: edge://settings/profiles/sync. I think Edge detected my sync was not working correctly previously in one of my profiles, so it did allow me to turn it off:
![image](https://github.com/MicrosoftDocs/Edge-Enterprise/assets/29506123/ee7eb5c7-62d5-4705-b306-68825adf1a70)


As you can see from the screenshot, I have the options to disable certain parts of sync, but not the whole thing. The ability to 'turn off sync' previously showed up at the top. Mainly sharing this because that could confuse folks.

Luckily for me, I have another browser profile that is broke:

![image](https://github.com/MicrosoftDocs/Edge-Enterprise/assets/29506123/3608b745-1185-47e9-b7d7-11e1d23d2585)

You'll note  that i'm on edge://settings/profiles/sync and the only option i have is to turn on sync, i don't have any option to reset sync, both options you shared are missing. these two options are only available if sync is turned on. Thus, I think these instructions are not quite correct:

> If you want to remove your data from Microsoft’s cloud, use the following steps to do a reset.


> Stop synchronization on devices except the device you're performing the reset on. In Microsoft Edge, select Settings > Profiles > Sync > Turn off sync.
After you stop synchronization, select Settings > Profiles > Sync > Reset sync. In the Reset sync dialog box, clear "Resume sync on this device after resetting sync", and then select Reset.


I can not complete step 2: settings->profile->sync->Reset Sync.  Additionally, the 'reset sync from Microsoft servers' is hidden under a sub menu, 'Still having sync problems? Try another option'. I'm not sure if that is suppose to expand when turning off sync but just sharing that I didn't have the option. I only had 'turn on sync'. This is why I created the issue.

**Comment by Y-Kelly** [comment]
@dotnvo Thanks for the feedback.  I'll pass it on to the team.  Appreciate the additional details!

**Comment by dotnvo** [comment]
Anytime.

Does this repo usually close the issues and fix later? Just use to other places in MS using issues and using commits to link to issues to track progress.
