### ISSUE TITLE
Migration from MicrosoftDocs/EdgeEnterprise to MicrosoftDocs/Edge-Enterprise Broke all GitHub Links from the core documentation

### ISSUE THREAD

**Issue by OftKilted** [MicrosoftDocs/Edge-Enterprise#57]
@dstrome The change over from MicrosoftDocs/EdgeEnterprise to the new project MicrosoftDocs/Edge-Enterprise has broken all of the github links from the bottom of the Microsoft Documentation pages.

For example:

https://docs.microsoft.com/en-us/DeployEdge/edge-ie-mode-policies

The github link at the bottom of the page goes to:
[Github Link for prior documentation](https://github.com/MicrosoftDocs/EdgeEnterprise/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20docs.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%20add98763-6344-6d9e-b1f4-39c995100050%0A*%20Version%20Independent%20ID%3A%205a9ac6ef-92ff-edfc-b3a6-af758642210f%0A*%20Content%3A%20%5BConfigure%20IE%20mode%20Policies%5D(https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2FDeployEdge%2Fedge-ie-mode-policies)%0A*%20Content%20Source%3A%20%5Bedgeenterprise%2Fedge-ie-mode-policies.md%5D(https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FEdgeEnterprise%2Fblob%2Fpublic%2Fedgeenterprise%2Fedge-ie-mode-policies.md)%0A*%20Product%3A%20**microsoft-edge**%0A*%20GitHub%20Login%3A%20%40cjacks%0A*%20Microsoft%20Alias%3A%20**cjacks**)

That link doesn't work and needs to be modified to:
[Correct Link](https://github.com/MicrosoftDocs/Edge-Enterprise/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20docs.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%20add98763-6344-6d9e-b1f4-39c995100050%0A*%20Version%20Independent%20ID%3A%205a9ac6ef-92ff-edfc-b3a6-af758642210f%0A*%20Content%3A%20%5BConfigure%20IE%20mode%20Policies%5D(https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2FDeployEdge%2Fedge-ie-mode-policies)%0A*%20Content%20Source%3A%20%5Bedgeenterprise%2Fedge-ie-mode-policies.md%5D(https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FEdgeEnterprise%2Fblob%2Fpublic%2Fedgeenterprise%2Fedge-ie-mode-policies.md)%0A*%20Product%3A%20**microsoft-edge**%0A*%20GitHub%20Login%3A%20%40cjacks%0A*%20Microsoft%20Alias%3A%20**cjacks**)

The sub-links that are created by the linking for MSDocs to Github also need to be updated to Edge-Enterprise as well.

Note: This affects any of the linking/feedback that goes back to GitHub

(note: Content Source: link updated to allow proper linking to new page)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: add98763-6344-6d9e-b1f4-39c995100050
* Version Independent ID: 5a9ac6ef-92ff-edfc-b3a6-af758642210f
* Content: [Configure IE mode Policies](https://docs.microsoft.com/en-us/DeployEdge/edge-ie-mode-policies)
* Content Source: [edge-enterprise/edge-ie-mode-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @cjacks
* Microsoft Alias: **cjacks**

**Comment by RAJU2529** [comment]
@cjacks. Verify this PR #58 and merge if looks good.

**Comment by kingma-sbw** [comment]
The link from https://docs.microsoft.com/en-us/deployedge/microsoft-edge-sysupdate-access-old-edge still is broken

**Comment by RAJU2529** [comment]
@kingma-sbw , In which article, did you found  broken link, , and specify the location

**Comment by dstrome** [comment]
Thank you for catching this. I've updated the configuration so I'm closing this issue. The updated configuration will be live shortly.
