### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Anojei** [MicrosoftDocs/Edge-Enterprise#570]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c0ccb95-a7bb-149b-c108-6e05bd6250cb
* Version Independent ID: 100b846e-b653-e339-69b0-7fffd03bbd9a
* Content: [Microsoft Edge support for Microsoft Defender SmartScreen](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-security-smartscreen)
* Content Source: [edgeenterprise/microsoft-edge-security-smartscreen.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-security-smartscreen.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by EllaMartinez1981** [comment]
1. Create a TXT record in your DNS configuration for the following hostname: _github-challenge-ella-softwar-ent.ellaintelligentglobalnetwork.websites.co.in
2. Use this code for the value of the TXT record: bec8475d61. Please note that the code will expire in 7 days.
3. Wait until your DNS configuration changes. This could take up to 72 hours to propagate.
