### ISSUE TITLE
Broken link in the document | Microsoft Edge stable release notes

### ISSUE THREAD

**Issue by HotCakeX** [MicrosoftDocs/Edge-Enterprise#581]
Hi,
There is a link in the document that leads to 404 error not found page.

![image](https://github.com/MicrosoftDocs/Edge-Enterprise/assets/118815227/e2971b6d-dc7e-4956-b5ab-111539d78939)

![image](https://github.com/MicrosoftDocs/Edge-Enterprise/assets/118815227/aa18aaab-fcf1-4f27-942a-6fff61fb017a)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ffcaf54-ce86-1b30-e947-540bf07a54c3
* Version Independent ID: 81267e97-e284-ff00-b081-476934538326
* Content: [Microsoft Edge release notes for Stable Channel](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **archandr**

**Comment by Y-Kelly** [comment]
@HotCakeX Thanks for letting us know!  I believe the correct URL is https://support.microsoft.com/en-us/topic/recover-lost-or-deleted-favorites-in-microsoft-edge-ac06270e-ba57-4266-8389-8bfd1df1aa5e.  We will work on updating the doc.

**Comment by HotCakeX** [comment]
@Y-Kelly Thank you ^^
