### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/Edge-Enterprise#582]
"**Microsoft Edge Sync Favorites Recovery.** ...
 For more information, see [Recover lost or deleted favorites in Microsoft Edge - Microsoft Support]
(https://learn.microsoft.com/en-us/topic/recover-lost-or-deleted-favorites-in-microsoft-edge-ac06270e-ba57-4266-8389-8bfd1df1aa5e))"
=
404 - Page not found

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ffcaf54-ce86-1b30-e947-540bf07a54c3
* Version Independent ID: 81267e97-e284-ff00-b081-476934538326
* Content: [Microsoft Edge release notes for Stable Channel](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel#version-1170204531-september-15-2023)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **archandr**

**Comment by Y-Kelly** [comment]
@BR77BE Thanks for letting us know!  I believe the correct URL is https://support.microsoft.com/en-us/topic/recover-lost-or-deleted-favorites-in-microsoft-edge-ac06270e-ba57-4266-8389-8bfd1df1aa5e.  We will work on updating the doc.
