### ISSUE TITLE
Edge displays chaotic pictures

### ISSUE THREAD

**Issue by dlyltm** [MicrosoftDocs/Edge-Enterprise#583]
I displayed the picture in Edge, which was originally like this:
![image](https://github.com/MicrosoftDocs/Edge-Enterprise/assets/33916145/f751be5a-20bf-44bc-858a-b3f9cfd473e6)
After the last update of Edge, it became like this:
![image](https://github.com/MicrosoftDocs/Edge-Enterprise/assets/33916145/7f0accbf-e733-423b-be4f-44ad1112e061)
The position and size have all changed. I can't find the reason.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@dlyltm Hello - These GitHub Issues are for feedback about Microsoft Edge Enterprise documentation.   

For issues you encounter while browsing, you can use our in-browser feedback tool.  It's under "..." menu > Help and feedback > Send feedback.  Thanks!
