### ISSUE TITLE
macOS 

### ISSUE THREAD

**Issue by miocr** [MicrosoftDocs/Edge-Enterprise#584]
_macOS_
_High Sierra (10.13) and later_

Not true - Edge 117+ support only macOS 10.15+. EdgeAutoUpdate ignore this and install update to 117 on macOS 10.14, 
Result = Edge locked and cannot be started, 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86847b80-8f8e-9493-86ff-5dfd6412b48f
* Version Independent ID: 2ce02bc3-24a1-8c9f-c787-34ab90e9f31d
* Content: [Microsoft Edge Supported Operating Systems](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-supported-operating-systems)
* Content Source: [edgeenterprise/microsoft-edge-supported-operating-systems.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-supported-operating-systems.md)
* Product: **microsoft-edge**
* GitHub Login: @srugh
* Microsoft Alias: **archandr**

**Comment by Y-Kelly** [comment]
@miocr Thanks for the feedback!  The team has updated the page.  They are also discussing how to improve this behavior in the future.
