### ISSUE TITLE
"Enable the Search bar" policy is completely missing from Intune

### ISSUE THREAD

**Issue by rbishop-etq** [MicrosoftDocs/Edge-Enterprise#587]
Policy is missing from AAD/Intune machine policy options. This policy of "SearchbarAllowed" aka "Enable the Search bar" is completely missing from Intune when trying to configure it. Seems it may not have been rolled out as a policy at all, otherwise it may have a different name?
I see that the other policies that were released around the same time are available, but this one is not. Please advise where this policy is or when it will be available for configuration on Intune enrolled windows machines.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@rbishop-etq SearchbarIsEnabledOnStartup was released around the same time.  Do you see it available in Intune?  

Previously I've heard that Microsoft Edge policies appear in Intune's administrative templates UI normally in 2-6 weeks.  Edge policies can be manually added through Intune before they are available in the UI by manually adding them using custom OMA-URI settings. Details at: https://learn.microsoft.com/en-us/deployedge/configure-edge-with-mdm. Intune also now provides a general ADMX installation experience that works with the Edge ADMX files as well to manually add settings.

**Comment by Y-Kelly** [comment]
Closing, no reply in over a week.

**Comment by rbishop-etq** [comment]
Intune team did finally get this added. Just took them quite a bit longer than normal for some reason. But its finally there and available!
Thanks!

**Comment by Y-Kelly** [comment]
Great to hear!  Have a good weekend!
