### ISSUE TITLE
BrowserReplacement registry value must be added manually

### ISSUE THREAD

**Issue by xoogu** [MicrosoftDocs/Edge-Enterprise#59]
Added the group policy and enabled the side by side policy. Rebooted. Installed Chromium Edge again. Couldn't find any way of accessing legacy edge, and the BrowserReplacement value was not set in the registry (the side-by-side policy value was set). Tried installing Edge from https://www.microsoft.com/en-us/edge rather than the Enterprise download, but still the same result.

If I manually add the BrowserReplacement value to the registry, that works and I can access legacy edge.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50c5ef44-3ee1-92f3-3e5f-7e58d1f12e4a
* Version Independent ID: 55e2c808-be8c-d39f-ff34-69c69759d57f
* Content: [Access the old version of Microsoft Edge](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-sysupdate-access-old-edge)
* Content Source: [edgeenterprise/microsoft-edge-sysupdate-access-old-edge.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-sysupdate-access-old-edge.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **jtkim**

**Comment by RAJU2529** [comment]
just now i enabled side by side browser experience. 
after editing  policy in gpo . we must update the gp by using comand with admin rights

**Gpupdate.exe /Force**

**Comment by Y-Kelly** [comment]
Clean up of issues.  Closing as this is no longer applicable, references Legacy MS Edge.
