### ISSUE TITLE
Feedback for "Reset Microsoft Edge data in the cloud"

### ISSUE THREAD

**Issue by trusktr** [MicrosoftDocs/Edge-Enterprise#590]
Nothing listed on that page helped me get Workspaces working again.

This is the problem people are having:

https://techcommunity.microsoft.com/t5/enterprise/edge-workspaces-error-v114/m-p/3841174/page/2

I switched to Edge, and paid for Office 365 **just for workspaces**. I left Chrome, literally, just for Workspaces.  I really hope this issue will be fixed.

I got my workspaces back by signing out, and then signing back in. 

They should just work offline, always available, like other features.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa2b6bb-c572-6b62-0b2a-5d11cc6c16c2
* Version Independent ID: bbd72cfb-0dd2-dce0-ede7-6887a2992bad
* Content: [Reset Microsoft Edge data in the cloud](https://learn.microsoft.com/en-us/deployedge/edge-learnmore-reset-data-in-cloud)
* Content Source: [edgeenterprise/edge-learnmore-reset-data-in-cloud.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-reset-data-in-cloud.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **archandr**

**Comment by Y-Kelly** [comment]
@trusktr Thanks for the feedback!  There is a doc specifically for Microsoft Edge Workspaces and that has been updated to mention trying to sign out and sign back in.  (https://learn.microsoft.com/en-us/deployedge/microsoft-edge-workspaces#my-user-got-the-error-unable-to-load-workspaces-message-what-should-they-do)  Generally this error message can apply to a few different issues, all of which are being investigated and the team is working on future updates.  

In regards to being able to work offline, I have passed this feedback on to the team and hopefully some improvements will be available in this area.

**Comment by Y-Kelly** [comment]
@trusktr There are some updates for offline functionality for Workspaces being released.  Here is a link to the Microsoft Edge Beta 120 Release Notes: https://learn.microsoft.com/en-us/deployedge/microsoft-edge-relnote-beta-channel#version-120022107-november-13-2023
