### ISSUE TITLE
Edge policy to disable "Microsoft Edge Secure Network" missing

### ISSUE THREAD

**Issue by TommyTran732** [MicrosoftDocs/Edge-Enterprise#592]
I cannot seem to find a policy to disable this anywhere in the documentation

**Comment by Y-Kelly** [comment]
@TommyTran732 I've reached out to the team for more information.  They've said that Microsoft Edge Secure Network is not enabled on managed devices and there are no plans to enable, which is why there is no policy for this feature.  Thanks!

**Comment by TommyTran732** [comment]
> @TommyTran732 I've reached out to the team for more information. They've said that Microsoft Edge Secure Network is not enabled on managed devices and there are no plans to enable, which is why there is no policy for this feature. Thanks!

Thank you for your response. How would this work on a Linux device though if I may ask? Is it expecting any specific MDM or something like that?

I noticed that it is enabled by default on my Linux workstation and I really don't want it to be enabled by default if I am doing mass deployment.

**Comment by Y-Kelly** [comment]
@TommyTran732 Sounds like you are the IT Admin for an organization, is that correct?  How is your Linux device managed by the organization?  Do you use Intune or something else?

**Comment by Y-Kelly** [comment]
@TommyTran732 The team has confirmed that Microsoft Edge on Linux will not be detected as an enterprise or managed device. The logic only applies to Windows and macOS.  

If you would like to submit feedback to the team regarding this, our in-browser feedback tool is under "..." menu > Help and feedback > Send feedback.  Thanks!
