### ISSUE TITLE
Transition from AutoUpdate to EdgeUpdater

### ISSUE THREAD

**Issue by joegoerlich** [MicrosoftDocs/Edge-Enterprise#597]
Hello,

MS Edge on my managed mac is on version 117.0. So it should already come with EdgeUpdater. 
But today I got an announcement for Edge version 117.2045 in MS AutoUpdate. 

So I'm wondering how to perform the transition from AutoUpdate to EdgeUpdater on our managed devices?
We still have 
        "/Applications/Microsoft Edge.app" =         {
            "Application ID" = EDGE01;
            LCID = 1033;
        };
in our /Library/Managed Preferences/com.microsoft.autoupdate2.plist so it seems AutoUpdate is still taking care of updates.

In /Library/LaunchDaemons I don't see the com.microsoft.EdgeUpdater.helper. Shouldn't the EdgeUpdater be registered as helper service there?

Any advice is much appreciated!

BR,
Joe

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8cff3e97-b0cf-2168-450c-5282d318c29e
* Version Independent ID: 8cff3e97-b0cf-2168-450c-5282d318c29e
* Content: [Microsoft Edge for macOS switch from Microsoft AutoUpdate to EdgeUpdater](https://learn.microsoft.com/en-us/deployedge/edge-learnmore-edgeupdater-for-macos)
* Content Source: [edgeenterprise/edge-learnmore-edgeupdater-for-macos.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-edgeupdater-for-macos.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **azeigler**

**Comment by Y-Kelly** [comment]
@joegoerlich Based on the information from the team, there wouldn't be a com.microsoft.EdgeUpdater.helper. However, there should be other daemons in /Library/LaunchDaemons with the com.microsoft.EdgeUpdater prefix. 

Also, depending on the ownership of the browser (if the browser is owned by the user and not by root), the location of where EdgeUpdater may be different.

Can you check if you have any installation of EdgeUpdater, which, for the current version, could be in:
/Library/Microsoft/EdgeUpdater
${HOME}/Library/Microsoft/EdgeUpdater

Also, the registration to MAU could be a remnant from a previous install that hasn't been cleaned up.

Let us know if you cannot find EdgeUpdater in any locations and we can investigate further.

**Comment by Y-Kelly** [comment]
Closing as there has not been any replies in ~ a month.  If you have updates please feel free to leave a new comment.  Thanks!
