### ISSUE TITLE
Enterprise Mode schema

### ISSUE THREAD

**Issue by bagnos** [MicrosoftDocs/Edge-Enterprise#6]
Hi,

Why don't you support the wildcard in sitelist?

Example:
 <site url="*.mydomain.com>
    <compat-mode>Default</compat-mode>
    <open-in>IE11</open-in>
  </site>

In our migration process to Edge we have lots of sites that need IE MODE. It's very difficult/impossible to write each site in the sitelist.

**Comment by Y-Kelly** [comment]
Clean up of old issues.   If you would like to submit a feature request, please use our in-browser feedback tool.  ("..." menu > Help and feedback > Send feedback)
