### ISSUE TITLE
Config for opt in/out sync

### ISSUE THREAD

**Issue by nkkinariwala** [MicrosoftDocs/Edge-Enterprise#602]
I liked the Team workspace with the fact that all the bookmarks can stay at one place but certainly, don't like the feature where tabs are automatically synchronized among team members. I understand this is by design, but it may not work for everyone. Probably, you can provide some config setting for the workspace owner to allow this or not. My team currently doesn't feel comfortable of using Team workspace due to auto-sync. Everyone has different needs and changes on those already open tabs make the team workspace unusable. Please let me know if you need more input

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 395cb351-c526-c346-2dd0-9f02e5e80b63
* Version Independent ID: 395cb351-c526-c346-2dd0-9f02e5e80b63
* Content: [Microsoft Edge Workspaces](https://learn.microsoft.com/en-us/DeployEdge/microsoft-edge-workspaces)
* Content Source: [edgeenterprise/microsoft-edge-workspaces.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-workspaces.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **danielfi**

**Comment by Y-Kelly** [comment]
Closing, discussion ongoing internally.
