### ISSUE TITLE
Invalid link in script

### ISSUE THREAD

**Issue by MilanKrocek** [MicrosoftDocs/Edge-Enterprise#603]
Hello,

it seems that the setup guide: https://setup.microsoft.com/edge/setup-guide contains a script with the link which is no more valid.

This guide is mentioned at least on these pages: 

- deploy-edge-with-configuration-manager.md
- configure-microsoft-edge.md

Reproduce the issue:

1. Click on the link at the beggining of this page (**Microsoft Edge setup guide**)
2. Fill necessary settings and then click on the button **"Download your script"**
3. Edit the script once you download it and check line 82: $PolicyTemplatesUrl = **'https://go.microsoft.com/fwlink/?linkid=2145079'**
4. You are redirected to: **https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/70222a88-f16a-4fb1-a58e-6fd7847de8d6/MicrosoftEdgePolicyTemplates.zip** which doesn't exist.

**Comment by Y-Kelly** [comment]
@MilanKrocek Thanks for reporting this issue.  I've reached out to the team that owns the tool and will circle back once they have any updates.

**Comment by Y-Kelly** [comment]
@MilanKrocek This issue should be fixed.  If you are still having issues, let us know. Thanks!
