### ISSUE TITLE
Remove the double quotes from the example for RestrictSigninPattern

### ISSUE THREAD

**Issue by adysanro** [MicrosoftDocs/Edge-Enterprise#605]
For this part:
https://learn.microsoft.com/en-us/DeployEdge/microsoft-edge-policies#example-value-448

Remove the double quotes ("") from the example or specify that the double quotes should not be used.
Using the double quotes will completely break the Edge browser sign-in and Edge startup process when used in combination with the "BrowserSignin" - Force (2) policy . This was validated on three machines (Windows 10 and Windows 11).

![image](https://github.com/MicrosoftDocs/Edge-Enterprise/assets/87180477/33aec143-34f6-4283-b3dc-79d40298c07b)

**Comment by Y-Kelly** [comment]
@adysanro This issue affects other policies as well, not only the RestrictSigninToPattern policy. There is existing work going on to make improvements in this area and the team has it on their roadmap to fix.

I've passed your feedback on to the team so they can take it into account when prioritizing the work. Thanks for the feedback!
