### ISSUE TITLE
The term "Microsoft Entra User" was incorrectly used when it should have been "AD User".

### ISSUE THREAD

**Issue by tatsuya-midorikawa** [MicrosoftDocs/Edge-Enterprise#606]
"AAD" has been rebranded as "Microsoft Entra" and it appears that maintainers are updating their documentation without knowing the difference between "AD" and "AAD".
Therefore, it is necessary to correct the notation to "AD user".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 48eb8663-d045-68fc-442c-f7db93d5cf75
* Version Independent ID: d31bc620-5e2d-8c80-344f-7ad1ab4b8712
* Content: [On-premises sync for Active Directory (AD) users](https://learn.microsoft.com/en-us/DeployEdge/microsoft-edge-on-premises-sync)
* Content Source: [edgeenterprise/microsoft-edge-on-premises-sync.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-on-premises-sync.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **archandr**

**Comment by Y-Kelly** [comment]
@tatsuya-midorikawa @SIkebe Thanks for calling this out.  We will work on updating the docs, should be completed in the next day or so.
