### ISSUE TITLE
Sort order in release tabled

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/Edge-Enterprise#607]
It would be better to have the table sorted newer to older. I would prefer to see the upcoming items and the recently released items at the top of the list so that I dont have to scroll so far, these are more important than the items from a long time ago. 

Also, it would be helpful to have the older items moved onto a separate archive page, maybe just have this page focused on the current calendar year 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5d1bc306-56a5-f501-b3e0-a661d57b1db4
* Version Independent ID: e4ef685b-8570-be80-9547-9956042b967e
* Content: [Microsoft Edge release schedule](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-release-schedule)
* Content Source: [edgeenterprise/microsoft-edge-release-schedule.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-release-schedule.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **leahtu**

**Comment by Y-Kelly** [comment]
@DeanGross Thanks for the feedback!  I'll pass this on to the team and they will investigate future enhancements for the release schedule page.
