### ISSUE TITLE
Clearify AuthServerAllowlist

### ISSUE THREAD

**Issue by toxarisswe** [MicrosoftDocs/Edge-Enterprise#61]
Hello.

When configuring AuthServerAllowlist, does Edge Chromium use this list only to determine when to try WIA-based SSO?
Or does Edge Chromium combine the list defined in Site-to-Zone along with AuthServerAllowlist?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1de76e25-d6fb-af1a-f593-f9695e4da22c
* Version Independent ID: 3bb59466-8415-287d-d6f8-bbe32a6b112e
* Content: [Microsoft Edge identity support and configuration](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-security-identity)
* Content Source: [edgeenterprise/microsoft-edge-security-identity.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-security-identity.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **avvaid**

**Comment by RAJU2529** [comment]
@toxarisswe , Your query is entirely difficult to answer from my side , so wait  few days to get answers from experienced users.

**Comment by Y-Kelly** [comment]
@toxarisswe Based on information from our Identity Team, MS Edge will either allow WIA based SSO for any website on the intranet by default or only the configured list of domains on this policy if configured. There’s no combining.

If you have further questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
