### ISSUE TITLE
sync option not available in profiles

### ISSUE THREAD

**Issue by adehaan-cloud-senang** [MicrosoftDocs/Edge-Enterprise#610]
When trying to solve the sync issue, resetting the sync status is not doable as instructed on this page. The sync option is not available in Edge profile.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa2b6bb-c572-6b62-0b2a-5d11cc6c16c2
* Version Independent ID: bbd72cfb-0dd2-dce0-ede7-6887a2992bad
* Content: [Reset Microsoft Edge data in the cloud](https://learn.microsoft.com/en-us/deployedge/edge-learnmore-reset-data-in-cloud#perform-a-reset-to-fix-a-synchronization-problem)
* Content Source: [edgeenterprise/edge-learnmore-reset-data-in-cloud.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-reset-data-in-cloud.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **archandr**

**Comment by Y-Kelly** [comment]
@adehaan-cloud-senang Hello - If you are signed into your profile with the issue, at the bottom of edge://settings/profiles/sync there should be a message "Still having sync problems?  Try another option" and it has a drop down to Reset Sync Data. 

![image](https://github.com/MicrosoftDocs/Edge-Enterprise/assets/74324031/14af8ac0-789e-4032-aad5-b8bf8ccbf505)

If you are still having sync issues, you can reach out to [Support - Microsoft Edge Developer](https://developer.microsoft.com/en-us/microsoft-edge/support/).  They would be able to help investigate your specific case.  Thanks!
