### ISSUE TITLE
Broken Link (MAM Windows)

### ISSUE THREAD

**Issue by JMCA2** [MicrosoftDocs/Edge-Enterprise#611]
This link, included in this page, doesn't work: [Mobile Application Management for Microsoft Edge on unmanaged Windows devices](https://learn.microsoft.com/en-us/mem/intune/apps/protect-edge-mam-windows)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b11becb9-7ff3-9c7d-a8d3-67f80cc31f3e
* Version Independent ID: b11becb9-7ff3-9c7d-a8d3-67f80cc31f3e
* Content: [Microsoft Edge for Business](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-for-business#mam-for-windows)
* Content Source: [edgeenterprise/microsoft-edge-for-business.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-for-business.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **archandr**

**Comment by Y-Kelly** [comment]
@JMCA2 Thanks for letting us know about the broken link!  The doc has been updated.
