### ISSUE TITLE
Missing a policy to override "Try the new look and feel of Microsoft Edge" setting

### ISSUE THREAD

**Issue by zakx** [MicrosoftDocs/Edge-Enterprise#612]
Hi,

I noticed that Edge has a new setting called "Try the new look and feel of Microsoft Edge". I'm running 119.0.2151.46 (stable) on arm64 (Apple Silicon / macOS). 

I cannot seem to find a policy that enables me to disable the new look and feel. It would be nice if there was such a policy.

Thanks!

**Comment by Y-Kelly** [comment]
@zakx I've reached out to the team for this and can follow up if they provide any insight.  

The best way to submit feedback and feature requests is through the browser ("..." menu > Help and feedback > Send feedback).  Thanks!

**Comment by zakx** [comment]
@Y-Kelly Thank you for your help. Sadly, I am unable to use the described way to submit feedback, as the Edge installation I am using has set UserFeedbackAllowed to false. Is there any way to provide feedback for users that have this policy in place?

**Comment by Y-Kelly** [comment]
@zakx If your organization has that policy set, I do not think there is any way around it.  I'll circle back to this issue with any updates from the team.
