### ISSUE TITLE
Policy no longer available

### ISSUE THREAD

**Issue by cchapin2020** [MicrosoftDocs/Edge-Enterprise#613]
[Enter feedback here]
I am running Edge v 119.0.2151.44 on Windows 11 Enterprise 23H2, build 22631.2506 and the HubsSidebarEnabled GPO is not available. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6191d038-8035-aeaf-3122-3245a6d868c7
* Version Independent ID: 6191d038-8035-aeaf-3122-3245a6d868c7
* Content: [Manage the sidebar in Microsoft Edge](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-sidebar)
* Content Source: [edgeenterprise/microsoft-edge-sidebar.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-sidebar.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kylemiller**

**Comment by Y-Kelly** [comment]
@cchapin2020 Can you provide more information?  I just downloaded the latest policy file (https://www.microsoft.com/en-gb/edge/business/download?form=MA13FJ) and was able to find the policy.  

![image](https://github.com/MicrosoftDocs/Edge-Enterprise/assets/74324031/0e292bb9-eb3a-4e67-b88b-0cdb31ca2c0f)

**Comment by cchapin2020** [comment]
Thank you - I did not realize that it was a separate ADMX and not the Microsoft Edge ADMX that is shipped with the OS found in Computer Configuration -> Administrative Templates -> Windows Components -> Microsoft Edge. I thought that the path given had accidently omitted the Windows Components level from the path. You can close this issue.

**Comment by cchapin2020** [comment]
The ADMX I was looking at is MicrosoftEdge.admx

**Comment by Y-Kelly** [comment]
@cchapin2020 Thanks for following up, I'll close this issue.
