### ISSUE TITLE
https://config.edge.skype.com called continually on non-Enterprise Edge

### ISSUE THREAD

**Issue by TPS** [MicrosoftDocs/Edge-Enterprise#615]
_N.B.: Per https://learn.microsoft.com/en-us/deployedge/edge-configuration-and-experiments, this is where feedback re: this issue should be posted.  If not, please move to the correct repo._

I run Edge on multiple non-Enterprise Windows & Android devices.  All of them call `https://config.edge.skype.com` constantly.  How should that be disabled?
- [ ] Will the policy mentioned on the page work on my Windows devices when I'm not running Enterprise?
- [ ] What about Android?  Policies seem irrelevant here.

**Comment by Y-Kelly** [comment]
@TPS This GitHub Repo and Issues are normally specific for enterprise documentation.  Generally, users are encouraged to leave feedback to the team through the browser ("..." menu > Help and feedback > Send feedback).  Or there are other online options which are focused on end users and not enterprises for example, https://answers.microsoft.com/en-us/microsoftedge.

You do not mention what Windows OS you are using but Windows Pro and Enterprise Editions should have the Group Policy Editor.  If you have Windows Pro that might be an option.  

In regards to Android, I do not see the ExperimentationAndConfigurationServiceControl Policy mentioned in the Mobile Policy Doc https://learn.microsoft.com/en-us/deployedge/microsoft-edge-mobile-policies
