### ISSUE TITLE
Version history for changes to ADMX files

### ISSUE THREAD

**Issue by rmadzharov** [MicrosoftDocs/Edge-Enterprise#62]
Hi,

Please do include newly added/deprecated settings for each revision of the ADMX files.

Version 83 vs 85 have about 40 new GPOs which users have to look for by themselves.

BR,
Radko

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-policies)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@rmadzharov Hello - Please take a look at our documentation which includes Release Notes with a section for Policy updates and lists new Policies as well as deprecated Policies.  For example, https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel#policy-updates

Hopefully that will help! 

If you have further questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
