### ISSUE TITLE
Lear, learn, learn

### ISSUE THREAD

**Issue by dzieebovivienne** [MicrosoftDocs/Edge-Enterprise#626]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb28ab57-0f2b-9254-c5e0-66364824b227
* Version Independent ID: 34e52b9a-f3fc-28e3-b5b1-f85d623a95cc
* Content: [Password Monitor auto-enabled for users](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-security-password-monitor)
* Content Source: [edgeenterprise/microsoft-edge-security-password-monitor.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-security-password-monitor.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **supalsul**

**Comment by Y-Kelly** [comment]
Closing, this does not look like an actual Edge Enterprise Doc issue.
