### ISSUE TITLE
Incorrect Policy Location

### ISSUE THREAD

**Issue by Jay-at-Schoeps** [MicrosoftDocs/Edge-Enterprise#628]
I found the policy under Administrative Templates | Windows Components | Microsoft Edge
The article is missing the Windows Components level

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c3415ed3-5ccf-198d-cee7-2dbbfe4b0959
* Version Independent ID: f1e17aeb-6ab5-3db2-80ac-c16514f80cf6
* Content: [Provision favorites for Microsoft Edge](https://learn.microsoft.com/en-us/deployedge/edge-learnmore-provision-favorites)
* Content Source: [edgeenterprise/edge-learnmore-provision-favorites.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-provision-favorites.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **capoon**

**Comment by Y-Kelly** [comment]
@Jay-at-Schoeps The most updated Microsoft Edge policies can be downloaded here: https://www.microsoft.com/en-us/edge/business/download?form=MA13FJ

They can be applied using these instructions: https://learn.microsoft.com/en-us/deployedge/configure-microsoft-edge

I was able to confirm the doc is correct: "navigate to Computer Configuration/Administrative Templates/Microsoft Edge/ and pick Configure Favorites."

![image](https://github.com/MicrosoftDocs/Edge-Enterprise/assets/74324031/bc5607d6-2c48-48c9-9c87-97124968e7cf)
