### ISSUE TITLE
Manage Microsoft Edge for signed in work profiles on BYOD

### ISSUE THREAD

**Issue by haneef95** [MicrosoftDocs/Edge-Enterprise#63]
Hi,

One of our clients would like to switch to Microsoft Edge from Chrome as their primary browser, many of their employees use BYOD (personal devices) to access business apps on the web. As such, they're planning on asking the employees to:

1. Create new edge profile
2. Sign in to it with their work M365 account

Is there a way to just manage that one profile which they're signing into their browser with? Is this documented somewhere?

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d806f80-9f3a-6c06-4465-116f40dd4b4b
* Version Independent ID: 25bfe392-86c0-2953-191f-7648985d956c
* Content: [Plan your deployment of Microsoft Edge](https://docs.microsoft.com/en-us/deployedge/deploy-edge-plan-deployment)
* Content Source: [edgeenterprise/deploy-edge-plan-deployment.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/deploy-edge-plan-deployment.md)
* Product: **microsoft-edge**
* GitHub Login: @appcompatguy
* Microsoft Alias: **cjacks**

**Comment by appcompatguy** [comment]
That's a great suggestion! At the moment, our configurations don't target profiles, but as we continue to investigate ways to support Work from Home, being able to apply different rules to different profiles makes sense. I'll discuss this with the team that owns enterprise management and as we evolve this we'll be sure to cover the scenario in documentation!

**Comment by haneef95** [comment]
Hi @appcompatguy,

Any update on this?

Thanks,

**Comment by Y-Kelly** [comment]
Cleaning up old issues.   

If you still have feature requests for Microsoft Edge, you can submit them through the browser. ("..." menu > Help and feedback > Send feedback). Thanks!
