### ISSUE TITLE
ForceSync Does Not Exist

### ISSUE THREAD

**Issue by NickDorak** [MicrosoftDocs/Edge-Enterprise#64]
The Group Policy "Force synchronization of browser data and do not show the sync consent prompt" or similar does not exist. 
https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#forcesync

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@NickDorak The ForceSync policy was added in MS Edge V86.  If you are still having an issue, can you share what version of the browser you are using? 

Also, if you have further questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!

**Comment by NickDorak** [comment]
I meant the GPO doesn't exist as referenced by this article.

**Comment by Y-Kelly** [comment]
Clean up of old issues.  Not enough information provided.  

If you would like to report a Microsoft Edge Enterprise documentation issue to the team please open a new issue and include relevant information/repro steps in the Comment section.

If you have general questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsiderForum) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!

**Comment by NickDorak** [comment]
> Clean up of old issues. Not enough information provided.
> 
> If you would like to report a Microsoft Edge Enterprise documentation issue to the team please open a new issue and include relevant information/repro steps in the Comment section.
> 
> If you have general questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsiderForum) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
@Y-Kelly 

What do you mean "Not enough information provided."?
One of the items referenced in the article doesn't exist. I provided the name to the item. What else do you need?

**Comment by Y-Kelly** [comment]
@NickDorak I'm sorry, I do not understand your issue.  What do you mean the item does not exist?  The Policy was added to MS Edge in v86.  Do you have the latest Policy files?  You can download them here: https://www.microsoft.com/en-us/edge/business/download

Are you saying the policy is not behaving as described in the documentation?  Please provide additional information.  Thanks!
