### ISSUE TITLE
Wrong command to update group policies

### ISSUE THREAD

**Issue by collaca** [MicrosoftDocs/Edge-Enterprise#65]
The note in "Enable rollback with Microsoft Edge update and Group Policy" section points to use "dsregcmd /status" to update group policies. Shouldn't "gpupdate /force" be used instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12e89255-aab6-fe92-7a4f-7c1a53d30f50
* Version Independent ID: dcb5637d-8829-83e2-d7e3-71714a7daf3a
* Content: [Microsoft Edge rollback for enterprises](https://docs.microsoft.com/en-us/deployedge/edge-learnmore-rollback)
* Content Source: [edgeenterprise/edge-learnmore-rollback.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-rollback.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **v-danwes**

**Comment by Y-Kelly** [comment]
@collaca Thanks for the feedback about the documentation! 

Adding @dan-wesley for follow up.

**Comment by dan-wesley** [comment]
@collaca thanks for catching this error. I've updated the doc and it will be published today.

**Comment by collaca** [comment]
Thanks!

[photo]
Carlos Collado
GM Fasttrack SME
Fasttrack Center – EMEA
https://fasttrack.microsoft.com<https://fasttrack.microsoft.com/>
Microsoft Edge
The browser for business | Standardize on one browser with Microsoft security and innovation
Get assistance from FastTrack<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Ffasttrack&data=02%7C01%7Cv-cacol%40microsoft.com%7Cebc5765797174341c8ca08d84e8d9dc0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637345717583321970&sdata=WClAUJPHSLGVe%2Fu8NzqBO31gi11nkwLumR7friLyDAc%3D&reserved=0> | Learn about Edge<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Fedge&data=02%7C01%7Cv-cacol%40microsoft.com%7Cebc5765797174341c8ca08d84e8d9dc0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637345717583326967&sdata=FEolvPKFvzsy%2FXSu1FO7X36cs7DLXr5zjZYcyWv%2B4Yg%3D&reserved=0>
