### ISSUE TITLE
Multiple Edge Profiles on Smartphones (Android/iOS)?

### ISSUE THREAD

**Issue by haneef95** [MicrosoftDocs/Edge-Enterprise#67]
Hi,

Any planned support for Edge Profiles on smartphones?

It would be really beneficial, especially since users tend to start using their BYOD for work. As to avoid having to carry two mobile devices.

Thanks,

**Comment by haneef95** [comment]
This feature along with #63 would be a deal breaker!

**Comment by RAJU2529** [comment]
@e0i   @nam31  please look into this issue #67.

**Comment by e0i** [comment]
@RAJU2529 We don’t coordinate these repositories. You don’t need to tag us for our help. Thank you.

**Comment by Y-Kelly** [comment]
Clean up of old issues.  I believe MS Edge mobile supports one personal and one work/school account.  

If you need more profiles for your scenario, you can send feedback through the browser or vote for this feature in the Feedback Portal. https://feedbackportal.microsoft.com/feedback/idea/53f999ab-3c3c-ec11-a81a-6045bd78c63c
