### ISSUE TITLE
There is no guidance to configure policies that require the JSON format 

### ISSUE THREAD

**Issue by RicaGomes** [MicrosoftDocs/Edge-Enterprise#7]
This feedback is related to the experience I been having with customers that are using this the "Browser Policy Reference" page to configuring Microsoft Edge. The majority of my customers (and I can confirm this is the same case for other colleagues of mine) have difficulties in understanding how to properly configure any policy that depends on the json format (example: ManagedSearchEngines, ManagedFavorites, WebAppInstallForceList, etc...)

What we are observing is customers are trying to use the examples in the policy (example: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#example-value-201) as they are presented on that section, by doing so, it will cause the policy not to be applied to Edge, accusing syntax errors (adds unnecessary spaces, character's and registry keys). In order for the policy to apply correctly, the syntax should be built around these rules:

1. Start with the “[“ and end with the “]” symbols (example: [{“element”:”value”}] )

1. True or False values should not be added with quotes (example: [{“element”:true}] )

1. The elements and values must be compliant with the json format

1. After building the json you need to convert it into a compact json format, 1 liner with no spaces or new lines

1. Use only documented elements and values

Would like to propose that the "Browser Policy Reference" documentation page could be updated to include:

1. An human readable format (keeping the one we currently have and maybe removing the registry path's)

1. Add an example copy-pasted friendly example (for testing purposes) that follows the rules above

1. Somewhere in the page we could have a guidance on how to build a json formatted to work with our policies.

As extra, we could offer our customers an official json format tool like the following example: https://jsonformatter.curiousconcept.com/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1cd3ad5-bb4a-54ff-84e7-18ca0b11368f
* Version Independent ID: 984abd8f-45eb-737b-ad74-07ec8261f9eb
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#example-value-201)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by CoertK** [comment]
I am looking into configuring WebAppInstallForceList for Edge and run into the same problem.
I have no clue how I am supposed to configure this example on a single line:
![image](https://user-images.githubusercontent.com/43961752/90988564-f6b17680-e593-11ea-8494-b4cee49283ec.png)

**Comment by henry-js** [comment]
So can anyone tell me how to configure the WebAppInstallForceList policy? Do I simply copy/paste the JSON string formatted to a single line?

**Comment by Y-Kelly** [comment]
Clean up of old issues.  This discussion does not have any recent activity.

Double checked the [policy documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies) and the policies mentioned in this thread now include a compact example value, which should help clarify.  

If you would like to report a Microsoft Edge Enterprise documentation issue to the team please open a new issue and include relevant information/repro steps in the Comment section.
