### ISSUE TITLE
Continuous open new tab when Configure Internet Explorer integration is set to 1 or 2

### ISSUE THREAD

**Issue by stevenfoo30** [MicrosoftDocs/Edge-Enterprise#70]
[Enter feedback here]

I am getting continuous open new tab when Configure Internet Explorer integration is set to 1 or 2.
I have configure the Enterprise Mode List and save XML and point to it in a share location.

When I click on the link that specify in the XML file. The link will continuous open new tab with the URL non stop.
The only way to stop that is log out and log in again..

This seem like a bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e59013ef-aae3-ee84-8bc3-8d2ad0c52e36
* Version Independent ID: f4e73402-3baf-a72b-96c5-cee4f04b8298
* Content: [Configure IE mode Policies](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-policies)
* Content Source: [edgeenterprise/edge-ie-mode-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @cjacks
* Microsoft Alias: **cjacks**

**Comment by stevenfoo30** [comment]
https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-policies#configure-internet-explorer-integration

Configure the Enterprise Mode Site List (Microsoft Edge, version 78 or later)
This policy lets you create a separate Enterprise Mode Site list for Microsoft Edge. Enabling this policy overrides the settings in the "Use the Enterprise Mode IE website list" policy, if "Configure Internet Explorer integration" is enabled. Disabling or not configuring this policy doesn't affect the default behavior of the "Configure Internet Explorer integration" policy.

**Comment by Y-Kelly** [comment]
Clean up of old issues.  

If you are still having a problem with IE mode, you can get detailed guidance on how to set up Internet Explorer mode through our [Getting Started guide](https://aka.ms/IEModeGuide) or by visiting our [IE mode documentation](https://docs.microsoft.com/deployedge/edge-ie-mode).  Also, you can contact App Assure at https://aka.ms/AppAssure for assistance.
