### ISSUE TITLE
#extensionsettings section should provide a URL specifying the syntax for the value of this policy

### ISSUE THREAD

**Issue by James-Noble** [MicrosoftDocs/Edge-Enterprise#72]
There is insufficient detail in this section of the syntax of the values of settings.  I searched around and found this page, which has the appropriate information: https://www.chromium.org/administrators/policy-list-3/extension-settings-full

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#extensionsettings)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by RAJU2529** [comment]
@James-Noble . ok good work. According to you what should to do with this article.

**Comment by ashishnirvana1** [comment]
@James-Noble - Could you provide more detail? Specifically a use case that you were looking for and didn't find the detail required. That will be helpful in providing the appropriate syntax.

**Comment by James-Noble** [comment]
Hi,

Since I submitted this issue, a new page has been linked from the section which explains the syntax. 
 This was not present before.
https://docs.microsoft.com/en-us/deployedge/microsoft-edge-manage-extensions-ref-guide 

In my opinion this means the issue is resolved.
