### ISSUE TITLE
Microsoft Edge Legacy can't be access after win10 20H2 update

### ISSUE THREAD

**Issue by zerorp** [MicrosoftDocs/Edge-Enterprise#75]
I need access legacy Edge to do some automation testing, it works well in 1909 build, but after 20H2 the legacy Edge can't be accessed anymore.

is there anyway to enable this again?
"[Side-by-side experience with Microsoft Edge Stable Channel and Microsoft Edge Legacy](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-sysupdate-access-old-edge#to-set-up-the-side-by-side-browser-experience-policy)"

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50c5ef44-3ee1-92f3-3e5f-7e58d1f12e4a
* Version Independent ID: 55e2c808-be8c-d39f-ff34-69c69759d57f
* Content: [Access the old version of Microsoft Edge](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-sysupdate-access-old-edge)
* Content Source: [edgeenterprise/microsoft-edge-sysupdate-access-old-edge.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-sysupdate-access-old-edge.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **jtkim**

**Comment by RAJU2529** [comment]
@zerorp . If you 20h1 and 20h2 before update, and also edge chromium before windows update, then it's possible . But in latest  version does not able to do now. Sorry

**Comment by ZMYaro** [comment]
Agreed, this is a big problem for developers who need to test on both the EdgeHTML and Chromium versions of Microsoft Edge.

**Comment by Y-Kelly** [comment]
Support for the Microsoft Edge Legacy desktop application ended on March 9, 2021, closing this issue. 

https://techcommunity.microsoft.com/t5/microsoft-365-blog/new-microsoft-edge-to-replace-microsoft-edge-legacy-with-april-s/ba-p/2114224
