### ISSUE TITLE
Cookie Security in Edge Kiosk Mode

### ISSUE THREAD

**Issue by danieltharris** [MicrosoftDocs/Edge-Enterprise#76]
If your kiosk web interface needs to be signed in to, for example during initial setup to allow a back-end API to know which location the kiosk is at and to return specific content for display....are there any concerns around a member of the public extracting an authentication cookie or similar that might be stored on the device, and then using that to authenticate from a different device outside of your intended use-case?

Would a native app be better suited so that the user accessing the Kiosk has no way of viewing the source code and cookies - or is Kiosk mode going to be suitable for this by protecting local storage/cookies effectively?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 229e4d46-19a6-c042-8ce1-844c44c00112
* Version Independent ID: 8ab07629-42a6-e7a1-86a9-f8103825ebc4
* Content: [Configure Microsoft Edge kiosk mode](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode)
* Content Source: [edgeenterprise/microsoft-edge-configure-kiosk-mode.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-configure-kiosk-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @Aguta
* Microsoft Alias: **aguta**

**Comment by Y-Kelly** [comment]
@danieltharris Hello - I'm checking with the Kiosk Mode team to see if they have any insight/information.  Thanks!

**Comment by Y-Kelly** [comment]
Clean up of old issues.  We did not receive any feedback from the team regarding this question.  

If you still need assistance you can reach out to [Support](https://developer.microsoft.com/en-us/microsoft-edge/support/) or the [FastTrack Team](https://www.microsoft.com/en-us/fasttrack/microsoft-365/microsoft-edge?rtc=1) and they can help with your specific scenario.
