### ISSUE TITLE
Unclear what "incompatible" means with regards to auto redirect to Edge from IE 11

### ISSUE THREAD

**Issue by teggno** [MicrosoftDocs/Edge-Enterprise#78]
In the sentence 

> When a user goes to a site that is incompatible with Internet Explorer, ...

what does "incompatible" mean? Is there some feature detection going on or is it some meta tag or HTTP header that's being used to determine if a site is incompatible? 
I'm asking this as a developer of public sites and as such would like to know if I have any way to make IE 11 display this prompt.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90451dc6-e4b1-9973-2309-5399e9a63496
* Version Independent ID: ce664b18-ab7e-604a-c475-55ce86b15284
* Content: [Redirection from Internet Explorer to Microsoft Edge for compatibility with modern web sites](https://docs.microsoft.com/en-us/deployedge/edge-learnmore-neededge#feedback)
* Content Source: [edgeenterprise/edge-learnmore-neededge.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-neededge.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **laannade**

**Comment by josip** [comment]
I seems it simply based on a list of publicly known websites that do not to work in IE, for example YouTube does not work/support IE anymore because IE does not support relevant video formats anymore.

This has been reverse-engineered here by ZDNet: https://www.zdnet.com/article/microsoft-will-forcibly-open-some-websites-in-edge-instead-of-internet-explorer/

I would too, also like to find out how to add our product to the list for same exact reason as YouTube.

**Comment by Y-Kelly** [comment]
@teggno Hello - Please see the following article which has some additional details and includes instructions if you are a site owner and want to request to be added to the Need Microsoft Edge list: https://docs.microsoft.com/en-us/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection

If you have further questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
