### ISSUE TITLE
GP ADMX file name has been changed 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/Edge-Enterprise#8]
i have verified in policy definations folder , there is no file called  edgeupdate.admx 
but  **msedgeupdate.admx** file is there 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c2c2341-3489-41ce-9223-71e27bf5d586
* Version Independent ID: 599462c4-4725-a8b3-29e9-d790238db1bf
* Content: [Microsoft Edge Update Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-update-policies#feedback)
* Content Source: [edgeenterprise/microsoft-edge-update-policies.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-update-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by RAJU2529** [comment]
I think the article has updated with a changed name,
Please @Brianalt-Msft conform it .

**Comment by tamarahills** [comment]
> I think the article has updated with a changed name,
> Please @Brianalt-Msft conform it .

Hi @RAJU2529 where are you seeing this?  In the documentation or the policy archive?

**Comment by RAJU2529** [comment]
@tamarahills , in the documentation only.  Name has been changed from **edgeupdate.admx**  to  **msedgeupdate.admx**. 
article has updated.

**Comment by RAJU2529** [comment]
@tamarahills , I am closing this issue, issue has been solved , hence closing.
