### ISSUE TITLE
Provide the available options for this policy [ CollectionsServicesAndExportsBlockList ]

### ISSUE THREAD

**Issue by v-abdh** [MicrosoftDocs/Edge-Enterprise#82]
I have customers who wanted to know more options about this policy **CollectionsServicesAndExportsBlockList**
there is only 1 option mentioned related to Pinterest , but it is not clear what other options can be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@v-abdh Hello!  The [documentation](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-policies#collectionsservicesandexportsblocklist) will be updated as additional options are added.  

Here are the current Policy options mapping:
- pinterest_suggestions (pinterest_suggestions) = Pinterest suggestions
- collections_share (collections_share) = Sharing of Collections

If you have further questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
