### ISSUE TITLE
No templates

### ISSUE THREAD

**Issue by bbloksma** [MicrosoftDocs/Edge-Enterprise#84]
[Enter feedback here]
On this page is a link https://aka.ms/EdgeEnterprise that supposedly has the "Microsoft Edge policy templates" but I have not been to find them. Either they are not there or too well hidden. :-(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e4fa0af-82d8-c1ca-02b3-fc55eb620ff3
* Version Independent ID: bd546e78-3406-0fdd-2aea-d0bd72be9f38
* Content: [Configure Microsoft Edge for Windows](https://docs.microsoft.com/en-us/DeployEdge/configure-microsoft-edge)
* Content Source: [edgeenterprise/configure-microsoft-edge.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/configure-microsoft-edge.md)
* Product: **microsoft-edge**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **brianalt**

**Comment by RAJU2529** [comment]
@bbloksma T
oday i downloaded the latest edge chromium-based administrative templates and added in windows 10  20H2. 
**https://www.microsoft.com/en-us/edge/business/download**  use chrome browser in windows or in android.

**Comment by Y-Kelly** [comment]
@bbloksma Hi!  Hope you were able to find the policy files but if not here is a screenshot specifically where on the page they can be found.  Thanks! 

![image](https://user-images.githubusercontent.com/74324031/112217292-b2e12700-8bdf-11eb-9b5e-13aa9505491f.png)
