### ISSUE TITLE
configuration of XML

### ISSUE THREAD

**Issue by TomoharuMisawa** [MicrosoftDocs/Edge-Enterprise#85]
It has the same configuration of XML as Enterprise mode and includes Teams.microsoft.com. In that case, do you think you need to set login.microsoftonline.com to None? will https://edge.microsoft.com/needededge/v1 be XML with different meanings in the same schema?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90451dc6-e4b1-9973-2309-5399e9a63496
* Version Independent ID: ce664b18-ab7e-604a-c475-55ce86b15284
* Content: [Redirection from Internet Explorer to Microsoft Edge for compatibility with modern web sites](https://docs.microsoft.com/en-us/deployedge/edge-learnmore-neededge?WT.mc_id=WDIT-MVP-5002496)
* Content Source: [edgeenterprise/edge-learnmore-neededge.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-neededge.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **laannade**

**Comment by dan-wesley** [comment]
@TomoharuMisawa I'm passing your question on to the appropriate PM to get an answer for you.

**Comment by Y-Kelly** [comment]
Clean up of old issues.  @TomoharuMisawa - Can you clarify your question?  The Need Microsoft Edge List automatically redirects IE users to MS Edge for sites on the list.  What enterprise mode xml file are you referencing?

**Comment by Y-Kelly** [comment]
Closing issue as there has not been any recent replies.  

@TomoharuMisawa If you still have questions about the Need Microsoft Edge List feel free to reach out to ietoedge@microsoft.com.
