### ISSUE TITLE
How to join the force-redirect-IE-to-Edge list?

### ISSUE THREAD

**Issue by brendanfalkowski** [MicrosoftDocs/Edge-Enterprise#86]
If our company's website discontinues IE support, how can we opt-in to joining the DLL list that forces Edge to open instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90451dc6-e4b1-9973-2309-5399e9a63496
* Version Independent ID: ce664b18-ab7e-604a-c475-55ce86b15284
* Content: [Redirection from Internet Explorer to Microsoft Edge for compatibility with modern web sites](https://docs.microsoft.com/en-us/deployedge/edge-learnmore-neededge)
* Content Source: [edgeenterprise/edge-learnmore-neededge.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-neededge.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **laannade**

**Comment by OftKilted** [comment]
The “Enterprise Mode” support is typically for internal users. Not external users.

https://docs.microsoft.com/en-us/internet-explorer/ie11-deploy-guide/turn-on-enterprise-mode-and-use-a-site-list

**Comment by josip** [comment]
I have the same question as the poster. 

I believe they are referring to the new "IE to Edge" list that Microsoft is maintaining, not internal/enterprise policy managers, as described here:

https://docs.microsoft.com/en-us/deployedge/edge-learnmore-neededge

**Comment by brendanfalkowski** [comment]
@josip @OftKilted — That's correct, I read about the "IE to Edge" list Microsoft is maintaining here:
https://www.zdnet.com/article/microsoft-will-forcibly-open-some-websites-in-edge-instead-of-internet-explorer/

But the only mention of it I could find on a Microsoft domain was that enterprise guide, so that's why I opened the ticket here.

**Comment by Y-Kelly** [comment]
@brendanfalkowski and @josip Hello!  Please see this article which has instructions for site owners to be added to the Need Microsoft Edge List: https://docs.microsoft.com/en-us/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection

If you have further questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
