### ISSUE TITLE
RE: Microsoft is Beginning to Nudge Users Away from Internet Explorer

### ISSUE THREAD

**Issue by geoperkins** [MicrosoftDocs/Edge-Enterprise#87]
The new Chromium Edge is fine, I like it. But before dropping support of IE11 when will Microsoft first update its own web infrastructure to work on anything but IE? I refer specifically to https://www.catalog.update.microsoft.com/Home.aspx which requires ActiveX in IE11 in order to download updates. How ironic. Microsoft has become so big and unwieldy that the left-hand does not know what the right-hand is doing!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90451dc6-e4b1-9973-2309-5399e9a63496
* Version Independent ID: ce664b18-ab7e-604a-c475-55ce86b15284
* Content: [Redirection from Internet Explorer to Microsoft Edge for compatibility with modern web sites](https://docs.microsoft.com/en-us/deployedge/edge-learnmore-neededge)
* Content Source: [edgeenterprise/edge-learnmore-neededge.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-neededge.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **laannade**

**Comment by Y-Kelly** [comment]
Clean up of old issues.  IE11 is retired and is out of support as of June 15, 2022. 
https://techcommunity.microsoft.com/t5/windows-it-pro-blog/internet-explorer-11-desktop-app-retirement-faq/ba-p/2366549
