### ISSUE TITLE
Redirection from Internet Explorer to Microsoft Edge for compatibility with modern web sites: Site list link?

### ISSUE THREAD

**Issue by NorbertKlein-Ildefeld** [MicrosoftDocs/Edge-Enterprise#88]
Is there a link to the IE-incompatible sites that MSFT maintains?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90451dc6-e4b1-9973-2309-5399e9a63496
* Version Independent ID: ce664b18-ab7e-604a-c475-55ce86b15284
* Content: [Redirection from Internet Explorer to Microsoft Edge for compatibility with modern web sites](https://docs.microsoft.com/en-us/deployedge/edge-learnmore-neededge)
* Content Source: [edgeenterprise/edge-learnmore-neededge.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-neededge.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **laannade**

**Comment by Y-Kelly** [comment]
@NorbertKlein-Ildefeld The Need Microsoft Edge List can be found here: https://edge.microsoft.com/neededge/v1

If you are a site owner and would like to request to be added/removed from the list please see this article: https://docs.microsoft.com/en-us/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection

If you have further questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions  please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise).  Thanks!

**Comment by NorbertKlein-Ildefeld** [comment]
thanks much for feedback, item can be closed
