### ISSUE TITLE
PostMessage

### ISSUE THREAD

**Issue by bagnos** [MicrosoftDocs/Edge-Enterprise#9]
Hi,

I'm trying to send window.postMessage() between an ie mode page and an edge chromium page, it doesn't works.

Do you support postMessage() between these page?

Thanks.

Simone

**Comment by Y-Kelly** [comment]
Clean up of old issues.  There was an update made in v96 for POST data, which may help: https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-faq#my-application-requires-transferring-post-data-between-ie-mode-and-microsoft-edge-is-this-supported

If this does not resolve your issue, you can use the in-browser feedback tool to submit a feature request.  It's under "..." menu > Help and feedback > Send feedback.
