### ISSUE TITLE
were is Synced data stored in my tenant. 

### ISSUE THREAD

**Issue by BenjaminChambersAFC** [MicrosoftDocs/Edge-Enterprise#91]
Hi
were is Synced data stored in my tenant.
You say "Synced data for Azure AD accounts is stored in secure servers according to the tenant ID."
But were is it, As admin can we delete that data
Can we see if user have used the Sync function.

All the best 
benjamin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 593ef462-f298-94e4-8135-152588023ca1
* Version Independent ID: b4290014-fbd2-92db-a873-06ddef7a476a
* Content: [Microsoft Edge and Enterprise State Roaming](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-enterprise-state-roaming)
* Content Source: [edgeenterprise/microsoft-edge-enterprise-state-roaming.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-enterprise-state-roaming.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by Y-Kelly** [comment]
@BenjaminChambersAFC Additional information about Sync can be found in the privacy whitepaper: https://learn.microsoft.com/en-us/microsoft-edge/privacy-whitepaper/#sync.  This might have some answers to your question or you can reach out to Support for Business ([Support - Microsoft Edge Developer](https://developer.microsoft.com/en-us/microsoft-edge/support/)) if you have additional questions.
