### ISSUE TITLE
Can the link be elaborated?

### ISSUE THREAD

**Issue by win2000b** [MicrosoftDocs/Edge-Enterprise#92]
From version 90 of Edge you have said that the new tab page experience will be deprecated. You say its available on admin.microsoft.com

https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#configure-the-microsoft-edge-new-tab-page-experience-deprecated

Please can you elaborate where within the admin centre? I've look and cannot find it...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@win2000b Please see the following article it should have the information you are looking for: https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-industry-news?view=o365-worldwide#microsoft-edge-new-tab-page

Thanks!

**Comment by Y-Kelly** [comment]
@win2000b Just as a quick follow up, the new tab page experience is not deprecated, rather the policy to control the toggle switch is deprecated as it is no longer required.

Here are a few additional links that may be helpful: 
[https://blogs.windows.com/msedgedev/2020/10/29/enterprise-new-tab-page-my-feed/]()
[https://docs.microsoft.com/en-us/DeployEdge/edge-learnmore-ntp-backward-compatibility]()
