### ISSUE TITLE
Publication/update date format

### ISSUE THREAD

**Issue by JNLlB** [MicrosoftDocs/Edge-Enterprise#93]
At the head of this article is a date:
**Microsoft Edge - Policies
11/04/2020 ...**

There is no indication of which date this is, but I would expect it to give the date of the latest revision. However, even though I'm signed in with a Microsoft Account which includes locale data and using a Windows computer with registered preferred date formats, I have no way of knowing whether this is a seven-month-old article (published 2020-04-11 or 11 April 2020) which may or may not be out of date, or a recent revision (updated 2020-11-04 or 4 November 2020). There are several ways of formatting dates so users outside USA can understand them at sight, but '11/04/2020' isn't one of them. I would put the possibilities in this order of preference:

1. 2020-11-04
2. 4 November 2020
3. November 4, 2020
...
99. 11/04/2020 

Thanks.
Noel Burgess
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies?source=docs#extensioninstallsources)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@JNLlB Thanks for the feedback!  We are going through and cleaning up these old issues.  

The formatting of the last modified date at the top of the page is determined by the language/country designation in the URL and cannot be adjusted.  

For example, docs.microsoft.com/**en-us**/deployedge/microsoft-edge-policies, this would follow the standard date format for the US = 08/24/2022

If it was Japanese, docs.microsoft.com/**ja-jp**/deployedge/microsoft-edge-policies.  The date is formatted like 2022/08/24
