### ISSUE TITLE
RestrictSigninToPattern setting description is a bit misleading

### ISSUE THREAD

**Issue by gmarnold25** [MicrosoftDocs/Edge-Enterprise#94]
The RestrictSigninToPattern setting description is misleading as it says "determines which accounts can be set as browser primary accounts." Where it actually should be something along the lines of "determines which accounts can be used to sign into the browser." Once you restrict that to whatever pattern it might be, it doesn't matter whether it is a primary profile or a second/third/fourth profile, only accounts that match that pattern are allowed to sign in. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-policies#restrictsignintopattern)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@gmarnold25 Thanks for the feedback!  We've passed it on to the MS Edge Identity Team.  We can follow up if there are any updates/insights to share. 

If you have further questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community Forum](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!

**Comment by joegoerlich** [comment]
Please see https://techcommunity.microsoft.com/t5/enterprise/adding-multiple-domains-to-restrictsignintopattern-string/m-p/1412242 from May 2020. 
@Y-Kelly  this still needs some clarifiaction, please.

**Comment by Y-Kelly** [comment]
@gmarnold25 @joegoerlich The policy documentation for RestrictSigninToPattern (https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-policies#restrictsignintopattern) has been updated. 

Thanks!
