### ISSUE TITLE
Don't post an update until the MSI file has been posted.

### ISSUE THREAD

**Issue by NotepadPlusUser** [MicrosoftDocs/Edge-Enterprise#96]
I check this page (and many others) daily for new versions: 
https://docs.microsoft.com/en-gb/DeployEdge/microsoft-edge-relnote-stable-channel
When there is an update I go to get it from the standard download page:
https://www.microsoft.com/en-us/edge/business/download 

Most times, however, when there is a new version, it has yet not been posted there.  This is annoying, because it is a waste of time and I have to remember tomorrow that I need to try again.

Can you please not post any note about a new version on the top website above until the download has been posted on the top website above.

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ffcaf54-ce86-1b30-e947-540bf07a54c3
* Version Independent ID: 81267e97-e284-ff00-b081-476934538326
* Content: [Microsoft Edge release notes for Stable Channel](https://docs.microsoft.com/en-gb/DeployEdge/microsoft-edge-relnote-stable-channel)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **aguta**

**Comment by Y-Kelly** [comment]
Clean up of old issues.  

When new versions of MS Edge are deployed, there is a standard rollout process.  

If you have feedback or feature requests for Microsoft Edge, you can submit them through the browser. ("..." menu > Help and feedback > Send feedback). Thanks!
