### ISSUE TITLE
"Microsoft Edge - Update policies" page is missing important information

### ISSUE THREAD

**Issue by cb55555** [MicrosoftDocs/Edge-Enterprise#97]
This registry value that is supposed to prevent updates as indicated in the documention:
```
Path: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\EdgeUpdate
Value Name: UpdateDefault
Value Type: REG_DWORD
```
stopped working at some point. I have an unattended console application running on a server that uses the Selenium driver for MSEdge to download files from a website. Each version of the driver works with a specific version of MSEdge, and I used the UpdateDefault registry value to keep it locked at version 84. This registry entry was working for awhile, but I noticed that my application stopped working at some point. I checked the browser version, and it was inexplicably updated to version 86.

I realized that the setting for "Manual updates only" DOES NOT prevent automatic updates from Windows Update. It only prevents automatic updates while the user is using the browser and goes to the About Microsoft Edge page.

I found another [page ](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-blocker-toolkit) about a toolkit that essentially updates a different registry setting in the same registry node:

```
Path: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\EdgeUpdate
Value Name: DoNotUpdateToEdgeWithChromium
Value Type: REG_DWORD
Values: 0/Undefined - Distribution is not blocked, 1 - Distribution is blocked
```

This registry value IS supposed to prevent updates from Windows Update. This documentation page in question should at least link to this other page or this DoNotUpdateToEdgeWithChromium value should just be included in this page. The current documentation, as-is, is misleading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96fddabd-2bac-2fab-a5ea-25c000b425fc
* Version Independent ID: 41bba38e-bd24-0496-da04-012d6deb5db8
* Content: [Microsoft Edge Update Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-update-policies)
* Content Source: [edgeenterprise/microsoft-edge-update-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-update-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment]
@cb55555 Thanks for the feedback about our documentation! 

Adding @dan-wesley for follow up

**Comment by andyzei** [comment]
Hi @cb55555,

Sorry that you've hit this issue. Are you sure that the device in question is AD domain-joined? That policy is only enforced on devices joined to a domain.

We have a couple of projects in the works to make it much easier to set up Edge for automation contexts -- stay tuned for that.

In the meantime, one workaround you can do is to just copy the Edge binaries out of the \Application folder to another location and run then from there. For example:

```
md C:\static_edge
xcopy /e /h "C:\Program Files (x86)\Microsoft\Edge\Application\87.0.664.52\*" C:\static_edge
<run msedge.exe>
```

The version in C:\static_edge will not update.

Let me know if you have any questions / feedback -- thanks!

Andy

**Comment by Y-Kelly** [comment]
Clean up of old issues.  Appears there has not been any recent activity in this thread.  

If you are still having an issue or would like to report another Microsoft Edge Enterprise documentation issue to the team please open a new issue and include relevant information/repro steps in the Comment section.
