### ISSUE TITLE
About Microsoft Edge Sync prerequisites

### ISSUE THREAD

**Issue by juhirao** [MicrosoftDocs/Edge-Enterprise#99]
[Enter feedback here]
As mentioned in the article, Microsoft Edge sync uses the AIP Service, so user must manage the AIP service.
However, to manage AIP services, user must have at least one subscription license in their tenant that allows user to use the AIP Service.
If there is no paid AIP license SKU in the tenant, the global administrator's account can't manage the AIP Service through the portal or PowerShell.
The prerequisites for the Docs article are written so that SKUs that do not include AIP licenses, such as Azure AD Premium (P1 and P2), are also available.
Implementation problems occur when users and partners incorrectly understand prerequisites and plan to purchase licenses.
Ask for improvements to the article, such as alerting you with the "Caution" comment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fa7eda4-6e4c-c2c8-a29a-ef2eead7f04f
* Version Independent ID: 414db256-c14b-ca11-b2a7-835aa9c9e041
* Content: [Microsoft Edge Enterprise Sync](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-enterprise-sync)
* Content Source: [edgeenterprise/microsoft-edge-enterprise-sync.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-enterprise-sync.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **scottbo**

**Comment by Y-Kelly** [comment]
@juhirao The team has made changes to the Microsoft Edge enterprise sync Prerequisites documentation.  Thanks!
